"""Python frontend for APXM workflows."""

from __future__ import annotations

from . import _generated
from .agent import Agent, BoundAgent
from .backends import (
    BackendRegistryError,
    BackendRoute,
    RegisteredBackend,
    RegisteredModel,
    config_path,
    get_backend,
    list_backends,
    select,
    select_backend,
)
try:
    from ._generated.models import Anthropic, Google, ModelId, OpenAI, Vllm
except ImportError:
    Anthropic = None  # type: ignore[assignment,misc]
    Google = None  # type: ignore[assignment,misc]
    ModelId = None  # type: ignore[assignment,misc]
    OpenAI = None  # type: ignore[assignment,misc]
    Vllm = None  # type: ignore[assignment,misc]
from .conversational import (
    CompactionPolicy,
    ConversationalAgent,
    MultiFlowArtifact,
)
from .constants import (
    CAPABILITY_BASH,
    CAPABILITY_HTTP_GET,
    CAPABILITY_HTTP_POST,
    CAPABILITY_MANAGE_TASK,
    CAPABILITY_READ,
    CAPABILITY_SCHEDULE,
    CAPABILITY_SEARCH_SKILLS,
    CAPABILITY_SEARCH_WEB,
    CAPABILITY_WRITE,
    TOOL_GROUP_AGENT_MANAGEMENT,
    TOOL_GROUP_AUTHORING,
    TOOL_GROUP_FILE,
    TOOL_GROUP_FILE_READ,
    TOOL_GROUP_FILE_WRITE,
    TOOL_GROUP_HTTP,
    TOOL_GROUP_SEARCH,
    TOOL_GROUP_SKILLS,
    TOOL_GROUP_TASK,
    TOOL_GROUP_WEB,
    TOOL_GROUP_WEB_SEARCH,
    Capability,
    DependencyType,
    ToolGroup,
)
from .hooks import HookFn, HookMode, LifecycleEvent, hook
from .config import (
    AgentConfig,
    BashConfig,
    ExecutionOptions,
    HookConfig,
    HookEvent,
    LoopGuardMiddlewareConfig,
    MiddlewareKind,
    NodePolicy,
    ReadConfig,
    SearchDepth,
    SearchWebConfig,
    TimeoutMiddlewareConfig,
    ToolsConfig,
    WorkflowTargetKind,
    WriteConfig,
)
from .decorators import compile
from .errors import ApxmError, CompilationError, ExecutionError, ServerError
from .execution import (
    CompiledFlow,
    ExecutionMode,
    ExecutionResult,
    ExecutionStats,
    LLMUsage,
    WorkflowRunResult,
    WorkflowCheckpoint,
    close,
    emit_air_if_requested,
    new_session,
    run,
    run_workflow_file,
    validate_graph,
)
from .ir import ApxmGraph, GraphEdge, GraphNode, Parameter
from .module import FlowModule
from .providers import ProviderSpec, list_providers, resolve_provider
from .proxy import GraphRecorder, NodeRef
from .sugar import AgentHandle, Loop, Team, spawn_agent_set
from .tools import FunctionTool, ToolContext, tool
from .paths import agent_cwd, find_repo_root, local_apxm_path, repo_path

__all__ = [
    "_generated",
    "Agent",
    "AgentConfig",
    "AgentHandle",
    "Loop",
    "agent_cwd",
    "Anthropic",
    "ApxmError",
    "ApxmGraph",
    "BackendRegistryError",
    "BackendRoute",
    "BashConfig",
    "BoundAgent",
    "close",
    "compile",
    "CompactionPolicy",
    "CompiledFlow",
    "CompilationError",
    "ConversationalAgent",
    "CAPABILITY_BASH",
    "CAPABILITY_HTTP_GET",
    "CAPABILITY_HTTP_POST",
    "CAPABILITY_MANAGE_TASK",
    "CAPABILITY_MEMORY_SEARCH_FACTS",
    "CAPABILITY_MEMORY_STORE_FACT",
    "CAPABILITY_READ",
    "CAPABILITY_SCHEDULE",
    "CAPABILITY_SEARCH_SKILLS",
    "CAPABILITY_SEARCH_WEB",
    "CAPABILITY_WRITE",
    "Capability",
    "DependencyType",
    "ExecutionError",
    "ExecutionOptions",
    "ExecutionMode",
    "ExecutionResult",
    "ExecutionStats",
    "emit_air_if_requested",
    "FlowModule",
    "find_repo_root",
    "FunctionTool",
    "Google",
    "GraphEdge",
    "GraphNode",
    "GraphRecorder",
    "hook",
    "HookConfig",
    "HookEvent",
    "HookFn",
    "HookMode",
    "MultiFlowArtifact",
    "LLMUsage",
    "config_path",
    "get_backend",
    "list_providers",
    "list_backends",
    "local_apxm_path",
    "LifecycleEvent",
    "LoopGuardMiddlewareConfig",
    "MiddlewareKind",
    "ModelId",
    "new_session",
    "NodePolicy",
    "NodeRef",
    "OpenAI",
    "Parameter",
    "ProviderSpec",
    "ReadConfig",
    "RegisteredBackend",
    "RegisteredModel",
    "run",
    "resolve_provider",
    "repo_path",
    "SearchWebConfig",
    "SearchDepth",
    "ServerError",
    "select",
    "select_backend",
    "spawn_agent_set",
    "Team",
    "TimeoutMiddlewareConfig",
    "tool",
    "ToolContext",
    "ToolGroup",
    "TOOL_GROUP_AGENT_MANAGEMENT",
    "TOOL_GROUP_AUTHORING",
    "TOOL_GROUP_FILE",
    "TOOL_GROUP_FILE_READ",
    "TOOL_GROUP_FILE_WRITE",
    "TOOL_GROUP_HTTP",
    "TOOL_GROUP_SEARCH",
    "TOOL_GROUP_SKILLS",
    "TOOL_GROUP_TASK",
    "TOOL_GROUP_WEB",
    "TOOL_GROUP_WEB_SEARCH",
    "ToolsConfig",
    "validate_graph",
    "Vllm",
    "WorkflowTargetKind",
    "WorkflowCheckpoint",
    "WorkflowRunResult",
    "WriteConfig",
    "run_workflow_file",
]
