/**
 * TSF-4: Python frontend parity lock.
 *
 * `workspace/contracts/vectors/air/*.air` (shared with the Rust and Python
 * frontends — see `crates/compiler/pipeline/tests/air_vectors.rs` and
 * `crates/compiler/frontend/python/apxm/ir.py`) are the cross-frontend AIR
 * reference vectors. Three of the six fixtures (`multi_agent_delegate`,
 * `capability_pipeline`, `checkpoint_pipeline`) were generated by Python's
 * `GraphRecorder.to_graph().to_air()` reference emitter (WF-3) and are
 * reproducible byte-for-byte from an equivalent TypeScript `GraphBuilder`
 * graph — this test locks that parity so it can't silently regress.
 *
 * The other three fixtures (`approval_gate`, `converse_agent`,
 * `runtime_agent_routing`) predate the current op-spec-driven emitter on
 * both frontends: they use syntax the current reference emitter does not
 * produce (quoted attribute keys, `ais.return` instead of `func.return`,
 * `RESUME`/`AUTONOMOUS` field text current `emission.py` doesn't render).
 * Python's own `GraphRecorder` cannot currently reproduce them either, so
 * there is nothing for TypeScript to construct parity against — they're
 * checked only for existence/readability here, not byte-diffed.
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { GraphBuilder } from "../src/builder.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// crates/compiler/frontend/typescript/test -> workspace/contracts/vectors/air
// (workspace/agents and workspace/contracts are sibling repos under workspace/).
const CONTRACTS_AIR_DIR = path.resolve(
  __dirname,
  "../../../../../../contracts/vectors/air",
);

function readFixture(name: string): string {
  return readFileSync(path.join(CONTRACTS_AIR_DIR, `${name}.air`), "utf-8");
}

/** Strip the leading `//`-comment documentation header, keeping from `module {` on. */
function stripHeaderComment(airText: string): string {
  const idx = airText.indexOf("module {");
  return idx === -1 ? airText : airText.slice(idx);
}

describe("TSF-4: TS/Python AIR emission parity", () => {
  it("multi_agent_delegate: spawn_agent + delegate + communicate byte-matches the Python reference", () => {
    const g = new GraphBuilder("multi_agent_delegate");
    g.spawnAgent({ name: "spawn_worker", agentName: "worker", agentRoute: "auto" });
    const task = g.delegate({
      name: "delegate_task",
      taskSpec: "Summarize the quarterly report.",
      targetAgent: "worker",
    });
    const reply = g.communicate({
      name: "collect_result",
      targetAgent: "worker",
      message: "Findings so far: {task}. Send back your final summary.",
      inputs: { task },
    });
    g.done(reply);

    const tsAir = g.toAir();
    const pyAir = stripHeaderComment(readFixture("multi_agent_delegate")).replace(/\n$/, "");
    expect(tsAir).toBe(pyAir);
  });

  it("capability_pipeline: register_capability + chained invoke_capability byte-matches the Python reference", () => {
    const g = new GraphBuilder("capability_pipeline");
    const registered = g.registerCapability({
      name: "register_lookup",
      capabilityName: "lookup_docs",
      description: "Look up internal documentation by query.",
      parametersSchema: '{"type": "object", "properties": {"query": {"type": "string"}}}',
    });
    const lookup = g.invokeCapability({
      name: "invoke_lookup",
      capability: "lookup_docs",
      params: '{"query": "release checklist"}',
    });
    g.addEdge(registered, lookup, "Control");
    const digest = g.invokeCapability({
      name: "invoke_digest",
      capability: "summarize_text",
      params: '{"text": "{lookup}"}',
      inputs: { lookup },
    });
    g.done(digest);

    const tsAir = g.toAir();
    const pyAir = stripHeaderComment(readFixture("capability_pipeline")).replace(/\n$/, "");
    expect(tsAir).toBe(pyAir);
  });

  it("checkpoint_pipeline: ask -> checkpoint -> ask byte-matches the Python reference", () => {
    const g = new GraphBuilder("checkpoint_pipeline");
    const draft = g.ask({ name: "draft_notes", prompt: "Draft release notes for version {version}." });
    const gate = g.checkpoint("await_signoff");
    g.addEdge(draft, gate, "Control");
    const final = g.ask({
      name: "polish_notes",
      prompt: "Polish this release-notes draft:\n\n{draft}",
      inputs: { draft },
    });
    g.addEdge(gate, final, "Control");
    g.done(final);

    const tsAir = g.toAir();
    const pyAir = stripHeaderComment(readFixture("checkpoint_pipeline")).replace(/\n$/, "");
    expect(tsAir).toBe(pyAir);
  });

  // approval_gate / converse_agent / runtime_agent_routing predate the
  // current reference emitter (see file header above) and aren't
  // GraphBuilder-reproducible on either frontend today; only confirm the
  // fixture files are present and non-empty so a future re-generation of
  // these three (making them GraphRecorder-reproducible again) is expected
  // to extend this suite with real byte-diff cases.
  it.each(["approval_gate", "converse_agent", "runtime_agent_routing"])(
    "%s: fixture file exists (legacy, not GraphBuilder-reproducible — see file header)",
    (name) => {
      const text = readFixture(name);
      expect(text.length).toBeGreaterThan(0);
      expect(text).toContain("module {");
    },
  );
});
