// AUTO-GENERATED by apxm codegen frontend-conformance; DO NOT EDIT.
// Every apxm.frontend-conformance vector, against the TypeScript frontend.

import { describe, expect, it } from "vitest";

import { VECTOR_IDS, runVector } from "../src/generated/conformance.ts";

describe("frontend conformance corpus", () => {
  it("projects every corpus vector", () => {
    expect(VECTOR_IDS).toEqual([
      "minimal_model_agent",
      "initial_context_assignment",
      "contextual_tool_loop",
      "capability_declared_twice",
      "composed_agent_event_and_task_group",
      "resumable_loop_block_arguments",
      "nested_loop_hook_targets_inner_loop",
      "agent_scope_hook_wraps_the_agent_body",
      "same_phase_hooks_run_in_declaration_order",
      "negative_integer_at_safe_boundary",
      "skill_carried_by_package_entry",
      "skill_written_inline_in_source",
      "rejects_unresolved_returned_call",
      "rejects_unresolved_operand_call",
      "rejects_effect_read_as_data",
      "rejects_extra_authored_operands",
      "rejects_predicate_integer_outside_safe_domain",
      "rejects_local_binding_shadowing_a_declared_marker",
      "rejects_display_name_marker_references",
      "rejects_handler_object_marker_references",
      "rejects_skill_with_no_instruction_source",
    ]);
  });

  for (const vectorId of VECTOR_IDS) {
    it(vectorId, () => {
      expect(runVector(vectorId).join("\n")).toBe("");
    });
  }
});
