// AUTO-GENERATED by apxm codegen typescript; DO NOT EDIT.

export type FieldSpec = {
  readonly name: string;
  readonly description: string;
  readonly required: boolean;
  readonly refType: string | null;
};

export type OpSpec = {
  readonly op: string;
  readonly name: string;
  readonly category: OpCategory;
  readonly description: string;
  readonly longDescription: string;
  readonly latency: string;
  readonly fields: readonly FieldSpec[];
  readonly producesOutput: boolean;
  readonly needsSubmission: boolean;
  readonly minInputs: number;
  readonly exampleJson: string | null;
};

export const AGENT: OpSpec = {
  op: "AGENT",
  name: "Agent",
  category: "metadata" as OpCategory,
  description: "Agent structural declaration (memory, beliefs, goals, capabilities)",
  longDescription: "Declares an agent's identity and initial AAM state. Every graph must have exactly one AGENT node. It configures memory tiers (STM/LTM/Episodic), initial beliefs and goals, and the capabilities the agent can invoke. The runtime uses this to initialize the agent's AAM before executing any other node.",
  latency: "none",
  fields: [
    { name: "memory", description: "Memory configuration", required: false, refType: null },
    { name: "beliefs", description: "Initial beliefs", required: false, refType: null },
    { name: "goals", description: "Initial goals", required: false, refType: null },
    { name: "capabilities", description: "Available capabilities", required: false, refType: null },
  ],
  producesOutput: false,
  needsSubmission: false,
  minInputs: 0,
  exampleJson: "{\"id\": 0, \"op\": \"AGENT\", \"attributes\": {\"memory\": {\"stm\": true}, \"beliefs\": {\"role\": \"analyst\"}, \"goals\": [\"summarize data\"], \"capabilities\": [\"search\", \"calculate\"]}}",
} as const;

export const QMEM: OpSpec = {
  op: "QMEM",
  name: "QueryMemory",
  category: "memory" as OpCategory,
  description: "Retrieve data from memory (STM, LTM, or Episodic)",
  longDescription: "Reads from the agent's memory system. Supports three tiers: STM (short-term, per-execution scratch), LTM (long-term, persists across runs), and Episodic (execution traces). The query string is matched against stored keys. Returns the stored value or null if not found.",
  latency: "low",
  fields: [
    { name: "query", description: "Query string or key to search for", required: true, refType: null },
    { name: "memory_tier", description: "Target memory tier: stm, ltm, or episodic", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 2, \"op\": \"QMEM\", \"attributes\": {\"query\": \"user_name\", \"memory_tier\": \"stm\"}}",
} as const;

export const UMEM: OpSpec = {
  op: "UMEM",
  name: "UpdateMemory",
  category: "memory" as OpCategory,
  description: "Persist or update data in memory",
  longDescription: "Writes a key-value pair to the agent's memory system. If the key already exists, the value is overwritten. Supports the same three memory tiers as QMEM. Use FENCE after UMEM if subsequent QMEM nodes must see the write.",
  latency: "low",
  fields: [
    { name: "key", description: "Key to store the value under", required: true, refType: null },
    { name: "value", description: "Value to store", required: true, refType: null },
    { name: "memory_tier", description: "Target memory tier: stm, ltm, or episodic", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 3, \"op\": \"UMEM\", \"attributes\": {\"key\": \"summary\", \"value\": \"Rust favors explicit ownership and borrowing.\", \"memory_tier\": \"stm\"}}",
} as const;

export const ASK: OpSpec = {
  op: "ASK",
  name: "Ask",
  category: "reasoning" as OpCategory,
  description: "Simple Q&A with LLM (no extended thinking) - LOW latency",
  longDescription: "Sends a prompt to the configured LLM and returns the response. The lightest LLM operation — no chain-of-thought or extended thinking. Use for straightforward questions, classifications, extractions, or reformulations. Template strings support named `{input}` interpolation for dataflow inputs via the node's `input_names` array.",
  latency: "medium",
  fields: [
    { name: "template_str", description: "Prompt template for the question", required: true, refType: null },
    { name: "temperature", description: "Sampling temperature (0.0-1.0)", required: false, refType: null },
    { name: "model", description: "LLM model override (uses config default)", required: false, refType: "model" },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 1, \"op\": \"ASK\", \"attributes\": {\"template_str\": \"Summarize: {source}\", \"input_names\": [\"source\"]}}",
} as const;

export const THINK: OpSpec = {
  op: "THINK",
  name: "Think",
  category: "reasoning" as OpCategory,
  description: "Extended thinking with token_budget - HIGH latency",
  longDescription: "Activates extended thinking (chain-of-thought) with a configurable token budget. The LLM produces internal reasoning before the final answer. Use for complex multi-step problems, math, code generation, or planning that benefits from deliberate reasoning. The budget controls how many tokens the model can spend thinking.",
  latency: "high",
  fields: [
    { name: "template_str", description: "Prompt template for deep reasoning", required: true, refType: null },
    { name: "budget", description: "Token budget for extended thinking", required: false, refType: null },
    { name: "temperature", description: "Sampling temperature (0.0-1.0)", required: false, refType: null },
    { name: "model", description: "LLM model override (uses config default)", required: false, refType: "model" },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 1, \"op\": \"THINK\", \"attributes\": {\"template_str\": \"Solve step by step: {problem}\", \"input_names\": [\"problem\"], \"budget\": 4096}}",
} as const;

export const REASON: OpSpec = {
  op: "REASON",
  name: "Reason",
  category: "reasoning" as OpCategory,
  description: "Structured reasoning with belief/goal updates - MEDIUM latency",
  longDescription: "Performs structured reasoning that can update the agent's beliefs and goals (AAM state). Unlike ASK, the runtime parses the LLM response for belief and goal mutations. Use when the agent needs to update its internal state based on new information. Supports structured JSON output mode.",
  latency: "medium",
  fields: [
    { name: "template_str", description: "Prompt template for structured reasoning", required: true, refType: null },
    { name: "temperature", description: "Sampling temperature (0.0-1.0)", required: false, refType: null },
    { name: "model", description: "LLM model override (uses config default)", required: false, refType: "model" },
    { name: "structured", description: "Enable structured JSON output", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 1, \"op\": \"REASON\", \"attributes\": {\"template_str\": \"Given {evidence}, update your analysis\", \"input_names\": [\"evidence\"], \"structured\": true}}",
} as const;

export const PLAN: OpSpec = {
  op: "PLAN",
  name: "Plan",
  category: "reasoning" as OpCategory,
  description: "Decompose goal into AIS subgraph",
  longDescription: "Uses the LLM to decompose a high-level goal into a sequence of concrete steps. The output is a structured plan that can be used to drive subsequent nodes. Supports optional constraints to bound the plan space.",
  latency: "high",
  fields: [
    { name: "goal", description: "Goal to decompose into steps", required: true, refType: null },
    { name: "constraints", description: "Constraints on the plan", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 1, \"op\": \"PLAN\", \"attributes\": {\"goal\": \"Research and summarize recent AI papers\", \"constraints\": \"max 5 steps\"}}",
} as const;

export const REFLECT: OpSpec = {
  op: "REFLECT",
  name: "Reflect",
  category: "reasoning" as OpCategory,
  description: "Analyze execution trace for self-improvement",
  longDescription: "Retrieves past execution traces and asks the LLM to analyze them for patterns, failures, or improvements. Useful for iterative refinement loops where the agent learns from its own execution history.",
  latency: "medium",
  fields: [
    { name: "trace_query", description: "Query to retrieve trace for reflection", required: true, refType: null },
    { name: "reflection_prompt", description: "Custom prompt for reflection", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 4, \"op\": \"REFLECT\", \"attributes\": {\"trace_query\": \"last_execution\"}}",
} as const;

export const VERIFY: OpSpec = {
  op: "VERIFY",
  name: "Verify",
  category: "reasoning" as OpCategory,
  description: "Fact-check outputs against evidence",
  longDescription: "Cross-references a claim against provided evidence using the LLM. Returns a verification result with confidence score. Use after ASK/THINK/REASON nodes to validate outputs before acting on them. Evidence may be supplied either as a literal attribute or via an incoming Data edge.",
  latency: "medium",
  fields: [
    { name: "claim", description: "Claim to verify", required: true, refType: null },
    { name: "evidence", description: "Evidence to check against", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 5, \"op\": \"VERIFY\", \"attributes\": {\"claim\": \"The solar system has eight planets.\"}}",
} as const;

export const INV_TOOL: OpSpec = {
  op: "INV_TOOL",
  name: "InvokeTool",
  category: "tools" as OpCategory,
  description: "Call external tool with structured params; store result",
  longDescription: "Invokes a registered capability (tool or function) by name. The capability must be declared in the AGENT node's capabilities list or registered in the runtime's CapabilityRegistry. Parameters are passed via the `params_json` attribute as a JSON object. The tool's return value becomes this node's output token.",
  latency: "medium",
  fields: [
    { name: "capability", description: "Name of the capability/tool to invoke", required: true, refType: "capability" },
    { name: "params_json", description: "JSON-encoded parameters to pass to the tool", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 2, \"op\": \"INV_TOOL\", \"attributes\": {\"capability\": \"web_search\", \"params_json\": \"{\\\"query\\\":\\\"rust ownership\\\"}\"}}",
} as const;

export const EXC: OpSpec = {
  op: "EXC",
  name: "ExecuteCode",
  category: "tools" as OpCategory,
  description: "Run code in a sandboxed environment; update Beliefs",
  longDescription: "Executes arbitrary code in a sandboxed environment. The sandbox prevents file system access, network calls, and other side effects unless explicitly allowed. The code's stdout/return value becomes the output token. Execution results are also written to the agent's beliefs.",
  latency: "low",
  fields: [
    { name: "code", description: "Code to execute", required: true, refType: null },
    { name: "sandbox_config", description: "Sandbox configuration", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 3, \"op\": \"EXC\", \"attributes\": {\"code\": \"print(2 + 2)\"}}",
} as const;

export const PRINT: OpSpec = {
  op: "PRINT",
  name: "PrintOutput",
  category: "tools" as OpCategory,
  description: "Print output to stdout for debugging or user display",
  longDescription: "Writes a message to stdout. Supports named `{input}` template interpolation via `input_names`. Useful for debugging graphs during development or displaying final results to the user. The message is also stored as the output token.",
  latency: "none",
  fields: [
    { name: "message", description: "Message to print", required: true, refType: null },
  ],
  producesOutput: false,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 4, \"op\": \"PRINT\", \"attributes\": {\"message\": \"Result: {result}\", \"input_names\": [\"result\"]}}",
} as const;

export const JUMP: OpSpec = {
  op: "JUMP",
  name: "Jump",
  category: "control_flow" as OpCategory,
  description: "Unconditional jump to a labeled instruction",
  longDescription: "Transfers control flow unconditionally to a target label. The label must correspond to a node ID in the graph. Edges from this node use Control dependency type.",
  latency: "none",
  fields: [
    { name: "label", description: "Target label to jump to", required: true, refType: null },
  ],
  producesOutput: false,
  needsSubmission: false,
  minInputs: 0,
  exampleJson: "{\"id\": 5, \"op\": \"JUMP\", \"attributes\": {\"label\": \"7\"}}",
} as const;

export const BRANCH_ON_VALUE: OpSpec = {
  op: "BRANCH_ON_VALUE",
  name: "BranchOnValue",
  category: "control_flow" as OpCategory,
  description: "Conditional branch based on token value comparison",
  longDescription: "Evaluates an input token against a value and branches to one of two labels. If the token matches the value, control goes to label_true; otherwise to label_false. Used for if/else patterns in agent workflows.",
  latency: "none",
  fields: [
    { name: "value", description: "Value to compare against", required: true, refType: null },
    { name: "true_label", description: "Label if comparison is true", required: true, refType: null },
    { name: "false_label", description: "Label if comparison is false", required: true, refType: null },
  ],
  producesOutput: false,
  needsSubmission: false,
  minInputs: 1,
  exampleJson: "{\"id\": 5, \"op\": \"BRANCH_ON_VALUE\", \"attributes\": {\"value\": \"yes\", \"true_label\": \"6\", \"false_label\": \"7\"}}",
} as const;

export const LOOP_START: OpSpec = {
  op: "LOOP_START",
  name: "LoopStart",
  category: "control_flow" as OpCategory,
  description: "Begin bounded loop",
  longDescription: "Marks the beginning of a bounded loop. The count_token specifies how many iterations to execute. Must be paired with a LOOP_END node. The compiler verifies loop bounds at compile time to prevent infinite loops.",
  latency: "none",
  fields: [
    { name: "count_token", description: "Token containing iteration count", required: true, refType: null },
  ],
  producesOutput: false,
  needsSubmission: false,
  minInputs: 1,
  exampleJson: "{\"id\": 3, \"op\": \"LOOP_START\", \"attributes\": {\"count_token\": \"3\"}}",
} as const;

export const LOOP_END: OpSpec = {
  op: "LOOP_END",
  name: "LoopEnd",
  category: "control_flow" as OpCategory,
  description: "End bounded loop",
  longDescription: "Marks the end of a bounded loop started by LOOP_START. The runtime decrements the loop counter and branches back to LOOP_START if iterations remain.",
  latency: "none",
  fields: [
  ],
  producesOutput: false,
  needsSubmission: false,
  minInputs: 0,
  exampleJson: null,
} as const;

export const RETURN: OpSpec = {
  op: "RETURN",
  name: "Return",
  category: "control_flow" as OpCategory,
  description: "Return from subgraph with result token",
  longDescription: "Returns a value from a subgraph or flow. The result value is provided via an incoming Data edge.",
  latency: "none",
  fields: [
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 1,
  exampleJson: "{\"id\": 6, \"op\": \"RETURN\", \"attributes\": {}}",
} as const;

export const SWITCH: OpSpec = {
  op: "SWITCH",
  name: "Switch",
  category: "control_flow" as OpCategory,
  description: "Multi-way branch based on string value comparison",
  longDescription: "Routes execution to one of several branches based on matching a discriminant token against case labels. Each case specifies a label string and a destination node. If no case matches, the default destination is used. The matched branch's result becomes the output token.",
  latency: "none",
  fields: [
    { name: "discriminant", description: "Token to match against case labels", required: true, refType: null },
    { name: "cases", description: "Array of case label/destination pairs", required: true, refType: null },
    { name: "default", description: "Default destination if no case matches", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 1,
  exampleJson: "{\"id\": 3, \"op\": \"SWITCH\", \"attributes\": {\"discriminant\": \"topic_kind\", \"cases\": [{\"label\": \"math\", \"node_id\": 4}, {\"label\": \"code\", \"node_id\": 5}], \"default\": \"6\"}}",
} as const;

export const FLOW_CALL: OpSpec = {
  op: "FLOW_CALL",
  name: "FlowCall",
  category: "control_flow" as OpCategory,
  description: "Call a flow on another agent with implicit parallelism",
  longDescription: "Invokes a named flow on a target agent. The target agent executes its flow graph independently and returns the result. Multiple FLOW_CALL nodes can execute in parallel if they have no data dependencies between them. This is the primary mechanism for multi-agent composition.",
  latency: "high",
  fields: [
    { name: "agent_name", description: "Name of the agent to call", required: true, refType: null },
    { name: "flow_name", description: "Name of the flow to invoke", required: true, refType: null },
    { name: "args", description: "Arguments to pass to the flow", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 4, \"op\": \"FLOW_CALL\", \"attributes\": {\"agent_name\": \"researcher\", \"flow_name\": \"analyze\", \"args\": {\"topic\": \"{topic}\"}, \"input_names\": [\"topic\"]}}",
} as const;

export const WORKFLOW_SPAWN: OpSpec = {
  op: "WORKFLOW_SPAWN",
  name: "WorkflowSpawn",
  category: "control_flow" as OpCategory,
  description: "Spawn an external graph, artifact, or workflow as a child execution",
  longDescription: "Invokes an external graph file, precompiled artifact, or workflow file as a child execution boundary. Arguments are passed by name through the args map. The child run resolves its session root from the explicit node attribute when present, otherwise it inherits the parent execution root.",
  latency: "high",
  fields: [
    { name: "target_kind", description: "Invocation target kind: graph_path, artifact_path, or workflow_path", required: true, refType: null },
    { name: "target", description: "Path of the graph, artifact, or workflow to execute", required: true, refType: null },
    { name: "args", description: "Arguments to pass to the child execution", required: false, refType: null },
    { name: "session_root", description: "Explicit session root for the child execution", required: false, refType: null },
    { name: "await_result", description: "Whether to wait for the child result (must be true in the current runtime)", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 5, \"op\": \"WORKFLOW_SPAWN\", \"attributes\": {\"target_kind\": \"workflow_path\", \"target\": \"workflows/review.apxmw\", \"args\": {\"topic\": \"{topic}\"}, \"input_names\": [\"topic\"], \"await_result\": true}}",
} as const;

export const MERGE: OpSpec = {
  op: "MERGE",
  name: "Merge",
  category: "synchronization" as OpCategory,
  description: "Sync parallel paths; aggregate tokens into one",
  longDescription: "Waits for multiple parallel branches to complete and combines their output tokens into a single aggregated result. Inputs are provided via incoming Data edges.",
  latency: "none",
  fields: [
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 1,
  exampleJson: "{\"id\": 6, \"op\": \"MERGE\", \"attributes\": {}}",
} as const;

export const FENCE: OpSpec = {
  op: "FENCE",
  name: "Fence",
  category: "synchronization" as OpCategory,
  description: "Memory barrier; order prior QMEM/UMEM operations",
  longDescription: "Ensures all preceding memory operations (UMEM writes) are visible to subsequent QMEM reads. Without a FENCE, the scheduler may reorder memory operations for parallelism. Place between UMEM and QMEM when ordering matters.",
  latency: "none",
  fields: [
    { name: "ordering", description: "Memory ordering constraint", required: false, refType: null },
  ],
  producesOutput: false,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: null,
} as const;

export const WAIT_ALL: OpSpec = {
  op: "WAIT_ALL",
  name: "WaitAll",
  category: "synchronization" as OpCategory,
  description: "Block until all specified tokens are available",
  longDescription: "Blocks execution until all listed input tokens are ready. Unlike MERGE, it does not combine the tokens — it simply acts as a synchronization barrier. Inputs are provided via incoming Data edges.",
  latency: "none",
  fields: [
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 1,
  exampleJson: "{\"id\": 5, \"op\": \"WAIT_ALL\", \"attributes\": {}}",
} as const;

export const TRY_CATCH: OpSpec = {
  op: "TRY_CATCH",
  name: "TryCatch",
  category: "error_handling" as OpCategory,
  description: "Structured exception handling with recovery subgraph",
  longDescription: "Wraps a try subgraph with a catch recovery subgraph. If any node in the try subgraph fails, execution transfers to the catch subgraph. The catch subgraph receives the error context and can attempt recovery or graceful degradation.",
  latency: "none",
  fields: [
    { name: "try_label", description: "Subgraph to try executing", required: true, refType: null },
    { name: "catch_label", description: "Recovery subgraph on failure", required: true, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 2, \"op\": \"TRY_CATCH\", \"attributes\": {\"try_label\": \"3\", \"catch_label\": \"4\"}}",
} as const;

export const ERR: OpSpec = {
  op: "ERR",
  name: "HandleError",
  category: "error_handling" as OpCategory,
  description: "Invoke recovery template on failure; update Goals/Beliefs",
  longDescription: "Handles an error by invoking a recovery template. The error handler can update the agent's goals and beliefs to reflect the failure and adapt the agent's strategy. Typically used inside TRY_CATCH catch subgraphs.",
  latency: "medium",
  fields: [
    { name: "error_handler", description: "Error handler to invoke", required: true, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 4, \"op\": \"ERR\", \"attributes\": {\"error_handler\": \"retry_with_fallback\"}}",
} as const;

export const COMMUNICATE: OpSpec = {
  op: "COMMUNICATE",
  name: "Communicate",
  category: "communication" as OpCategory,
  description: "Send message to recipient agent via selected protocol",
  longDescription: "Sends a message from this agent to another agent. The message is received via input tokens from upstream edges. Supports four protocol dispatch modes: 'local' (default, in-process sub-flow), 'http'/'https' (external APXM agent), 'acp' (ACP subprocess via ProcessTable), and 'broadcast' (fan-out to all agents). The recipient attribute accepts 'recipient' or 'target' as key.",
  latency: "medium",
  fields: [
    { name: "recipient", description: "Target agent name (or URL for http protocol)", required: true, refType: null },
    { name: "message", description: "Message content to send", required: false, refType: null },
    { name: "protocol", description: "Dispatch protocol: local (default), http, https, acp, broadcast", required: false, refType: null },
    { name: "llm_operation", description: "Semantic LLM operation for analysis when this communication sends an agent prompt", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 3, \"op\": \"COMMUNICATE\", \"attributes\": {\"recipient\": \"reviewer\", \"protocol\": \"acp\"}}",
} as const;

export const HANDOFF: OpSpec = {
  op: "HANDOFF",
  name: "Handoff",
  category: "communication" as OpCategory,
  description: "Hand off execution from one agent to another with optional state transfer",
  longDescription: "Transfers execution control from a source agent to a target agent. When transfer_state is true, the source agent's context-stack frames are copied to the target agent so it can continue with full conversational context. Emits HANDOFF_START and HANDOFF_END events with span continuity for tracing. The target agent's response becomes this node's output token.",
  latency: "medium",
  fields: [
    { name: "handoff_from", description: "Source agent name", required: true, refType: null },
    { name: "handoff_to", description: "Target agent name", required: true, refType: null },
    { name: "payload", description: "Message payload to pass to the target agent", required: false, refType: null },
    { name: "transfer_state", description: "Whether to copy context-stack frames from source to target (default: true)", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 1,
  exampleJson: "{\"id\": 3, \"op\": \"HANDOFF\", \"attributes\": {\"handoff_from\": \"agent_a\", \"handoff_to\": \"agent_b\", \"transfer_state\": true}}",
} as const;

export const UPDATE_GOAL: OpSpec = {
  op: "UPDATE_GOAL",
  name: "UpdateGoal",
  category: "memory" as OpCategory,
  description: "Modify AAM goals at runtime: set, remove, or clear",
  longDescription: "Dynamically modifies the agent's goal set during execution. Supports three actions: 'set' (upsert a goal with priority), 'remove' (delete a specific goal), and 'clear' (remove all goals). Goal changes are visible to subsequent REASON and REFLECT nodes.",
  latency: "none",
  fields: [
    { name: "goal_id", description: "Goal identifier (used as description key for upsert/remove)", required: true, refType: null },
    { name: "action", description: "Action to perform: set (default), remove, clear", required: false, refType: null },
    { name: "priority", description: "Goal priority (u32, default: 1)", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 0,
  exampleJson: "{\"id\": 3, \"op\": \"UPDATE_GOAL\", \"attributes\": {\"goal_id\": \"optimize_latency\", \"action\": \"set\", \"priority\": 2}}",
} as const;

export const GUARD: OpSpec = {
  op: "GUARD",
  name: "Guard",
  category: "control_flow" as OpCategory,
  description: "Enforce preconditions: halt or skip based on condition",
  longDescription: "Evaluates a condition expression against the input token. If the condition fails, the guard either halts execution with an error or skips the downstream subgraph (configurable via on_fail). Use to enforce invariants like confidence thresholds, non-null checks, or content validation.",
  latency: "none",
  fields: [
    { name: "condition", description: "Condition expression: '> 0.8', '!= null', 'not_empty', etc.", required: true, refType: null },
    { name: "error_message", description: "Message on failure", required: false, refType: null },
    { name: "on_fail", description: "Failure mode: halt (default) or skip", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 1,
  exampleJson: "{\"id\": 3, \"op\": \"GUARD\", \"attributes\": {\"condition\": \"> 0.8\", \"on_fail\": \"skip\", \"error_message\": \"Confidence too low\"}}",
} as const;

export const CLAIM: OpSpec = {
  op: "CLAIM",
  name: "Claim",
  category: "communication" as OpCategory,
  description: "Atomically claim a task from a shared work queue via APXM server",
  longDescription: "Claims a task from a distributed work queue managed by the APXM server. The claim is atomic — only one agent gets each task. The claimed task is leased for a configurable duration. If the agent doesn't complete within the lease, the task returns to the queue for other agents.",
  latency: "low",
  fields: [
    { name: "queue", description: "Queue name to claim from", required: true, refType: null },
    { name: "lease_ms", description: "Lease duration in ms (default: 60000)", required: false, refType: null },
    { name: "max_wait_ms", description: "Max time to wait for a task (default: 5000)", required: false, refType: null },
    { name: "server_url", description: "Override APXM_SERVER_URL env var", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 2, \"op\": \"CLAIM\", \"attributes\": {\"queue\": \"review_tasks\", \"lease_ms\": 30000}}",
} as const;

export const PAUSE: OpSpec = {
  op: "PAUSE",
  name: "Pause",
  category: "communication" as OpCategory,
  description: "Suspend execution pending human-in-the-loop review via checkpoint",
  longDescription: "Creates a checkpoint and suspends execution until a human resumes it via the APXM server API. The pause message is displayed to the human reviewer. Optionally sends a webhook notification. The human can provide input that becomes this node's output token when RESUME is called.",
  latency: "high",
  fields: [
    { name: "message", description: "Human-readable message explaining the pause", required: true, refType: null },
    { name: "checkpoint_id", description: "Stable checkpoint ID (auto-generated if omitted)", required: false, refType: null },
    { name: "timeout_ms", description: "Max wait in ms (0 = indefinite, default: 0)", required: false, refType: null },
    { name: "poll_interval_ms", description: "Polling interval in ms (default: 2000)", required: false, refType: null },
    { name: "notification_url", description: "Webhook URL to notify on pause creation", required: false, refType: null },
    { name: "server_url", description: "Override APXM_SERVER_URL env var", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 5, \"op\": \"PAUSE\", \"attributes\": {\"message\": \"Please review the analysis before proceeding\"}}",
} as const;

export const RESUME: OpSpec = {
  op: "RESUME",
  name: "Resume",
  category: "control_flow" as OpCategory,
  description: "Resume a suspended PAUSE checkpoint; polls server until human resumes; returns human_input",
  longDescription: "Polls the APXM server for a specific checkpoint until a human resumes it. When resumed, the human's input (if any) becomes this node's output token. Configurable polling interval and max attempts prevent indefinite blocking.",
  latency: "high",
  fields: [
    { name: "checkpoint", description: "Checkpoint ID to resume from", required: true, refType: null },
    { name: "poll_max_attempts", description: "Max polling attempts (default 60 × 5s = 5 min)", required: false, refType: null },
    { name: "poll_interval_ms", description: "Interval between polls in ms (default 5000)", required: false, refType: null },
    { name: "server_url", description: "Override APXM_SERVER_URL env var", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 6, \"op\": \"RESUME\", \"attributes\": {\"checkpoint\": \"review_checkpoint_1\"}}",
} as const;

export const DELEGATE: OpSpec = {
  op: "DELEGATE",
  name: "Delegate",
  category: "coordination" as OpCategory,
  description: "Delegate a task to a sub-agent for execution",
  longDescription: "Creates a sub-task from a task specification and assigns it to a target agent. Returns a task handle that can be used to track the delegated work. The target agent executes the task independently and reports results back.",
  latency: "medium",
  fields: [
    { name: "task_spec", description: "Description of the task to delegate", required: true, refType: null },
    { name: "target_agent", description: "Name of the agent to delegate to", required: true, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\\\"id\\\": 3, \\\"op\\\": \\\"DELEGATE\\\", \\\"attributes\\\": {\\\"task_spec\\\": \\\"Analyze the dataset\\\", \\\"target_agent\\\": \\\"analyst\\\"}}",
} as const;

export const NEGOTIATE: OpSpec = {
  op: "NEGOTIATE",
  name: "Negotiate",
  category: "coordination" as OpCategory,
  description: "Multi-agent negotiation protocol for consensus building",
  longDescription: "Initiates a multi-party negotiation protocol among a set of agents. A proposal is circulated to all parties for a configurable number of rounds. Returns the consensus result or a timeout if no agreement is reached.",
  latency: "high",
  fields: [
    { name: "parties", description: "List of agent names participating in negotiation", required: true, refType: null },
    { name: "proposal", description: "The proposal to negotiate on", required: true, refType: null },
    { name: "max_rounds", description: "Maximum negotiation rounds (default: 3)", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\\\"id\\\": 4, \\\"op\\\": \\\"NEGOTIATE\\\", \\\"attributes\\\": {\\\"parties\\\": [\\\"agent_a\\\", \\\"agent_b\\\"], \\\"proposal\\\": \\\"Choose the best approach\\\", \\\"max_rounds\\\": 3}}",
} as const;

export const NOP: OpSpec = {
  op: "NOP",
  name: "Nop",
  category: "identity" as OpCategory,
  description: "No-op passthrough with no side effects or AAM transition",
  longDescription: "Pure passthrough operation with no side effects and no AAM state transition. Passes through its first input unchanged, or returns Null if no inputs. Useful as a placeholder, sync point, or structural node in graph composition.",
  latency: "none",
  fields: [
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 0,
  exampleJson: "{\\\"id\\\": 2, \\\"op\\\": \\\"NOP\\\"}",
} as const;

export const IDENTITY: OpSpec = {
  op: "IDENTITY",
  name: "Identity",
  category: "identity" as OpCategory,
  description: "Identity passthrough that records an AAM identity transition",
  longDescription: "Like NOP but produces an AAM identity transition (state unchanged but recorded in the execution trace). Useful for observability when you want to mark a point in the graph without changing state.",
  latency: "none",
  fields: [
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 0,
  exampleJson: "{\\\"id\\\": 2, \\\"op\\\": \\\"IDENTITY\\\"}",
} as const;

export const SPAWN_AGENT: OpSpec = {
  op: "SPAWN_AGENT",
  name: "SpawnAgent",
  category: "coordination" as OpCategory,
  description: "Create a new agent instance at runtime, optionally as an ACP subprocess",
  longDescription: "Spawns a new agent instance. Without 'profile', registers a local process for flow-based agents. With 'profile', spawns a real ACP subprocess through the ProcessTable's AgentSpawner. The agent can then receive COMMUNICATE (protocol 'acp' or 'local') or DELEGATE messages. Returns the agent's identifier and metadata.",
  latency: "medium",
  fields: [
    { name: "agent_name", description: "Name for the new agent", required: true, refType: null },
    { name: "profile", description: "Registered ACP agent profile. When present, spawns an ACP subprocess", required: false, refType: "agent profile" },
    { name: "mode", description: "Agent mode to set after spawn (e.g. 'architect', 'code')", required: false, refType: null },
    { name: "model", description: "Model override accepted by the selected backend", required: false, refType: "model" },
    { name: "cwd", description: "Working directory for the agent subprocess (defaults to current dir)", required: false, refType: null },
    { name: "capabilities", description: "List of capabilities for the new agent", required: false, refType: null },
    { name: "goals", description: "Initial goals for the new agent", required: false, refType: null },
    { name: "system_prompt", description: "System prompt / instructions for inline agents — enables HANDOFF/COMMUNICATE dispatch without registering the agent as a separate compiled flow", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 1, \"op\": \"SPAWN_AGENT\", \"attributes\": {\"agent_name\": \"worker\", \"profile\": \"example-acp-profile\", \"mode\": \"architect\"}}",
} as const;

export const SPAWN_TEAM: OpSpec = {
  op: "SPAWN_TEAM",
  name: "SpawnTeam",
  category: "coordination" as OpCategory,
  description: "Spawn all members of a team (expands to N SPAWN_AGENT operations)",
  longDescription: "Spawns all members of a named team definition from ~/.apxm/teams.toml. Each member is spawned with its configured role, profile, and optional system_prompt. Returns an object containing all spawned agent identifiers. Team definitions are loaded from the TeamRegistry at runtime.",
  latency: "medium",
  fields: [
    { name: "team_name", description: "Name of the team to spawn (from ~/.apxm/teams.toml)", required: true, refType: null },
    { name: "cwd", description: "Working directory for all team member subprocesses (defaults to current dir)", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 1, \"op\": \"SPAWN_TEAM\", \"attributes\": {\"team_name\": \"ultrathink\", \"cwd\": \"/path/to/project\"}}",
} as const;

export const REGISTER_CAPABILITY: OpSpec = {
  op: "REGISTER_CAPABILITY",
  name: "RegisterCapability",
  category: "coordination" as OpCategory,
  description: "Register a new capability (tool) in the runtime registry",
  longDescription: "Dynamically registers a new capability in the runtime's capability registry. The capability becomes available for INV_TOOL operations after registration. Returns a confirmation with the registered capability name.",
  latency: "low",
  fields: [
    { name: "capability_name", description: "Name for the capability to register", required: true, refType: null },
    { name: "description", description: "Human-readable description of the capability", required: false, refType: null },
    { name: "parameters_schema", description: "JSON schema for capability parameters", required: false, refType: null },
    { name: "python_handler_id", description: "Stable content-addressed id (sha256:<hex64>) for a Python-backed tool handler", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\\\"id\\\": 3, \\\"op\\\": \\\"REGISTER_CAPABILITY\\\", \\\"attributes\\\": {\\\"capability_name\\\": \\\"custom_tool\\\", \\\"description\\\": \\\"A custom analysis tool\\\"}}",
} as const;

export const AUTONOMOUS: OpSpec = {
  op: "AUTONOMOUS",
  name: "Autonomous",
  category: "coordination" as OpCategory,
  description: "Run a goal-directed autonomous loop with the configured model",
  longDescription: "Runs an iterative plan / act / evaluate loop against a goal prompt. The node keeps calling the configured model until the goal is achieved or `max_iterations` is reached. Optional backend, model, system prompt, provider, and temperature attributes follow the same routing contract as the other LLM operations.",
  latency: "high",
  fields: [
    { name: "prompt", description: "Goal or objective for the autonomous loop", required: true, refType: null },
    { name: "max_iterations", description: "Maximum number of plan / act / evaluate iterations before stopping", required: false, refType: null },
    { name: "backend", description: "Backend override for the autonomous loop", required: false, refType: "backend" },
    { name: "model", description: "Model override for the autonomous loop", required: false, refType: "model" },
    { name: "provider", description: "Provider override when backend routing is not used", required: false, refType: null },
    { name: "system_prompt", description: "System prompt applied to each model call in the loop", required: false, refType: null },
    { name: "temperature", description: "Sampling temperature for the loop's model calls", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: true,
  minInputs: 0,
  exampleJson: "{\"id\": 3, \"op\": \"AUTONOMOUS\", \"attributes\": {\"prompt\": \"Find the root cause and propose a fix\", \"max_iterations\": 6}}",
} as const;

export const CHECKPOINT: OpSpec = {
  op: "CHECKPOINT",
  name: "Checkpoint",
  category: "synchronization" as OpCategory,
  description: "Create a durable execution checkpoint and emit a manifest token",
  longDescription: "Serializes execution state at a barrier point and persists it under a stable checkpoint identifier. The snapshot captures AAM state plus runtime checkpoint metadata, and emits a manifest token containing the checkpoint id, timestamp, and byte size so downstream nodes can reference the saved state. Execution continues immediately after the snapshot — this is NOT a suspend point (use PAUSE when you need human-gated suspension).",
  latency: "low",
  fields: [
    { name: "checkpoint_id", description: "Stable identifier for this checkpoint", required: true, refType: null },
    { name: "scope", description: "Snapshot scope: full (default) or local", required: false, refType: null },
    { name: "storage", description: "Storage backend: fs (default), memory, or custom", required: false, refType: null },
    { name: "ttl_seconds", description: "Time-to-live for the checkpoint in seconds", required: false, refType: null },
    { name: "on_fail", description: "Failure mode: halt (default) or continue", required: false, refType: null },
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 1,
  exampleJson: "{\"id\": 4, \"op\": \"CHECKPOINT\", \"attributes\": {\"checkpoint_id\": \"before_analysis\"}}",
} as const;

export const CONST_STR: OpSpec = {
  op: "CONST_STR",
  name: "ConstStr",
  category: "internal" as OpCategory,
  description: "String constant (compiler internal for string literals)",
  longDescription: "Compiler-internal operation that produces a constant string value. Not available in the public AIS. The compiler generates CONST_STR nodes when lowering template strings to explicit dataflow.",
  latency: "none",
  fields: [
    { name: "value", description: "The string constant value", required: true, refType: null },
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 0,
  exampleJson: null,
} as const;

export const YIELD: OpSpec = {
  op: "YIELD",
  name: "Yield",
  category: "internal" as OpCategory,
  description: "Yield value from switch case region (terminates region)",
  longDescription: "Compiler-internal operation that terminates a switch case region and yields a value to the parent SWITCH node. Not available in the public AIS.",
  latency: "none",
  fields: [
    { name: "value", description: "The value to yield from the region", required: true, refType: null },
  ],
  producesOutput: true,
  needsSubmission: false,
  minInputs: 1,
  exampleJson: null,
} as const;

export const ALL_OPERATIONS: readonly OpSpec[] = [
  AGENT,
  QMEM,
  UMEM,
  ASK,
  THINK,
  REASON,
  PLAN,
  REFLECT,
  VERIFY,
  INV_TOOL,
  EXC,
  PRINT,
  JUMP,
  BRANCH_ON_VALUE,
  LOOP_START,
  LOOP_END,
  RETURN,
  SWITCH,
  FLOW_CALL,
  WORKFLOW_SPAWN,
  MERGE,
  FENCE,
  WAIT_ALL,
  TRY_CATCH,
  ERR,
  COMMUNICATE,
  HANDOFF,
  UPDATE_GOAL,
  GUARD,
  CLAIM,
  PAUSE,
  RESUME,
  DELEGATE,
  NEGOTIATE,
  NOP,
  IDENTITY,
  SPAWN_AGENT,
  SPAWN_TEAM,
  REGISTER_CAPABILITY,
  AUTONOMOUS,
  CHECKPOINT,
  CONST_STR,
  YIELD,
] as const;

export type OpCategory =
  | "communication"
  | "control_flow"
  | "coordination"
  | "error_handling"
  | "identity"
  | "internal"
  | "memory"
  | "metadata"
  | "reasoning"
  | "synchronization"
  | "tools";

export const ATTR = {
  AGENT_NAME: "agent_name",
  TEAM_NAME: "team_name",
  FLOW_NAME: "flow_name",
  PROFILE: "profile",
  NODE_NAME: "node_name",
  MODE: "mode",
  CWD: "cwd",
  MODEL: "model",
  PROVIDER: "provider",
  API_KEY: "api_key",
  BASE_URL: "base_url",
  TEMPERATURE: "temperature",
  SYSTEM_PROMPT: "system_prompt",
  TOOLS_CONFIG: "tools_config",
  TOKEN_BUDGET: "token_budget",
  OUTPUT_SCHEMA: "output_schema",
  MAX_SCHEMA_RETRIES: "max_schema_retries",
  MAX_ITERATIONS: "max_iterations",
  HANDOFF_TARGETS: "handoff_targets",
  INNER_PLAN_SUPPORTED: "inner_plan_supported",
  ENABLE_INNER_PLAN: "enable_inner_plan",
  BIND_INNER_PLAN_OUTPUTS: "bind_inner_plan_outputs",
  BACKEND: "backend",
  MAX_TOOL_ITERATIONS: "max_tool_iterations",
  BUDGET: "budget",
  TEMPLATE_STR: "template_str",
  PROMPT: "prompt",
  TEMPLATE: "template",
  INPUT_NAMES: "input_names",
  QUERY: "query",
  MEMORY_TIER: "memory_tier",
  KEY: "key",
  VALUE: "value",
  LIMIT: "limit",
  CAPABILITY: "capability",
  PARAMS_JSON: "params_json",
  TOOLS_ENABLED: "tools_enabled",
  TOOLS: "tools",
  TOOL_GROUPS: "tool_groups",
  CODE: "code",
  INTERPRETER: "interpreter",
  CAPABILITY_NAME: "capability_name",
  DESCRIPTION: "description",
  PARAMETERS_SCHEMA: "parameters_schema",
  PYTHON_HANDLER_ID: "python_handler_id",
  MESSAGE: "message",
  RECIPIENT: "recipient",
  TARGET: "target",
  TARGET_KIND: "target_kind",
  PROTOCOL: "protocol",
  LLM_OPERATION: "llm_operation",
  GOAL: "goal",
  GOAL_ID: "goal_id",
  PRIORITY: "priority",
  CONDITION: "condition",
  EVIDENCE: "evidence",
  CLAIM: "claim",
  GUARDRAIL_KIND: "guardrail_kind",
  DISCRIMINANT: "discriminant",
  LABEL: "label",
  TRUE_LABEL: "true_label",
  FALSE_LABEL: "false_label",
  CASE_LABELS: "case_labels",
  TRY_LABEL: "try_label",
  CATCH_LABEL: "catch_label",
  AWAIT_RESULT: "await_result",
  RECOVERY_TEMPLATE: "recovery_template",
  CASE_REGIONS: "case_regions",
  DEFAULT_REGION: "default_region",
  REGION: "region",
  ON_FAIL: "on_fail",
  ERROR_MESSAGE: "error_message",
  SCOPE: "scope",
  STORAGE: "storage",
  TTL_SECONDS: "ttl_seconds",
  STRATEGY: "strategy",
  SEPARATOR: "separator",
  ACTION: "action",
  TOKENS: "tokens",
  TRACE_ID: "trace_id",
  TRACE: "trace",
  TRACE_QUERY: "trace_query",
  QUEUE: "queue",
  CHECKPOINT: "checkpoint",
  CHECKPOINT_ID: "checkpoint_id",
  SERVER_URL: "server_url",
  STAGING_ID: "staging_id",
  CONTEXT_KEY: "context_key",
  LEASE_MS: "lease_ms",
  MAX_WAIT_MS: "max_wait_ms",
  NOTIFICATION_URL: "notification_url",
  POLL_INTERVAL_MS: "poll_interval_ms",
  POLL_MAX_ATTEMPTS: "poll_max_attempts",
  TIMEOUT_MS: "timeout_ms",
  TIMEOUT: "timeout",
  MAX_RETRIES: "max_retries",
  HISTORY_LIMIT: "history_limit",
  COUNT: "count",
  TASK_SPEC: "task_spec",
  TARGET_AGENT: "target_agent",
  PARTIES: "parties",
  PROPOSAL: "proposal",
  MAX_ROUNDS: "max_rounds",
  ARGS: "args",
  SESSION_ROOT: "session_root",
  HANDOFF: "handoff",
  HANDOFF_FROM: "handoff_from",
  HANDOFF_TO: "handoff_to",
  TRANSFER_STATE: "transfer_state",
  CACHED_SYSTEM_PROMPT: "cached_system_prompt",
  MEMOIZABLE: "memoizable",
  RETRY_COUNT: "retry_count",
  __PROFILE_LATENCY_MS: "__profile_latency_ms",
  __PROFILE_P99_LATENCY_MS: "__profile_p99_latency_ms",
  __PROFILE_ERROR_RATE: "__profile_error_rate",
  __PROFILE_AVG_TOKENS: "__profile_avg_tokens",
  __PROFILE_TOKEN_WARNING: "__profile_token_warning",
  WARMUP_CANDIDATE: "warmup_candidate",
  SHARED_PREFIX_EST_TOKENS: "shared_prefix_est_tokens",
  SHARED_PREFIX_GROUP_SIZE: "shared_prefix_group_size",
  DOWNSTREAM_NODES: "downstream_nodes",
  FANOUT_COUNT: "fanout_count",
  REMAINING_PATH_LEN: "remaining_path_len",
  LATENCY_CLASS: "latency_class",
  BATCH_GROUP: "batch_group",
  STAGE_INDEX: "stage_index",
  ESTIMATED_DYNAMIC_TOKENS: "estimated_dynamic_tokens",
  SHARED_PREFIX_GROUP: "shared_prefix_group",
  EST_TEMPLATE_TOKENS: "est_template_tokens",
  AIS_SHARED_PREFIX_GROUP: "ais.shared_prefix_group",
  AIS_SHARED_PREFIX_EST_TOKENS: "ais.shared_prefix_est_tokens",
  AIS_SHARED_PREFIX_GROUP_SIZE: "ais.shared_prefix_group_size",
  AIS_WARMUP_CANDIDATE: "ais.warmup_candidate",
  AIS_DOWNSTREAM_NODES: "ais.downstream_nodes",
  AIS_FANOUT_COUNT: "ais.fanout_count",
  AIS_REMAINING_PATH_LEN: "ais.remaining_path_len",
  AIS_LATENCY_CLASS: "ais.latency_class",
  AIS_BATCH_GROUP: "ais.batch_group",
  AIS_STAGE_INDEX: "ais.stage_index",
  AIS_ESTIMATED_DYNAMIC_TOKENS: "ais.estimated_dynamic_tokens",
  MEMORY: "memory",
  BELIEFS: "beliefs",
  GOALS: "goals",
  CAPABILITIES: "capabilities",
  SANDBOX_CONFIG: "sandbox_config",
  CONSTRAINTS: "constraints",
  REFLECTION_PROMPT: "reflection_prompt",
  PARAMETERS: "parameters",
  STRUCTURED: "structured",
  TOKEN: "token",
  COUNT_TOKEN: "count_token",
  CASES: "cases",
  DEFAULT: "default",
  ORDERING: "ordering",
  PAYLOAD: "payload",
  ERROR_HANDLER: "error_handler",
} as const;

export const GRAPH_METRICS = {
  GRAPH_METRICS: "graph_metrics",
  GRAPH_METRIC_GRAPH: "graph",
  GRAPH_METRIC_NODES: "nodes",
  GRAPH_METRIC_AGGREGATES: "aggregates",
  GRAPH_METRIC_BY_AGENT: "by_agent",
  GRAPH_METRIC_PROCESS_SPAWNS: "process_spawns",
  GRAPH_METRIC_PROMPT_TURNS: "prompt_turns",
} as const;

export type ProviderProtocol =
  | "openai"
  | "anthropic"
  | "google"
  | "ollama"
  | "vllm"
  | "mock";

export type ProviderSpec = {
  readonly id: string;
  readonly protocol: ProviderProtocol;
  readonly defaultBaseUrl: string | null;
  readonly requiresApiKey: boolean;
  readonly apiKeyEnvVar: string | null;
  readonly aliases: readonly string[];
};

export const BUILTIN_PROVIDERS: readonly ProviderSpec[] = [
  {
    id: "ollama",
    protocol: "ollama" as ProviderProtocol,
    defaultBaseUrl: "http://localhost:11434",
    requiresApiKey: false,
    apiKeyEnvVar: "OLLAMA_API_KEY",
    aliases: [],
  },
  {
    id: "openai",
    protocol: "openai" as ProviderProtocol,
    defaultBaseUrl: null,
    requiresApiKey: true,
    apiKeyEnvVar: "OPENAI_API_KEY",
    aliases: [],
  },
  {
    id: "anthropic",
    protocol: "anthropic" as ProviderProtocol,
    defaultBaseUrl: null,
    requiresApiKey: true,
    apiKeyEnvVar: "ANTHROPIC_API_KEY",
    aliases: [],
  },
  {
    id: "google",
    protocol: "google" as ProviderProtocol,
    defaultBaseUrl: null,
    requiresApiKey: true,
    apiKeyEnvVar: "GOOGLE_API_KEY",
    aliases: ["gemini"],
  },
  {
    id: "vllm",
    protocol: "vllm" as ProviderProtocol,
    defaultBaseUrl: "http://localhost:8916/v1",
    requiresApiKey: false,
    apiKeyEnvVar: null,
    aliases: ["vllm-graph-aware"],
  },
  {
    id: "openrouter",
    protocol: "openai" as ProviderProtocol,
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    requiresApiKey: true,
    apiKeyEnvVar: "OPENROUTER_API_KEY",
    aliases: [],
  },
  {
    id: "mock",
    protocol: "mock" as ProviderProtocol,
    defaultBaseUrl: null,
    requiresApiKey: false,
    apiKeyEnvVar: null,
    aliases: [],
  },
] as const;

export type AgentTemplate = {
  readonly name: string;
  readonly command: string;
  readonly defaultMode: string | null;
  readonly defaultModel: string | null;
};

export const ALL_AGENTS: readonly AgentTemplate[] = [
  {
    name: "claude",
    command: "npx -y @agentclientprotocol/claude-agent-acp@^0.24.2",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "codex",
    command: "npx @zed-industries/codex-acp@^0.10.0",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "copilot",
    command: "copilot --acp --stdio",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "cursor",
    command: "cursor-agent acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "droid",
    command: "droid exec --output-format acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "gemini",
    command: "gemini --acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "iflow",
    command: "iflow --experimental-acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "kilocode",
    command: "npx -y @kilocode/cli acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "kimi",
    command: "kimi acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "kiro",
    command: "kiro-cli-chat acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "opencode",
    command: "npx -y opencode-ai acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "pi",
    command: "npx pi-acp@^0.0.22",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "qoder",
    command: "qodercli --acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "qwen",
    command: "qwen --acp",
    defaultMode: null,
    defaultModel: null,
  },
  {
    name: "trae",
    command: "traecli acp serve",
    defaultMode: null,
    defaultModel: null,
  },
] as const;
