//! Authoring diagnostic-code codegen: the closed set of rejection reasons the
//! source-first frontends can raise, projected into both from the one place the
//! repository already states them.
//!
//! The source of truth is `contracts/vectors/apxm.frontend-surface.json`, whose
//! `declarations[].diagnostics` name the codes each public marker can raise.
//! ADR-0015 §7 makes that manifest the single machine-readable statement of the
//! authoring surface — "every public declaration/marker, its accepted
//! arguments, inferred types, bound semantic node, and the diagnostics it can
//! raise" — so the vocabulary is projected from it rather than restated in
//! Rust. A Rust enum would be a second spelling that no Rust code reads: these
//! are source-capture rejections raised in Python and TypeScript, distinct from
//! `apxm_program::diagnostic::DiagnosticCode`, which is the graph/AIR/source-map
//! *verification* vocabulary and is raised only by Rust.
//!
//! Adding a code is therefore an edit to the manifest — where the reviewer sees
//! which marker gained a rejection reason — and a regeneration, never a new
//! string literal in one frontend.

use serde_json::Value;

pub const PYTHON_DIAGNOSTICS_FILE: &str = "diagnostics.py";
pub const TYPESCRIPT_DIAGNOSTICS_FILE: &str = "diagnostics.ts";
/// The same vocabulary for the packaging package that carries TypeScript's
/// shipped-handler declaration. The manifest projects `Tool.define` into
/// `@apxm/agent-packaging`, which is a different package from the authoring
/// frontend and cannot import its internals, so the codes it raises are
/// projected there from the manifest rather than spelled as literals.
pub const JAVASCRIPT_DIAGNOSTICS_FILE: &str = "diagnostics.mjs";

const PYTHON_HEADER: &str = "# AUTO-GENERATED by apxm codegen diagnostics; DO NOT EDIT.";
const TYPESCRIPT_HEADER: &str = "// AUTO-GENERATED by apxm codegen diagnostics; DO NOT EDIT.";

const TYPE_NAME: &str = "DiagnosticCode";
const SET_NAME: &str = "DIAGNOSTIC_CODES";

const FRONTEND_SURFACE_MANIFEST: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../contracts/vectors/apxm.frontend-surface.json"
));

/// One emitted code: the identifier both frontends bind and the code string.
struct Code {
    ident: String,
    value: String,
}

/// Every diagnostic the manifest's declarations name, in manifest order with
/// repeats dropped, so the emitted vocabulary reads concept by concept the way
/// the manifest does and does not reorder when a declaration gains a code.
fn codes() -> Vec<Code> {
    let manifest: Value = serde_json::from_str(FRONTEND_SURFACE_MANIFEST)
        .expect("apxm.frontend-surface manifest is valid JSON");
    let declarations = manifest["declarations"]
        .as_array()
        .expect("the manifest states a declarations array");

    let mut seen: Vec<String> = Vec::new();
    for declaration in declarations {
        for diagnostic in declaration["diagnostics"]
            .as_array()
            .expect("every declaration states its diagnostics")
        {
            let value = diagnostic
                .as_str()
                .expect("a diagnostic code is a string")
                .to_string();
            if !seen.contains(&value) {
                seen.push(value);
            }
        }
    }
    assert!(
        !seen.is_empty(),
        "the manifest names no diagnostic to project"
    );
    seen.into_iter()
        .map(|value| Code {
            ident: screaming_snake(&value),
            value,
        })
        .collect()
}

/// `AgentBodyNotAsync` -> `AGENT_BODY_NOT_ASYNC`. Codes are CamelCase in the
/// manifest and on the wire; the constant naming one is not.
fn screaming_snake(value: &str) -> String {
    let mut buf = String::with_capacity(value.len() + 4);
    for (index, ch) in value.char_indices() {
        if ch.is_ascii_uppercase() && index > 0 {
            buf.push('_');
        }
        buf.push(ch.to_ascii_uppercase());
    }
    buf
}

fn quote(value: &str) -> String {
    serde_json::to_string(value).expect("diagnostic code string literal")
}

/// One indented member per line, each opened by its own newline.
fn lines(indent: &str, rendered: impl Iterator<Item = String>) -> String {
    let mut buf = String::new();
    for line in rendered {
        buf.push('\n');
        buf.push_str(indent);
        buf.push_str(&line);
    }
    buf
}

pub fn render_diagnostics_python() -> String {
    let codes = codes();
    let mut buf = String::new();
    buf.push_str(PYTHON_HEADER);
    buf.push_str(
        "\n\"\"\"The closed set of reasons the frontend rejects authored source.\n\n\
         A rejection carries one of these codes so a caller can branch on the reason\n\
         without matching on the message text, and so the reason a marker can give is\n\
         the reason the published surface manifest says it can give.\n\n\
         This module is internal to the frontend.\n\"\"\"\n\n\
         from typing import Final, Literal, TypeAlias\n\n",
    );

    buf.push_str(&format!(
        "{TYPE_NAME}: TypeAlias = Literal[{}\n]\n",
        lines(
            "    ",
            codes.iter().map(|code| format!("{},", quote(&code.value)))
        )
    ));
    for code in &codes {
        buf.push_str(&format!(
            "{}: Final[{TYPE_NAME}] = {}\n",
            code.ident,
            quote(&code.value)
        ));
    }
    buf.push_str(&format!(
        "{SET_NAME}: Final[tuple[{TYPE_NAME}, ...]] = ({}\n)\n",
        lines("    ", codes.iter().map(|code| format!("{},", code.ident)))
    ));

    buf.push_str("\n__all__ = [");
    for name in exported_names(&codes) {
        buf.push_str(&format!("\n    {},", quote(&name)));
    }
    buf.push_str("\n]\n");
    buf
}

pub fn render_diagnostics_typescript() -> String {
    let codes = codes();
    let mut buf = String::new();
    buf.push_str(TYPESCRIPT_HEADER);
    buf.push_str(
        "\n// The closed set of reasons the frontend rejects authored source.\n\
         //\n\
         // A rejection carries one of these codes so a caller can branch on the reason\n\
         // without matching on the message text, and so the reason a marker can give is\n\
         // the reason the published surface manifest says it can give.\n\
         //\n\
         // This module is internal to the frontend.\n\n",
    );

    buf.push_str(&format!(
        "export type {TYPE_NAME} ={};\n",
        lines(
            "  ",
            codes.iter().map(|code| format!("| {}", quote(&code.value)))
        )
    ));
    for code in &codes {
        buf.push_str(&format!(
            "export const {} = {} satisfies {TYPE_NAME};\n",
            code.ident,
            quote(&code.value)
        ));
    }
    buf.push_str(&format!(
        "export const {SET_NAME} = [{}\n] as const satisfies readonly {TYPE_NAME}[];\n",
        lines("  ", codes.iter().map(|code| format!("{},", code.ident)))
    ));
    buf
}

pub fn render_diagnostics_javascript() -> String {
    let codes = codes();
    let mut buf = String::new();
    buf.push_str(TYPESCRIPT_HEADER);
    buf.push_str(
        "\n// The closed set of reasons the frontend rejects authored source.\n\
         //\n\
         // A rejection carries one of these codes so a caller can branch on the reason\n\
         // without matching on the message text, and so the reason a declaration can\n\
         // give is the reason the published surface manifest says it can give.\n\
         //\n\
         // This module is internal to the packaging package.\n\n",
    );
    for code in &codes {
        buf.push_str(&format!(
            "export const {} = {};\n",
            code.ident,
            quote(&code.value)
        ));
    }
    buf.push_str(&format!(
        "export const {SET_NAME} = Object.freeze([{}\n]);\n",
        lines("  ", codes.iter().map(|code| format!("{},", code.ident)))
    ));
    buf
}

fn exported_names(codes: &[Code]) -> Vec<String> {
    let mut names = vec![TYPE_NAME.to_string()];
    names.extend(codes.iter().map(|code| code.ident.clone()));
    names.push(SET_NAME.to_string());
    names
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated() -> [String; 3] {
        [
            render_diagnostics_python(),
            render_diagnostics_typescript(),
            render_diagnostics_javascript(),
        ]
    }

    /// The vocabulary is the manifest's, code for code. A declaration that gains
    /// a rejection reason gains a symbol here without this test being edited,
    /// and a code invented in one frontend has no symbol to bind.
    #[test]
    fn generated_vocabulary_is_exactly_the_manifest_declared_codes() {
        let manifest: Value =
            serde_json::from_str(FRONTEND_SURFACE_MANIFEST).expect("frontend-surface manifest");
        for rendered in generated() {
            for declaration in manifest["declarations"]
                .as_array()
                .expect("declarations array")
            {
                for diagnostic in declaration["diagnostics"]
                    .as_array()
                    .expect("diagnostics array")
                {
                    let code = diagnostic.as_str().expect("code string");
                    assert!(rendered.contains(&quote(code)), "{code}");
                }
            }
        }
    }

    /// The manifest declares one code per marker concern more than once —
    /// nothing is emitted twice, which would be a duplicate `const` in
    /// TypeScript and a silent rebinding in Python.
    #[test]
    fn every_code_is_emitted_once() {
        let codes = codes();
        for code in &codes {
            assert_eq!(
                codes
                    .iter()
                    .filter(|other| other.value == code.value)
                    .count(),
                1,
                "{} is emitted more than once",
                code.value
            );
            assert_eq!(
                codes
                    .iter()
                    .filter(|other| other.ident == code.ident)
                    .count(),
                1,
                "{} names more than one code",
                code.ident
            );
        }
    }

    #[test]
    fn generated_codes_name_camel_case_values_as_identifiers() {
        let python = render_diagnostics_python();
        assert!(
            python.contains("AGENT_BODY_NOT_ASYNC: Final[DiagnosticCode] = \"AgentBodyNotAsync\"")
        );
        assert!(
            python.contains(
                "HOOK_TARGET_UNRESOLVED: Final[DiagnosticCode] = \"HookTargetUnresolved\""
            )
        );
        let typescript = render_diagnostics_typescript();
        assert!(typescript.contains(
            "export const MODEL_UNTYPED_SCHEMA = \"ModelUntypedSchema\" satisfies DiagnosticCode;"
        ));
        let javascript = render_diagnostics_javascript();
        assert!(javascript.contains(
            "export const CAPABILITY_HANDLER_OPEN_OBJECT = \"CapabilityHandlerOpenObject\";"
        ));
    }

    /// This vocabulary lands inside the installable authoring packages, so it
    /// must not carry a name the manifest itself marks non-public. The forbidden
    /// list is read from the manifest rather than restated.
    #[test]
    fn no_non_public_name_reaches_the_authoring_packages() {
        let manifest: Value =
            serde_json::from_str(FRONTEND_SURFACE_MANIFEST).expect("frontend-surface manifest");
        let forbidden: Vec<&str> = manifest["non_public"]
            .as_array()
            .expect("non_public array")
            .iter()
            .map(|name| name.as_str().expect("non-public name"))
            .collect();
        assert!(forbidden.contains(&"FIVE_OPS"));

        for rendered in generated() {
            let tokens: Vec<&str> = rendered
                .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '_' || ch == '.'))
                .collect();
            let offenders: Vec<&&str> = forbidden
                .iter()
                .filter(|name| tokens.contains(*name))
                .collect();
            assert!(
                offenders.is_empty(),
                "the diagnostic vocabulary publishes non-public names: {offenders:?}"
            );
        }
    }
}
