//! FrontendGraph vocabulary codegen: every closed string set the
//! `apxm.frontend-graph` contract states, projected into both authoring
//! frontends from the published schema itself.
//!
//! The source of truth is the contract file, not either frontend and not the
//! Rust consumer enums in `apxm_program::frontend_graph`. Both frontends emit
//! FrontendGraph documents that Rust decodes with `deny_unknown_fields`, so a
//! member typed by hand in Python or TypeScript that the schema does not state
//! is a document Rust rejects — which is exactly the drift this projection
//! removes. `semantic_conformance` already pins the Rust enums against the same
//! schema paths, so schema, Rust, Python, and TypeScript resolve one set.
//!
//! Two closed sets the schema states are deliberately **not** emitted here:
//! `PermissionDecision`, which `codegen_permissions` already owns and which
//! would otherwise gain a second spelling, and anything naming an AIS
//! operation — the schema states none, and a test holds the emitted text
//! against the frontend-surface manifest's own `non_public` list.

use serde_json::Value;

pub const PYTHON_FRONTEND_GRAPH_FILE: &str = "frontend_graph.py";
pub const TYPESCRIPT_FRONTEND_GRAPH_FILE: &str = "frontend-graph.ts";

const PYTHON_HEADER: &str = "# AUTO-GENERATED by apxm codegen frontend-vocabulary; DO NOT EDIT.";
const TYPESCRIPT_HEADER: &str =
    "// AUTO-GENERATED by apxm codegen frontend-vocabulary; DO NOT EDIT.";

const FRONTEND_GRAPH_SCHEMA: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../contracts/schemas/apxm.frontend-graph.json"
));

/// Where one closed set is stated in `apxm.frontend-graph`.
pub(crate) enum Source {
    /// A top-level `properties.<property>.enum`.
    RootEnum { property: &'static str },
    /// A `$defs.<def>.properties.<property>.enum`.
    DefEnum {
        def: &'static str,
        property: &'static str,
    },
    /// A `$defs.<def>.oneOf` whose branches each pin one
    /// `properties.<discriminant>.const`. Branches may be `$ref`s into `$defs`.
    DiscriminatedConst {
        def: &'static str,
        discriminant: &'static str,
    },
}

/// One emitted vocabulary: its type name, the prefix each member constant
/// carries, the name of the tuple/array naming every member, and where the
/// contract states the set.
pub(crate) struct Family {
    pub(crate) type_name: &'static str,
    pub(crate) prefix: &'static str,
    set_name: &'static str,
    pub(crate) source: Source,
}

/// Every closed string set `apxm.frontend-graph` states, in schema order.
///
/// Member constants are prefixed because the sets overlap: `context` is both a
/// `Declaration.decl_kind` and a `Parameter.role`, and `loop` is a
/// `ControlIntent.control_kind` while `loop_body` is a `Region.region_role`. An
/// unprefixed constant would collide or, worse, silently resolve to the wrong
/// vocabulary's member.
pub(crate) const FAMILIES: &[Family] = &[
    Family {
        type_name: "SourceLanguage",
        prefix: "SOURCE_LANGUAGE_",
        set_name: "SOURCE_LANGUAGES",
        source: Source::RootEnum {
            property: "source_language",
        },
    },
    Family {
        type_name: "DeclKind",
        prefix: "DECL_KIND_",
        set_name: "DECL_KINDS",
        source: Source::DefEnum {
            def: "Declaration",
            property: "decl_kind",
        },
    },
    Family {
        type_name: "ParameterRole",
        prefix: "PARAMETER_ROLE_",
        set_name: "PARAMETER_ROLES",
        source: Source::DefEnum {
            def: "Parameter",
            property: "role",
        },
    },
    Family {
        type_name: "ValueOrigin",
        prefix: "VALUE_ORIGIN_",
        set_name: "VALUE_ORIGINS",
        source: Source::DefEnum {
            def: "Value",
            property: "origin",
        },
    },
    Family {
        type_name: "ValueExpressionKind",
        prefix: "VALUE_EXPRESSION_KIND_",
        set_name: "VALUE_EXPRESSION_KINDS",
        source: Source::DiscriminatedConst {
            def: "ValueExpression",
            discriminant: "kind",
        },
    },
    Family {
        type_name: "RegionRole",
        prefix: "REGION_ROLE_",
        set_name: "REGION_ROLES",
        source: Source::DefEnum {
            def: "Region",
            property: "region_role",
        },
    },
    Family {
        type_name: "IntentKind",
        prefix: "INTENT_KIND_",
        set_name: "INTENT_KINDS",
        source: Source::DefEnum {
            def: "CallIntent",
            property: "intent_kind",
        },
    },
    Family {
        type_name: "ReceiverKind",
        prefix: "RECEIVER_KIND_",
        set_name: "RECEIVER_KINDS",
        source: Source::DefEnum {
            def: "CallIntent",
            property: "receiver_kind",
        },
    },
    Family {
        type_name: "ControlKind",
        prefix: "CONTROL_KIND_",
        set_name: "CONTROL_KINDS",
        source: Source::DefEnum {
            def: "ControlIntent",
            property: "control_kind",
        },
    },
    Family {
        type_name: "PredicateComparator",
        prefix: "PREDICATE_COMPARATOR_",
        set_name: "PREDICATE_COMPARATORS",
        source: Source::DiscriminatedConst {
            def: "ControlPredicate",
            discriminant: "comparator",
        },
    },
    Family {
        type_name: "PredicateScalarType",
        prefix: "PREDICATE_SCALAR_TYPE_",
        set_name: "PREDICATE_SCALAR_TYPES",
        source: Source::DiscriminatedConst {
            def: "PredicateLiteral",
            discriminant: "scalar_type",
        },
    },
    Family {
        type_name: "SkillInstructionKind",
        prefix: "SKILL_INSTRUCTION_KIND_",
        set_name: "SKILL_INSTRUCTION_KINDS",
        source: Source::DiscriminatedConst {
            def: "SkillInstructionSource",
            discriminant: "kind",
        },
    },
    Family {
        type_name: "HookScope",
        prefix: "HOOK_SCOPE_",
        set_name: "HOOK_SCOPES",
        source: Source::DefEnum {
            def: "HookBinding",
            property: "scope",
        },
    },
    Family {
        type_name: "HookPhase",
        prefix: "HOOK_PHASE_",
        set_name: "HOOK_PHASES",
        source: Source::DefEnum {
            def: "HookBinding",
            property: "phase",
        },
    },
    Family {
        type_name: "HookReturnMode",
        prefix: "HOOK_RETURN_MODE_",
        set_name: "HOOK_RETURN_MODES",
        source: Source::DefEnum {
            def: "HookBinding",
            property: "return_mode",
        },
    },
];

/// One emitted member: the identifier both frontends bind and the wire string
/// the contract states.
struct Member {
    ident: String,
    value: String,
}

pub(crate) fn schema() -> Value {
    serde_json::from_str(FRONTEND_GRAPH_SCHEMA).expect("apxm.frontend-graph is valid JSON")
}

/// The vocabulary family projecting `$defs.<def>.properties.<property>.enum`,
/// if any. `codegen_frontend_records` resolves every enum-typed record field
/// through this lookup rather than re-deriving the FrontendGraph vocabulary.
pub(crate) fn family_for_def_enum(def: &str, property: &str) -> Option<&'static Family> {
    FAMILIES.iter().find(|family| {
        matches!(
            &family.source,
            Source::DefEnum { def: family_def, property: family_property }
                if *family_def == def && *family_property == property
        )
    })
}

/// The vocabulary family projecting `$defs.<def>.oneOf[*].properties.<discriminant>.const`,
/// if any. `def` here is the *union's* `$defs` key (e.g. `ValueExpression`),
/// not a branch's, since the discriminant is stated once for the whole union.
pub(crate) fn family_for_discriminated_const(
    def: &str,
    discriminant: &str,
) -> Option<&'static Family> {
    FAMILIES.iter().find(|family| {
        matches!(
            &family.source,
            Source::DiscriminatedConst { def: family_def, discriminant: family_discriminant }
                if *family_def == def && *family_discriminant == discriminant
        )
    })
}

/// The vocabulary family a `$defs.<def>.oneOf` discriminates on, with the
/// discriminant property's name. `codegen_frontend_serializers` resolves a
/// union's branch constants through this rather than restating which property
/// the contract discriminates each union on.
pub(crate) fn family_for_union(def: &str) -> Option<(&'static Family, &'static str)> {
    FAMILIES.iter().find_map(|family| match &family.source {
        Source::DiscriminatedConst {
            def: family_def,
            discriminant,
        } if *family_def == def => Some((family, *discriminant)),
        _ => None,
    })
}

/// Resolve one local `#/$defs/...` reference, or return the branch unchanged.
fn resolve<'a>(schema: &'a Value, branch: &'a Value) -> &'a Value {
    match branch["$ref"].as_str() {
        Some(reference) => {
            let name = reference
                .strip_prefix("#/$defs/")
                .unwrap_or_else(|| panic!("unsupported schema ref: {reference}"));
            &schema["$defs"][name]
        }
        None => branch,
    }
}

fn string_members(node: &Value, path: &str) -> Vec<String> {
    node.as_array()
        .unwrap_or_else(|| panic!("{path} states an array"))
        .iter()
        .map(|member| {
            member
                .as_str()
                .unwrap_or_else(|| panic!("{path} member is a string"))
                .to_string()
        })
        .collect()
}

fn members(family: &Family, schema: &Value) -> Vec<Member> {
    let values = match &family.source {
        Source::RootEnum { property } => string_members(
            &schema["properties"][property]["enum"],
            &format!("properties.{property}.enum"),
        ),
        Source::DefEnum { def, property } => string_members(
            &schema["$defs"][def]["properties"][property]["enum"],
            &format!("$defs.{def}.properties.{property}.enum"),
        ),
        Source::DiscriminatedConst { def, discriminant } => schema["$defs"][def]["oneOf"]
            .as_array()
            .unwrap_or_else(|| panic!("$defs.{def}.oneOf states an array"))
            .iter()
            .map(|branch| {
                resolve(schema, branch)["properties"][discriminant]["const"]
                    .as_str()
                    .unwrap_or_else(|| {
                        panic!("$defs.{def}.oneOf branch pins {discriminant} to a string const")
                    })
                    .to_string()
            })
            .collect(),
    };

    let mut seen = Vec::new();
    let mut emitted = Vec::new();
    for value in values {
        // A discriminated union may repeat a discriminant across branches that
        // differ only in payload; one member is emitted per distinct value.
        if seen.contains(&value) {
            continue;
        }
        seen.push(value.clone());
        emitted.push(Member {
            ident: format!("{}{}", family.prefix, screaming_snake(&value)),
            value,
        });
    }
    emitted
}

/// Uppercase every ASCII alphanumeric and replace everything else with `_`, so
/// a wire string is a stable identifier in both languages.
pub(crate) fn screaming_snake(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

pub(crate) fn quote(value: &str) -> String {
    serde_json::to_string(value).expect("vocabulary string literal")
}

/// One indented member per line, each opened by its own newline, so a
/// single-member set still renders a well-formed literal.
fn lines(indent: &str, rendered: impl Iterator<Item = String>) -> String {
    let mut buf = String::new();
    for line in rendered {
        buf.push('\n');
        buf.push_str(indent);
        buf.push_str(&line);
    }
    buf
}

pub fn render_frontend_graph_python() -> String {
    let schema = schema();
    let mut buf = String::new();
    buf.push_str(PYTHON_HEADER);
    buf.push_str(
        "\n\"\"\"Every closed string set the apxm.frontend-graph contract states.\n\n\
         The frontend emits source-graph documents that Rust decodes against this\n\
         same contract with unknown members rejected, so a hand-typed string that the\n\
         contract does not state is a document the compiler refuses. Bind the constant\n\
         instead of retyping the string: a misspelled constant is an ImportError, a\n\
         misspelled string reaches the compiler and fails there.\n\n\
         This module is internal to the frontend. It carries source-intent vocabulary\n\
         only, never an AIR or AIS operation name.\n\"\"\"\n\n\
         from typing import Final, Literal, TypeAlias\n",
    );

    let mut exported: Vec<String> = Vec::new();
    for family in FAMILIES {
        let members = members(family, &schema);
        buf.push_str(&format!(
            "\n{}: TypeAlias = Literal[{}\n]\n",
            family.type_name,
            lines(
                "    ",
                members
                    .iter()
                    .map(|member| format!("{},", quote(&member.value)))
            )
        ));
        for member in &members {
            buf.push_str(&format!(
                "{}: Final[{}] = {}\n",
                member.ident,
                family.type_name,
                quote(&member.value)
            ));
        }
        buf.push_str(&format!(
            "{}: Final[tuple[{}, ...]] = ({}\n)\n",
            family.set_name,
            family.type_name,
            lines(
                "    ",
                members.iter().map(|member| format!("{},", member.ident))
            )
        ));

        exported.push(family.type_name.to_string());
        exported.extend(members.iter().map(|member| member.ident.clone()));
        exported.push(family.set_name.to_string());
    }

    buf.push_str("\n__all__ = [");
    for name in exported {
        buf.push_str(&format!("\n    {},", quote(&name)));
    }
    buf.push_str("\n]\n");
    buf
}

pub fn render_frontend_graph_typescript() -> String {
    let schema = schema();
    let mut buf = String::new();
    buf.push_str(TYPESCRIPT_HEADER);
    buf.push_str(
        "\n// Every closed string set the apxm.frontend-graph contract states.\n\
         //\n\
         // The frontend emits source-graph documents that Rust decodes against this\n\
         // same contract with unknown members rejected, so a hand-typed string that the\n\
         // contract does not state is a document the compiler refuses. Bind the constant\n\
         // instead of retyping the string: a misspelled constant fails to compile, a\n\
         // misspelled string reaches the compiler and fails there.\n\
         //\n\
         // This module is internal to the frontend. It carries source-intent vocabulary\n\
         // only, never an AIR or AIS operation name.\n",
    );

    for family in FAMILIES {
        let members = members(family, &schema);
        buf.push_str(&format!(
            "\nexport type {} ={};\n",
            family.type_name,
            lines(
                "  ",
                members
                    .iter()
                    .map(|member| format!("| {}", quote(&member.value)))
            )
        ));
        for member in &members {
            buf.push_str(&format!(
                "export const {} = {} satisfies {};\n",
                member.ident,
                quote(&member.value),
                family.type_name
            ));
        }
        buf.push_str(&format!(
            "export const {} = [{}\n] as const satisfies readonly {}[];\n",
            family.set_name,
            lines(
                "  ",
                members.iter().map(|member| format!("{},", member.ident))
            ),
            family.type_name
        ));
    }
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    const FRONTEND_SURFACE_MANIFEST: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../contracts/vectors/apxm.frontend-surface.json"
    ));

    fn generated() -> [String; 2] {
        [
            render_frontend_graph_python(),
            render_frontend_graph_typescript(),
        ]
    }

    /// The projection is the contract's, member for member. A set the schema
    /// widens or narrows moves here without this test being edited, and a
    /// member neither frontend could have typed by hand cannot appear.
    #[test]
    fn every_family_is_exactly_the_set_the_contract_states() {
        let schema = schema();
        for rendered in generated() {
            for family in FAMILIES {
                let members = members(family, &schema);
                assert!(!members.is_empty(), "{} is empty", family.type_name);
                for member in &members {
                    assert!(
                        rendered.contains(&quote(&member.value)),
                        "{} omits {}",
                        family.type_name,
                        member.value
                    );
                    assert!(
                        rendered.contains(&member.ident),
                        "{} omits {}",
                        family.type_name,
                        member.ident
                    );
                }
            }
        }
    }

    /// The six FrontendGraph enums both frontends re-typed as bare strings, plus
    /// the Hook scope set each hand-kept twice, are the reason this generator
    /// exists. Losing any one of them silently re-opens that drift.
    #[test]
    fn the_hand_typed_sets_are_the_ones_projected() {
        let python = render_frontend_graph_python();
        for expected in [
            "DECL_KIND_MODEL_BINDING: Final[DeclKind] = \"model_binding\"",
            "PARAMETER_ROLE_AGENT_FACADE: Final[ParameterRole] = \"agent_facade\"",
            "VALUE_ORIGIN_RESUME_INPUT: Final[ValueOrigin] = \"resume_input\"",
            "REGION_ROLE_LOOP_BODY: Final[RegionRole] = \"loop_body\"",
            "INTENT_KIND_TOOL_INVOCATION: Final[IntentKind] = \"tool_invocation\"",
            "CONTROL_KIND_TASK_GROUP: Final[ControlKind] = \"task_group\"",
            "HOOK_SCOPE_CAPABILITY: Final[HookScope] = \"capability\"",
        ] {
            assert!(python.contains(expected), "{expected}");
        }

        let typescript = render_frontend_graph_typescript();
        for expected in [
            "export const DECL_KIND_MODEL_BINDING = \"model_binding\" satisfies DeclKind;",
            "export const HOOK_SCOPE_CAPABILITY = \"capability\" satisfies HookScope;",
            "] as const satisfies readonly HookScope[];",
        ] {
            assert!(typescript.contains(expected), "{expected}");
        }
    }

    /// `PermissionDecision` is stated by this schema and already generated by
    /// `codegen_permissions`. Emitting it here would be a second spelling of one
    /// vocabulary in the same package.
    #[test]
    fn the_permission_decision_vocabulary_is_left_to_its_own_generator() {
        for rendered in generated() {
            for absent in ["PermissionDecision", "PERMISSION_DECISION_", "Allow", "Ask"] {
                assert!(!rendered.contains(absent), "{absent}: {rendered}");
            }
        }
    }

    /// This vocabulary lands inside the installable authoring packages, so it
    /// must not carry a name the frontend-surface manifest itself marks
    /// non-public. The forbidden list is read from that manifest rather than
    /// restated, so tightening the manifest tightens this generator.
    ///
    /// Membership is tested token-wise, not by substring: `REGION_ROLE_LOOP_BODY`
    /// contains the characters of `OP_` without naming an operation.
    #[test]
    fn no_non_public_name_reaches_the_authoring_packages() {
        let manifest: Value =
            serde_json::from_str(FRONTEND_SURFACE_MANIFEST).expect("frontend-surface manifest");
        let forbidden = string_members(&manifest["non_public"], "non_public");
        assert!(forbidden.contains(&"FIVE_OPS".to_string()));

        for rendered in generated() {
            let tokens: Vec<&str> = rendered
                .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '_' || ch == '.'))
                .collect();
            let offenders: Vec<&String> = forbidden
                .iter()
                .filter(|name| tokens.contains(&name.as_str()))
                .collect();
            assert!(
                offenders.is_empty(),
                "the FrontendGraph vocabulary publishes non-public names: {offenders:?}"
            );
        }
    }
}
