//! Capability catalogue codegen: the author-facing capability id and
//! builtin-group vocabulary, projected into both authoring frontends.
//!
//! The projection is by **set membership**, not by constant enumeration.
//! `apxm_ais::capabilities` declares more constants than an author may bind:
//! `MANAGE_TASK` has an `AGENT_MANAGEMENT_BUILTINS` slot but is deliberately
//! absent from `BUILTINS`, so `agent lint`'s builtin check rejects it. Emitting
//! every `pub const` would mint a symbol that fails lint the moment it is
//! imported. The emitted id set is therefore exactly `BUILTINS` — the same
//! allowlist `check_capability_bindings` accepts — and the emitted group set is
//! exactly `BUILTIN_GROUPS`. `STANDARD_BUILTINS` is projected as a named subset
//! of the ids, never as a separate symbol family.

use std::collections::BTreeMap;

use apxm_ais::capabilities::{BUILTIN_GROUPS, BUILTINS, STANDARD_BUILTINS};

pub const PYTHON_CAPABILITIES_FILE: &str = "capabilities.py";
pub const TYPESCRIPT_CAPABILITIES_FILE: &str = "capabilities.ts";

const PYTHON_HEADER: &str = "# AUTO-GENERATED by apxm codegen capabilities; DO NOT EDIT.";
const TYPESCRIPT_HEADER: &str = "// AUTO-GENERATED by apxm codegen capabilities; DO NOT EDIT.";

const GROUP_SYMBOL_PREFIX: &str = "GROUP_";

/// A generated symbol: the identifier authors import and the wire id it carries.
struct Symbol {
    ident: String,
    value: &'static str,
}

fn capability_symbols() -> Vec<Symbol> {
    BUILTINS.iter().map(|id| symbol("", id)).collect()
}

fn group_symbols() -> Vec<Symbol> {
    BUILTIN_GROUPS
        .iter()
        .map(|group| symbol(GROUP_SYMBOL_PREFIX, group))
        .collect()
}

/// Return the first collision in the generated frontend namespace.
///
/// Frontend identifiers normalize punctuation to `_` and share one module
/// namespace for capability and group symbols. A new AIS id such as
/// `foo-bar` must therefore not be allowed to silently collide with
/// `foo_bar`, or with a group such as `foo.bar`. The source catalogue is the
/// authority for values, but this projection owns the additional identifier
/// invariant and must fail codegen before it writes ambiguous files.
fn first_symbol_collision(
    capabilities: &[Symbol],
    groups: &[Symbol],
) -> Option<(String, &'static str, &'static str)> {
    let mut seen: BTreeMap<String, &'static str> = BTreeMap::new();
    for symbol in capabilities.iter().chain(groups) {
        if let Some(previous) = seen.insert(symbol.ident.clone(), symbol.value) {
            return Some((symbol.ident.clone(), previous, symbol.value));
        }
    }
    None
}

fn assert_symbol_namespace_is_unique(capabilities: &[Symbol], groups: &[Symbol]) {
    if let Some((ident, previous, current)) = first_symbol_collision(capabilities, groups) {
        panic!(
            "capability catalogue symbols collide after frontend normalization: {ident} maps both {previous:?} and {current:?}"
        );
    }
}

/// `STANDARD_BUILTINS` as identifiers already emitted for `BUILTINS`. A member
/// outside `BUILTINS` would name an undefined symbol, so it is rejected here
/// rather than emitted into a frontend that cannot compile.
fn standard_capability_idents() -> Vec<String> {
    STANDARD_BUILTINS
        .iter()
        .map(|id| {
            assert!(
                BUILTINS.contains(id),
                "STANDARD_BUILTINS member {id:?} is absent from BUILTINS"
            );
            symbol("", id).ident
        })
        .collect()
}

fn symbol(prefix: &str, value: &'static str) -> Symbol {
    let mut ident = String::from(prefix);
    for ch in value.chars() {
        ident.push(if ch.is_ascii_alphanumeric() {
            ch.to_ascii_uppercase()
        } else {
            '_'
        });
    }
    Symbol { ident, value }
}

fn quote(value: &str) -> String {
    serde_json::to_string(value).expect("capability id string literal")
}

/// One indented member per line, each opened by its own newline, so both an
/// empty and a single-member set still render a well-formed literal.
fn members(indent: &str, rendered: impl Iterator<Item = String>) -> String {
    let mut buf = String::new();
    for member in rendered {
        buf.push('\n');
        buf.push_str(indent);
        buf.push_str(&member);
    }
    buf
}

fn union(values: impl Iterator<Item = &'static str>) -> String {
    members("  ", values.map(|value| format!("| {}", quote(value))))
}

pub fn render_capabilities_python() -> String {
    let capabilities = capability_symbols();
    let groups = group_symbols();
    let standard = standard_capability_idents();
    assert_symbol_namespace_is_unique(&capabilities, &groups);

    let mut buf = String::new();
    buf.push_str(PYTHON_HEADER);
    buf.push_str(
        "\n\"\"\"Capability ids and builtin groups an Agent Program may bind by name.\n\n\
         Every id here is admitted by the compiler builtin allowlist, so binding one\n\
         needs no capability registration. Import the symbol instead of retyping the\n\
         string: a misspelled symbol is an ImportError, a misspelled string is a\n\
         capability that silently matches nothing.\n\"\"\"\n\n\
         from typing import Final, Literal, TypeAlias\n\n",
    );

    buf.push_str(&format!(
        "CapabilityId: TypeAlias = Literal[{}\n]\n",
        members(
            "    ",
            capabilities
                .iter()
                .map(|symbol| format!("{},", quote(symbol.value)))
        )
    ));
    buf.push_str(&format!(
        "BuiltinGroup: TypeAlias = Literal[{}\n]\n\n",
        members(
            "    ",
            groups
                .iter()
                .map(|symbol| format!("{},", quote(symbol.value)))
        )
    ));

    for symbol in &capabilities {
        buf.push_str(&format!(
            "{}: Final[CapabilityId] = {}\n",
            symbol.ident,
            quote(symbol.value)
        ));
    }
    buf.push('\n');
    for symbol in &groups {
        buf.push_str(&format!(
            "{}: Final[BuiltinGroup] = {}\n",
            symbol.ident,
            quote(symbol.value)
        ));
    }

    buf.push_str(&format!(
        "\nSTANDARD_BUILTIN_CAPABILITIES: Final[tuple[CapabilityId, ...]] = ({}\n)\n",
        members("    ", standard.iter().map(|ident| format!("{ident},")))
    ));
    buf.push_str(&format!(
        "BUILTIN_CAPABILITIES: Final[tuple[CapabilityId, ...]] = ({}\n)\n",
        members(
            "    ",
            capabilities
                .iter()
                .map(|symbol| format!("{},", symbol.ident))
        )
    ));
    buf.push_str(&format!(
        "BUILTIN_GROUPS: Final[tuple[BuiltinGroup, ...]] = ({}\n)\n",
        members(
            "    ",
            groups.iter().map(|symbol| format!("{},", symbol.ident))
        )
    ));

    buf.push_str("\n__all__ = [");
    for name in exported_names(&capabilities, &groups) {
        buf.push_str(&format!("\n    {},", quote(&name)));
    }
    buf.push_str("\n]\n");
    buf
}

pub fn render_capabilities_typescript() -> String {
    let capabilities = capability_symbols();
    let groups = group_symbols();
    let standard = standard_capability_idents();
    assert_symbol_namespace_is_unique(&capabilities, &groups);

    let mut buf = String::new();
    buf.push_str(TYPESCRIPT_HEADER);
    buf.push_str(
        "\n// Capability ids and builtin groups an Agent Program may bind by name.\n\
         // Every id here is admitted by the compiler builtin allowlist, so binding one\n\
         // needs no capability registration. Import the symbol instead of retyping the\n\
         // string: a misspelled symbol fails to compile, a misspelled string is a\n\
         // capability that silently matches nothing.\n\n",
    );

    buf.push_str(&format!(
        "export type CapabilityId ={};\n",
        union(capabilities.iter().map(|symbol| symbol.value))
    ));
    buf.push_str(&format!(
        "export type BuiltinGroup ={};\n\n",
        union(groups.iter().map(|symbol| symbol.value))
    ));

    for symbol in &capabilities {
        buf.push_str(&format!(
            "export const {} = {} satisfies CapabilityId;\n",
            symbol.ident,
            quote(symbol.value)
        ));
    }
    buf.push('\n');
    for symbol in &groups {
        buf.push_str(&format!(
            "export const {} = {} satisfies BuiltinGroup;\n",
            symbol.ident,
            quote(symbol.value)
        ));
    }

    buf.push_str(&format!(
        "\nexport const STANDARD_BUILTIN_CAPABILITIES = [{}\n] as const satisfies readonly CapabilityId[];\n",
        members("  ", standard.iter().map(|ident| format!("{ident},")))
    ));
    buf.push_str(&format!(
        "export const BUILTIN_CAPABILITIES = [{}\n] as const satisfies readonly CapabilityId[];\n",
        members(
            "  ",
            capabilities
                .iter()
                .map(|symbol| format!("{},", symbol.ident))
        )
    ));
    buf.push_str(&format!(
        "export const BUILTIN_GROUPS = [{}\n] as const satisfies readonly BuiltinGroup[];\n",
        members(
            "  ",
            groups.iter().map(|symbol| format!("{},", symbol.ident))
        )
    ));
    buf
}

fn exported_names(capabilities: &[Symbol], groups: &[Symbol]) -> Vec<String> {
    let mut names = vec!["BuiltinGroup".to_string(), "CapabilityId".to_string()];
    names.extend(capabilities.iter().map(|symbol| symbol.ident.clone()));
    names.extend(groups.iter().map(|symbol| symbol.ident.clone()));
    names.extend(
        [
            "BUILTIN_CAPABILITIES",
            "BUILTIN_GROUPS",
            "STANDARD_BUILTIN_CAPABILITIES",
        ]
        .map(str::to_string),
    );
    names
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `MANAGE_TASK` is declared in the SSOT and slotted into
    /// `AGENT_MANAGEMENT_BUILTINS`, but `agent lint` rejects it as a builtin
    /// binding because it is not in `BUILTINS`. Emitting the id set rather than
    /// the constant list is what keeps it off the authoring surface, and
    /// `SCHEDULE` — in `BUILTINS` but not `STANDARD_BUILTINS` — on it.
    #[test]
    fn generated_catalogue_projects_binding_admissibility_not_the_constant_list() {
        for generated in [
            render_capabilities_python(),
            render_capabilities_typescript(),
        ] {
            assert!(!generated.contains("MANAGE_TASK"), "{generated}");
            assert!(!generated.contains("manage_task"), "{generated}");
            assert!(generated.contains("SCHEDULE"), "{generated}");
            for id in BUILTINS {
                assert!(generated.contains(&quote(id)), "{id}");
            }
            for group in BUILTIN_GROUPS {
                assert!(generated.contains(&quote(group)), "{group}");
            }
        }
    }

    /// Capability ids are bindable names; AIS operations are not authorable at
    /// all. This catalogue lands in the same packages the authoring surface
    /// ships, so it must not smuggle in the operation vocabulary that
    /// `apxm.frontend-surface`'s `non_public` list and ADR-0009/0015 keep off it.
    #[test]
    fn generated_catalogue_publishes_no_operation_vocabulary() {
        let operation_markers = [
            "model.call",
            "capability.invoke",
            "program.new",
            "program.invoke",
            "await.event",
            "ais.",
            "OP_",
            "FIVE_OPS",
            "SEMANTIC_",
            "STRUCTURAL_",
        ];
        for generated in [
            render_capabilities_python(),
            render_capabilities_typescript(),
        ] {
            let offenders: Vec<&str> = operation_markers
                .into_iter()
                .filter(|marker| generated.contains(marker))
                .collect();
            assert!(
                offenders.is_empty(),
                "capability catalogue publishes operation vocabulary: {offenders:?}"
            );
        }
    }

    #[test]
    fn generated_catalogue_names_dotted_ids_as_identifiers() {
        let python = render_capabilities_python();
        assert!(python.contains("MCP_CALL: Final[CapabilityId] = \"mcp.call\""));
        assert!(python.contains("PROVIDER_CALL: Final[CapabilityId] = \"provider.call\""));
        let typescript = render_capabilities_typescript();
        assert!(
            typescript.contains("export const MCP_CALL = \"mcp.call\" satisfies CapabilityId;")
        );
        assert!(typescript.contains("export const GROUP_SKILLS = \"skills\""));
    }

    #[test]
    fn normalized_capability_and_group_symbols_must_not_collide() {
        let capabilities = vec![
            Symbol {
                ident: "FOO_BAR".to_string(),
                value: "foo-bar",
            },
            Symbol {
                ident: "FOO_BAR".to_string(),
                value: "foo_bar",
            },
        ];
        let groups = Vec::new();
        let collision = first_symbol_collision(&capabilities, &groups)
            .expect("the projection must detect a normalized identifier collision");
        assert_eq!(collision.0, "FOO_BAR");
        assert_eq!(collision.1, "foo-bar");
        assert_eq!(collision.2, "foo_bar");
    }
}
