use std::fs;
use std::path::Path;

use anyhow::Result;

use super::registry::{
    FrontendOperationSpec, agent_templates, builtin_providers, graph_attr_constants,
    graph_metric_constants, operation_specs, provider_protocols,
};

pub fn render_typescript_frontend_ops() -> String {
    let mut buf = String::new();
    buf.push_str(
        "/**\n\
         * AUTO-GENERATED by apxm codegen typescript-frontend -- DO NOT EDIT BY HAND.\n\
         *\n\
         * Regenerate with: npm run codegen (from crates/compiler/frontend/typescript).\n\
         */\n\n",
    );

    let ops = operation_specs();
    let op_name_union = ops
        .iter()
        .map(|spec| ts_string(&spec.op.to_string()))
        .collect::<Vec<_>>()
        .join(" | ");

    buf.push_str("/** Schema version of the source op-spec catalog (apxm.op-spec.v1). */\n");
    buf.push_str(&format!(
        "export const OP_SPEC_SCHEMA_VERSION = {};\n\n",
        ts_string(apxm_ais::OP_SPEC_SCHEMA_VERSION)
    ));
    buf.push_str(
        "/** Total operations declared by the source catalog (including pseudo-ops). */\n",
    );
    buf.push_str(&format!(
        "export const OP_SPEC_TOTAL_OPERATIONS = {};\n\n",
        ops.len()
    ));
    buf.push_str("/** Union of every AIS opcode name in the catalog. */\n");
    buf.push_str(&format!("export type OpName = {op_name_union};\n\n"));
    buf.push_str("/** A single field/attribute an AIS operation accepts. */\n");
    buf.push_str("export interface OpField {\n");
    buf.push_str("  readonly name: string;\n");
    buf.push_str("  readonly required: boolean;\n");
    buf.push_str("  readonly description: string;\n");
    buf.push_str("  readonly refType: string | null;\n");
    buf.push_str("}\n\n");
    buf.push_str("/** Full metadata for one AIS operation generated from op-spec.v1.json. */\n");
    buf.push_str("export interface OpSpec {\n");
    buf.push_str("  readonly op: OpName;\n");
    buf.push_str("  readonly rustVariant: string;\n");
    buf.push_str("  readonly name: string;\n");
    buf.push_str("  readonly category: string;\n");
    buf.push_str("  readonly description: string;\n");
    buf.push_str("  readonly longDescription: string;\n");
    buf.push_str("  readonly latency: string;\n");
    buf.push_str("  readonly wireIndex: number | null;\n");
    buf.push_str("  readonly isPseudoOp: boolean;\n");
    buf.push_str("  readonly minInputs: number;\n");
    buf.push_str("  readonly producesOutput: boolean;\n");
    buf.push_str("  readonly needsSubmission: boolean;\n");
    buf.push_str("  readonly fields: readonly OpField[];\n");
    buf.push_str("  readonly exampleJson: string | null;\n");
    buf.push_str("}\n\n");
    buf.push_str("/** Every operation spec, keyed by opcode name. */\n");
    buf.push_str("export const OP_SPECS: Readonly<Record<OpName, OpSpec>> = {\n");
    for spec in &ops {
        render_frontend_op_entry(&mut buf, spec);
    }
    buf.push_str("};\n\n");
    buf.push_str("/** All operation specs as an array, in catalog order. */\n");
    buf.push_str("export const ALL_OPERATIONS: readonly OpSpec[] = Object.values(OP_SPECS);\n\n");
    buf.push_str("/** Opcodes that never produce a result token. */\n");
    buf.push_str("export const VOID_OPS: ReadonlySet<OpName> = new Set(\n");
    buf.push_str(
        "  ALL_OPERATIONS.filter((spec) => !spec.producesOutput).map((spec) => spec.op),\n",
    );
    buf.push_str(");\n\n");
    buf.push_str(
        "/** Required (non-optional) attribute names per opcode, for graph validation. */\n",
    );
    buf.push_str("export const REQUIRED_ATTRS: Readonly<Record<OpName, ReadonlySet<string>>> = Object.fromEntries(\n");
    buf.push_str("  ALL_OPERATIONS.map((spec) => [\n");
    buf.push_str("    spec.op,\n");
    buf.push_str("    new Set(spec.fields.filter((f) => f.required).map((f) => f.name)),\n");
    buf.push_str("  ]),\n");
    buf.push_str(") as unknown as Readonly<Record<OpName, ReadonlySet<string>>>;\n");

    buf
}

pub fn render_typescript_frontend_workflow_schema(schema_path: &Path) -> Result<String> {
    let raw = fs::read_to_string(schema_path)?;
    let schema: serde_json::Value = serde_json::from_str(&raw)?;
    let schema_json = serde_json::to_string_pretty(&schema)?;
    Ok(format!(
        "/**\n\
         * AUTO-GENERATED by apxm codegen typescript-frontend -- DO NOT EDIT BY HAND.\n\
         *\n\
         * Regenerate with: npm run codegen (from crates/compiler/frontend/typescript).\n\
         */\n\n\
         /**\n\
         * Vendored copy of workflow-draft.v1.json from workspace/contracts/schemas/.\n\
         * Source of truth: workspace/contracts/schemas/workflow-draft.v1.json.\n\
         * Re-vendor with: npm run codegen.\n\
         */\n\
         export const WORKFLOW_DRAFT_V1_SCHEMA = {schema_json} as const;\n"
    ))
}

pub fn render_typescript_frontend_files(
    workflow_schema_path: &Path,
) -> Result<Vec<(&'static str, String)>> {
    Ok(vec![
        ("ops.ts", render_typescript_frontend_ops()),
        ("builder-ops.ts", render_typescript_frontend_builder_ops()),
        (
            "workflow-draft-schema.ts",
            render_typescript_frontend_workflow_schema(workflow_schema_path)?,
        ),
    ])
}

pub fn write_typescript_frontend_generated(
    output_dir: impl AsRef<Path>,
    workflow_schema_path: &Path,
) -> Result<()> {
    let output_dir = output_dir.as_ref();
    fs::create_dir_all(output_dir)?;
    for (filename, content) in render_typescript_frontend_files(workflow_schema_path)? {
        fs::write(output_dir.join(filename), content)?;
    }
    Ok(())
}

pub fn render_generated_typescript() -> String {
    let mut buf = String::new();
    buf.push_str("// AUTO-GENERATED by apxm codegen typescript; DO NOT EDIT.\n\n");

    let ops = operation_specs();

    render_ts_field_spec(&mut buf);
    render_ts_op_spec(&mut buf);
    render_ts_dependency_types(&mut buf);
    render_ts_capability_groups(&mut buf);
    render_ts_operations(&mut buf, &ops);
    render_ts_categories(&mut buf, &ops);
    render_ts_attr_constants(&mut buf);
    render_ts_graph_metric_constants(&mut buf);
    render_ts_provider_types(&mut buf);
    render_ts_agents(&mut buf);

    buf
}

pub fn write_generated_typescript(output_path: impl AsRef<Path>) -> Result<()> {
    let output_path = output_path.as_ref();
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output_path, render_generated_typescript())?;
    Ok(())
}

fn render_frontend_op_entry(buf: &mut String, spec: &FrontendOperationSpec) {
    let op = spec.op.to_string();
    buf.push_str(&format!("  {}: {{\n", ts_string(&op)));
    buf.push_str(&format!("    op: {},\n", ts_string(&op)));
    buf.push_str(&format!(
        "    rustVariant: {},\n",
        ts_string(&format!("{:?}", spec.op))
    ));
    buf.push_str(&format!("    name: {},\n", ts_string(spec.name)));
    buf.push_str(&format!("    category: {},\n", ts_string(spec.category)));
    buf.push_str(&format!(
        "    description: {},\n",
        ts_string(spec.description)
    ));
    buf.push_str(&format!(
        "    longDescription: {},\n",
        ts_string(spec.long_description)
    ));
    buf.push_str(&format!("    latency: {},\n", ts_string(spec.latency)));
    buf.push_str(&format!(
        "    wireIndex: {},\n",
        ts_optional_number(spec.op.to_wire_index())
    ));
    buf.push_str(&format!(
        "    isPseudoOp: {},\n",
        ts_bool(spec.op.to_wire_index().is_none())
    ));
    buf.push_str(&format!("    minInputs: {},\n", spec.min_inputs));
    buf.push_str(&format!(
        "    producesOutput: {},\n",
        ts_bool(spec.produces_output)
    ));
    buf.push_str(&format!(
        "    needsSubmission: {},\n",
        ts_bool(spec.needs_submission)
    ));
    buf.push_str("    fields: [\n");
    for field in &spec.fields {
        buf.push_str(&format!(
            "      {{ name: {}, required: {}, description: {}, refType: {} }},\n",
            ts_string(field.name),
            ts_bool(field.required),
            ts_string(field.description),
            ts_optional_string(field.ref_type),
        ));
    }
    buf.push_str("    ],\n");
    buf.push_str(&format!(
        "    exampleJson: {},\n",
        ts_optional_string(spec.example_json)
    ));
    buf.push_str("  },\n");
}

fn render_typescript_frontend_builder_ops() -> String {
    let ops = operation_specs();
    let methods = ops
        .iter()
        .map(|spec| {
            (
                spec.op.to_string(),
                builder_method_name(&spec.op.to_string()),
            )
        })
        .collect::<Vec<_>>();
    let method_name_union = methods
        .iter()
        .map(|(_, method)| ts_string(method))
        .collect::<Vec<_>>()
        .join(" | ");
    let handwritten_methods = [
        "ask",
        "autonomous",
        "checkpoint",
        "communicate",
        "delegate",
        "invokeCapability",
        "merge",
        "nop",
        "pause",
        "registerCapability",
        "resume",
        "spawnAgent",
        "think",
        "waitAll",
    ];

    let mut buf = String::new();
    buf.push_str(
        "/**\n\
         * AUTO-GENERATED by apxm codegen typescript-frontend -- DO NOT EDIT BY HAND.\n\
         *\n\
         * Regenerate with: npm run codegen (from crates/compiler/frontend/typescript).\n\
         */\n\n",
    );
    buf.push_str("import type { GenericOpOptions, NodeRef } from \"../builder.js\";\n");
    buf.push_str("import type { OpName } from \"./ops.js\";\n\n");
    buf.push_str("/** Generated method names that expose the AIS catalog on GraphBuilder. */\n");
    buf.push_str(&format!(
        "export type GeneratedBuilderMethodName = {method_name_union};\n\n"
    ));
    buf.push_str("/** Catalog operation to generated GraphBuilder method name. */\n");
    buf.push_str(
        "export const GENERATED_GRAPH_BUILDER_OP_METHODS: Readonly<Record<OpName, GeneratedBuilderMethodName>> = {\n",
    );
    for (op, method) in &methods {
        buf.push_str(&format!("  {}: {},\n", ts_string(op), ts_string(method)));
    }
    buf.push_str("};\n\n");
    buf.push_str("declare module \"../builder.js\" {\n");
    buf.push_str("  interface GraphBuilder {\n");
    for (_, method) in &methods {
        if !handwritten_methods.contains(&method.as_str()) {
            buf.push_str(&format!(
                "    {}(options?: GenericOpOptions): NodeRef;\n",
                method
            ));
        }
    }
    buf.push_str("  }\n");
    buf.push_str("}\n\n");
    buf.push_str("type GraphBuilderPrototype = {\n");
    buf.push_str("  op(opType: OpName, options?: GenericOpOptions): NodeRef;\n");
    buf.push_str("};\n\n");
    buf.push_str(
        "/** Install catalog-derived methods without replacing handwritten ergonomic methods. */\n",
    );
    buf.push_str(
        "export function installGeneratedGraphBuilderOps(builderClass: { prototype: GraphBuilderPrototype }): void {\n",
    );
    buf.push_str(
        "  const prototype = builderClass.prototype as GraphBuilderPrototype & Record<string, unknown>;\n",
    );
    buf.push_str(
        "  for (const [opType, method] of Object.entries(GENERATED_GRAPH_BUILDER_OP_METHODS) as Array<[OpName, GeneratedBuilderMethodName]>) {\n",
    );
    buf.push_str("    if (typeof prototype[method] === \"function\") continue;\n");
    buf.push_str("    Object.defineProperty(prototype, method, {\n");
    buf.push_str("      configurable: true,\n");
    buf.push_str("      writable: true,\n");
    buf.push_str("      value: function generatedBuilderOp(this: GraphBuilderPrototype, options: GenericOpOptions = {}): NodeRef {\n");
    buf.push_str("        return this.op(opType, options);\n");
    buf.push_str("      },\n");
    buf.push_str("    });\n");
    buf.push_str("  }\n");
    buf.push_str("}\n");
    buf
}

fn builder_method_name(op: &str) -> String {
    match op {
        "RETURN" => "returnNode".to_string(),
        "SWITCH" => "switchNode".to_string(),
        "YIELD" => "yieldNode".to_string(),
        _ => lower_camel_case(op),
    }
}

fn lower_camel_case(value: &str) -> String {
    let parts = value
        .split(|c| c == '_' || c == '.')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>();
    let mut out = String::new();
    for (index, part) in parts.iter().enumerate() {
        let lower = part.to_ascii_lowercase();
        if index == 0 {
            out.push_str(&lower);
        } else {
            let mut chars = lower.chars();
            if let Some(first) = chars.next() {
                out.push(first.to_ascii_uppercase());
                out.extend(chars);
            }
        }
    }
    out
}

fn render_ts_dependency_types(buf: &mut String) {
    buf.push_str("export enum DependencyType {\n");
    buf.push_str("  DATA = \"Data\",\n");
    buf.push_str("  CONTROL = \"Control\",\n");
    buf.push_str("  EFFECT = \"Effect\",\n");
    buf.push_str("}\n\n");
}

fn render_ts_capability_groups(buf: &mut String) {
    use apxm_core::constants::capabilities::groups;

    const CAPABILITY_GROUPS: &[(&str, &str)] = &[
        ("FILE", groups::FILE),
        ("FILE_READ", groups::FILE_READ),
        ("FILE_WRITE", groups::FILE_WRITE),
        ("HTTP", groups::HTTP),
        ("WEB", groups::WEB),
        ("SEARCH", groups::SEARCH),
        ("WEB_SEARCH", groups::WEB_SEARCH),
        ("SKILLS", groups::SKILLS),
        ("AUTHORING", groups::AUTHORING),
        ("TASK", groups::TASK),
        ("AGENT_MANAGEMENT", groups::AGENT_MANAGEMENT),
    ];

    buf.push_str("export enum ToolGroup {\n");
    for (ident, value) in CAPABILITY_GROUPS {
        buf.push_str(&format!("  {ident} = {},\n", ts_string(value)));
    }
    buf.push_str("}\n\n");
}

fn render_ts_field_spec(buf: &mut String) {
    buf.push_str("export type FieldSpec = {\n");
    buf.push_str("  readonly name: string;\n");
    buf.push_str("  readonly description: string;\n");
    buf.push_str("  readonly required: boolean;\n");
    buf.push_str("  readonly refType: string | null;\n");
    buf.push_str("};\n\n");
}

fn render_ts_op_spec(buf: &mut String) {
    buf.push_str("export type OpSpec = {\n");
    buf.push_str("  readonly op: string;\n");
    buf.push_str("  readonly name: string;\n");
    buf.push_str("  readonly category: OpCategory;\n");
    buf.push_str("  readonly description: string;\n");
    buf.push_str("  readonly longDescription: string;\n");
    buf.push_str("  readonly latency: string;\n");
    buf.push_str("  readonly fields: readonly FieldSpec[];\n");
    buf.push_str("  readonly producesOutput: boolean;\n");
    buf.push_str("  readonly needsSubmission: boolean;\n");
    buf.push_str("  readonly minInputs: number;\n");
    buf.push_str("  readonly exampleJson: string | null;\n");
    buf.push_str("};\n\n");
}

fn render_ts_operations(buf: &mut String, ops: &[FrontendOperationSpec]) {
    for spec in ops {
        let op = spec.op.to_string();
        let ident = op.to_ascii_uppercase();
        buf.push_str(&format!("export const {ident}: OpSpec = {{\n"));
        buf.push_str(&format!("  op: {},\n", ts_string(&op)));
        buf.push_str(&format!("  name: {},\n", ts_string(spec.name)));
        buf.push_str(&format!(
            "  category: {} as OpCategory,\n",
            ts_string(spec.category)
        ));
        buf.push_str(&format!(
            "  description: {},\n",
            ts_string(spec.description)
        ));
        buf.push_str(&format!(
            "  longDescription: {},\n",
            ts_string(spec.long_description)
        ));
        buf.push_str(&format!("  latency: {},\n", ts_string(spec.latency)));
        buf.push_str("  fields: [\n");
        for f in &spec.fields {
            buf.push_str(&format!(
                "    {{ name: {}, description: {}, required: {}, refType: {} }},\n",
                ts_string(f.name),
                ts_string(f.description),
                ts_bool(f.required),
                ts_optional_string(f.ref_type),
            ));
        }
        buf.push_str("  ],\n");
        buf.push_str(&format!(
            "  producesOutput: {},\n",
            ts_bool(spec.produces_output)
        ));
        buf.push_str(&format!(
            "  needsSubmission: {},\n",
            ts_bool(spec.needs_submission)
        ));
        buf.push_str(&format!("  minInputs: {},\n", spec.min_inputs));
        buf.push_str(&format!(
            "  exampleJson: {},\n",
            ts_optional_string(spec.example_json)
        ));
        buf.push_str("} as const;\n\n");
    }

    buf.push_str("export const ALL_OPERATIONS: readonly OpSpec[] = [\n");
    for spec in ops {
        buf.push_str(&format!(
            "  {},\n",
            spec.op.to_string().to_ascii_uppercase()
        ));
    }
    buf.push_str("] as const;\n\n");
}

fn render_ts_categories(buf: &mut String, ops: &[FrontendOperationSpec]) {
    let mut categories: Vec<&str> = ops.iter().map(|s| s.category).collect();
    categories.sort_unstable();
    categories.dedup();

    buf.push_str("export type OpCategory =\n");
    for (i, cat) in categories.iter().enumerate() {
        let sep = if i < categories.len() - 1 { "" } else { ";" };
        buf.push_str(&format!("  | {}{}\n", ts_string(cat), sep));
    }
    buf.push('\n');
}

fn render_ts_attr_constants(buf: &mut String) {
    buf.push_str("export const ATTR = {\n");
    for item in graph_attr_constants() {
        buf.push_str(&format!("  {}: {},\n", item.name, ts_string(item.value)));
    }
    buf.push_str("} as const;\n\n");
}

fn render_ts_graph_metric_constants(buf: &mut String) {
    buf.push_str("export const GRAPH_METRICS = {\n");
    for item in graph_metric_constants() {
        buf.push_str(&format!("  {}: {},\n", item.name, ts_string(item.value)));
    }
    buf.push_str("} as const;\n\n");
}

fn render_ts_provider_types(buf: &mut String) {
    let protocols = provider_protocols();
    buf.push_str("export type ProviderProtocol =\n");
    for (i, proto) in protocols.iter().enumerate() {
        let sep = if i < protocols.len() - 1 { "" } else { ";" };
        buf.push_str(&format!("  | {}{}\n", ts_string(proto), sep));
    }
    buf.push('\n');

    buf.push_str("export type ProviderSpec = {\n");
    buf.push_str("  readonly id: string;\n");
    buf.push_str("  readonly protocol: ProviderProtocol;\n");
    buf.push_str("  readonly defaultBaseUrl: string | null;\n");
    buf.push_str("  readonly requiresApiKey: boolean;\n");
    buf.push_str("  readonly apiKeyEnvVar: string | null;\n");
    buf.push_str("  readonly aliases: readonly string[];\n");
    buf.push_str("};\n\n");

    let providers = builtin_providers();
    buf.push_str("export const BUILTIN_PROVIDERS: readonly ProviderSpec[] = [\n");
    for p in &providers {
        buf.push_str("  {\n");
        buf.push_str(&format!("    id: {},\n", ts_string(p.id)));
        buf.push_str(&format!(
            "    protocol: {} as ProviderProtocol,\n",
            ts_string(p.protocol)
        ));
        buf.push_str(&format!(
            "    defaultBaseUrl: {},\n",
            ts_optional_string(p.default_base_url)
        ));
        buf.push_str(&format!(
            "    requiresApiKey: {},\n",
            ts_bool(p.requires_api_key)
        ));
        buf.push_str(&format!(
            "    apiKeyEnvVar: {},\n",
            ts_optional_string(p.api_key_env_var)
        ));
        buf.push_str(&format!(
            "    aliases: [{}],\n",
            p.aliases
                .iter()
                .map(|a| ts_string(a))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        buf.push_str("  },\n");
    }
    buf.push_str("] as const;\n\n");
}

fn render_ts_agents(buf: &mut String) {
    buf.push_str("export type AgentTemplate = {\n");
    buf.push_str("  readonly name: string;\n");
    buf.push_str("  readonly command: string;\n");
    buf.push_str("  readonly description: string | null;\n");
    buf.push_str("  readonly routeCapabilities: readonly string[];\n");
    buf.push_str("  readonly source: string;\n");
    buf.push_str("  readonly defaultMode: string | null;\n");
    buf.push_str("  readonly defaultModel: string | null;\n");
    buf.push_str("};\n\n");

    let templates = agent_templates();
    buf.push_str("export const ALL_AGENTS: readonly AgentTemplate[] = [\n");
    for t in &templates {
        buf.push_str("  {\n");
        buf.push_str(&format!("    name: {},\n", ts_string(&t.name)));
        buf.push_str(&format!("    command: {},\n", ts_string(&t.command)));
        buf.push_str(&format!(
            "    description: {},\n",
            ts_optional_string(t.description.as_deref())
        ));
        buf.push_str("    routeCapabilities: [\n");
        for capability in &t.route_capabilities {
            buf.push_str(&format!("      {},\n", ts_string(capability)));
        }
        buf.push_str("    ],\n");
        buf.push_str(&format!("    source: {},\n", ts_string(&t.source)));
        buf.push_str(&format!(
            "    defaultMode: {},\n",
            ts_optional_string(t.default_mode.as_deref())
        ));
        buf.push_str(&format!(
            "    defaultModel: {},\n",
            ts_optional_string(t.default_model.as_deref())
        ));
        buf.push_str("  },\n");
    }
    buf.push_str("] as const;\n");
}

fn ts_string(value: &str) -> String {
    serde_json::to_string(value).expect("ts string literal")
}

fn ts_optional_string(value: Option<&str>) -> String {
    match value {
        Some(v) => ts_string(v),
        None => "null".to_string(),
    }
}

fn ts_optional_number(value: Option<u32>) -> String {
    match value {
        Some(value) => value.to_string(),
        None => "null".to_string(),
    }
}

fn ts_bool(value: bool) -> &'static str {
    if value { "true" } else { "false" }
}
