//! Frontend-conformance codegen: one shared corpus of authored-source fixtures
//! and expected FrontendGraph facts, projected into a runnable harness for
//! every registered authoring language.
//!
//! `contracts/vectors/apxm.frontend-conformance.json` states each vector once —
//! its declarations, its programs' bodies in a language-neutral statement
//! vocabulary, and what the resulting FrontendGraph, canonical AIR, and compiled
//! artifact must say. This generator projects that one statement into Python and
//! TypeScript. Neither language restates a fixture, so a vector cannot pass in
//! one language because its hand-written mirror in the other drifted: adding a
//! vector adds a case to both harnesses at once, and a language that does not
//! implement it fails.
//!
//! **The corpus is inlined here, at generation time, rather than read at test
//! time.** Neither authoring package ships `contracts/`: the Python wheel
//! packages `apxm_program*` only, and `@apxm/frontend` publishes `dist` only. A
//! harness that opened `contracts/vectors/...` would therefore work from a repo
//! checkout and fail from an installed package — the two configurations
//! `tests_program/test_packed_package.py` and `test/packed-package.test.ts`
//! exercise. TypeScript adds a second reason: `tsc` erases the typed interface
//! an Agent capture reads back, and the published package carries no
//! `inlineSources` map, so a TypeScript fixture cannot be recovered from the
//! running module and has to be carried as authored text either way. Inlining is
//! also what every other generator here does with the schemas it projects.
//!
//! Four files come out of one arm, because a harness is only a gate if both
//! halves are generated:
//!
//! * `apxm_program/_generated/conformance.py` and `src/generated/conformance.ts`
//!   carry the corpus, the fixtures, and the query evaluator. They live inside
//!   the packages so an installed package carries its own conformance harness.
//! * `tests_program/test_frontend_conformance.py` and
//!   `test/frontend-conformance.test.ts` are the test-runner invokers. They are
//!   generated too: a hand-written invoker could be deleted and that language
//!   would silently stop being checked.
//!
//! Python and TypeScript reach their capture entry differently, and the
//! difference is forced by the languages rather than chosen. Python's capture
//! reads an `async def` back through `inspect.getsource`, so the Python harness
//! carries its fixtures as real generated module code. TypeScript's capture
//! reads authored text, which the harness supplies through the package's own
//! `submitAuthoredSource` before calling the public `Agent(...)`. Both paths run
//! entirely through the surface an installed package publishes.

use std::collections::BTreeSet;

use serde_json::{Map, Value};

pub const PYTHON_CONFORMANCE_FILE: &str = "conformance.py";
pub const TYPESCRIPT_CONFORMANCE_FILE: &str = "conformance.ts";
pub const PYTHON_CONFORMANCE_TEST_FILE: &str = "test_frontend_conformance.py";
pub const TYPESCRIPT_CONFORMANCE_TEST_FILE: &str = "frontend-conformance.test.ts";

const CORPUS_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../contracts/vectors/apxm.frontend-conformance.json"
));

const PYTHON_HEADER: &str = "# AUTO-GENERATED by apxm codegen frontend-conformance; DO NOT EDIT.";
const TYPESCRIPT_HEADER: &str =
    "// AUTO-GENERATED by apxm codegen frontend-conformance; DO NOT EDIT.";

/// The one reference a corpus declaration uses to mean "a package-local handler
/// object rather than an exact typed reference". Each language projects it into
/// whatever its own frontend would reject.
const HANDLER_OBJECT_REFERENCE: &str = "@handler_object";

pub fn corpus() -> Value {
    serde_json::from_str(CORPUS_JSON).expect("apxm.frontend-conformance corpus parses")
}

fn vectors(corpus: &Value) -> &Vec<Value> {
    corpus["vectors"]
        .as_array()
        .expect("the corpus states a vectors array")
}

fn string(value: &Value, key: &str) -> String {
    value[key]
        .as_str()
        .unwrap_or_else(|| panic!("the corpus states a string {key}"))
        .to_string()
}

fn array<'a>(value: &'a Value, key: &str) -> &'a [Value] {
    value
        .get(key)
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[])
}

/// The Context declaration one name refers to, out of the corpus's shared set.
fn context_named<'a>(corpus: &'a Value, name: &str) -> &'a Value {
    array(corpus, "contexts")
        .iter()
        .find(|context| context["name"] == *name)
        .unwrap_or_else(|| panic!("the corpus declares a Context named {name}"))
}

/// The Contexts one vector uses, in the order both languages declare them.
fn vector_contexts(corpus: &Value, vector: &Value) -> Vec<String> {
    let mut names: Vec<String> = Vec::new();
    for program in array(vector, "programs") {
        if let Some(name) = program.get("context").and_then(Value::as_str) {
            if !names.iter().any(|found| found == name) {
                names.push(name.to_string());
            }
        }
        walk(array(program, "body"), &mut |statement| {
            if let Some(name) = statement.get("context").and_then(Value::as_str) {
                if array(corpus, "contexts")
                    .iter()
                    .any(|context| context["name"] == *name)
                    && !names.iter().any(|found| found == name)
                {
                    names.push(name.to_string());
                }
            }
        });
    }
    names
}

fn walk(body: &[Value], visit: &mut impl FnMut(&Value)) {
    for statement in body {
        visit(statement);
        walk(array(statement, "body"), visit);
    }
}

// ---------------------------------------------------------------------------
// Literals
// ---------------------------------------------------------------------------

/// Render one JSON value as the Python literal that reconstructs it.
fn python_literal(value: &Value) -> String {
    match value {
        Value::Null => "None".to_string(),
        Value::Bool(true) => "True".to_string(),
        Value::Bool(false) => "False".to_string(),
        Value::Number(number) => number.to_string(),
        Value::String(text) => python_string(text),
        Value::Array(items) => format!(
            "[{}]",
            items
                .iter()
                .map(python_literal)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Value::Object(fields) => format!(
            "{{{}}}",
            fields
                .iter()
                .map(|(key, entry)| format!("{}: {}", python_string(key), python_literal(entry)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// A double-quoted Python string literal, which JSON string escaping produces.
fn python_string(text: &str) -> String {
    Value::String(text.to_string()).to_string()
}

/// Render one JSON value as the TypeScript literal that reconstructs it, which
/// for every shape the corpus uses is the JSON text itself.
fn typescript_literal(value: &Value) -> String {
    value.to_string()
}

fn typescript_string(text: &str) -> String {
    Value::String(text.to_string()).to_string()
}

// ---------------------------------------------------------------------------
// Python projection
// ---------------------------------------------------------------------------

fn python_scalar_type(scalar: &str) -> &'static str {
    match scalar {
        "list" => "tuple",
        "boolean" => "bool",
        "integer" => "int",
        "string" => "str",
        other => panic!("unhandled corpus scalar {other}"),
    }
}

fn python_default(scalar: &str, default: &Value) -> String {
    if scalar == "list" {
        return "()".to_string();
    }
    python_literal(default)
}

fn python_expression(node: &Value) -> String {
    let kind = string(node, "expr");
    let arguments = || {
        array(node, "arguments")
            .iter()
            .map(python_expression)
            .collect::<Vec<_>>()
            .join(", ")
    };
    match kind.as_str() {
        "name" => string(node, "name"),
        "integer" => node["value"].to_string(),
        "field" => format!(
            "{}[{}]",
            string(node, "name"),
            python_string(&string(node, "field"))
        ),
        "context" => "agent.context".to_string(),
        "effect" => format!("await {}({})", string(node, "binding"), arguments()),
        "unawaited_effect" => format!("{}({})", string(node, "binding"), arguments()),
        "plain_call" => format!("{}({})", string(node, "callee"), arguments()),
        "invoke" => format!("await {}.invoke({})", string(node, "instance"), arguments()),
        "await_event" => format!("await {}.wait()", string(node, "event")),
        other => panic!("unhandled corpus expression {other}"),
    }
}

fn python_body(corpus: &Value, body: &[Value], indent: usize) -> Vec<String> {
    let pad = " ".repeat(indent);
    let mut lines = Vec::new();
    for statement in body {
        let kind = string(statement, "stmt");
        let nested = || python_body(corpus, array(statement, "body"), indent + 4);
        match kind.as_str() {
            "let_null" => lines.push(format!("{pad}{} = None", string(statement, "name"))),
            "bind" => lines.push(format!(
                "{pad}{} = {}",
                string(statement, "name"),
                python_expression(&statement["value"])
            )),
            "return" => lines.push(format!(
                "{pad}return {}",
                python_expression(&statement["value"])
            )),
            "expr" => lines.push(format!("{pad}{}", python_expression(&statement["value"]))),
            "loop_forever" => {
                lines.push(format!("{pad}while True:"));
                lines.extend(nested());
            }
            "if_not_null" => {
                lines.push(format!(
                    "{pad}if {} is not None:",
                    python_expression(&statement["value"])
                ));
                lines.extend(nested());
            }
            "if_equals" => {
                lines.push(format!(
                    "{pad}if {} == {}:",
                    python_expression(&statement["left"]),
                    python_expression(&statement["right"])
                ));
                lines.extend(nested());
            }
            "set_context" => {
                let values = statement["values"]
                    .as_object()
                    .cloned()
                    .unwrap_or_else(Map::new);
                let arguments = values
                    .iter()
                    .map(|(key, value)| format!("{key}={}", python_literal(value)))
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!(
                    "{pad}agent.context = {}({arguments})",
                    string(statement, "context")
                ));
            }
            "yield" => lines.push(format!(
                "{pad}{} = await agent.yield_({})",
                string(statement, "name"),
                python_expression(&statement["value"])
            )),
            "new_program" => lines.push(format!(
                "{pad}{} = {}.new(context={}())",
                string(statement, "name"),
                string(statement, "program"),
                string(statement, "context")
            )),
            "task_group" => {
                lines.push(format!("{pad}async with TaskGroup():"));
                lines.extend(nested());
            }
            "shadow_binding" => lines.push(format!(
                "{pad}{} = lambda value: value",
                string(statement, "name")
            )),
            other => panic!("unhandled corpus statement {other}"),
        }
    }
    lines
}

fn python_declaration(declaration: &Value) -> String {
    let marker = string(declaration, "marker");
    let typed = if marker == "Event" {
        "[object]"
    } else {
        "[object, object]"
    };
    let permission = match declaration.get("permission") {
        None => String::new(),
        Some(permission) if permission["decision"] == "allow" => ", permission=Allow".to_string(),
        Some(permission) => format!(
            ", permission=Ask({})",
            python_string(&string(permission, "reason"))
        ),
    };
    format!(
        "{} = {marker}{typed}({}{permission})",
        string(declaration, "name"),
        python_string(&string(declaration, "target_ref"))
    )
}

fn python_context(context: &Value) -> Vec<String> {
    let mut lines = vec![
        "@Context".to_string(),
        format!("class {}:", string(context, "name")),
    ];
    for field in array(context, "fields") {
        let scalar = string(field, "scalar");
        lines.push(format!(
            "    {}: {} = {}",
            string(field, "name"),
            python_scalar_type(&scalar),
            python_default(&scalar, &field["default"])
        ));
    }
    lines
}

fn python_hook(corpus: &Value, hook: &Value) -> Vec<String> {
    let mut lines = vec![
        format!(
            "@Hook.{}(target={}, scope={})",
            string(hook, "phase"),
            python_string(&string(hook, "target")),
            python_string(&string(hook, "scope"))
        ),
        format!("async def {}(agent) -> None:", string(hook, "name")),
    ];
    let body = python_body(corpus, array(hook, "body"), 4);
    if body.is_empty() {
        lines.push("    return None".to_string());
    } else {
        lines.extend(body);
    }
    lines
}

fn python_program(corpus: &Value, program: &Value, indent: usize) -> Vec<String> {
    let pad = " ".repeat(indent);
    let mut arguments = vec![
        format!("input={}", string(program, "input")),
        format!("output={}", string(program, "output")),
    ];
    if let Some(context) = program.get("context").and_then(Value::as_str) {
        arguments.push(format!("context={context}"));
    }
    let mut lines = vec![
        format!("{pad}@Agent({})", arguments.join(", ")),
        format!(
            "{pad}async def {}(agent, input):",
            string(program, "program_id")
        ),
    ];
    lines.extend(python_body(corpus, array(program, "body"), indent + 4));
    lines
}

pub fn render_conformance_python() -> String {
    let corpus = corpus();
    let mut out: Vec<String> = Vec::new();
    out.push(PYTHON_HEADER.to_string());
    out.push(PYTHON_MODULE_DOC.to_string());
    out.push(String::new());
    out.push("from __future__ import annotations".to_string());
    out.push(String::new());
    out.push("import json".to_string());
    out.push("import re".to_string());
    out.push("from typing import Any, Optional".to_string());
    out.push(String::new());
    out.push(
        "from .. import Agent, Capability, Context, Event, Hook, Model, TaskGroup, Tool"
            .to_string(),
    );
    out.push("from ..permissions import Allow, Ask".to_string());
    out.push(String::new());
    out.push(PYTHON_RUNTIME.to_string());
    out.push(String::new());

    out.push("_EXPECTATIONS: dict[str, list[dict[str, Any]]] = {".to_string());
    for vector in vectors(&corpus) {
        let Some(expectations) = vector.get("expect") else {
            continue;
        };
        out.push(format!("    {}: [", python_string(&string(vector, "id"))));
        for expectation in expectations.as_array().expect("expect states an array") {
            out.push(format!("        {},", python_literal(expectation)));
        }
        out.push("    ],".to_string());
    }
    out.push("}".to_string());
    out.push(String::new());

    for type_ref in array(&corpus, "type_refs") {
        let name = type_ref.as_str().expect("a type ref is a string");
        out.push(format!("class {name}:"));
        out.push(
            "    \"\"\"A typed declaration the conformance corpus states an interface with.\"\"\""
                .to_string(),
        );
        out.push(String::new());
    }
    for context in array(&corpus, "contexts") {
        out.push(String::new());
        out.extend(python_context(context));
        out.push(String::new());
    }

    let mut ids: Vec<String> = Vec::new();
    for vector in vectors(&corpus) {
        let id = string(vector, "id");
        out.push(String::new());
        out.push(format!("# vector: {id}"));
        if let Some(rejections) = vector.get("declaration_rejections") {
            out.extend(python_declaration_rejections(&id, rejections));
        } else if let Some(rejects) = vector.get("rejects") {
            out.extend(python_rejection_vector(&corpus, &id, vector, rejects));
        } else {
            out.extend(python_program_vector(&corpus, &id, vector));
        }
        ids.push(id);
    }

    out.push(String::new());
    out.push(String::new());
    out.push("VECTOR_IDS: tuple[str, ...] = (".to_string());
    for id in &ids {
        out.push(format!("    {},", python_string(id)));
    }
    out.push(")".to_string());
    out.push(String::new());
    out.push("_VECTORS = {".to_string());
    for id in &ids {
        out.push(format!("    {}: _vector_{id},", python_string(id)));
    }
    out.push("}".to_string());
    out.push(String::new());
    out.push(PYTHON_TAIL.to_string());

    let mut rendered = out.join("\n");
    rendered.push('\n');
    rendered
}

fn python_declaration_rejections(id: &str, rejections: &Value) -> Vec<String> {
    let markers: Vec<String> = array(rejections, "markers")
        .iter()
        .map(|marker| marker.as_str().expect("a marker is a string").to_string())
        .collect();
    let message = string(rejections, "message_contains");
    vec![
        format!("def _vector_{id}() -> list[str]:"),
        "    failures: list[str] = []".to_string(),
        format!("    for marker in ({},):", markers.join(", ")),
        format!(
            "        for reference in {}:",
            python_literal(&rejections["references"])
        ),
        format!(
            "            argument: Any = (lambda: None) if reference == {} else reference",
            python_string(HANDLER_OBJECT_REFERENCE)
        ),
        "            try:".to_string(),
        "                marker(argument)".to_string(),
        "            except (ValueError, TypeError) as error:".to_string(),
        format!(
            "                if {} not in str(error):",
            python_string(&message)
        ),
        format!(
            "                    failures.append(_failure({}, f\"declaring {{reference!r}} was rejected with {{error}}\"))",
            python_string(id)
        ),
        "            else:".to_string(),
        format!(
            "                failures.append(_failure({}, f\"declaring {{reference!r}} was accepted, and the corpus states it is rejected\"))",
            python_string(id)
        ),
        "    return failures".to_string(),
    ]
}

fn python_rejection_vector(
    corpus: &Value,
    id: &str,
    vector: &Value,
    rejects: &Value,
) -> Vec<String> {
    let mut lines = vec![format!("def _vector_{id}() -> list[str]:")];
    for declaration in array(vector, "declarations") {
        lines.push(format!("    {}", python_declaration(declaration)));
    }
    lines.push("    try:".to_string());
    for program in array(vector, "programs") {
        lines.extend(python_program(corpus, program, 8));
    }
    lines.push("    except Exception as error:".to_string());
    match rejects.get("message_contains").and_then(Value::as_str) {
        None => lines.push("        return []".to_string()),
        Some(message) => {
            lines.push(format!(
                "        if {} in str(error):",
                python_string(message)
            ));
            lines.push("            return []".to_string());
            lines.push(format!(
                "        return [_failure({}, f\"rejected with {{str(error)!r}}, which does not state {}\")]",
                python_string(id),
                message.replace('"', "'")
            ));
        }
    }
    lines.push(format!(
        "    return [_failure({}, \"authoring was accepted, and the corpus states it is rejected\")]",
        python_string(id)
    ));
    lines
}

fn python_program_vector(corpus: &Value, id: &str, vector: &Value) -> Vec<String> {
    let mut lines = Vec::new();
    for declaration in array(vector, "declarations") {
        lines.push(python_declaration(declaration));
    }
    let mut hooks: Vec<String> = Vec::new();
    for program in array(vector, "programs") {
        // A Python Hook binds through the module globals its Agent resolves, so
        // it is declared above that Agent and removed again below it: a Hook
        // left in scope would bind into every later vector's capture too.
        for hook in array(program, "hooks") {
            lines.push(String::new());
            lines.extend(python_hook(corpus, hook));
            hooks.push(string(hook, "name"));
        }
        lines.push(String::new());
        lines.extend(python_program(corpus, program, 0));
    }
    for hook in hooks {
        lines.push(String::new());
        lines.push(format!("del {hook}"));
    }
    let subject = string(
        array(vector, "programs")
            .last()
            .expect("a program vector states at least one program"),
        "program_id",
    );
    lines.push(String::new());
    lines.push(format!("def _vector_{id}() -> list[str]:"));
    lines.push(format!(
        "    return _check({}, {subject}, _EXPECTATIONS[{}])",
        python_string(id),
        python_string(id)
    ));
    lines
}

// ---------------------------------------------------------------------------
// TypeScript projection
// ---------------------------------------------------------------------------

fn typescript_scalar_type(scalar: &str) -> &'static str {
    match scalar {
        "list" => "unknown[]",
        "boolean" => "boolean",
        "integer" => "number",
        "string" => "string",
        other => panic!("unhandled corpus scalar {other}"),
    }
}

fn typescript_expression(node: &Value) -> String {
    let kind = string(node, "expr");
    let arguments = || {
        array(node, "arguments")
            .iter()
            .map(typescript_expression)
            .collect::<Vec<_>>()
            .join(", ")
    };
    match kind.as_str() {
        "name" => string(node, "name"),
        "integer" => node["value"].to_string(),
        "field" => format!("{}.{}", string(node, "name"), string(node, "field")),
        "context" => "agent.context".to_string(),
        "effect" => format!("await {}({})", string(node, "binding"), arguments()),
        "unawaited_effect" => format!("{}({})", string(node, "binding"), arguments()),
        "plain_call" => format!("{}({})", string(node, "callee"), arguments()),
        "invoke" => format!("await {}.invoke({})", string(node, "instance"), arguments()),
        "await_event" => format!("await {}.wait()", string(node, "event")),
        other => panic!("unhandled corpus expression {other}"),
    }
}

/// The object literal one Context's declared defaults, overridden by `values`,
/// state. TypeScript states every field where Python names only the overrides.
fn typescript_context_literal(corpus: &Value, name: &str, values: &Map<String, Value>) -> String {
    let context = context_named(corpus, name);
    let fields: Vec<String> = array(context, "fields")
        .iter()
        .map(|field| {
            let field_name = string(field, "name");
            let value = values.get(&field_name).unwrap_or(&field["default"]);
            format!("{field_name}: {}", typescript_literal(value))
        })
        .collect();
    format!("{{ {} }}", fields.join(", "))
}

fn typescript_body(
    corpus: &Value,
    body: &[Value],
    indent: usize,
    declared: &mut BTreeSet<String>,
) -> Vec<String> {
    let pad = " ".repeat(indent);
    let mut lines = Vec::new();
    for statement in body {
        let kind = string(statement, "stmt");
        match kind.as_str() {
            "let_null" => {
                let name = string(statement, "name");
                declared.insert(name.clone());
                lines.push(format!("{pad}let {name}: any = null;"));
            }
            "bind" => {
                let name = string(statement, "name");
                let keyword = if declared.contains(&name) {
                    ""
                } else {
                    "const "
                };
                declared.insert(name.clone());
                lines.push(format!(
                    "{pad}{keyword}{name} = {};",
                    typescript_expression(&statement["value"])
                ));
            }
            "return" => lines.push(format!(
                "{pad}return {};",
                typescript_expression(&statement["value"])
            )),
            "expr" => lines.push(format!(
                "{pad}{};",
                typescript_expression(&statement["value"])
            )),
            "loop_forever" => {
                lines.push(format!("{pad}while (true) {{"));
                lines.extend(typescript_body(
                    corpus,
                    array(statement, "body"),
                    indent + 2,
                    declared,
                ));
                lines.push(format!("{pad}}}"));
            }
            "if_not_null" => {
                lines.push(format!(
                    "{pad}if ({} !== null) {{",
                    typescript_expression(&statement["value"])
                ));
                lines.extend(typescript_body(
                    corpus,
                    array(statement, "body"),
                    indent + 2,
                    declared,
                ));
                lines.push(format!("{pad}}}"));
            }
            "if_equals" => {
                lines.push(format!(
                    "{pad}if ({} === {}) {{",
                    typescript_expression(&statement["left"]),
                    typescript_expression(&statement["right"])
                ));
                lines.extend(typescript_body(
                    corpus,
                    array(statement, "body"),
                    indent + 2,
                    declared,
                ));
                lines.push(format!("{pad}}}"));
            }
            "set_context" => {
                let values = statement["values"]
                    .as_object()
                    .cloned()
                    .unwrap_or_else(Map::new);
                lines.push(format!(
                    "{pad}agent.context = {};",
                    typescript_context_literal(corpus, &string(statement, "context"), &values)
                ));
            }
            "yield" => lines.push(format!(
                "{pad}{} = await agent.yield_({});",
                string(statement, "name"),
                typescript_expression(&statement["value"])
            )),
            "new_program" => {
                let name = string(statement, "name");
                declared.insert(name.clone());
                lines.push(format!(
                    "{pad}const {name} = {}.new({{ context: {} }});",
                    string(statement, "program"),
                    typescript_context_literal(corpus, &string(statement, "context"), &Map::new())
                ));
            }
            "task_group" => {
                lines.push(format!("{pad}await TaskGroup.run(async () => {{"));
                lines.extend(typescript_body(
                    corpus,
                    array(statement, "body"),
                    indent + 2,
                    declared,
                ));
                lines.push(format!("{pad}}});"));
            }
            "shadow_binding" => {
                let name = string(statement, "name");
                declared.insert(name.clone());
                lines.push(format!("{pad}const {name} = async (value: any) => value;"));
            }
            other => panic!("unhandled corpus statement {other}"),
        }
    }
    lines
}

fn typescript_declaration(declaration: &Value) -> String {
    let marker = string(declaration, "marker");
    let typed = if marker == "Event" {
        "<Input>"
    } else {
        "<Input, Output>"
    };
    let options = match declaration.get("permission") {
        None => String::new(),
        Some(permission) if permission["decision"] == "allow" => {
            ", { permission: Allow }".to_string()
        }
        Some(permission) => format!(
            ", {{ permission: Ask({}) }}",
            typescript_string(&string(permission, "reason"))
        ),
    };
    format!(
        "const {} = {marker}{typed}({}{options});",
        string(declaration, "name"),
        typescript_string(&string(declaration, "target_ref"))
    )
}

/// The authored TypeScript module one vector's programs are captured from.
fn typescript_source_text(corpus: &Value, vector: &Value) -> String {
    let mut lines = vec![
        "import { Agent, Capability, Context, Event, Hook, Model, TaskGroup, Tool } from \"@apxm/frontend\";"
            .to_string(),
        String::new(),
    ];
    for type_ref in array(corpus, "type_refs") {
        lines.push(format!(
            "type {} = any;",
            type_ref.as_str().expect("a type ref is a string")
        ));
    }
    let contexts = vector_contexts(corpus, vector);
    for name in &contexts {
        let context = context_named(corpus, name);
        let fields: Vec<String> = array(context, "fields")
            .iter()
            .map(|field| {
                format!(
                    "{}: {}",
                    string(field, "name"),
                    typescript_scalar_type(&string(field, "scalar"))
                )
            })
            .collect();
        lines.push(format!("type {name} = {{ {} }};", fields.join(", ")));
    }
    lines.push(String::new());
    for name in &contexts {
        lines.push(format!(
            "const {name} = Context<{name}>({});",
            typescript_context_literal(corpus, name, &Map::new())
        ));
    }
    for declaration in array(vector, "declarations") {
        lines.push(typescript_declaration(declaration));
    }
    for program in array(vector, "programs") {
        lines.push(String::new());
        lines.extend(typescript_program_text(corpus, program));
        for hook in array(program, "hooks") {
            lines.push(String::new());
            lines.extend(typescript_hook_text(corpus, program, hook));
        }
    }
    let mut text = lines.join("\n");
    text.push('\n');
    text
}

fn typescript_program_text(corpus: &Value, program: &Value) -> Vec<String> {
    let context = program.get("context").and_then(Value::as_str);
    let generics = match context {
        Some(context) => format!(
            "<{}, {}, {context}>",
            string(program, "input"),
            string(program, "output")
        ),
        None => format!(
            "<{}, {}>",
            string(program, "input"),
            string(program, "output")
        ),
    };
    let mut lines = vec![
        format!(
            "const {} = Agent{generics}({{",
            string(program, "program_id")
        ),
        format!(
            "  name: {},",
            typescript_string(&string(program, "program_id"))
        ),
    ];
    if let Some(context) = context {
        lines.push(format!("  context: {context},"));
    }
    lines.push("  async run(agent, input) {".to_string());
    lines.extend(typescript_body(
        corpus,
        array(program, "body"),
        4,
        &mut BTreeSet::new(),
    ));
    lines.push("  },".to_string());
    lines.push("});".to_string());
    lines
}

fn typescript_hook_text(corpus: &Value, program: &Value, hook: &Value) -> Vec<String> {
    let context = program
        .get("context")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    let mut lines = vec![
        format!(
            "const {} = Hook.{}<{context}>({{",
            string(hook, "name"),
            string(hook, "phase")
        ),
        format!("  agent: {},", string(program, "program_id")),
        format!("  target: {},", string(hook, "target")),
        format!("  scope: {},", typescript_string(&string(hook, "scope"))),
        "  async run(agent) {".to_string(),
    ];
    lines.extend(typescript_body(
        corpus,
        array(hook, "body"),
        4,
        &mut BTreeSet::new(),
    ));
    lines.push("  },".to_string());
    lines.push("});".to_string());
    lines
}

fn typescript_agent_call(program: &Value) -> String {
    let context = match program.get("context").and_then(Value::as_str) {
        Some(context) => format!(" context: {context},"),
        None => String::new(),
    };
    format!(
        "  const {id} = Agent<Input, Output>({{ name: {name},{context} async run() {{ return null; }} }});",
        id = string(program, "program_id"),
        name = typescript_string(&string(program, "program_id"))
    )
}

pub fn render_conformance_typescript() -> String {
    let corpus = corpus();
    let mut out: Vec<String> = Vec::new();
    out.push(TYPESCRIPT_HEADER.to_string());
    out.push(TYPESCRIPT_MODULE_DOC.to_string());
    out.push(String::new());
    out.push(
        "import { Agent, Capability, Context, Event, Model, Tool } from \"../index.js\";"
            .to_string(),
    );
    out.push("import { submitAuthoredSource } from \"../node.js\";".to_string());
    out.push("import { Allow, Ask } from \"../permissions.js\";".to_string());
    out.push(String::new());
    for type_ref in array(&corpus, "type_refs") {
        out.push(format!(
            "type {} = any;",
            type_ref.as_str().expect("a type ref is a string")
        ));
    }
    for context in array(&corpus, "contexts") {
        let fields: Vec<String> = array(context, "fields")
            .iter()
            .map(|field| {
                format!(
                    "{}: {}",
                    string(field, "name"),
                    typescript_scalar_type(&string(field, "scalar"))
                )
            })
            .collect();
        out.push(format!(
            "type {} = {{ {} }};",
            string(context, "name"),
            fields.join(", ")
        ));
    }
    out.push(String::new());
    out.push(TYPESCRIPT_RUNTIME.to_string());

    out.push("const EXPECTATIONS: Readonly<Record<string, Expectation[]>> = {".to_string());
    for vector in vectors(&corpus) {
        let Some(expectations) = vector.get("expect") else {
            continue;
        };
        out.push(format!("  {}: [", typescript_string(&string(vector, "id"))));
        for expectation in expectations.as_array().expect("expect states an array") {
            out.push(format!("    {},", typescript_literal(expectation)));
        }
        out.push("  ],".to_string());
    }
    out.push("};".to_string());

    let mut ids: Vec<String> = Vec::new();
    for vector in vectors(&corpus) {
        let id = string(vector, "id");
        out.push(String::new());
        if let Some(rejections) = vector.get("declaration_rejections") {
            out.extend(typescript_declaration_rejections(&id, rejections));
        } else {
            out.push(format!(
                "const source_{id} = {};",
                typescript_string(&typescript_source_text(&corpus, vector))
            ));
            out.push(String::new());
            out.push(format!("function vector_{id}(): string[] {{"));
            for name in vector_contexts(&corpus, vector) {
                out.push(format!(
                    "  const {name} = Context<{name}>({});",
                    typescript_context_literal(&corpus, &name, &Map::new())
                ));
                out.push(format!("  void {name};"));
            }
            for declaration in array(vector, "declarations") {
                out.push(format!("  {}", typescript_declaration(declaration)));
                out.push(format!("  void {};", string(declaration, "name")));
            }
            out.push(format!(
                "  submitAuthoredSource({{ fileName: {}, text: source_{id} }});",
                typescript_string(&format!("{id}.ts"))
            ));
            match vector.get("rejects") {
                Some(rejects) => {
                    out.push("  try {".to_string());
                    for program in array(vector, "programs") {
                        out.push(format!("  {}", typescript_agent_call(program)));
                        out.push(format!("    void {};", string(program, "program_id")));
                    }
                    out.push("  } catch (error) {".to_string());
                    match rejects.get("message_contains").and_then(Value::as_str) {
                        None => out.push("    return [];".to_string()),
                        Some(message) => {
                            out.push(format!(
                                "    if (String(error).includes({})) {{",
                                typescript_string(message)
                            ));
                            out.push("      return [];".to_string());
                            out.push("    }".to_string());
                            out.push(format!(
                                "    return [failure({}, `rejected with ${{JSON.stringify(String(error))}}, which does not state {}`)];",
                                typescript_string(&id),
                                message.replace('"', "'")
                            ));
                        }
                    }
                    out.push("  }".to_string());
                    out.push(format!(
                        "  return [failure({}, \"authoring was accepted, and the corpus states it is rejected\")];",
                        typescript_string(&id)
                    ));
                }
                None => {
                    let programs = array(vector, "programs");
                    for program in programs {
                        out.push(typescript_agent_call(program));
                    }
                    for program in &programs[..programs.len() - 1] {
                        out.push(format!("  void {};", string(program, "program_id")));
                    }
                    out.push(format!(
                        "  return check({}, {}, EXPECTATIONS[{}]);",
                        typescript_string(&id),
                        string(programs.last().expect("one program"), "program_id"),
                        typescript_string(&id)
                    ));
                }
            }
            out.push("}".to_string());
        }
        ids.push(id);
    }

    out.push(String::new());
    out.push("export const VECTOR_IDS: readonly string[] = [".to_string());
    for id in &ids {
        out.push(format!("  {},", typescript_string(id)));
    }
    out.push("];".to_string());
    out.push(String::new());
    out.push("const VECTORS: Readonly<Record<string, () => string[]>> = {".to_string());
    for id in &ids {
        out.push(format!("  {}: vector_{id},", typescript_string(id)));
    }
    out.push("};".to_string());
    out.push(String::new());
    out.push(TYPESCRIPT_TAIL.to_string());

    let mut rendered = out.join("\n");
    rendered.push('\n');
    rendered
}

fn typescript_declaration_rejections(id: &str, rejections: &Value) -> Vec<String> {
    let markers: Vec<String> = array(rejections, "markers")
        .iter()
        .map(|marker| {
            let name = marker.as_str().expect("a marker is a string");
            format!("[\"{name}\", {name} as unknown as (reference: unknown) => unknown]")
        })
        .collect();
    let message = string(rejections, "message_contains");
    let mut lines = vec![
        format!("function vector_{id}(): string[] {{"),
        "  const failures: string[] = [];".to_string(),
        format!(
            "  const markers: Array<[string, (reference: unknown) => unknown]> = [{}];",
            markers.join(", ")
        ),
        format!(
            "  const references = {};",
            typescript_literal(&rejections["references"])
        ),
        "  for (const [, marker] of markers) {".to_string(),
        "    for (const reference of references) {".to_string(),
        format!(
            "      const argument: unknown = reference === {} ? {{ run() {{}} }} : reference;",
            typescript_string(HANDLER_OBJECT_REFERENCE)
        ),
        "      try {".to_string(),
        "        marker(argument);".to_string(),
    ];
    lines.push(format!(
        "        failures.push(failure({}, `declaring ${{JSON.stringify(reference)}} was accepted, and the corpus states it is rejected`));",
        typescript_string(id)
    ));
    lines.push("      } catch (error) {".to_string());
    lines.push(format!(
        "        if (!String(error).includes({})) {{",
        typescript_string(&message)
    ));
    lines.push(format!(
        "          failures.push(failure({}, `declaring ${{JSON.stringify(reference)}} was rejected with ${{String(error)}}`));",
        typescript_string(id)
    ));
    lines.push("        }".to_string());
    lines.push("      }".to_string());
    lines.push("    }".to_string());
    lines.push("  }".to_string());
    lines.push("  return failures;".to_string());
    lines.push("}".to_string());
    lines
}

// ---------------------------------------------------------------------------
// Test-runner invokers
// ---------------------------------------------------------------------------

pub fn render_conformance_python_test() -> String {
    let corpus = corpus();
    let mut out = vec![
        PYTHON_HEADER.to_string(),
        "\"\"\"Every apxm.frontend-conformance vector, against the Python frontend.\"\"\""
            .to_string(),
        String::new(),
        "from __future__ import annotations".to_string(),
        String::new(),
        "import pytest".to_string(),
        String::new(),
        "from apxm_program._generated.conformance import VECTOR_IDS, run_vector".to_string(),
        String::new(),
        String::new(),
        "@pytest.mark.parametrize(\"vector_id\", VECTOR_IDS)".to_string(),
        "def test_frontend_conformance_vector(vector_id: str) -> None:".to_string(),
        "    failures = run_vector(vector_id)".to_string(),
        "    assert not failures, \"\\n\".join(failures)".to_string(),
        String::new(),
        String::new(),
        "def test_every_corpus_vector_is_projected() -> None:".to_string(),
        "    assert VECTOR_IDS == (".to_string(),
    ];
    for vector in vectors(&corpus) {
        out.push(format!("        {},", python_string(&string(vector, "id"))));
    }
    out.push("    )".to_string());
    let mut rendered = out.join("\n");
    rendered.push('\n');
    rendered
}

pub fn render_conformance_typescript_test() -> String {
    let corpus = corpus();
    let mut out = vec![
        TYPESCRIPT_HEADER.to_string(),
        "// Every apxm.frontend-conformance vector, against the TypeScript frontend.".to_string(),
        String::new(),
        "import { describe, expect, it } from \"vitest\";".to_string(),
        String::new(),
        "import { VECTOR_IDS, runVector } from \"../src/generated/conformance.ts\";".to_string(),
        String::new(),
        "describe(\"frontend conformance corpus\", () => {".to_string(),
        "  it(\"projects every corpus vector\", () => {".to_string(),
        "    expect(VECTOR_IDS).toEqual([".to_string(),
    ];
    for vector in vectors(&corpus) {
        out.push(format!(
            "      {},",
            typescript_string(&string(vector, "id"))
        ));
    }
    out.push("    ]);".to_string());
    out.push("  });".to_string());
    out.push(String::new());
    out.push("  for (const vectorId of VECTOR_IDS) {".to_string());
    out.push("    it(vectorId, () => {".to_string());
    out.push("      expect(runVector(vectorId).join(\"\\n\")).toBe(\"\");".to_string());
    out.push("    });".to_string());
    out.push("  }".to_string());
    out.push("});".to_string());
    let mut rendered = out.join("\n");
    rendered.push('\n');
    rendered
}

// ---------------------------------------------------------------------------
// Fixed harness bodies
// ---------------------------------------------------------------------------

const PYTHON_MODULE_DOC: &str = r##""""The shared frontend-conformance corpus, projected into Python.

Every fixture and every expectation here is generated from
`contracts/vectors/apxm.frontend-conformance.json`. The corpus is carried as
data rather than read from disk: an installed `apxm_program` wheel packages
`apxm_program` only, so there is no `contracts/` directory to resolve a path
against, and this harness runs the same from the repository and from a wheel.

Programs are authored at module scope because Python capture reads an
`async def` back through `inspect.getsource`, which needs a real file. Vectors
the corpus states are rejected are authored inside their own function instead,
so importing this module does not raise.
""""##;

const TYPESCRIPT_MODULE_DOC: &str = r#"// The shared frontend-conformance corpus, projected into TypeScript.
//
// Every fixture and every expectation here is generated from
// `contracts/vectors/apxm.frontend-conformance.json`. The corpus is carried as
// data rather than read from disk: `@apxm/frontend` publishes `dist` only, so
// there is no `contracts/` directory to resolve a path against, and this
// harness runs the same from the repository and from an installed package.
//
// Each vector supplies its authored text through the package's own
// `submitAuthoredSource` and then calls the public `Agent(...)`, because
// TypeScript capture reads authored source rather than a live closure and `tsc`
// has already erased the typed interface from the module that runs. That import
// makes this module Node-only; nothing in the browser authoring entrypoint
// imports it."#;

const PYTHON_RUNTIME: &str = r#"
LANGUAGE = "python"


def _failure(vector: str, diff: str) -> str:
    """Render one conformance failure as its own closed reason."""
    return f"FrontendConformanceFailure{{language={LANGUAGE}, vector={vector!r}, diff={diff!r}}}"


_MISSING = object()


def _segments(path: str) -> list[str]:
    """Split a query path on the dots that are not inside a bracket."""
    segments: list[str] = []
    depth = 0
    current: list[str] = []
    for character in path:
        if character == "[":
            depth += 1
        elif character == "]":
            depth -= 1
        if character == "." and depth == 0:
            segments.append("".join(current))
            current = []
            continue
        current.append(character)
    if current:
        segments.append("".join(current))
    return segments


def _step(cursor: Any, segment: str) -> Any:
    """Apply one `name[bracket]...` query segment to the cursor."""
    name, _, rest = segment.partition("[")
    if name:
        if isinstance(cursor, list):
            cursor = [item[name] for item in cursor if isinstance(item, dict) and name in item]
        elif isinstance(cursor, dict):
            cursor = cursor.get(name, _MISSING)
        else:
            cursor = _MISSING
    while rest:
        bracket, _, rest = rest.partition("]")
        cursor = _bracket(cursor, bracket)
        rest = rest.lstrip("[")
    return cursor


def _bracket(cursor: Any, bracket: str) -> Any:
    """`[]` flattens one level, `[n]` indexes, and `[key=value]` filters."""
    if not isinstance(cursor, list):
        return _MISSING
    if bracket == "":
        if cursor and all(isinstance(item, list) for item in cursor):
            return [inner for item in cursor for inner in item]
        return cursor
    if "=" in bracket:
        key, _, wanted = bracket.partition("=")
        return [item for item in cursor if _scalar(_dotted(item, key)) == wanted]
    index = int(bracket)
    return cursor[index] if index < len(cursor) else _MISSING


def _dotted(item: Any, key: str) -> Any:
    for part in key.split("."):
        if not isinstance(item, dict) or part not in item:
            return _MISSING
        item = item[part]
    return item


def _scalar(value: Any) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    return str(value)


def _resolve(subject: Any, query: str) -> Any:
    """Resolve one corpus query against a captured program."""
    source, _, path = query.partition(":")
    if source == "diagnostics":
        return subject.diagnostics()
    if source == "graph":
        cursor: Any = subject.frontend_graph()
    elif source == "air":
        cursor = json.loads(subject.canonical_air())
    elif source == "artifact":
        cursor = subject.artifact()
    else:
        raise ValueError(f"unknown corpus query source {source!r}")
    for segment in _segments(path):
        cursor = _step(cursor, segment)
    return cursor


def _render(value: Any) -> str:
    if value is _MISSING:
        return "<absent>"
    return json.dumps(value, sort_keys=True, default=str)


def _sorted_scalars(value: Any) -> list[str]:
    return sorted(_scalar(item) for item in (value if isinstance(value, list) else [value]))


def _check(vector: str, subject: Any, expectations: list[dict[str, Any]]) -> list[str]:
    """Evaluate every expectation the corpus states about one captured program."""
    failures: list[str] = []
    for expectation in expectations:
        query = expectation["query"]
        actual = _resolve(subject, query)
        for operator, argument in expectation.items():
            if operator == "query":
                continue
            detail = _apply(subject, operator, actual, argument)
            if detail is not None:
                failures.append(_failure(vector, f"{query} {detail}"))
    return failures


def _apply(subject: Any, operator: str, actual: Any, argument: Any) -> Optional[str]:
    """One corpus operator, or a rendered difference when it does not hold."""
    if operator == "equals":
        if actual != argument:
            return f"expected {_render(argument)}, got {_render(actual)}"
    elif operator == "set_equals":
        if not isinstance(actual, list) or _sorted_scalars(actual) != _sorted_scalars(argument):
            return f"expected the set {_render(argument)}, got {_render(actual)}"
    elif operator in ("includes", "set_includes"):
        if not isinstance(actual, list) or any(item not in actual for item in argument):
            return f"expected to include {_render(argument)}, got {_render(actual)}"
    elif operator == "length":
        if not isinstance(actual, list) or len(actual) != argument:
            return f"expected {argument} entries, got {_render(actual)}"
    elif operator == "every_equals":
        if not isinstance(actual, list) or any(item != argument for item in actual):
            return f"expected every entry to be {_render(argument)}, got {_render(actual)}"
    elif operator == "every_matches":
        pattern = re.compile(argument)
        items = actual if isinstance(actual, list) else [actual]
        if not items or any(pattern.search(_scalar(item)) is None for item in items):
            return f"expected every entry to match {argument!r}, got {_render(actual)}"
    elif operator == "same_as":
        other = _resolve(subject, argument)
        if actual != other:
            return f"expected to equal {argument} ({_render(other)}), got {_render(actual)}"
    elif operator == "set_same_as":
        other = _resolve(subject, argument)
        if _sorted_scalars(actual) != _sorted_scalars(other):
            return f"expected the same set as {argument} ({_render(other)}), got {_render(actual)}"
    elif operator == "differs_from":
        other = _resolve(subject, argument)
        if actual == other:
            return f"expected to differ from {argument}, and both are {_render(actual)}"
    elif operator == "includes_query":
        other = _resolve(subject, argument)
        wanted = other if isinstance(other, list) else [other]
        if not isinstance(actual, list) or any(item not in actual for item in wanted):
            return f"expected to include {argument} ({_render(other)}), got {_render(actual)}"
    else:
        raise ValueError(f"unknown corpus expectation operator {operator!r}")
    return None
"#;

const PYTHON_TAIL: &str = r#"
def run_vector(vector_id: str) -> list[str]:
    """Every failure one corpus vector states against this frontend."""
    return _VECTORS[vector_id]()


def run_conformance() -> list[str]:
    """Every failure the whole corpus states against this frontend."""
    return [failure for vector_id in VECTOR_IDS for failure in run_vector(vector_id)]
"#;

const TYPESCRIPT_RUNTIME: &str = r#"const LANGUAGE = "typescript";

type Json = any;

export type Expectation = { query: string } & Record<string, unknown>;

type Subject = {
  frontendGraph(): Json;
  diagnostics(): string | null;
  canonicalAir(): string;
  artifact(): Json;
};

/** Render one conformance failure as its own closed reason. */
function failure(vector: string, diff: string): string {
  return `FrontendConformanceFailure{language=${LANGUAGE}, vector=${JSON.stringify(vector)}, diff=${JSON.stringify(diff)}}`;
}

const ABSENT = Symbol("absent");

function scalar(value: unknown): string {
  return typeof value === "string" ? value : JSON.stringify(value) ?? String(value);
}

/** Order object keys so deep equality does not depend on emission order. */
function canonical(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(canonical);
  }
  if (typeof value === "object" && value !== null) {
    const ordered: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      ordered[key] = canonical((value as Record<string, unknown>)[key]);
    }
    return ordered;
  }
  return value;
}

function dotted(item: unknown, key: string): unknown {
  let cursor: unknown = item;
  for (const part of key.split(".")) {
    if (typeof cursor !== "object" || cursor === null || !(part in cursor)) {
      return ABSENT;
    }
    cursor = (cursor as Record<string, unknown>)[part];
  }
  return cursor;
}

/** `[]` flattens one level, `[n]` indexes, and `[key=value]` filters. */
function bracket(cursor: unknown, expression: string): unknown {
  if (!Array.isArray(cursor)) {
    return ABSENT;
  }
  if (expression === "") {
    return cursor.length > 0 && cursor.every((item) => Array.isArray(item))
      ? cursor.flat()
      : cursor;
  }
  const equals = expression.indexOf("=");
  if (equals !== -1) {
    const key = expression.slice(0, equals);
    const wanted = expression.slice(equals + 1);
    return cursor.filter((item) => scalar(dotted(item, key)) === wanted);
  }
  const index = Number(expression);
  return index < cursor.length ? cursor[index] : ABSENT;
}

/** Apply one `name[bracket]...` query segment to the cursor. */
function step(cursor: unknown, segment: string): unknown {
  const open = segment.indexOf("[");
  const name = open === -1 ? segment : segment.slice(0, open);
  let current = cursor;
  if (name !== "") {
    if (Array.isArray(current)) {
      current = current
        .filter((item) => typeof item === "object" && item !== null && name in item)
        .map((item) => (item as Record<string, unknown>)[name]);
    } else if (typeof current === "object" && current !== null && name in current) {
      current = (current as Record<string, unknown>)[name];
    } else {
      return ABSENT;
    }
  }
  let rest = open === -1 ? "" : segment.slice(open + 1);
  while (rest !== "") {
    const close = rest.indexOf("]");
    current = bracket(current, rest.slice(0, close));
    rest = rest.slice(close + 1).replace(/^\[/, "");
  }
  return current;
}

/** Split a query path on the dots that are not inside a bracket. */
function segments(path: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let current = "";
  for (const character of path) {
    if (character === "[") depth += 1;
    if (character === "]") depth -= 1;
    if (character === "." && depth === 0) {
      parts.push(current);
      current = "";
      continue;
    }
    current += character;
  }
  if (current !== "") parts.push(current);
  return parts;
}

/** Resolve one corpus query against a captured program. */
function resolve(subject: Subject, query: string): unknown {
  const colon = query.indexOf(":");
  const source = colon === -1 ? query : query.slice(0, colon);
  const path = colon === -1 ? "" : query.slice(colon + 1);
  if (source === "diagnostics") {
    return subject.diagnostics();
  }
  let cursor: unknown;
  if (source === "graph") cursor = subject.frontendGraph();
  else if (source === "air") cursor = JSON.parse(subject.canonicalAir());
  else if (source === "artifact") cursor = subject.artifact();
  else throw new Error(`unknown corpus query source '${source}'`);
  for (const segment of segments(path)) {
    cursor = step(cursor, segment);
  }
  return cursor;
}

function render(value: unknown): string {
  return value === ABSENT ? "<absent>" : JSON.stringify(canonical(value)) ?? String(value);
}

function same(left: unknown, right: unknown): boolean {
  return JSON.stringify(canonical(left ?? null)) === JSON.stringify(canonical(right ?? null));
}

function sortedScalars(value: unknown): string {
  return JSON.stringify((Array.isArray(value) ? value.map(scalar) : [scalar(value)]).sort());
}

function includesAll(actual: unknown, wanted: unknown[]): boolean {
  return Array.isArray(actual) && wanted.every((item) => actual.some((entry) => same(entry, item)));
}

/** One corpus operator, or a rendered difference when it does not hold. */
function apply(
  subject: Subject,
  operator: string,
  actual: unknown,
  argument: unknown,
): string | null {
  switch (operator) {
    case "equals":
      return same(actual, argument)
        ? null
        : `expected ${render(argument)}, got ${render(actual)}`;
    case "set_equals":
      return sortedScalars(actual) === sortedScalars(argument)
        ? null
        : `expected the set ${render(argument)}, got ${render(actual)}`;
    case "includes":
    case "set_includes":
      return includesAll(actual, argument as unknown[])
        ? null
        : `expected to include ${render(argument)}, got ${render(actual)}`;
    case "length":
      return Array.isArray(actual) && actual.length === argument
        ? null
        : `expected ${String(argument)} entries, got ${render(actual)}`;
    case "every_equals":
      return Array.isArray(actual) && actual.every((item) => same(item, argument))
        ? null
        : `expected every entry to be ${render(argument)}, got ${render(actual)}`;
    case "every_matches": {
      const pattern = new RegExp(argument as string);
      const items = Array.isArray(actual) ? actual : [actual];
      return items.length > 0 && items.every((item) => pattern.test(scalar(item)))
        ? null
        : `expected every entry to match ${render(argument)}, got ${render(actual)}`;
    }
    case "same_as": {
      const other = resolve(subject, argument as string);
      return same(actual, other)
        ? null
        : `expected to equal ${String(argument)} (${render(other)}), got ${render(actual)}`;
    }
    case "set_same_as": {
      const other = resolve(subject, argument as string);
      return sortedScalars(actual) === sortedScalars(other)
        ? null
        : `expected the same set as ${String(argument)} (${render(other)}), got ${render(actual)}`;
    }
    case "differs_from": {
      const other = resolve(subject, argument as string);
      return same(actual, other)
        ? `expected to differ from ${String(argument)}, and both are ${render(actual)}`
        : null;
    }
    case "includes_query": {
      const other = resolve(subject, argument as string);
      const wanted = Array.isArray(other) ? other : [other];
      return includesAll(actual, wanted)
        ? null
        : `expected to include ${String(argument)} (${render(other)}), got ${render(actual)}`;
    }
    default:
      throw new Error(`unknown corpus expectation operator '${operator}'`);
  }
}

/** Evaluate every expectation the corpus states about one captured program. */
function check(vector: string, subject: Subject, expectations: Expectation[]): string[] {
  const failures: string[] = [];
  for (const expectation of expectations) {
    const actual = resolve(subject, expectation.query);
    for (const [operator, argument] of Object.entries(expectation)) {
      if (operator === "query") continue;
      const detail = apply(subject, operator, actual, argument);
      if (detail !== null) {
        failures.push(failure(vector, `${expectation.query} ${detail}`));
      }
    }
  }
  return failures;
}
"#;

const TYPESCRIPT_TAIL: &str = r#"/** Every failure one corpus vector states against this frontend. */
export function runVector(vectorId: string): string[] {
  const vector = VECTORS[vectorId];
  if (vector === undefined) {
    throw new Error(`unknown conformance vector '${vectorId}'`);
  }
  return vector();
}

/** Every failure the whole corpus states against this frontend. */
export function runConformance(): string[] {
  return VECTOR_IDS.flatMap((vectorId) => runVector(vectorId));
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    const SCHEMA_JSON: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../contracts/schemas/apxm.frontend-conformance.json"
    ));

    fn generated() -> [String; 4] {
        [
            render_conformance_python(),
            render_conformance_typescript(),
            render_conformance_python_test(),
            render_conformance_typescript_test(),
        ]
    }

    /// Every vector the corpus states reaches every registered language. This is
    /// the property that makes the corpus a conformance suite rather than two
    /// hand-written suites: a vector cannot be added to one language only.
    #[test]
    fn every_vector_reaches_every_language() {
        let corpus = corpus();
        for rendered in generated() {
            for vector in vectors(&corpus) {
                let id = string(vector, "id");
                assert!(rendered.contains(&id), "{id} missing from a projection");
            }
        }
    }

    /// Both harnesses raise the same named failure, in the register the sibling
    /// frontend-surface gate uses.
    #[test]
    fn both_languages_report_the_same_named_failure() {
        assert!(render_conformance_python().contains("FrontendConformanceFailure{{language="));
        assert!(
            render_conformance_typescript()
                .contains("FrontendConformanceFailure{language=${LANGUAGE}")
        );
    }

    /// Every operator the corpus uses is one the projected evaluators implement.
    #[test]
    fn every_corpus_operator_is_implemented() {
        let corpus = corpus();
        let python = render_conformance_python();
        let typescript = render_conformance_typescript();
        for vector in vectors(&corpus) {
            for expectation in array(vector, "expect") {
                for operator in expectation
                    .as_object()
                    .expect("an expectation states an object")
                    .keys()
                {
                    if operator == "query" {
                        continue;
                    }
                    assert!(
                        python.contains("_apply(subject, operator")
                            && python.contains(&format!("{operator:?}")),
                        "python evaluator does not implement {operator}"
                    );
                    assert!(
                        typescript.contains(&format!("case {operator:?}:")),
                        "typescript evaluator does not implement {operator}"
                    );
                }
            }
        }
    }

    /// The corpus is inlined at generation time; no projection opens a file or
    /// resolves a repository path at test time, because neither authoring
    /// package ships `contracts/` and a path that worked from the repository
    /// would break from an installed package.
    #[test]
    fn no_projection_reads_the_corpus_at_test_time() {
        for rendered in generated() {
            for reader in [
                "open(",
                "readFileSync",
                "read_text",
                "Path(",
                "__file__",
                "import.meta.url",
                "process.cwd",
            ] {
                assert!(
                    !rendered.contains(reader),
                    "a projection resolves {reader} at test time"
                );
            }
        }
    }

    /// Every vocabulary the corpus writes in is one its own schema states. The
    /// schema is where a statement, expression, or operator is added; a corpus
    /// that reached past it would be projecting something no contract names.
    #[test]
    fn the_corpus_stays_inside_its_own_schema() {
        let corpus = corpus();
        let schema: Value = serde_json::from_str(SCHEMA_JSON).expect("the corpus schema parses");
        let closed = |name: &str| -> BTreeSet<String> {
            schema["$defs"][name]["enum"]
                .as_array()
                .unwrap_or_else(|| panic!("$defs.{name}.enum states an array"))
                .iter()
                .map(|entry| {
                    entry
                        .as_str()
                        .expect("an enum member is a string")
                        .to_string()
                })
                .collect()
        };
        let statements = closed("StatementKind");
        let expressions = closed("ExpressionKind");
        let operators: BTreeSet<String> = schema["$defs"]["Expectation"]["properties"]
            .as_object()
            .expect("Expectation.properties states an object")
            .keys()
            .cloned()
            .collect();

        fn note_expression(node: &Value, seen: &mut BTreeSet<String>) {
            if let Some(kind) = node.get("expr").and_then(Value::as_str) {
                seen.insert(kind.to_string());
            }
            for argument in array(node, "arguments") {
                note_expression(argument, seen);
            }
        }

        for vector in vectors(&corpus) {
            for program in array(vector, "programs") {
                let mut bodies: Vec<&Value> = vec![program];
                for hook in array(program, "hooks") {
                    bodies.push(hook);
                }
                for owner in bodies {
                    walk(array(owner, "body"), &mut |statement| {
                        let kind = string(statement, "stmt");
                        assert!(
                            statements.contains(&kind),
                            "{kind} is not a schema statement"
                        );
                        for key in ["value", "left", "right"] {
                            if let Some(node) = statement.get(key) {
                                let mut seen = BTreeSet::new();
                                note_expression(node, &mut seen);
                                for expression in seen {
                                    assert!(
                                        expressions.contains(&expression),
                                        "{expression} is not a schema expression"
                                    );
                                }
                            }
                        }
                    });
                }
            }
            for expectation in array(vector, "expect") {
                for operator in expectation
                    .as_object()
                    .expect("an expectation states an object")
                    .keys()
                {
                    assert!(
                        operators.contains(operator),
                        "{operator} is not a schema expectation operator"
                    );
                }
            }
        }
    }

    /// Each language's fixtures reach that language's own capture entry.
    #[test]
    fn each_language_uses_its_own_capture_entry() {
        let python = render_conformance_python();
        assert!(python.contains("@Agent(input=Input, output=Output)"));
        assert!(python.contains("async def Summarizer(agent, input):"));

        let typescript = render_conformance_typescript();
        assert!(typescript.contains("submitAuthoredSource({ fileName: \"minimal_model_agent.ts\""));
        assert!(typescript.contains("const source_minimal_model_agent = "));
    }
}
