//! FrontendGraph serializer codegen: one `serialize_<record>` per contract
//! record, projected into both authoring frontends from the published schema.
//!
//! This is §5 of `docs/ideas/frontend-vocabulary-generation.md`. Most of an
//! emitter is one rule applied once per record: build a mapping holding every
//! required key, then add each optional key if and only if its source value is
//! stated. That rule is fully determined by the schema's `required` and
//! `properties`, so it is generated here beside the §4 record types rather than
//! hand-written a fourteenth time.
//!
//! Keys are emitted in contract order — required first in `required` order,
//! then the rest — which is the same order `codegen_frontend_records` lays out
//! the record's fields. Pinning the order to the contract is the point: a
//! hand-written emitter's key order is whichever order that language's author
//! happened to type, and the two frontends had drifted into two different ones.
//!
//! Two parts of the emitters are frontend policy rather than contract
//! projection and stay hand-written in `_emit.py` and `emit.ts`: the block
//! derivation that places a yielded resume value in its enclosing region's
//! block, and the `region_annotations` derivation that marks a `loop` control
//! intent's first body region. Neither is stated by this schema.
//!
//! A discriminated union (`ValueExpression`, `ControlPredicate`,
//! `PredicateLiteral`) gets a dispatcher that reads the discriminant the
//! contract states for it and delegates to the branch serializer. The
//! discriminant property and its per-branch constants resolve through the same
//! `FAMILIES` table the vocabulary generator projects, so a union the contract
//! re-discriminates moves here without a second schema-path resolver.

use serde_json::Value;

use super::codegen_frontend_records::{
    Branch, FieldKind, RECORDS, RecordField, UNIONS, UnionDef, fields_for,
};
use super::codegen_frontend_vocabulary::{family_for_union, quote, schema, screaming_snake};

pub const PYTHON_FRONTEND_SERIALIZERS_FILE: &str = "frontend_serializers.py";
pub const TYPESCRIPT_FRONTEND_SERIALIZERS_FILE: &str = "frontend-serializers.ts";

const PYTHON_HEADER: &str = "# AUTO-GENERATED by apxm codegen frontend-serializers; DO NOT EDIT.";
const TYPESCRIPT_HEADER: &str =
    "// AUTO-GENERATED by apxm codegen frontend-serializers; DO NOT EDIT.";

/// The parameter and local the emitted bodies bind. A record field carrying
/// either name would shadow them, so the generator refuses to emit one.
const RESERVED_FIELD_NAMES: &[&str] = &["record", "emitted", "discriminant"];

/// `SsaExpression` -> `ssa_expression`. Every record and branch name the
/// contract states is plain PascalCase, so one underscore before each capital
/// is the whole rule.
fn snake(name: &str) -> String {
    let mut buf = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                buf.push('_');
            }
            buf.push(ch.to_ascii_lowercase());
        } else {
            buf.push(ch);
        }
    }
    buf
}

fn py_serializer(name: &str) -> String {
    format!("serialize_{}", snake(name))
}

fn ts_serializer(name: &str) -> String {
    format!("serialize{name}")
}

/// Every record this generator emits a serializer for: each `$defs` record, then
/// each union branch the contract states inline.
fn serialized_records() -> Vec<&'static str> {
    let mut records: Vec<&'static str> = RECORDS.to_vec();
    for union in UNIONS {
        for branch in union.branches {
            if let Branch::Inline { name, .. } = branch {
                records.push(name);
            }
        }
    }
    records
}

/// The field list of one emitted record, with `own_def` set to the `$defs` key
/// whose discriminant the record resolves against.
fn fields_of(schema: &Value, name: &str) -> Vec<RecordField> {
    for union in UNIONS {
        for branch in union.branches {
            if let Branch::Inline {
                name: branch_name,
                index,
            } = branch
            {
                if *branch_name == name {
                    return fields_for(&schema["$defs"][union.name]["oneOf"][*index], union.name);
                }
            }
        }
    }
    fields_for(&schema["$defs"][name], name)
}

/// One union branch's discriminant constant identifier, resolved through the
/// vocabulary family the contract states the union's discriminant with.
fn branch_constant(
    schema: &Value,
    union: &UnionDef,
    branch: &Branch,
    discriminant: &str,
) -> String {
    let (family, _) = family_for_union(union.name)
        .unwrap_or_else(|| panic!("frontend-serializers: {} states no family", union.name));
    let branch_schema = match branch {
        Branch::Named(name) => &schema["$defs"][name],
        Branch::Inline { index, .. } => &schema["$defs"][union.name]["oneOf"][*index],
    };
    let value = branch_schema["properties"][discriminant]["const"]
        .as_str()
        .unwrap_or_else(|| {
            panic!(
                "frontend-serializers: a {} branch pins no {discriminant} const",
                union.name
            )
        });
    format!("{}{}", family.prefix, screaming_snake(value))
}

fn branch_name(branch: &Branch) -> &'static str {
    match branch {
        Branch::Named(name) => name,
        Branch::Inline { name, .. } => name,
    }
}

fn py_value(kind: &FieldKind, access: &str) -> String {
    match kind {
        FieldKind::Str | FieldKind::Int | FieldKind::Bool | FieldKind::Vocabulary(_) => {
            access.to_string()
        }
        FieldKind::StrTuple => format!("list({access})"),
        FieldKind::Permission => format!("serialize_permission({access})"),
        FieldKind::Local(name) => format!("{}({access})", py_serializer(name)),
        FieldKind::LocalTuple(name) => {
            format!("[{}(item) for item in {access}]", py_serializer(name))
        }
    }
}

fn ts_value(kind: &FieldKind, access: &str) -> String {
    match kind {
        FieldKind::Str | FieldKind::Int | FieldKind::Bool | FieldKind::Vocabulary(_) => {
            access.to_string()
        }
        FieldKind::StrTuple => format!("[...{access}]"),
        FieldKind::Permission => format!("serializePermission({access})"),
        FieldKind::Local(name) => format!("{}({access})", ts_serializer(name)),
        FieldKind::LocalTuple(name) => {
            format!("{access}.map((item) => {}(item))", ts_serializer(name))
        }
    }
}

fn assert_nameable(record: &str, fields: &[RecordField]) {
    for field in fields {
        assert!(
            !RESERVED_FIELD_NAMES.contains(&field.name.as_str()),
            "frontend-serializers: {record}.{} shadows an emitted local",
            field.name
        );
    }
}

fn render_py_serializer(name: &str, fields: &[RecordField]) -> String {
    assert_nameable(name, fields);
    let mut buf = format!(
        "\n\ndef {}(record: {name}) -> dict[str, Any]:\n    \
         \"\"\"One `{name}` in contract key order: every required key, then each stated optional key.\"\"\"\n",
        py_serializer(name)
    );
    let required: Vec<&RecordField> = fields.iter().filter(|field| field.required).collect();
    if required.is_empty() {
        buf.push_str("    emitted: dict[str, Any] = {}\n");
    } else {
        buf.push_str("    emitted: dict[str, Any] = {\n");
        for field in required {
            buf.push_str(&format!(
                "        \"{}\": {},\n",
                field.name,
                py_value(&field.kind, &format!("_field(record, \"{}\")", field.name))
            ));
        }
        buf.push_str("    }\n");
    }
    for field in fields.iter().filter(|field| !field.required) {
        buf.push_str(&format!(
            "    {name_} = _field(record, \"{name_}\")\n    if {name_} is not None:\n        emitted[\"{name_}\"] = {}\n",
            py_value(&field.kind, &field.name),
            name_ = field.name
        ));
    }
    buf.push_str("    return emitted\n");
    buf
}

fn render_ts_serializer(name: &str, fields: &[RecordField]) -> String {
    assert_nameable(name, fields);
    let mut buf = format!(
        "\n/** One `{name}` in contract key order: every required key, then each stated optional key. */\nexport function {}(record: {name}): Json {{\n",
        ts_serializer(name)
    );
    let required: Vec<&RecordField> = fields.iter().filter(|field| field.required).collect();
    if required.is_empty() {
        buf.push_str("  const emitted: Json = {};\n");
    } else {
        buf.push_str("  const emitted: Json = {\n");
        for field in required {
            buf.push_str(&format!(
                "    {}: {},\n",
                field.name,
                ts_value(&field.kind, &format!("record.{}", field.name))
            ));
        }
        buf.push_str("  };\n");
    }
    for field in fields.iter().filter(|field| !field.required) {
        buf.push_str(&format!(
            "  if (record.{name_} !== undefined) {{\n    emitted.{name_} = {};\n  }}\n",
            ts_value(&field.kind, &format!("record.{}", field.name)),
            name_ = field.name
        ));
    }
    buf.push_str("  return emitted;\n}\n");
    buf
}

fn render_py_union(schema: &Value, union: &UnionDef) -> String {
    let (_, discriminant) = family_for_union(union.name)
        .unwrap_or_else(|| panic!("frontend-serializers: {} states no family", union.name));
    let mut buf = format!(
        "\n\ndef {}(record: {}) -> dict[str, Any]:\n    \
         \"\"\"One `{}` branch, chosen by the `{discriminant}` the contract discriminates on.\"\"\"\n    \
         discriminant = _field(record, \"{discriminant}\")\n",
        py_serializer(union.name),
        union.name,
        union.name
    );
    for branch in union.branches {
        buf.push_str(&format!(
            "    if discriminant == {}:\n        return {}(record)\n",
            branch_constant(schema, union, branch, discriminant),
            py_serializer(branch_name(branch))
        ));
    }
    buf.push_str(&format!(
        "    raise ValueError(f\"{} states no branch for {discriminant} {{discriminant!r}}\")\n",
        union.name
    ));
    buf
}

fn render_ts_union(schema: &Value, union: &UnionDef) -> String {
    let (_, discriminant) = family_for_union(union.name)
        .unwrap_or_else(|| panic!("frontend-serializers: {} states no family", union.name));
    let mut buf = format!(
        "\n/** One `{}` branch, chosen by the `{discriminant}` the contract discriminates on. */\nexport function {}(record: {}): Json {{\n  const discriminant = record.{discriminant};\n",
        union.name,
        ts_serializer(union.name),
        union.name
    );
    for branch in union.branches {
        let name = branch_name(branch);
        buf.push_str(&format!(
            "  if (discriminant === {}) {{\n    return {}(record as {name});\n  }}\n",
            branch_constant(schema, union, branch, discriminant),
            ts_serializer(name)
        ));
    }
    buf.push_str(&format!(
        "  throw new Error(`{} states no branch for {discriminant} '${{discriminant}}'`);\n}}\n",
        union.name
    ));
    buf
}

/// Every discriminant constant the union dispatchers bind, in emission order.
fn discriminant_constants(schema: &Value) -> Vec<String> {
    let mut constants = Vec::new();
    for union in UNIONS {
        let (_, discriminant) = family_for_union(union.name)
            .unwrap_or_else(|| panic!("frontend-serializers: {} states no family", union.name));
        for branch in union.branches {
            let constant = branch_constant(schema, union, branch, discriminant);
            if !constants.contains(&constant) {
                constants.push(constant);
            }
        }
    }
    constants.sort();
    constants
}

/// Every record and union type the emitted signatures name, in emission order.
fn referenced_types() -> Vec<String> {
    let mut names: Vec<String> = RECORDS.iter().map(|record| (*record).to_string()).collect();
    for union in UNIONS {
        for branch in union.branches {
            if let Branch::Inline { name, .. } = branch {
                names.push((*name).to_string());
            }
        }
        names.push(union.name.to_string());
    }
    names.sort();
    names
}

pub fn render_frontend_serializers_python() -> String {
    let schema = schema();
    let mut buf = String::new();
    buf.push_str(PYTHON_HEADER);
    buf.push_str(
        "\n\"\"\"One serializer per apxm.frontend-graph contract record.\n\n\
         Each function holds every required key the contract states, then each optional\n\
         key whose value is stated, in the contract's own key order. A key the contract\n\
         adds, drops, or makes optional moves here on the next regeneration rather than\n\
         needing an edit in two languages.\n\n\
         A serializer reads either a generated record from `frontend_records` or the\n\
         equivalent bound-tree record, which carries the same field names — the bound\n\
         tree still spells a value expression and a predicate literal as the plain\n\
         mapping the contract states, so `_field` reads a mapping key as readily as an\n\
         attribute.\n\n\
         The emitters' two policy derivations — placing a yielded resume value in its\n\
         enclosing region's block, and annotating a loop's first body region — are not\n\
         contract projections and stay hand-written in `_emit`.\n\"\"\"\n\n\
         from __future__ import annotations\n\n\
         from collections.abc import Mapping\n\
         from typing import Any, Union\n",
    );

    let constants = discriminant_constants(&schema);
    if !constants.is_empty() {
        buf.push_str(&format!(
            "\nfrom .frontend_graph import (\n{}\n)\n",
            constants
                .iter()
                .map(|name| format!("    {name},"))
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }
    buf.push_str(&format!(
        "\nfrom .frontend_records import (\n{}\n)\n",
        referenced_types()
            .iter()
            .map(|name| format!("    {name},"))
            .collect::<Vec<_>>()
            .join("\n")
    ));
    buf.push_str("\nfrom .permissions import Permission, PermissionDecision\n");

    buf.push_str(
        "\n\ndef _field(record: Any, name: str) -> Any:\n    \
         \"\"\"Read one contract field from a generated record or its wire mapping.\"\"\"\n    \
         if isinstance(record, Mapping):\n        return record.get(name)\n    \
         return getattr(record, name, None)\n",
    );
    buf.push_str(
        "\n\ndef serialize_permission(record: Permission) -> Union[PermissionDecision, dict[str, Any]]:\n    \
         \"\"\"One `PermissionDecision`: the bare decision, or the object form when it gives a reason.\"\"\"\n    \
         decision = _field(record, \"decision\")\n    \
         reason = _field(record, \"reason\")\n    \
         return decision if reason is None else {\"decision\": decision, \"reason\": reason}\n",
    );

    for name in serialized_records() {
        buf.push_str(&render_py_serializer(name, &fields_of(&schema, name)));
    }
    for union in UNIONS {
        buf.push_str(&render_py_union(&schema, union));
    }

    buf.push_str("\n\n__all__ = [\n    \"serialize_permission\",");
    for name in serialized_records() {
        buf.push_str(&format!("\n    {},", quote(&py_serializer(name))));
    }
    for union in UNIONS {
        buf.push_str(&format!("\n    {},", quote(&py_serializer(union.name))));
    }
    buf.push_str("\n]\n");
    buf
}

pub fn render_frontend_serializers_typescript() -> String {
    let schema = schema();
    let mut buf = String::new();
    buf.push_str(TYPESCRIPT_HEADER);
    buf.push_str(
        "\n// One serializer per apxm.frontend-graph contract record.\n\
         //\n\
         // Each function holds every required key the contract states, then each optional\n\
         // key whose value is stated, in the contract's own key order. A key the contract\n\
         // adds, drops, or makes optional moves here on the next regeneration rather than\n\
         // needing an edit in two languages.\n\
         //\n\
         // A serializer reads either a generated record from `frontend-records` or the\n\
         // equivalent bound-tree record, which carries the same field names.\n\
         //\n\
         // The emitters' two policy derivations — placing a yielded resume value in its\n\
         // enclosing region's block, and annotating a loop's first body region — are not\n\
         // contract projections and stay hand-written in `emit.ts`.\n",
    );

    let constants = discriminant_constants(&schema);
    if !constants.is_empty() {
        buf.push_str(&format!(
            "\nimport {{\n{}\n}} from \"./frontend-graph.js\";\n",
            constants
                .iter()
                .map(|name| format!("  {name},"))
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }
    buf.push_str(&format!(
        "\nimport type {{\n{}\n}} from \"./frontend-records.js\";\n",
        referenced_types()
            .iter()
            .map(|name| format!("  {name},"))
            .collect::<Vec<_>>()
            .join("\n")
    ));
    buf.push_str("\nimport type { Permission, PermissionDecision } from \"./permissions.js\";\n");
    buf.push_str("\nimport type { Json } from \"../contract.js\";\n");

    buf.push_str(
        "\n/** One `PermissionDecision`: the bare decision, or the object form when it gives a reason. */\n\
         export function serializePermission(\n  record: Permission,\n): PermissionDecision | Json {\n  \
         return record.reason === undefined\n    ? record.decision\n    : { decision: record.decision, reason: record.reason };\n}\n",
    );

    for name in serialized_records() {
        buf.push_str(&render_ts_serializer(name, &fields_of(&schema, name)));
    }
    for union in UNIONS {
        buf.push_str(&render_ts_union(&schema, union));
    }
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    const FRONTEND_SURFACE_MANIFEST: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../contracts/vectors/apxm.frontend-surface.json"
    ));

    fn generated() -> [String; 2] {
        [
            render_frontend_serializers_python(),
            render_frontend_serializers_typescript(),
        ]
    }

    /// Every record type §4 emits gets a serializer, in both languages: a
    /// record with no serializer is a fold that has to hand-build that shape.
    #[test]
    fn every_record_and_union_has_a_serializer() {
        let python = render_frontend_serializers_python();
        let typescript = render_frontend_serializers_typescript();
        for record in RECORDS.iter().copied() {
            assert!(python.contains(&py_serializer(record)), "{record}");
            assert!(typescript.contains(&ts_serializer(record)), "{record}");
        }
        for union in UNIONS {
            assert!(
                python.contains(&py_serializer(union.name)),
                "{}",
                union.name
            );
            assert!(
                typescript.contains(&ts_serializer(union.name)),
                "{}",
                union.name
            );
            for branch in union.branches {
                let name = branch_name(branch);
                assert!(python.contains(&py_serializer(name)), "{name}");
                assert!(typescript.contains(&ts_serializer(name)), "{name}");
            }
        }
    }

    /// Required keys are unconditional and optional keys are guarded — §5's
    /// whole rule. `Declaration` states both kinds, so it pins both halves.
    #[test]
    fn required_keys_are_unconditional_and_optional_keys_are_guarded() {
        let python = render_frontend_serializers_python();
        assert!(python.contains("\"decl_id\": _field(record, \"decl_id\"),"));
        assert!(python.contains("    target_ref = _field(record, \"target_ref\")\n    if target_ref is not None:\n        emitted[\"target_ref\"] = target_ref\n"));

        let typescript = render_frontend_serializers_typescript();
        assert!(typescript.contains("    decl_id: record.decl_id,"));
        assert!(typescript.contains(
            "  if (record.target_ref !== undefined) {\n    emitted.target_ref = record.target_ref;\n  }\n"
        ));
    }

    /// Keys land in the contract's order, not either language's. `Region`
    /// states `parent_region_id` between two required keys, so a serializer
    /// that kept schema-document order rather than required-then-optional
    /// order would emit it second.
    #[test]
    fn keys_follow_the_contract_order_required_first() {
        let python = render_frontend_serializers_python();
        let region = python
            .split_once("def serialize_region(")
            .expect("serialize_region")
            .1;
        let execution_order = region.find("execution_order").expect("execution_order");
        let parent_region_id = region.find("parent_region_id").expect("parent_region_id");
        assert!(execution_order < parent_region_id);
    }

    /// A union dispatches on the discriminant the contract states for it,
    /// through the vocabulary generator's constants rather than a restated
    /// string literal.
    #[test]
    fn unions_dispatch_through_the_generated_discriminant_constants() {
        let python = render_frontend_serializers_python();
        assert!(python.contains("discriminant = _field(record, \"comparator\")"));
        assert!(python.contains("if discriminant == PREDICATE_COMPARATOR_TRUTHY:"));
        assert!(python.contains("if discriminant == VALUE_EXPRESSION_KIND_SSA:"));
        assert!(python.contains("if discriminant == PREDICATE_SCALAR_TYPE_NULL:"));

        let typescript = render_frontend_serializers_typescript();
        assert!(typescript.contains("const discriminant = record.comparator;"));
        assert!(typescript.contains("if (discriminant === PREDICATE_COMPARATOR_TRUTHY) {"));
    }

    /// `PermissionDecision` keeps the one projection the contract's two-branch
    /// `oneOf` states — a bare decision, or the object form when it explains
    /// itself — rather than a second spelling per frontend.
    #[test]
    fn the_permission_decision_projection_is_emitted_once_per_language() {
        for rendered in generated() {
            assert!(
                rendered.contains("serialize_permission")
                    || rendered.contains("serializePermission")
            );
        }
        assert!(render_frontend_serializers_python().contains(
            "return decision if reason is None else {\"decision\": decision, \"reason\": reason}"
        ));
        assert!(
            render_frontend_serializers_typescript()
                .contains("    : { decision: record.decision, reason: record.reason };")
        );
    }

    /// These modules land inside the installable authoring packages, so they
    /// must not carry a name the frontend-surface manifest marks non-public.
    #[test]
    fn no_non_public_name_reaches_the_authoring_packages() {
        let manifest: Value =
            serde_json::from_str(FRONTEND_SURFACE_MANIFEST).expect("frontend-surface manifest");
        let forbidden: Vec<String> = manifest["non_public"]
            .as_array()
            .expect("non_public states an array")
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .expect("non_public member is a string")
                    .to_string()
            })
            .collect();
        assert!(forbidden.contains(&"FIVE_OPS".to_string()));

        for rendered in generated() {
            let tokens: Vec<&str> = rendered
                .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '_' || ch == '.'))
                .collect();
            let offenders: Vec<&String> = forbidden
                .iter()
                .filter(|name| tokens.contains(&name.as_str()))
                .collect();
            assert!(
                offenders.is_empty(),
                "non-public names leaked: {offenders:?}"
            );
        }
    }
}
