[package]
name = "apxm-server-api"
version.workspace = true
edition.workspace = true

[dependencies]
apxm-core = { path = "../../machine/apxm-core" }
apxm-ais = { path = "../../machine/apxm-ais" }
apxm-runtime = { path = "../../runtime/apxm-runtime" }
apxm-compiler = { path = "../../compiler/apxm-compiler" }
apxm-backends = { path = "../../runtime/apxm-backends" }
async-trait = "0.1"
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
