[package]
name = "apxm-frontend-typescript"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[lib]
name = "apxm_frontend_typescript"
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
apxm-program.workspace = true
serde_json.workspace = true
napi = { version = "2", default-features = false, features = ["napi8"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
