#!/usr/bin/env node
// Codegen for @apxm/frontend.
//
// Reads the AIS op catalog (op-spec.v1.json, TSF-1) and the workflow-draft.v1
// JSON Schema (WF-2 contracts) and emits TypeScript source under
// src/generated/. Mirrors the pattern used by the Python frontend's
// apxm/_generated/ package (generated from the same op-spec source).
//
// Regenerate with: npm run codegen

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, "..");
const REPO_ROOT = path.resolve(PKG_ROOT, "../../../../"); // crates/compiler/frontend/typescript -> repo root
const WORKSPACE_ROOT = path.resolve(REPO_ROOT, ".."); // apxm-project

const OP_SPEC_PATH = path.join(
  REPO_ROOT,
  "crates/machine/ais/generated/op-spec.v1.json",
);
const WORKFLOW_DRAFT_SCHEMA_PATH = path.join(
  WORKSPACE_ROOT,
  "contracts/schemas/workflow-draft.v1.json",
);

const GENERATED_DIR = path.join(PKG_ROOT, "src/generated");

const HEADER = `/**
 * AUTO-GENERATED by scripts/codegen.mjs — DO NOT EDIT BY HAND.
 *
 * Regenerate with: npm run codegen (from crates/compiler/frontend/typescript)
 */
`;

function tsStringLiteral(value) {
  return JSON.stringify(value);
}

function generateOps() {
  const raw = readFileSync(OP_SPEC_PATH, "utf-8");
  const spec = JSON.parse(raw);
  const ops = spec.operations;

  const opNames = ops.map((o) => o.op);
  const opNameUnion = opNames.map((n) => tsStringLiteral(n)).join(" | ");

  const specEntries = ops
    .map((o) => {
      const fields = o.fields
        .map(
          (f) => `    { name: ${tsStringLiteral(f.name)}, required: ${f.required}, description: ${tsStringLiteral(f.description)}, refType: ${f.ref_type === null || f.ref_type === undefined ? "null" : tsStringLiteral(f.ref_type)} }`,
        )
        .join(",\n");
      return `  ${tsStringLiteral(o.op)}: {
    op: ${tsStringLiteral(o.op)},
    rustVariant: ${tsStringLiteral(o.rust_variant)},
    name: ${tsStringLiteral(o.name)},
    category: ${tsStringLiteral(o.category)},
    description: ${tsStringLiteral(o.description)},
    longDescription: ${tsStringLiteral(o.long_description)},
    latency: ${tsStringLiteral(o.latency)},
    wireIndex: ${o.wire_index === null || o.wire_index === undefined ? "null" : o.wire_index},
    isPseudoOp: ${o.is_pseudo_op},
    minInputs: ${o.min_inputs},
    producesOutput: ${o.produces_output},
    needsSubmission: ${o.needs_submission},
    fields: [
${fields}
    ],
    exampleJson: ${o.example_json === null || o.example_json === undefined ? "null" : tsStringLiteral(o.example_json)},
  }`;
    })
    .join(",\n");

  const out = `${HEADER}
/** Schema version of the source op-spec catalog (apxm.op-spec.v1). */
export const OP_SPEC_SCHEMA_VERSION = ${tsStringLiteral(spec.schema_version)};

/** Total operations declared by the source catalog (including pseudo-ops). */
export const OP_SPEC_TOTAL_OPERATIONS = ${spec.total_operations};

/** Union of every AIS opcode name in the catalog. */
export type OpName = ${opNameUnion};

/** A single field/attribute an AIS operation accepts. */
export interface OpField {
  readonly name: string;
  readonly required: boolean;
  readonly description: string;
  readonly refType: string | null;
}

/** Full metadata for one AIS operation, mirrored from op-spec.v1.json. */
export interface OpSpec {
  readonly op: OpName;
  readonly rustVariant: string;
  readonly name: string;
  readonly category: string;
  readonly description: string;
  readonly longDescription: string;
  readonly latency: string;
  readonly wireIndex: number | null;
  readonly isPseudoOp: boolean;
  readonly minInputs: number;
  readonly producesOutput: boolean;
  readonly needsSubmission: boolean;
  readonly fields: readonly OpField[];
  readonly exampleJson: string | null;
}

/** Every operation spec, keyed by opcode name. */
export const OP_SPECS: Readonly<Record<OpName, OpSpec>> = {
${specEntries}
};

/** All operation specs as an array, in catalog order. */
export const ALL_OPERATIONS: readonly OpSpec[] = Object.values(OP_SPECS);

/** Opcodes that never produce a result token (void ops in AIR emission). */
export const VOID_OPS: ReadonlySet<OpName> = new Set(
  ALL_OPERATIONS.filter((spec) => !spec.producesOutput).map((spec) => spec.op),
);

/** Required (non-optional) attribute names per opcode, for graph validation. */
export const REQUIRED_ATTRS: Readonly<Record<OpName, ReadonlySet<string>>> = Object.fromEntries(
  ALL_OPERATIONS.map((spec) => [
    spec.op,
    new Set(spec.fields.filter((f) => f.required).map((f) => f.name)),
  ]),
) as unknown as Readonly<Record<OpName, ReadonlySet<string>>>;
`;

  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(path.join(GENERATED_DIR, "ops.ts"), out, "utf-8");
  console.log(`wrote ${path.join(GENERATED_DIR, "ops.ts")} (${ops.length} ops)`);
}

function generateWorkflowDraftSchema() {
  const raw = readFileSync(WORKFLOW_DRAFT_SCHEMA_PATH, "utf-8");
  const schema = JSON.parse(raw);

  const out = `${HEADER}
/**
 * Vendored copy of workflow-draft.v1.json from workspace/contracts/schemas/.
 * Source of truth: workspace/contracts/schemas/workflow-draft.v1.json (WF-2).
 * Re-vendor with: npm run codegen.
 */
export const WORKFLOW_DRAFT_V1_SCHEMA = ${JSON.stringify(schema, null, 2)} as const;
`;

  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(path.join(GENERATED_DIR, "workflow-draft-schema.ts"), out, "utf-8");
  console.log(`wrote ${path.join(GENERATED_DIR, "workflow-draft-schema.ts")}`);
}

generateOps();
generateWorkflowDraftSchema();
