"""LLM provider registry — re-exports from codegen.

All provider data is now generated by apxm-frontend codegen.
"""
from apxm._generated.providers import (  # noqa: F401
    BUILTIN_PROVIDERS,
    REGISTERED_PROVIDERS,
    ProviderSpec,
    list_providers,
    resolve_provider,
)
