# AUTO-GENERATED by apxm codegen capabilities; DO NOT EDIT.
"""Capability ids and builtin groups an Agent Program may bind by name.

Every id here is admitted by the compiler builtin allowlist, so binding one
needs no capability registration. Import the symbol instead of retyping the
string: a misspelled symbol is an ImportError, a misspelled string is a
capability that silently matches nothing.
"""

from typing import Final, Literal, TypeAlias

CapabilityId: TypeAlias = Literal[
    "bash",
    "read",
    "write",
    "search_web",
    "http_get",
    "http_post",
    "count_tokens",
    "list_skills",
    "search_skills",
    "read_skill",
    "mcp.call",
    "provider.call",
    "schedule",
]
BuiltinGroup: TypeAlias = Literal[
    "skills",
    "discovery",
]

BASH: Final[CapabilityId] = "bash"
READ: Final[CapabilityId] = "read"
WRITE: Final[CapabilityId] = "write"
SEARCH_WEB: Final[CapabilityId] = "search_web"
HTTP_GET: Final[CapabilityId] = "http_get"
HTTP_POST: Final[CapabilityId] = "http_post"
COUNT_TOKENS: Final[CapabilityId] = "count_tokens"
LIST_SKILLS: Final[CapabilityId] = "list_skills"
SEARCH_SKILLS: Final[CapabilityId] = "search_skills"
READ_SKILL: Final[CapabilityId] = "read_skill"
MCP_CALL: Final[CapabilityId] = "mcp.call"
PROVIDER_CALL: Final[CapabilityId] = "provider.call"
SCHEDULE: Final[CapabilityId] = "schedule"

GROUP_SKILLS: Final[BuiltinGroup] = "skills"
GROUP_DISCOVERY: Final[BuiltinGroup] = "discovery"

STANDARD_BUILTIN_CAPABILITIES: Final[tuple[CapabilityId, ...]] = (
    BASH,
    READ,
    WRITE,
    SEARCH_WEB,
    HTTP_GET,
    HTTP_POST,
    COUNT_TOKENS,
    LIST_SKILLS,
    SEARCH_SKILLS,
    READ_SKILL,
)
BUILTIN_CAPABILITIES: Final[tuple[CapabilityId, ...]] = (
    BASH,
    READ,
    WRITE,
    SEARCH_WEB,
    HTTP_GET,
    HTTP_POST,
    COUNT_TOKENS,
    LIST_SKILLS,
    SEARCH_SKILLS,
    READ_SKILL,
    MCP_CALL,
    PROVIDER_CALL,
    SCHEDULE,
)
BUILTIN_GROUPS: Final[tuple[BuiltinGroup, ...]] = (
    GROUP_SKILLS,
    GROUP_DISCOVERY,
)

__all__ = [
    "BuiltinGroup",
    "CapabilityId",
    "BASH",
    "READ",
    "WRITE",
    "SEARCH_WEB",
    "HTTP_GET",
    "HTTP_POST",
    "COUNT_TOKENS",
    "LIST_SKILLS",
    "SEARCH_SKILLS",
    "READ_SKILL",
    "MCP_CALL",
    "PROVIDER_CALL",
    "SCHEDULE",
    "GROUP_SKILLS",
    "GROUP_DISCOVERY",
    "BUILTIN_CAPABILITIES",
    "BUILTIN_GROUPS",
    "STANDARD_BUILTIN_CAPABILITIES",
]
