# AUTO-GENERATED by apxm codegen diagnostics; DO NOT EDIT.
"""The closed set of reasons the frontend rejects authored source.

A rejection carries one of these codes so a caller can branch on the reason
without matching on the message text, and so the reason a marker can give is
the reason the published surface manifest says it can give.

This module is internal to the frontend.
"""

from typing import Final, Literal, TypeAlias

DiagnosticCode: TypeAlias = Literal[
    "AgentBodyNotAsync",
    "AgentMissingInputOutput",
    "AgentDynamicArgument",
    "AgentFacadeImported",
    "ContextNotTyped",
    "ContextMutableGlobal",
    "ContextDynamicDefault",
    "ModelRefNotExact",
    "ModelDisplayNameRejected",
    "ModelUntypedSchema",
    "ToolRefNotCapability",
    "ToolDisplayNameRejected",
    "ToolCredentialInSource",
    "CapabilityRefNotExact",
    "CapabilityDisplayNameRejected",
    "CapabilityHandlerUntypedSchema",
    "CapabilityHandlerOpenObject",
    "CapabilityHandlerReadOnlyUndeclared",
    "HookTargetUnresolved",
    "HookDynamicRegistration",
    "HookOrderAmbiguous",
    "EventNotTyped",
    "EventWaitOutsideBody",
    "TaskGroupMissingJoin",
    "TaskGroupDetachedWork",
    "TaskGroupRawCoroutine",
]
AGENT_BODY_NOT_ASYNC: Final[DiagnosticCode] = "AgentBodyNotAsync"
AGENT_MISSING_INPUT_OUTPUT: Final[DiagnosticCode] = "AgentMissingInputOutput"
AGENT_DYNAMIC_ARGUMENT: Final[DiagnosticCode] = "AgentDynamicArgument"
AGENT_FACADE_IMPORTED: Final[DiagnosticCode] = "AgentFacadeImported"
CONTEXT_NOT_TYPED: Final[DiagnosticCode] = "ContextNotTyped"
CONTEXT_MUTABLE_GLOBAL: Final[DiagnosticCode] = "ContextMutableGlobal"
CONTEXT_DYNAMIC_DEFAULT: Final[DiagnosticCode] = "ContextDynamicDefault"
MODEL_REF_NOT_EXACT: Final[DiagnosticCode] = "ModelRefNotExact"
MODEL_DISPLAY_NAME_REJECTED: Final[DiagnosticCode] = "ModelDisplayNameRejected"
MODEL_UNTYPED_SCHEMA: Final[DiagnosticCode] = "ModelUntypedSchema"
TOOL_REF_NOT_CAPABILITY: Final[DiagnosticCode] = "ToolRefNotCapability"
TOOL_DISPLAY_NAME_REJECTED: Final[DiagnosticCode] = "ToolDisplayNameRejected"
TOOL_CREDENTIAL_IN_SOURCE: Final[DiagnosticCode] = "ToolCredentialInSource"
CAPABILITY_REF_NOT_EXACT: Final[DiagnosticCode] = "CapabilityRefNotExact"
CAPABILITY_DISPLAY_NAME_REJECTED: Final[DiagnosticCode] = "CapabilityDisplayNameRejected"
CAPABILITY_HANDLER_UNTYPED_SCHEMA: Final[DiagnosticCode] = "CapabilityHandlerUntypedSchema"
CAPABILITY_HANDLER_OPEN_OBJECT: Final[DiagnosticCode] = "CapabilityHandlerOpenObject"
CAPABILITY_HANDLER_READ_ONLY_UNDECLARED: Final[DiagnosticCode] = "CapabilityHandlerReadOnlyUndeclared"
HOOK_TARGET_UNRESOLVED: Final[DiagnosticCode] = "HookTargetUnresolved"
HOOK_DYNAMIC_REGISTRATION: Final[DiagnosticCode] = "HookDynamicRegistration"
HOOK_ORDER_AMBIGUOUS: Final[DiagnosticCode] = "HookOrderAmbiguous"
EVENT_NOT_TYPED: Final[DiagnosticCode] = "EventNotTyped"
EVENT_WAIT_OUTSIDE_BODY: Final[DiagnosticCode] = "EventWaitOutsideBody"
TASK_GROUP_MISSING_JOIN: Final[DiagnosticCode] = "TaskGroupMissingJoin"
TASK_GROUP_DETACHED_WORK: Final[DiagnosticCode] = "TaskGroupDetachedWork"
TASK_GROUP_RAW_COROUTINE: Final[DiagnosticCode] = "TaskGroupRawCoroutine"
DIAGNOSTIC_CODES: Final[tuple[DiagnosticCode, ...]] = (
    AGENT_BODY_NOT_ASYNC,
    AGENT_MISSING_INPUT_OUTPUT,
    AGENT_DYNAMIC_ARGUMENT,
    AGENT_FACADE_IMPORTED,
    CONTEXT_NOT_TYPED,
    CONTEXT_MUTABLE_GLOBAL,
    CONTEXT_DYNAMIC_DEFAULT,
    MODEL_REF_NOT_EXACT,
    MODEL_DISPLAY_NAME_REJECTED,
    MODEL_UNTYPED_SCHEMA,
    TOOL_REF_NOT_CAPABILITY,
    TOOL_DISPLAY_NAME_REJECTED,
    TOOL_CREDENTIAL_IN_SOURCE,
    CAPABILITY_REF_NOT_EXACT,
    CAPABILITY_DISPLAY_NAME_REJECTED,
    CAPABILITY_HANDLER_UNTYPED_SCHEMA,
    CAPABILITY_HANDLER_OPEN_OBJECT,
    CAPABILITY_HANDLER_READ_ONLY_UNDECLARED,
    HOOK_TARGET_UNRESOLVED,
    HOOK_DYNAMIC_REGISTRATION,
    HOOK_ORDER_AMBIGUOUS,
    EVENT_NOT_TYPED,
    EVENT_WAIT_OUTSIDE_BODY,
    TASK_GROUP_MISSING_JOIN,
    TASK_GROUP_DETACHED_WORK,
    TASK_GROUP_RAW_COROUTINE,
)

__all__ = [
    "DiagnosticCode",
    "AGENT_BODY_NOT_ASYNC",
    "AGENT_MISSING_INPUT_OUTPUT",
    "AGENT_DYNAMIC_ARGUMENT",
    "AGENT_FACADE_IMPORTED",
    "CONTEXT_NOT_TYPED",
    "CONTEXT_MUTABLE_GLOBAL",
    "CONTEXT_DYNAMIC_DEFAULT",
    "MODEL_REF_NOT_EXACT",
    "MODEL_DISPLAY_NAME_REJECTED",
    "MODEL_UNTYPED_SCHEMA",
    "TOOL_REF_NOT_CAPABILITY",
    "TOOL_DISPLAY_NAME_REJECTED",
    "TOOL_CREDENTIAL_IN_SOURCE",
    "CAPABILITY_REF_NOT_EXACT",
    "CAPABILITY_DISPLAY_NAME_REJECTED",
    "CAPABILITY_HANDLER_UNTYPED_SCHEMA",
    "CAPABILITY_HANDLER_OPEN_OBJECT",
    "CAPABILITY_HANDLER_READ_ONLY_UNDECLARED",
    "HOOK_TARGET_UNRESOLVED",
    "HOOK_DYNAMIC_REGISTRATION",
    "HOOK_ORDER_AMBIGUOUS",
    "EVENT_NOT_TYPED",
    "EVENT_WAIT_OUTSIDE_BODY",
    "TASK_GROUP_MISSING_JOIN",
    "TASK_GROUP_DETACHED_WORK",
    "TASK_GROUP_RAW_COROUTINE",
    "DIAGNOSTIC_CODES",
]
