# AUTO-GENERATED by apxm codegen frontend-vocabulary; DO NOT EDIT.
"""Every closed string set the apxm.frontend-graph contract states.

The frontend emits source-graph documents that Rust decodes against this
same contract with unknown members rejected, so a hand-typed string that the
contract does not state is a document the compiler refuses. Bind the constant
instead of retyping the string: a misspelled constant is an ImportError, a
misspelled string reaches the compiler and fails there.

This module is internal to the frontend. It carries source-intent vocabulary
only, never an AIR or AIS operation name.
"""

from typing import Final, Literal, TypeAlias

SourceLanguage: TypeAlias = Literal[
    "python",
    "typescript",
]
SOURCE_LANGUAGE_PYTHON: Final[SourceLanguage] = "python"
SOURCE_LANGUAGE_TYPESCRIPT: Final[SourceLanguage] = "typescript"
SOURCE_LANGUAGES: Final[tuple[SourceLanguage, ...]] = (
    SOURCE_LANGUAGE_PYTHON,
    SOURCE_LANGUAGE_TYPESCRIPT,
)

DeclKind: TypeAlias = Literal[
    "context",
    "model_binding",
    "tool_binding",
    "capability_binding",
    "event_type",
]
DECL_KIND_CONTEXT: Final[DeclKind] = "context"
DECL_KIND_MODEL_BINDING: Final[DeclKind] = "model_binding"
DECL_KIND_TOOL_BINDING: Final[DeclKind] = "tool_binding"
DECL_KIND_CAPABILITY_BINDING: Final[DeclKind] = "capability_binding"
DECL_KIND_EVENT_TYPE: Final[DeclKind] = "event_type"
DECL_KINDS: Final[tuple[DeclKind, ...]] = (
    DECL_KIND_CONTEXT,
    DECL_KIND_MODEL_BINDING,
    DECL_KIND_TOOL_BINDING,
    DECL_KIND_CAPABILITY_BINDING,
    DECL_KIND_EVENT_TYPE,
)

ParameterRole: TypeAlias = Literal[
    "agent_facade",
    "input",
    "context",
    "ordinary",
]
PARAMETER_ROLE_AGENT_FACADE: Final[ParameterRole] = "agent_facade"
PARAMETER_ROLE_INPUT: Final[ParameterRole] = "input"
PARAMETER_ROLE_CONTEXT: Final[ParameterRole] = "context"
PARAMETER_ROLE_ORDINARY: Final[ParameterRole] = "ordinary"
PARAMETER_ROLES: Final[tuple[ParameterRole, ...]] = (
    PARAMETER_ROLE_AGENT_FACADE,
    PARAMETER_ROLE_INPUT,
    PARAMETER_ROLE_CONTEXT,
    PARAMETER_ROLE_ORDINARY,
)

ValueOrigin: TypeAlias = Literal[
    "parameter",
    "call_result",
    "block_argument",
    "context_value",
    "literal",
    "resume_input",
]
VALUE_ORIGIN_PARAMETER: Final[ValueOrigin] = "parameter"
VALUE_ORIGIN_CALL_RESULT: Final[ValueOrigin] = "call_result"
VALUE_ORIGIN_BLOCK_ARGUMENT: Final[ValueOrigin] = "block_argument"
VALUE_ORIGIN_CONTEXT_VALUE: Final[ValueOrigin] = "context_value"
VALUE_ORIGIN_LITERAL: Final[ValueOrigin] = "literal"
VALUE_ORIGIN_RESUME_INPUT: Final[ValueOrigin] = "resume_input"
VALUE_ORIGINS: Final[tuple[ValueOrigin, ...]] = (
    VALUE_ORIGIN_PARAMETER,
    VALUE_ORIGIN_CALL_RESULT,
    VALUE_ORIGIN_BLOCK_ARGUMENT,
    VALUE_ORIGIN_CONTEXT_VALUE,
    VALUE_ORIGIN_LITERAL,
    VALUE_ORIGIN_RESUME_INPUT,
)

ValueExpressionKind: TypeAlias = Literal[
    "ssa",
    "context",
    "projection",
    "object",
    "array",
    "string",
    "integer",
    "boolean",
    "null",
]
VALUE_EXPRESSION_KIND_SSA: Final[ValueExpressionKind] = "ssa"
VALUE_EXPRESSION_KIND_CONTEXT: Final[ValueExpressionKind] = "context"
VALUE_EXPRESSION_KIND_PROJECTION: Final[ValueExpressionKind] = "projection"
VALUE_EXPRESSION_KIND_OBJECT: Final[ValueExpressionKind] = "object"
VALUE_EXPRESSION_KIND_ARRAY: Final[ValueExpressionKind] = "array"
VALUE_EXPRESSION_KIND_STRING: Final[ValueExpressionKind] = "string"
VALUE_EXPRESSION_KIND_INTEGER: Final[ValueExpressionKind] = "integer"
VALUE_EXPRESSION_KIND_BOOLEAN: Final[ValueExpressionKind] = "boolean"
VALUE_EXPRESSION_KIND_NULL: Final[ValueExpressionKind] = "null"
VALUE_EXPRESSION_KINDS: Final[tuple[ValueExpressionKind, ...]] = (
    VALUE_EXPRESSION_KIND_SSA,
    VALUE_EXPRESSION_KIND_CONTEXT,
    VALUE_EXPRESSION_KIND_PROJECTION,
    VALUE_EXPRESSION_KIND_OBJECT,
    VALUE_EXPRESSION_KIND_ARRAY,
    VALUE_EXPRESSION_KIND_STRING,
    VALUE_EXPRESSION_KIND_INTEGER,
    VALUE_EXPRESSION_KIND_BOOLEAN,
    VALUE_EXPRESSION_KIND_NULL,
)

RegionRole: TypeAlias = Literal[
    "function_body",
    "conditional_arm",
    "loop_body",
    "task_scope",
    "task_child",
    "try_body",
    "catch_body",
    "hook_body",
]
REGION_ROLE_FUNCTION_BODY: Final[RegionRole] = "function_body"
REGION_ROLE_CONDITIONAL_ARM: Final[RegionRole] = "conditional_arm"
REGION_ROLE_LOOP_BODY: Final[RegionRole] = "loop_body"
REGION_ROLE_TASK_SCOPE: Final[RegionRole] = "task_scope"
REGION_ROLE_TASK_CHILD: Final[RegionRole] = "task_child"
REGION_ROLE_TRY_BODY: Final[RegionRole] = "try_body"
REGION_ROLE_CATCH_BODY: Final[RegionRole] = "catch_body"
REGION_ROLE_HOOK_BODY: Final[RegionRole] = "hook_body"
REGION_ROLES: Final[tuple[RegionRole, ...]] = (
    REGION_ROLE_FUNCTION_BODY,
    REGION_ROLE_CONDITIONAL_ARM,
    REGION_ROLE_LOOP_BODY,
    REGION_ROLE_TASK_SCOPE,
    REGION_ROLE_TASK_CHILD,
    REGION_ROLE_TRY_BODY,
    REGION_ROLE_CATCH_BODY,
    REGION_ROLE_HOOK_BODY,
)

IntentKind: TypeAlias = Literal[
    "model_invocation",
    "tool_invocation",
    "capability_invocation",
    "agent_creation",
    "agent_invocation",
    "event_wait",
]
INTENT_KIND_MODEL_INVOCATION: Final[IntentKind] = "model_invocation"
INTENT_KIND_TOOL_INVOCATION: Final[IntentKind] = "tool_invocation"
INTENT_KIND_CAPABILITY_INVOCATION: Final[IntentKind] = "capability_invocation"
INTENT_KIND_AGENT_CREATION: Final[IntentKind] = "agent_creation"
INTENT_KIND_AGENT_INVOCATION: Final[IntentKind] = "agent_invocation"
INTENT_KIND_EVENT_WAIT: Final[IntentKind] = "event_wait"
INTENT_KINDS: Final[tuple[IntentKind, ...]] = (
    INTENT_KIND_MODEL_INVOCATION,
    INTENT_KIND_TOOL_INVOCATION,
    INTENT_KIND_CAPABILITY_INVOCATION,
    INTENT_KIND_AGENT_CREATION,
    INTENT_KIND_AGENT_INVOCATION,
    INTENT_KIND_EVENT_WAIT,
)

ReceiverKind: TypeAlias = Literal[
    "program_ref",
    "program_instance_ref",
]
RECEIVER_KIND_PROGRAM_REF: Final[ReceiverKind] = "program_ref"
RECEIVER_KIND_PROGRAM_INSTANCE_REF: Final[ReceiverKind] = "program_instance_ref"
RECEIVER_KINDS: Final[tuple[ReceiverKind, ...]] = (
    RECEIVER_KIND_PROGRAM_REF,
    RECEIVER_KIND_PROGRAM_INSTANCE_REF,
)

ControlKind: TypeAlias = Literal[
    "conditional",
    "switch",
    "loop",
    "task_group",
    "try_catch",
    "throw",
    "yield",
    "return",
]
CONTROL_KIND_CONDITIONAL: Final[ControlKind] = "conditional"
CONTROL_KIND_SWITCH: Final[ControlKind] = "switch"
CONTROL_KIND_LOOP: Final[ControlKind] = "loop"
CONTROL_KIND_TASK_GROUP: Final[ControlKind] = "task_group"
CONTROL_KIND_TRY_CATCH: Final[ControlKind] = "try_catch"
CONTROL_KIND_THROW: Final[ControlKind] = "throw"
CONTROL_KIND_YIELD: Final[ControlKind] = "yield"
CONTROL_KIND_RETURN: Final[ControlKind] = "return"
CONTROL_KINDS: Final[tuple[ControlKind, ...]] = (
    CONTROL_KIND_CONDITIONAL,
    CONTROL_KIND_SWITCH,
    CONTROL_KIND_LOOP,
    CONTROL_KIND_TASK_GROUP,
    CONTROL_KIND_TRY_CATCH,
    CONTROL_KIND_THROW,
    CONTROL_KIND_YIELD,
    CONTROL_KIND_RETURN,
)

PredicateComparator: TypeAlias = Literal[
    "truthy",
    "equals",
    "not_equals",
]
PREDICATE_COMPARATOR_TRUTHY: Final[PredicateComparator] = "truthy"
PREDICATE_COMPARATOR_EQUALS: Final[PredicateComparator] = "equals"
PREDICATE_COMPARATOR_NOT_EQUALS: Final[PredicateComparator] = "not_equals"
PREDICATE_COMPARATORS: Final[tuple[PredicateComparator, ...]] = (
    PREDICATE_COMPARATOR_TRUTHY,
    PREDICATE_COMPARATOR_EQUALS,
    PREDICATE_COMPARATOR_NOT_EQUALS,
)

PredicateScalarType: TypeAlias = Literal[
    "boolean",
    "string",
    "integer",
    "null",
]
PREDICATE_SCALAR_TYPE_BOOLEAN: Final[PredicateScalarType] = "boolean"
PREDICATE_SCALAR_TYPE_STRING: Final[PredicateScalarType] = "string"
PREDICATE_SCALAR_TYPE_INTEGER: Final[PredicateScalarType] = "integer"
PREDICATE_SCALAR_TYPE_NULL: Final[PredicateScalarType] = "null"
PREDICATE_SCALAR_TYPES: Final[tuple[PredicateScalarType, ...]] = (
    PREDICATE_SCALAR_TYPE_BOOLEAN,
    PREDICATE_SCALAR_TYPE_STRING,
    PREDICATE_SCALAR_TYPE_INTEGER,
    PREDICATE_SCALAR_TYPE_NULL,
)

HookScope: TypeAlias = Literal[
    "agent",
    "loop",
    "node",
    "model",
    "capability",
]
HOOK_SCOPE_AGENT: Final[HookScope] = "agent"
HOOK_SCOPE_LOOP: Final[HookScope] = "loop"
HOOK_SCOPE_NODE: Final[HookScope] = "node"
HOOK_SCOPE_MODEL: Final[HookScope] = "model"
HOOK_SCOPE_CAPABILITY: Final[HookScope] = "capability"
HOOK_SCOPES: Final[tuple[HookScope, ...]] = (
    HOOK_SCOPE_AGENT,
    HOOK_SCOPE_LOOP,
    HOOK_SCOPE_NODE,
    HOOK_SCOPE_MODEL,
    HOOK_SCOPE_CAPABILITY,
)

HookPhase: TypeAlias = Literal[
    "before",
    "after",
]
HOOK_PHASE_BEFORE: Final[HookPhase] = "before"
HOOK_PHASE_AFTER: Final[HookPhase] = "after"
HOOK_PHASES: Final[tuple[HookPhase, ...]] = (
    HOOK_PHASE_BEFORE,
    HOOK_PHASE_AFTER,
)

HookReturnMode: TypeAlias = Literal[
    "observe",
    "replace_result",
]
HOOK_RETURN_MODE_OBSERVE: Final[HookReturnMode] = "observe"
HOOK_RETURN_MODE_REPLACE_RESULT: Final[HookReturnMode] = "replace_result"
HOOK_RETURN_MODES: Final[tuple[HookReturnMode, ...]] = (
    HOOK_RETURN_MODE_OBSERVE,
    HOOK_RETURN_MODE_REPLACE_RESULT,
)

__all__ = [
    "SourceLanguage",
    "SOURCE_LANGUAGE_PYTHON",
    "SOURCE_LANGUAGE_TYPESCRIPT",
    "SOURCE_LANGUAGES",
    "DeclKind",
    "DECL_KIND_CONTEXT",
    "DECL_KIND_MODEL_BINDING",
    "DECL_KIND_TOOL_BINDING",
    "DECL_KIND_CAPABILITY_BINDING",
    "DECL_KIND_EVENT_TYPE",
    "DECL_KINDS",
    "ParameterRole",
    "PARAMETER_ROLE_AGENT_FACADE",
    "PARAMETER_ROLE_INPUT",
    "PARAMETER_ROLE_CONTEXT",
    "PARAMETER_ROLE_ORDINARY",
    "PARAMETER_ROLES",
    "ValueOrigin",
    "VALUE_ORIGIN_PARAMETER",
    "VALUE_ORIGIN_CALL_RESULT",
    "VALUE_ORIGIN_BLOCK_ARGUMENT",
    "VALUE_ORIGIN_CONTEXT_VALUE",
    "VALUE_ORIGIN_LITERAL",
    "VALUE_ORIGIN_RESUME_INPUT",
    "VALUE_ORIGINS",
    "ValueExpressionKind",
    "VALUE_EXPRESSION_KIND_SSA",
    "VALUE_EXPRESSION_KIND_CONTEXT",
    "VALUE_EXPRESSION_KIND_PROJECTION",
    "VALUE_EXPRESSION_KIND_OBJECT",
    "VALUE_EXPRESSION_KIND_ARRAY",
    "VALUE_EXPRESSION_KIND_STRING",
    "VALUE_EXPRESSION_KIND_INTEGER",
    "VALUE_EXPRESSION_KIND_BOOLEAN",
    "VALUE_EXPRESSION_KIND_NULL",
    "VALUE_EXPRESSION_KINDS",
    "RegionRole",
    "REGION_ROLE_FUNCTION_BODY",
    "REGION_ROLE_CONDITIONAL_ARM",
    "REGION_ROLE_LOOP_BODY",
    "REGION_ROLE_TASK_SCOPE",
    "REGION_ROLE_TASK_CHILD",
    "REGION_ROLE_TRY_BODY",
    "REGION_ROLE_CATCH_BODY",
    "REGION_ROLE_HOOK_BODY",
    "REGION_ROLES",
    "IntentKind",
    "INTENT_KIND_MODEL_INVOCATION",
    "INTENT_KIND_TOOL_INVOCATION",
    "INTENT_KIND_CAPABILITY_INVOCATION",
    "INTENT_KIND_AGENT_CREATION",
    "INTENT_KIND_AGENT_INVOCATION",
    "INTENT_KIND_EVENT_WAIT",
    "INTENT_KINDS",
    "ReceiverKind",
    "RECEIVER_KIND_PROGRAM_REF",
    "RECEIVER_KIND_PROGRAM_INSTANCE_REF",
    "RECEIVER_KINDS",
    "ControlKind",
    "CONTROL_KIND_CONDITIONAL",
    "CONTROL_KIND_SWITCH",
    "CONTROL_KIND_LOOP",
    "CONTROL_KIND_TASK_GROUP",
    "CONTROL_KIND_TRY_CATCH",
    "CONTROL_KIND_THROW",
    "CONTROL_KIND_YIELD",
    "CONTROL_KIND_RETURN",
    "CONTROL_KINDS",
    "PredicateComparator",
    "PREDICATE_COMPARATOR_TRUTHY",
    "PREDICATE_COMPARATOR_EQUALS",
    "PREDICATE_COMPARATOR_NOT_EQUALS",
    "PREDICATE_COMPARATORS",
    "PredicateScalarType",
    "PREDICATE_SCALAR_TYPE_BOOLEAN",
    "PREDICATE_SCALAR_TYPE_STRING",
    "PREDICATE_SCALAR_TYPE_INTEGER",
    "PREDICATE_SCALAR_TYPE_NULL",
    "PREDICATE_SCALAR_TYPES",
    "HookScope",
    "HOOK_SCOPE_AGENT",
    "HOOK_SCOPE_LOOP",
    "HOOK_SCOPE_NODE",
    "HOOK_SCOPE_MODEL",
    "HOOK_SCOPE_CAPABILITY",
    "HOOK_SCOPES",
    "HookPhase",
    "HOOK_PHASE_BEFORE",
    "HOOK_PHASE_AFTER",
    "HOOK_PHASES",
    "HookReturnMode",
    "HOOK_RETURN_MODE_OBSERVE",
    "HOOK_RETURN_MODE_REPLACE_RESULT",
    "HOOK_RETURN_MODES",
]
