# AUTO-GENERATED by apxm codegen frontend-vocabulary; DO NOT EDIT.
"""The scopes a Hook declares itself over.

A Hook states `scope=CAPABILITY` rather than `scope="capability"`, so the
scope an author writes is the scope the contract states rather than a string
that has to match one. Every name here aliases the constant the internal
source-graph vocabulary already carries, so each scope has one spelling.

Authors reach these through `apxm_program.scopes`, this module's public path.
"""

from .frontend_graph import HookScope as Scope
from .frontend_graph import (
    HOOK_SCOPE_AGENT as AGENT,
    HOOK_SCOPE_LOOP as LOOP,
    HOOK_SCOPE_NODE as NODE,
    HOOK_SCOPE_MODEL as MODEL,
    HOOK_SCOPE_CAPABILITY as CAPABILITY,
    HOOK_SCOPES as SCOPES,
)

__all__ = [
    "Scope",
    "AGENT",
    "LOOP",
    "NODE",
    "MODEL",
    "CAPABILITY",
    "SCOPES",
]
