# AUTO-GENERATED by compiler frontend; DO NOT EDIT.
_CODEGEN_HASH: str = "c147814b4839b55d"
from dataclasses import dataclass
from typing import Final

@dataclass(frozen=True)
class AgentRef:
    name: str
    command: str
    description: str | None
    route_capabilities: tuple[str, ...]
    source: str
    default_mode: str | None
    default_model: str | None

claude: Final = AgentRef(
    name="claude",
    command="npx -y @agentclientprotocol/claude-agent-acp@^0.24.2",
    description="Claude Code ACP profile for repository analysis, edits, command execution, review, and workflow planning.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

codex: Final = AgentRef(
    name="codex",
    command="npx -y @zed-industries/codex-acp@^0.16.0",
    description="Codex ACP profile for coding, tests, code review, and workflow implementation.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

copilot: Final = AgentRef(
    name="copilot",
    command="copilot --acp --stdio",
    description="GitHub Copilot ACP profile for coding assistance, repository edits, and review.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

cursor: Final = AgentRef(
    name="cursor",
    command="cursor-agent acp",
    description="Cursor agent ACP profile for codebase navigation, edits, and verification.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

droid: Final = AgentRef(
    name="droid",
    command="droid exec --output-format acp",
    description="Droid ACP profile for repository tasks exposed through Droid's ACP output mode.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

gemini: Final = AgentRef(
    name="gemini",
    command="gemini --acp",
    description="Gemini ACP profile for codebase analysis, implementation, and verification.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

iflow: Final = AgentRef(
    name="iflow",
    command="iflow --experimental-acp",
    description="iFlow experimental ACP profile for repository analysis and implementation tasks.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

kilocode: Final = AgentRef(
    name="kilocode",
    command="npx -y @kilocode/cli acp",
    description="Kilo Code ACP profile for implementation, command execution, and verification tasks.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

kimi: Final = AgentRef(
    name="kimi",
    command="kimi acp",
    description="Kimi ACP profile for coding, analysis, and review tasks.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

kiro: Final = AgentRef(
    name="kiro",
    command="kiro-cli-chat acp",
    description="Kiro ACP profile for coding-agent tasks through kiro-cli-chat.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

opencode: Final = AgentRef(
    name="opencode",
    command="npx -y opencode-ai acp",
    description="OpenCode ACP profile for implementation, command execution, and code review.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

pi: Final = AgentRef(
    name="pi",
    command="npx pi-acp@^0.0.22",
    description="Pi ACP profile for general reasoning and coding-agent tasks when the Pi CLI is installed.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

qoder: Final = AgentRef(
    name="qoder",
    command="qodercli --acp",
    description="Qoder ACP profile for repository implementation and review workflows.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

qwen: Final = AgentRef(
    name="qwen",
    command="qwen --acp",
    description="Qwen ACP profile for coding, analysis, workflow planning, and verification.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

trae: Final = AgentRef(
    name="trae",
    command="traecli acp serve",
    description="Trae ACP profile for codebase implementation and review tasks.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

ALL_AGENTS: Final[tuple[AgentRef, ...]] = (
    claude,
    codex,
    copilot,
    cursor,
    droid,
    gemini,
    iflow,
    kilocode,
    kimi,
    kiro,
    opencode,
    pi,
    qoder,
    qwen,
    trae,
)
