# AUTO-GENERATED by compiler frontend; DO NOT EDIT.
_CODEGEN_HASH: str = "e5587c727de0b5e0"
from dataclasses import dataclass
from typing import Final

@dataclass(frozen=True)
class AgentRef:
    name: str
    command: str
    description: str | None
    route_capabilities: tuple[str, ...]
    source: str
    default_mode: str | None
    default_model: str | None

claude: Final = AgentRef(
    name="claude",
    command="npx -y @agentclientprotocol/claude-agent-acp@^0.24.2",
    description="Claude Code ACP profile for repository analysis, edits, command execution, review, and workflow planning.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

codex: Final = AgentRef(
    name="codex",
    command="npx -y @zed-industries/codex-acp@^0.16.0",
    description="Codex ACP profile for coding, tests, code review, and workflow implementation.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

custom: Final = AgentRef(
    name="custom",
    command="",
    description="Generic custom-command profile for any ACP-speaking CLI outside the tuned working set (claude, codex, gemini) — for example copilot, pi, cursor, droid, kilocode, kimi, kiro, opencode, qoder, qwen, trae, or iflow. Set `command` to that CLI's ACP invocation via `apxm agent add <name> --command \"...\"`, or copy this profile into ~/.apxm/agents.toml with `command` filled in; no dedicated Rust template is required.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

gemini: Final = AgentRef(
    name="gemini",
    command="gemini --acp",
    description="Gemini ACP profile for codebase analysis, implementation, and verification.",
    route_capabilities=(
        "read",
        "write",
        "execute",
        "critique",
        "workflow_author",
        "planner",
        "reviewer",
        "critic",
        "verifier",
        "synthesizer",
    ),
    source="template",
    default_mode=None,
    default_model=None,
)

ALL_AGENTS: Final[tuple[AgentRef, ...]] = (
    claude,
    codex,
    custom,
    gemini,
)
