# AUTO-GENERATED by compiler frontend; DO NOT EDIT.
_CODEGEN_HASH: str = "7fcc45eb59579b6a"
from dataclasses import dataclass
from typing import Final

@dataclass(frozen=True)
class FieldSpec:
    name: str
    description: str
    required: bool
    ref_type: str | None

@dataclass(frozen=True)
class OpSpec:
    op: str
    name: str
    category: str
    description: str
    long_description: str
    latency: str
    fields: tuple[FieldSpec, ...]
    produces_output: bool
    needs_submission: bool
    min_inputs: int
    example_json: str | None

AGENT: Final = OpSpec(
    op="AGENT",
    name="Agent",
    category="metadata",
    description="Agent structural declaration (memory, beliefs, goals, capabilities)",
    long_description="Declares an agent's identity and initial AAM state. Every graph must have exactly one AGENT node. It configures memory tiers (STM/LTM/Episodic), initial beliefs and goals, and the capabilities the agent can invoke. The runtime uses this to initialize the agent's AAM before executing any other node.",
    latency="none",
    fields=(FieldSpec(name="memory", description="Memory configuration", required=False, ref_type=None), FieldSpec(name="beliefs", description="Initial beliefs", required=False, ref_type=None), FieldSpec(name="goals", description="Initial goals", required=False, ref_type=None), FieldSpec(name="capabilities", description="Available capabilities", required=False, ref_type=None)),
    produces_output=False,
    needs_submission=False,
    min_inputs=0,
    example_json="{\"id\": 0, \"op\": \"AGENT\", \"attributes\": {\"memory\": {\"stm\": true}, \"beliefs\": {\"role\": \"analyst\"}, \"goals\": [\"summarize data\"], \"capabilities\": [\"search\", \"calculate\"]}}",
)

QMEM: Final = OpSpec(
    op="QMEM",
    name="QueryMemory",
    category="memory",
    description="Retrieve data from memory (STM, LTM, or Episodic)",
    long_description="Reads from the agent's memory system. Supports three tiers: STM (short-term, per-execution scratch), LTM (long-term, persists across runs), and Episodic (execution traces). The query string is matched against stored keys. Returns the stored value or null if not found.",
    latency="low",
    fields=(FieldSpec(name="query", description="Query string or key to search for", required=True, ref_type=None), FieldSpec(name="memory_tier", description="Target memory tier: stm, ltm, or episodic", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 2, \"op\": \"QMEM\", \"attributes\": {\"query\": \"user_name\", \"memory_tier\": \"stm\"}}",
)

UMEM: Final = OpSpec(
    op="UMEM",
    name="UpdateMemory",
    category="memory",
    description="Persist or update data in memory",
    long_description="Writes a key-value pair to the agent's memory system. If the key already exists, the value is overwritten. Supports the same three memory tiers as QMEM. Use FENCE after UMEM if subsequent QMEM nodes must see the write.",
    latency="low",
    fields=(FieldSpec(name="key", description="Key to store the value under", required=True, ref_type=None), FieldSpec(name="value", description="Value to store", required=True, ref_type=None), FieldSpec(name="memory_tier", description="Target memory tier: stm, ltm, or episodic", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 3, \"op\": \"UMEM\", \"attributes\": {\"key\": \"summary\", \"value\": \"Rust favors explicit ownership and borrowing.\", \"memory_tier\": \"stm\"}}",
)

ASK: Final = OpSpec(
    op="ASK",
    name="Ask",
    category="reasoning",
    description="Simple Q&A with LLM (no extended thinking)",
    long_description="Sends a prompt to the configured LLM and returns the response. The lightest LLM operation — no chain-of-thought or extended thinking. Use for straightforward questions, classifications, extractions, or reformulations. Template strings support named `{input}` interpolation for dataflow inputs via the node's `input_names` array.",
    latency="medium",
    fields=(FieldSpec(name="template_str", description="Prompt template for the question", required=True, ref_type=None), FieldSpec(name="temperature", description="Sampling temperature (0.0-1.0)", required=False, ref_type=None), FieldSpec(name="model", description="LLM model override (uses config default)", required=False, ref_type="model")),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 1, \"op\": \"ASK\", \"attributes\": {\"template_str\": \"Summarize: {source}\", \"input_names\": [\"source\"]}}",
)

THINK: Final = OpSpec(
    op="THINK",
    name="Think",
    category="reasoning",
    description="Extended thinking with token_budget",
    long_description="Activates extended thinking (chain-of-thought) with a configurable token budget. The LLM produces internal reasoning before the final answer. Use for complex multi-step problems, math, code generation, or planning that benefits from deliberate reasoning. The budget controls how many tokens the model can spend thinking.",
    latency="high",
    fields=(FieldSpec(name="template_str", description="Prompt template for deep reasoning", required=True, ref_type=None), FieldSpec(name="budget", description="Token budget for extended thinking", required=False, ref_type=None), FieldSpec(name="temperature", description="Sampling temperature (0.0-1.0)", required=False, ref_type=None), FieldSpec(name="model", description="LLM model override (uses config default)", required=False, ref_type="model")),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 1, \"op\": \"THINK\", \"attributes\": {\"template_str\": \"Solve step by step: {problem}\", \"input_names\": [\"problem\"], \"budget\": 4096}}",
)

REASON: Final = OpSpec(
    op="REASON",
    name="Reason",
    category="reasoning",
    description="Structured reasoning with belief/goal updates",
    long_description="Performs structured reasoning that can update the agent's beliefs and goals (AAM state). Unlike ASK, the runtime parses the LLM response for belief and goal mutations. Use when the agent needs to update its internal state based on new information. Supports structured JSON output mode.",
    latency="medium",
    fields=(FieldSpec(name="template_str", description="Prompt template for structured reasoning", required=True, ref_type=None), FieldSpec(name="temperature", description="Sampling temperature (0.0-1.0)", required=False, ref_type=None), FieldSpec(name="model", description="LLM model override (uses config default)", required=False, ref_type="model"), FieldSpec(name="structured", description="Enable structured JSON output", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 1, \"op\": \"REASON\", \"attributes\": {\"template_str\": \"Given {evidence}, update your analysis\", \"input_names\": [\"evidence\"], \"structured\": true}}",
)

PLAN: Final = OpSpec(
    op="PLAN",
    name="Plan",
    category="reasoning",
    description="Decompose goal into AIS subgraph",
    long_description="Uses the LLM to decompose a high-level goal into a sequence of concrete steps. The output is a structured plan that can be used to drive subsequent nodes. Supports optional constraints to bound the plan space.",
    latency="high",
    fields=(FieldSpec(name="goal", description="Goal to decompose into steps", required=True, ref_type=None), FieldSpec(name="constraints", description="Constraints on the plan", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 1, \"op\": \"PLAN\", \"attributes\": {\"goal\": \"Research and summarize recent AI papers\", \"constraints\": \"max 5 steps\"}}",
)

REFLECT: Final = OpSpec(
    op="REFLECT",
    name="Reflect",
    category="reasoning",
    description="Analyze execution trace for self-improvement",
    long_description="Retrieves past execution traces and asks the LLM to analyze them for patterns, failures, or improvements. Useful for iterative refinement loops where the agent learns from its own execution history.",
    latency="medium",
    fields=(FieldSpec(name="trace_query", description="Query to retrieve trace for reflection", required=True, ref_type=None), FieldSpec(name="reflection_prompt", description="Custom prompt for reflection", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 4, \"op\": \"REFLECT\", \"attributes\": {\"trace_query\": \"last_execution\"}}",
)

VERIFY: Final = OpSpec(
    op="VERIFY",
    name="Verify",
    category="reasoning",
    description="Fact-check outputs against evidence",
    long_description="Cross-references a claim against provided evidence using the LLM. Returns a verification result with confidence score. Use after ASK/THINK/REASON nodes to validate outputs before acting on them. Evidence may be supplied either as a literal attribute or via an incoming Data edge.",
    latency="medium",
    fields=(FieldSpec(name="claim", description="Claim to verify", required=True, ref_type=None), FieldSpec(name="evidence", description="Evidence to check against", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 5, \"op\": \"VERIFY\", \"attributes\": {\"claim\": \"The solar system has eight planets.\"}}",
)

INV_CAP: Final = OpSpec(
    op="INV_CAP",
    name="InvokeTool",
    category="tools",
    description="Call external tool with structured params; store result",
    long_description="Invokes a registered capability (tool or function) by name. The capability must be declared in the AGENT node's capabilities list or registered in the runtime's CapabilityRegistry. Parameters are passed via the `params_json` attribute as a JSON object. The tool's return value becomes this node's output token.",
    latency="medium",
    fields=(FieldSpec(name="capability", description="Name of the capability/tool to invoke", required=True, ref_type="capability"), FieldSpec(name="params_json", description="JSON-encoded parameters to pass to the tool", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 2, \"op\": \"INV_CAP\", \"attributes\": {\"capability\": \"web_search\", \"params_json\": \"{\\\"query\\\":\\\"rust ownership\\\"}\"}}",
)

EXC: Final = OpSpec(
    op="EXC",
    name="ExecuteCode",
    category="tools",
    description="Run code in a sandboxed environment; update Beliefs",
    long_description="Executes arbitrary code in a sandboxed environment. The sandbox prevents file system access, network calls, and other side effects unless explicitly allowed. The code's stdout/return value becomes the output token. Execution results are also written to the agent's beliefs.",
    latency="low",
    fields=(FieldSpec(name="code", description="Code to execute", required=True, ref_type=None), FieldSpec(name="sandbox_config", description="Sandbox configuration", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 3, \"op\": \"EXC\", \"attributes\": {\"code\": \"print(2 + 2)\"}}",
)

PRINT: Final = OpSpec(
    op="PRINT",
    name="PrintOutput",
    category="tools",
    description="Print output to stdout for debugging or user display",
    long_description="Writes a message to stdout. Supports named `{input}` template interpolation via `input_names`. Useful for debugging graphs during development or displaying final results to the user. The message is also stored as the output token.",
    latency="none",
    fields=(FieldSpec(name="message", description="Message to print", required=True, ref_type=None),),
    produces_output=False,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 4, \"op\": \"PRINT\", \"attributes\": {\"message\": \"Result: {result}\", \"input_names\": [\"result\"]}}",
)

JUMP: Final = OpSpec(
    op="JUMP",
    name="Jump",
    category="control_flow",
    description="Unconditional jump to a labeled instruction",
    long_description="Transfers control flow unconditionally to a target label. The label must correspond to a node ID in the graph. Edges from this node use Control dependency type.",
    latency="none",
    fields=(FieldSpec(name="label", description="Target label to jump to", required=True, ref_type=None),),
    produces_output=False,
    needs_submission=False,
    min_inputs=0,
    example_json="{\"id\": 5, \"op\": \"JUMP\", \"attributes\": {\"label\": \"7\"}}",
)

BRANCH_ON_VALUE: Final = OpSpec(
    op="BRANCH_ON_VALUE",
    name="BranchOnValue",
    category="control_flow",
    description="Conditional branch based on token value comparison",
    long_description="Evaluates an input token against a value and branches to one of two labels. If the token matches the value, control goes to label_true; otherwise to label_false. Used for if/else patterns in agent workflows.",
    latency="none",
    fields=(FieldSpec(name="value", description="Value to compare against", required=True, ref_type=None), FieldSpec(name="true_label", description="Label if comparison is true", required=True, ref_type=None), FieldSpec(name="false_label", description="Label if comparison is false", required=True, ref_type=None)),
    produces_output=False,
    needs_submission=False,
    min_inputs=1,
    example_json="{\"id\": 5, \"op\": \"BRANCH_ON_VALUE\", \"attributes\": {\"value\": \"yes\", \"true_label\": \"6\", \"false_label\": \"7\"}}",
)

RETURN: Final = OpSpec(
    op="RETURN",
    name="Return",
    category="control_flow",
    description="Return from subgraph with result token",
    long_description="Returns a value from a subgraph or flow. The result value is provided via an incoming Data edge.",
    latency="none",
    fields=(),
    produces_output=True,
    needs_submission=False,
    min_inputs=1,
    example_json="{\"id\": 6, \"op\": \"RETURN\", \"attributes\": {}}",
)

SWITCH: Final = OpSpec(
    op="SWITCH",
    name="Switch",
    category="control_flow",
    description="Multi-way branch based on string value comparison",
    long_description="Routes execution to one of several branches based on matching a discriminant token against case labels. Each case specifies a label string and a destination node. If no case matches, the default destination is used. The matched branch's result becomes the output token.",
    latency="none",
    fields=(FieldSpec(name="discriminant", description="Token to match against case labels", required=True, ref_type=None), FieldSpec(name="cases", description="Array of case label/destination pairs", required=True, ref_type=None), FieldSpec(name="default", description="Default destination if no case matches", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=False,
    min_inputs=1,
    example_json="{\"id\": 3, \"op\": \"SWITCH\", \"attributes\": {\"discriminant\": \"topic_kind\", \"cases\": [{\"label\": \"math\", \"node_id\": 4}, {\"label\": \"code\", \"node_id\": 5}], \"default\": \"6\"}}",
)

FLOW_CALL: Final = OpSpec(
    op="FLOW_CALL",
    name="FlowCall",
    category="control_flow",
    description="Call a flow on another agent with implicit parallelism",
    long_description="Invokes a named flow on a target agent. The target agent executes its flow graph independently and returns the result. Multiple FLOW_CALL nodes can execute in parallel if they have no data dependencies between them. This is the primary mechanism for multi-agent composition.",
    latency="high",
    fields=(FieldSpec(name="agent_name", description="Name of the agent to call", required=True, ref_type=None), FieldSpec(name="flow_name", description="Name of the flow to invoke", required=True, ref_type=None), FieldSpec(name="args", description="Arguments to pass to the flow", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 4, \"op\": \"FLOW_CALL\", \"attributes\": {\"agent_name\": \"researcher\", \"flow_name\": \"analyze\", \"args\": {\"topic\": \"{topic}\"}, \"input_names\": [\"topic\"]}}",
)

WORKFLOW_SPAWN: Final = OpSpec(
    op="WORKFLOW_SPAWN",
    name="WorkflowSpawn",
    category="control_flow",
    description="Spawn an external AIR file, artifact, or workflow as a child execution",
    long_description="Invokes an external AIR file, precompiled artifact, or workflow file as a child execution boundary. Arguments are passed by name through the args map. The child run resolves its session root from the explicit node attribute when present, otherwise it inherits the parent execution root.",
    latency="high",
    fields=(FieldSpec(name="target_kind", description="Invocation target kind: air_path, artifact_path, or workflow_path", required=True, ref_type=None), FieldSpec(name="target", description="Path of the AIR file, artifact, or workflow to execute", required=True, ref_type=None), FieldSpec(name="args", description="Arguments to pass to the child execution", required=False, ref_type=None), FieldSpec(name="session_root", description="Explicit session root for the child execution", required=False, ref_type=None), FieldSpec(name="await_result", description="Whether to wait for the child result (must be true in the current runtime)", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 5, \"op\": \"WORKFLOW_SPAWN\", \"attributes\": {\"target_kind\": \"workflow_path\", \"target\": \"workflows/review.apxmw\", \"args\": {\"topic\": \"{topic}\"}, \"input_names\": [\"topic\"], \"await_result\": true}}",
)

CALL_SKILL: Final = OpSpec(
    op="CALL_SKILL",
    name="CallSkill",
    category="control_flow",
    description="Call another skill by manifest identity (id or id@version)",
    long_description="Invokes another skill resolved by manifest identity through the live SkillLibrary, rather than by raw artifact path. Resolution is lazy: the runtime parses `<skill_id>[@<version>]`, looks up the matching .apxmobj, admits the child's required capabilities against the parent's grant, dispatches the child entry DAG, and records the resolved (skill_id, version, artifact_hash) triple in the parent's provenance. Failure modes are typed: InvalidSkillId, SkillNotFound, SkillVersionNotFound, CapabilityWiden, CallSkillDepthExceeded, ChildExecutionFailed.",
    latency="high",
    fields=(FieldSpec(name="skill_id", description="Skill identifier: \"id\" (latest) or \"id@version\" (pinned)", required=True, ref_type=None), FieldSpec(name="args", description="Positional arguments forwarded to the child's entry-flow input vector", required=False, ref_type=None), FieldSpec(name="input_names", description="Optional name vector mapping parent outputs onto the child's positional args", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 6, \"op\": \"CALL_SKILL\", \"attributes\": {\"skill_id\": \"apxm-orient@0.2.0\", \"args\": [\"context\"], \"input_names\": [\"context\"]}}",
)

MERGE: Final = OpSpec(
    op="MERGE",
    name="Merge",
    category="synchronization",
    description="Sync parallel paths; aggregate tokens into one",
    long_description="Waits for multiple parallel branches to complete and combines their output tokens into a single aggregated result. Inputs are provided via incoming Data edges.",
    latency="none",
    fields=(),
    produces_output=True,
    needs_submission=True,
    min_inputs=1,
    example_json="{\"id\": 6, \"op\": \"MERGE\", \"attributes\": {}}",
)

FENCE: Final = OpSpec(
    op="FENCE",
    name="Fence",
    category="synchronization",
    description="Memory barrier; order prior QMEM/UMEM operations",
    long_description="Ensures all preceding memory operations (UMEM writes) are visible to subsequent QMEM reads. Without a FENCE, the scheduler may reorder memory operations for parallelism. Place between UMEM and QMEM when ordering matters.",
    latency="none",
    fields=(FieldSpec(name="ordering", description="Memory ordering constraint", required=False, ref_type=None),),
    produces_output=False,
    needs_submission=True,
    min_inputs=0,
    example_json=None,
)

WAIT_ALL: Final = OpSpec(
    op="WAIT_ALL",
    name="WaitAll",
    category="synchronization",
    description="Block until all specified tokens are available",
    long_description="Blocks execution until all listed input tokens are ready. Unlike MERGE, it does not combine the tokens — it simply acts as a synchronization barrier. Inputs are provided via incoming Data edges.",
    latency="none",
    fields=(),
    produces_output=True,
    needs_submission=True,
    min_inputs=1,
    example_json="{\"id\": 5, \"op\": \"WAIT_ALL\", \"attributes\": {}}",
)

TRY_CATCH: Final = OpSpec(
    op="TRY_CATCH",
    name="TryCatch",
    category="error_handling",
    description="Structured exception handling with recovery subgraph",
    long_description="Wraps a try subgraph with a catch recovery subgraph. If any node in the try subgraph fails, execution transfers to the catch subgraph. The catch subgraph receives the error context and can attempt recovery or graceful degradation.",
    latency="none",
    fields=(FieldSpec(name="try_label", description="Subgraph to try executing", required=True, ref_type=None), FieldSpec(name="catch_label", description="Recovery subgraph on failure", required=True, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 2, \"op\": \"TRY_CATCH\", \"attributes\": {\"try_label\": \"3\", \"catch_label\": \"4\"}}",
)

ERR: Final = OpSpec(
    op="ERR",
    name="HandleError",
    category="error_handling",
    description="Invoke recovery template on failure; update Goals/Beliefs",
    long_description="Handles an error by invoking a recovery template. The error handler can update the agent's goals and beliefs to reflect the failure and adapt the agent's strategy. Typically used inside TRY_CATCH catch subgraphs.",
    latency="medium",
    fields=(FieldSpec(name="recovery_template", description="Error handler / recovery template to invoke", required=True, ref_type=None),),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 4, \"op\": \"ERR\", \"attributes\": {\"recovery_template\": \"retry_with_fallback\"}}",
)

COMMUNICATE: Final = OpSpec(
    op="COMMUNICATE",
    name="Communicate",
    category="communication",
    description="Send message to recipient agent via selected protocol",
    long_description="Sends a message from this agent to another agent. The message is received via input tokens from upstream edges. Supports four protocol dispatch modes: 'local' (default, in-process sub-flow), 'http'/'https' (external APXM agent), 'acp' (ACP subprocess via ProcessTable), and 'broadcast' (fan-out to all agents). The recipient attribute key is 'recipient'.",
    latency="medium",
    fields=(FieldSpec(name="recipient", description="Target agent name (or URL for http protocol)", required=True, ref_type=None), FieldSpec(name="message", description="Message content to send", required=False, ref_type=None), FieldSpec(name="protocol", description="Dispatch protocol: local (default), http, https, acp, broadcast", required=False, ref_type=None), FieldSpec(name="llm_operation", description="Semantic LLM operation for analysis when this communication sends an agent prompt", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 3, \"op\": \"COMMUNICATE\", \"attributes\": {\"recipient\": \"reviewer\", \"protocol\": \"acp\"}}",
)

HANDOFF: Final = OpSpec(
    op="HANDOFF",
    name="Handoff",
    category="communication",
    description="Hand off execution from one agent to another with optional state transfer",
    long_description="Transfers execution control from a source agent to a target agent. When transfer_state is true, the source agent's context-stack frames are copied to the target agent so it can continue with full conversational context. Emits HANDOFF_START and HANDOFF_END events with span continuity for tracing. The target agent's response becomes this node's output token.",
    latency="medium",
    fields=(FieldSpec(name="handoff_from", description="Source agent name", required=True, ref_type=None), FieldSpec(name="handoff_to", description="Target agent name", required=True, ref_type=None), FieldSpec(name="payload", description="Message payload to pass to the target agent", required=False, ref_type=None), FieldSpec(name="transfer_state", description="Whether to copy context-stack frames from source to target (default: true)", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=1,
    example_json="{\"id\": 3, \"op\": \"HANDOFF\", \"attributes\": {\"handoff_from\": \"agent_a\", \"handoff_to\": \"agent_b\", \"transfer_state\": true}}",
)

UPDATE_GOAL: Final = OpSpec(
    op="UPDATE_GOAL",
    name="UpdateGoal",
    category="memory",
    description="Modify AAM goals at runtime: set, remove, or clear",
    long_description="Dynamically modifies the agent's goal set during execution. Supports three actions: 'set' (upsert a goal with priority), 'remove' (delete a specific goal), and 'clear' (remove all goals). Goal changes are visible to subsequent REASON and REFLECT nodes.",
    latency="none",
    fields=(FieldSpec(name="goal_id", description="Goal identifier (used as description key for upsert/remove)", required=True, ref_type=None), FieldSpec(name="action", description="Action to perform: set (default), remove, clear", required=False, ref_type=None), FieldSpec(name="priority", description="Goal priority (u32, default: 1)", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=False,
    min_inputs=0,
    example_json="{\"id\": 3, \"op\": \"UPDATE_GOAL\", \"attributes\": {\"goal_id\": \"optimize_latency\", \"action\": \"set\", \"priority\": 2}}",
)

PAUSE: Final = OpSpec(
    op="PAUSE",
    name="Pause",
    category="communication",
    description="Suspend execution pending human-in-the-loop review via checkpoint",
    long_description="Creates a checkpoint and suspends execution until a human resumes it via the APXM server API. The pause message is displayed to the human reviewer. Optionally sends a webhook notification. The human can provide input that becomes this node's output token when RESUME is called.",
    latency="high",
    fields=(FieldSpec(name="message", description="Human-readable message explaining the pause", required=True, ref_type=None), FieldSpec(name="checkpoint_id", description="Stable checkpoint ID (auto-generated if omitted)", required=False, ref_type=None), FieldSpec(name="timeout_ms", description="Max wait in ms (0 = indefinite, default: 0)", required=False, ref_type=None), FieldSpec(name="poll_interval_ms", description="Polling interval in ms (default: 2000)", required=False, ref_type=None), FieldSpec(name="notification_url", description="Webhook URL to notify on pause creation", required=False, ref_type=None), FieldSpec(name="server_url", description="Override APXM_SERVER_URL env var", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 5, \"op\": \"PAUSE\", \"attributes\": {\"message\": \"Please review the analysis before proceeding\"}}",
)

RESUME: Final = OpSpec(
    op="RESUME",
    name="Resume",
    category="control_flow",
    description="Resume a suspended PAUSE checkpoint; polls server until human resumes; returns human_input",
    long_description="Polls the APXM server for a specific checkpoint until a human resumes it. When resumed, the human's input (if any) becomes this node's output token. Configurable polling interval and max attempts prevent indefinite blocking.",
    latency="high",
    fields=(FieldSpec(name="checkpoint", description="Checkpoint ID to resume from", required=True, ref_type=None), FieldSpec(name="poll_max_attempts", description="Max polling attempts (default 60 × 5s = 5 min)", required=False, ref_type=None), FieldSpec(name="poll_interval_ms", description="Interval between polls in ms (default 5000)", required=False, ref_type=None), FieldSpec(name="server_url", description="Override APXM_SERVER_URL env var", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 6, \"op\": \"RESUME\", \"attributes\": {\"checkpoint\": \"review_checkpoint_1\"}}",
)

DELEGATE: Final = OpSpec(
    op="DELEGATE",
    name="Delegate",
    category="coordination",
    description="Delegate a task to a sub-agent for execution",
    long_description="Creates a sub-task from a task specification and assigns it to a target agent. Returns a task handle that can be used to track the delegated work. The target agent executes the task independently and reports results back.",
    latency="medium",
    fields=(FieldSpec(name="task_spec", description="Description of the task to delegate", required=True, ref_type=None), FieldSpec(name="target_agent", description="Name of the agent to delegate to", required=True, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\\\"id\\\": 3, \\\"op\\\": \\\"DELEGATE\\\", \\\"attributes\\\": {\\\"task_spec\\\": \\\"Analyze the dataset\\\", \\\"target_agent\\\": \\\"analyst\\\"}}",
)

NOP: Final = OpSpec(
    op="NOP",
    name="Nop",
    category="identity",
    description="No-op passthrough with no side effects or AAM transition",
    long_description="Pure passthrough operation with no side effects and no AAM state transition. Passes through its first input unchanged, or returns Null if no inputs. Useful as a placeholder, sync point, or structural node in graph composition.",
    latency="none",
    fields=(),
    produces_output=True,
    needs_submission=False,
    min_inputs=0,
    example_json="{\\\"id\\\": 2, \\\"op\\\": \\\"NOP\\\"}",
)

IDENTITY: Final = OpSpec(
    op="IDENTITY",
    name="Identity",
    category="identity",
    description="Identity passthrough that records an AAM identity transition",
    long_description="Like NOP but produces an AAM identity transition (state unchanged but recorded in the execution trace). Useful for observability when you want to mark a point in the graph without changing state.",
    latency="none",
    fields=(),
    produces_output=True,
    needs_submission=False,
    min_inputs=0,
    example_json="{\\\"id\\\": 2, \\\"op\\\": \\\"IDENTITY\\\"}",
)

SPAWN_AGENT: Final = OpSpec(
    op="SPAWN_AGENT",
    name="SpawnAgent",
    category="coordination",
    description="Create a new agent instance at runtime, optionally as an ACP subprocess",
    long_description="Spawns a new agent instance. Without profile or agent_route, registers a local process for flow-based agents. With profile, spawns that ACP profile. With agent_route='auto', APXM selects an ACP profile from host-supplied route candidates using required_capabilities and preferred_profiles. The agent can then receive COMMUNICATE (protocol 'acp' or 'local') or DELEGATE messages. Returns the agent's identifier and metadata.",
    latency="medium",
    fields=(FieldSpec(name="agent_name", description="Name for the new agent", required=True, ref_type=None), FieldSpec(name="profile", description="APXM ACP agent profile. When present, spawns an ACP subprocess", required=False, ref_type="agent profile"), FieldSpec(name="agent_route", description="Set to 'auto' to let APXM select an ACP profile when profile is omitted", required=False, ref_type=None), FieldSpec(name="required_capabilities", description="Abstract route capabilities required from the selected ACP profile", required=False, ref_type=None), FieldSpec(name="preferred_profiles", description="Preferred APXM ACP profiles used as a tie-breaker after capability fit", required=False, ref_type=None), FieldSpec(name="mode", description="Agent mode to set after spawn (e.g. 'architect', 'code')", required=False, ref_type=None), FieldSpec(name="model", description="Agent-specific model hint accepted by the selected ACP profile", required=False, ref_type=None), FieldSpec(name="cwd", description="Working directory for the agent subprocess (defaults to current dir)", required=False, ref_type=None), FieldSpec(name="capabilities", description="List of capabilities for the new agent", required=False, ref_type=None), FieldSpec(name="goals", description="Initial goals for the new agent", required=False, ref_type=None), FieldSpec(name="system_prompt", description="System prompt / instructions for inline agents — enables HANDOFF/COMMUNICATE dispatch without registering the agent as a separate compiled flow", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 1, \"op\": \"SPAWN_AGENT\", \"attributes\": {\"agent_name\": \"worker\", \"profile\": \"example-acp-profile\", \"mode\": \"architect\"}}",
)

REGISTER_CAPABILITY: Final = OpSpec(
    op="REGISTER_CAPABILITY",
    name="RegisterCapability",
    category="coordination",
    description="Register a new capability (tool) in the runtime registry",
    long_description="Dynamically registers a new capability in the runtime's capability registry. The capability becomes available for INV_CAP operations after registration. Returns a confirmation with the registered capability name.",
    latency="low",
    fields=(FieldSpec(name="capability_name", description="Name for the capability to register", required=True, ref_type=None), FieldSpec(name="description", description="Human-readable description of the capability", required=False, ref_type=None), FieldSpec(name="parameters_schema", description="JSON schema for capability parameters", required=False, ref_type=None), FieldSpec(name="python_handler_id", description="Stable content-addressed id (sha256:<hex64>) for a Python-backed tool handler", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\\\"id\\\": 3, \\\"op\\\": \\\"REGISTER_CAPABILITY\\\", \\\"attributes\\\": {\\\"capability_name\\\": \\\"custom_tool\\\", \\\"description\\\": \\\"A custom analysis tool\\\"}}",
)

REGISTER_HOOK: Final = OpSpec(
    op="REGISTER_HOOK",
    name="RegisterHook",
    category="coordination",
    description="Register an author lifecycle hook into the artifact hook registry",
    long_description="Registers one typed author lifecycle hook into the per-artifact hook registry. The binding travels inside the AIR artifact and dispatches through the artifact's language-specific handler bridge. The runtime applies pre/post_cap hooks at the tool dispatch sites, pre/post_ask as Ask middleware, and session_start as an awaited pre-step.",
    latency="low",
    fields=(FieldSpec(name="hook_event", description="Lifecycle event the hook binds to", required=True, ref_type=None), FieldSpec(name="hook_match", description="Glob over tool/op name the hook applies to (default *)", required=False, ref_type=None), FieldSpec(name="hook_mode", description="Hook mode: observe or gate", required=False, ref_type=None), FieldSpec(name="hook_handler_id", description="Stable content-addressed id (sha256:<hex64>) for the artifact hook handler", required=True, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\\\"id\\\": 4, \\\"op\\\": \\\"REGISTER_HOOK\\\", \\\"attributes\\\": {\\\"hook_event\\\": \\\"pre_cap\\\", \\\"hook_match\\\": \\\"lookup\\\", \\\"hook_mode\\\": \\\"gate\\\", \\\"hook_handler_id\\\": \\\"sha256:...\\\"}}",
)

AUTONOMOUS: Final = OpSpec(
    op="AUTONOMOUS",
    name="Autonomous",
    category="coordination",
    description="Macro-op: a fused goal-directed plan/act/evaluate loop, not the general iteration mechanism",
    long_description="AUTONOMOUS is a macro-op — a single node that fuses an internal plan / act / evaluate loop against a goal prompt, implemented as a Rust loop inside the handler (not graph-level iteration). The node keeps calling the configured model until the goal is achieved or `max_iterations` is reached. It is independent of, and not a substitute for, the general in-graph iteration mechanism, which is splice-based (a fresh sub-DAG grafted into the live execution per turn/iteration via `splice_dag`/`rearm_session_turn`). Optional backend, model, system prompt, provider, and temperature attributes follow the same routing contract as the other LLM operations.",
    latency="high",
    fields=(FieldSpec(name="prompt", description="Goal or objective for the autonomous loop", required=True, ref_type=None), FieldSpec(name="max_iterations", description="Maximum number of plan / act / evaluate iterations before stopping", required=False, ref_type=None), FieldSpec(name="backend", description="Backend override for the autonomous loop", required=False, ref_type="backend"), FieldSpec(name="model", description="Model override for the autonomous loop", required=False, ref_type="model"), FieldSpec(name="provider", description="Provider override when backend routing is not used", required=False, ref_type=None), FieldSpec(name="system_prompt", description="System prompt applied to each model call in the loop", required=False, ref_type=None), FieldSpec(name="temperature", description="Sampling temperature for the loop's model calls", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"id\": 3, \"op\": \"AUTONOMOUS\", \"attributes\": {\"prompt\": \"Find the root cause and propose a fix\", \"max_iterations\": 6}}",
)

CHECKPOINT: Final = OpSpec(
    op="CHECKPOINT",
    name="Checkpoint",
    category="synchronization",
    description="Create a durable execution checkpoint and emit a manifest token",
    long_description="Serializes execution state at a barrier point and persists it under a stable checkpoint identifier. The snapshot captures AAM state plus runtime checkpoint metadata, and emits a manifest token containing the checkpoint id, timestamp, and byte size so downstream nodes can reference the saved state. Execution continues immediately after the snapshot — this is NOT a suspend point (use PAUSE when you need human-gated suspension).",
    latency="low",
    fields=(FieldSpec(name="checkpoint_id", description="Stable identifier for this checkpoint", required=True, ref_type=None), FieldSpec(name="scope", description="Snapshot scope: full (default) or local", required=False, ref_type=None), FieldSpec(name="storage", description="Storage backend: fs (default), memory, or custom", required=False, ref_type=None), FieldSpec(name="ttl_seconds", description="Time-to-live for the checkpoint in seconds", required=False, ref_type=None), FieldSpec(name="on_fail", description="Failure mode: halt (default) or continue", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=False,
    min_inputs=1,
    example_json="{\"id\": 4, \"op\": \"CHECKPOINT\", \"attributes\": {\"checkpoint_id\": \"before_analysis\"}}",
)

CONST_STR: Final = OpSpec(
    op="CONST_STR",
    name="ConstStr",
    category="internal",
    description="String constant (compiler internal for string literals)",
    long_description="Compiler-internal operation that produces a constant string value. Not available in the public AIS. The compiler generates CONST_STR nodes when lowering template strings to explicit dataflow.",
    latency="none",
    fields=(FieldSpec(name="value", description="The string constant value", required=True, ref_type=None),),
    produces_output=True,
    needs_submission=False,
    min_inputs=0,
    example_json=None,
)

YIELD: Final = OpSpec(
    op="YIELD",
    name="Yield",
    category="internal",
    description="Yield value from switch case region (terminates region)",
    long_description="Compiler-internal operation that terminates a switch case region and yields a value to the parent SWITCH node. Not available in the public AIS.",
    latency="none",
    fields=(FieldSpec(name="value", description="The value to yield from the region", required=True, ref_type=None),),
    produces_output=True,
    needs_submission=False,
    min_inputs=1,
    example_json=None,
)

ALL_OPERATIONS: Final[tuple[OpSpec, ...]] = (
    AGENT,
    QMEM,
    UMEM,
    ASK,
    THINK,
    REASON,
    PLAN,
    REFLECT,
    VERIFY,
    INV_CAP,
    EXC,
    PRINT,
    JUMP,
    BRANCH_ON_VALUE,
    RETURN,
    SWITCH,
    FLOW_CALL,
    WORKFLOW_SPAWN,
    CALL_SKILL,
    MERGE,
    FENCE,
    WAIT_ALL,
    TRY_CATCH,
    ERR,
    COMMUNICATE,
    HANDOFF,
    UPDATE_GOAL,
    PAUSE,
    RESUME,
    DELEGATE,
    NOP,
    IDENTITY,
    SPAWN_AGENT,
    REGISTER_CAPABILITY,
    REGISTER_HOOK,
    AUTONOMOUS,
    CHECKPOINT,
    CONST_STR,
    YIELD,
)

CATEGORY_METADATA: Final[str] = "metadata"
CATEGORY_MEMORY: Final[str] = "memory"
CATEGORY_REASONING: Final[str] = "reasoning"
CATEGORY_TOOLS: Final[str] = "tools"
CATEGORY_CONTROL_FLOW: Final[str] = "control_flow"
CATEGORY_SYNCHRONIZATION: Final[str] = "synchronization"
CATEGORY_ERROR_HANDLING: Final[str] = "error_handling"
CATEGORY_COMMUNICATION: Final[str] = "communication"
CATEGORY_COORDINATION: Final[str] = "coordination"
CATEGORY_IDENTITY: Final[str] = "identity"
CATEGORY_INTERNAL: Final[str] = "internal"

OP_AGENT: Final[str] = "AGENT"
OP_QMEM: Final[str] = "QMEM"
OP_UMEM: Final[str] = "UMEM"
OP_ASK: Final[str] = "ASK"
OP_THINK: Final[str] = "THINK"
OP_REASON: Final[str] = "REASON"
OP_PLAN: Final[str] = "PLAN"
OP_REFLECT: Final[str] = "REFLECT"
OP_VERIFY: Final[str] = "VERIFY"
OP_INV_CAP: Final[str] = "INV_CAP"
OP_EXC: Final[str] = "EXC"
OP_PRINT: Final[str] = "PRINT"
OP_JUMP: Final[str] = "JUMP"
OP_BRANCH_ON_VALUE: Final[str] = "BRANCH_ON_VALUE"
OP_RETURN: Final[str] = "RETURN"
OP_SWITCH: Final[str] = "SWITCH"
OP_FLOW_CALL: Final[str] = "FLOW_CALL"
OP_WORKFLOW_SPAWN: Final[str] = "WORKFLOW_SPAWN"
OP_CALL_SKILL: Final[str] = "CALL_SKILL"
OP_MERGE: Final[str] = "MERGE"
OP_FENCE: Final[str] = "FENCE"
OP_WAIT_ALL: Final[str] = "WAIT_ALL"
OP_TRY_CATCH: Final[str] = "TRY_CATCH"
OP_ERR: Final[str] = "ERR"
OP_COMMUNICATE: Final[str] = "COMMUNICATE"
OP_HANDOFF: Final[str] = "HANDOFF"
OP_UPDATE_GOAL: Final[str] = "UPDATE_GOAL"
OP_PAUSE: Final[str] = "PAUSE"
OP_RESUME: Final[str] = "RESUME"
OP_DELEGATE: Final[str] = "DELEGATE"
OP_NOP: Final[str] = "NOP"
OP_IDENTITY: Final[str] = "IDENTITY"
OP_SPAWN_AGENT: Final[str] = "SPAWN_AGENT"
OP_REGISTER_CAPABILITY: Final[str] = "REGISTER_CAPABILITY"
OP_REGISTER_HOOK: Final[str] = "REGISTER_HOOK"
OP_AUTONOMOUS: Final[str] = "AUTONOMOUS"
OP_CHECKPOINT: Final[str] = "CHECKPOINT"
OP_CONST_STR: Final[str] = "CONST_STR"
OP_YIELD: Final[str] = "YIELD"

LLM_OPS: Final[frozenset] = frozenset({"ASK", "THINK", "REASON", "PLAN", "REFLECT", "VERIFY"})
