# AUTO-GENERATED by compiler frontend; DO NOT EDIT.
_CODEGEN_HASH: str = "e2beffe4a6eb4a4a"
from dataclasses import dataclass
from typing import Final

@dataclass(frozen=True)
class FieldSpec:
    name: str
    description: str
    required: bool
    ref_type: str | None

@dataclass(frozen=True)
class OpSpec:
    op: str
    name: str
    category: str
    description: str
    long_description: str
    latency: str
    fields: tuple[FieldSpec, ...]
    produces_output: bool
    needs_submission: bool
    min_inputs: int
    example_json: str | None

MODEL_CALL: Final = OpSpec(
    op="model.call",
    name="ModelCall",
    category="semantic",
    description="Invoke an admitted model with explicit request and options",
    long_description="Portable runtime effect that invokes exactly one admitted model binding. Returns typed model output; operational evidence is recorded separately. Does not mutate context or execute tool loops.",
    latency="medium",
    fields=(FieldSpec(name="model_ref", description="Exact admitted model target reference", required=True, ref_type="model"), FieldSpec(name="request", description="Typed model request payload", required=True, ref_type=None), FieldSpec(name="options", description="Explicit model call options", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"node_id\":\"model_1\",\"op\":\"model.call\",\"operands\":{\"model_ref\":\"summarizer_model\",\"request\":{\"messages\":[]},\"options\":{\"temperature\":0.2}}}",
)

CAPABILITY_INVOKE: Final = OpSpec(
    op="capability.invoke",
    name="CapabilityInvoke",
    category="semantic",
    description="Invoke one admitted Capability through the authority/effect chokepoint",
    long_description="The only executable Capability chokepoint. Admission, grant validation, effect identity, retry, cancellation, and audit apply here.",
    latency="medium",
    fields=(FieldSpec(name="capability_ref", description="Exact admitted capability reference", required=True, ref_type="capability"), FieldSpec(name="arguments", description="Typed capability input payload", required=True, ref_type=None), FieldSpec(name="context_projection", description="Optional typed context projection for the capability call", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"node_id\":\"cap_1\",\"op\":\"capability.invoke\",\"operands\":{\"capability_ref\":\"search_docs\",\"arguments\":{\"query\":\"release checklist\"}}}",
)

PROGRAM_NEW: Final = OpSpec(
    op="program.new",
    name="ProgramNew",
    category="semantic",
    description="Create a stateful Program Instance from an exact Program reference",
    long_description="Records logical Program Instance creation against an exact imported ProgramRef and optional typed initial context.",
    latency="low",
    fields=(FieldSpec(name="program_ref", description="Exact imported program reference", required=True, ref_type="program reference"), FieldSpec(name="initial_context", description="Typed initial Program Context when the program requires construction", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"node_id\":\"new_1\",\"op\":\"program.new\",\"operands\":{\"program_ref\":\"specialist\",\"initial_context\":{\"domain\":\"security\"}}}",
)

PROGRAM_INVOKE: Final = OpSpec(
    op="program.invoke",
    name="ProgramInvoke",
    category="semantic",
    description="Invoke a ProgramRef one-shot or a ProgramInstanceRef statefully",
    long_description="Receiver union selects one-shot versus stateful semantics. The only caller-data operand is typed input `I`.",
    latency="medium",
    fields=(FieldSpec(name="receiver", description="ProgramRef or ProgramInstanceRef receiver union", required=True, ref_type=None), FieldSpec(name="input", description="Typed invocation input", required=True, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"node_id\":\"invoke_1\",\"op\":\"program.invoke\",\"operands\":{\"receiver\":{\"program_instance_ref\":\"specialist_inst\"},\"input\":{\"question\":\"status?\"}}}",
)

AWAIT_EVENT: Final = OpSpec(
    op="await.event",
    name="AwaitEvent",
    category="semantic",
    description="Suspend on a typed durable external event or approval signal",
    long_description="Parks the current Program Invocation until a typed EventRef terminal value is available. Does not commit an invocation boundary.",
    latency="high",
    fields=(FieldSpec(name="event_ref", description="Typed durable event reference", required=True, ref_type="event reference"), FieldSpec(name="timeout_ms", description="Optional await timeout in milliseconds", required=False, ref_type=None), FieldSpec(name="cancellation", description="Optional cancellation scope bound to the await occurrence", required=False, ref_type=None)),
    produces_output=True,
    needs_submission=True,
    min_inputs=0,
    example_json="{\"node_id\":\"await_1\",\"op\":\"await.event\",\"operands\":{\"event_ref\":\"approval_42\",\"timeout_ms\":300000}}",
)

ALL_OPERATIONS: Final[tuple[OpSpec, ...]] = (
    MODEL_CALL,
    CAPABILITY_INVOKE,
    PROGRAM_NEW,
    PROGRAM_INVOKE,
    AWAIT_EVENT,
)

CATEGORY_METADATA: Final[str] = "metadata"
CATEGORY_MEMORY: Final[str] = "memory"
CATEGORY_REASONING: Final[str] = "reasoning"
CATEGORY_TOOLS: Final[str] = "tools"
CATEGORY_CONTROL_FLOW: Final[str] = "control_flow"
CATEGORY_SYNCHRONIZATION: Final[str] = "synchronization"
CATEGORY_ERROR_HANDLING: Final[str] = "error_handling"
CATEGORY_COMMUNICATION: Final[str] = "communication"
CATEGORY_COORDINATION: Final[str] = "coordination"
CATEGORY_IDENTITY: Final[str] = "identity"
CATEGORY_INTERNAL: Final[str] = "internal"

OP_MODEL_CALL: Final[str] = "model.call"
OP_CAPABILITY_INVOKE: Final[str] = "capability.invoke"
OP_PROGRAM_NEW: Final[str] = "program.new"
OP_PROGRAM_INVOKE: Final[str] = "program.invoke"
OP_AWAIT_EVENT: Final[str] = "await.event"

LLM_OPS: Final[frozenset] = frozenset({})
