# AUTO-GENERATED by compiler frontend; DO NOT EDIT.
_CODEGEN_HASH: str = "d420066557e73b97"
from dataclasses import dataclass
from typing import Final

@dataclass(frozen=True)
class ProviderSpec:
    id: str
    protocol: str
    default_base_url: str | None
    requires_api_key: bool
    api_key_env_var: str | None
    aliases: tuple[str, ...]

OLLAMA: Final = ProviderSpec(
    id="ollama",
    protocol="ollama",
    default_base_url="http://localhost:11434",
    requires_api_key=False,
    api_key_env_var="OLLAMA_API_KEY",
    aliases=(),
)

OPENAI: Final = ProviderSpec(
    id="openai",
    protocol="openai",
    default_base_url=None,
    requires_api_key=True,
    api_key_env_var="OPENAI_API_KEY",
    aliases=(),
)

ANTHROPIC: Final = ProviderSpec(
    id="anthropic",
    protocol="anthropic",
    default_base_url=None,
    requires_api_key=True,
    api_key_env_var="ANTHROPIC_API_KEY",
    aliases=(),
)

GOOGLE: Final = ProviderSpec(
    id="google",
    protocol="google",
    default_base_url=None,
    requires_api_key=True,
    api_key_env_var="GOOGLE_API_KEY",
    aliases=("gemini",),
)

VLLM: Final = ProviderSpec(
    id="vllm",
    protocol="vllm",
    default_base_url="http://localhost:8916/v1",
    requires_api_key=False,
    api_key_env_var=None,
    aliases=("vllm-graph-aware",),
)

OPENROUTER: Final = ProviderSpec(
    id="openrouter",
    protocol="openai",
    default_base_url="https://openrouter.ai/api/v1",
    requires_api_key=True,
    api_key_env_var="OPENROUTER_API_KEY",
    aliases=(),
)

MOCK: Final = ProviderSpec(
    id="mock",
    protocol="mock",
    default_base_url=None,
    requires_api_key=False,
    api_key_env_var=None,
    aliases=(),
)

BUILTIN_PROVIDERS: Final[tuple[ProviderSpec, ...]] = (
    OLLAMA,
    OPENAI,
    ANTHROPIC,
    GOOGLE,
    VLLM,
    OPENROUTER,
    MOCK,
)

PROVIDER_PROTOCOLS: Final[tuple[str, ...]] = ("openai", "anthropic", "google", "ollama", "vllm", "mock")

REGISTERED_PROVIDERS: dict[str, ProviderSpec] = {}
for _p in BUILTIN_PROVIDERS:
    REGISTERED_PROVIDERS[_p.id] = _p
    for _a in _p.aliases:
        REGISTERED_PROVIDERS[_a] = _p

def resolve_provider(name: str) -> ProviderSpec:
    spec = REGISTERED_PROVIDERS.get(name.lower())
    if spec is None:
        valid = sorted({p.id for p in BUILTIN_PROVIDERS})
        raise ValueError(
            f"Unknown provider '{name}'. "
            f"Registered APXM providers: {', '.join(valid)}. "
            f"To add a custom provider, register it in apxm-core and apxm-backends first."
        )
    return spec

def list_providers() -> list[str]:
    return sorted({p.id for p in BUILTIN_PROVIDERS})
