//! Canonical closed AIS operation families.
//!
//! This module is the single source of truth for the five public semantic
//! operations and the compiler-emitted structural operations accepted by
//! `apxm.air.v1` and `apxm.frontend-graph.v1`.

use super::category::OperationCategory;
use serde::{Deserialize, Serialize};
use std::fmt;

/// The closed compiler-emitted structural AIS operation family.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum StructuralOpKind {
    #[serde(rename = "function")]
    Function,
    #[serde(rename = "region")]
    Region,
    #[serde(rename = "block")]
    Block,
    #[serde(rename = "value")]
    Value,
    #[serde(rename = "branch")]
    Branch,
    #[serde(rename = "switch")]
    Switch,
    #[serde(rename = "ais.loop")]
    Loop,
    #[serde(rename = "parallel_join")]
    ParallelJoin,
    #[serde(rename = "try")]
    Try,
    #[serde(rename = "throw")]
    Throw,
    #[serde(rename = "catch")]
    Catch,
    #[serde(rename = "return")]
    Return,
    #[serde(rename = "yield")]
    Yield,
}

impl StructuralOpKind {
    #[must_use]
    pub const fn wire(self) -> &'static str {
        match self {
            Self::Function => "function",
            Self::Region => "region",
            Self::Block => "block",
            Self::Value => "value",
            Self::Branch => "branch",
            Self::Switch => "switch",
            Self::Loop => "ais.loop",
            Self::ParallelJoin => "parallel_join",
            Self::Try => "try",
            Self::Throw => "throw",
            Self::Catch => "catch",
            Self::Return => "return",
            Self::Yield => "yield",
        }
    }

    #[must_use]
    pub const fn mlir_cpp_class(self) -> &'static str {
        match self {
            Self::Function => "StructuralFunctionOp",
            Self::Region => "StructuralRegionOp",
            Self::Block => "StructuralBlockOp",
            Self::Value => "StructuralValueOp",
            Self::Branch => "StructuralBranchOp",
            Self::Switch => "StructuralSwitchOp",
            Self::Loop => "LoopOp",
            Self::ParallelJoin => "StructuralParallelJoinOp",
            Self::Try => "StructuralTryOp",
            Self::Throw => "StructuralThrowOp",
            Self::Catch => "StructuralCatchOp",
            Self::Return => "StructuralReturnOp",
            Self::Yield => "StructuralYieldOp",
        }
    }

    #[must_use]
    pub const fn all() -> [Self; 13] {
        [
            Self::Function,
            Self::Region,
            Self::Block,
            Self::Value,
            Self::Branch,
            Self::Switch,
            Self::Loop,
            Self::ParallelJoin,
            Self::Try,
            Self::Throw,
            Self::Catch,
            Self::Return,
            Self::Yield,
        ]
    }
}

impl fmt::Display for StructuralOpKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.wire())
    }
}

impl std::str::FromStr for StructuralOpKind {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, String> {
        Self::all()
            .into_iter()
            .find(|kind| kind.wire() == value.trim())
            .ok_or_else(|| format!("Unknown structural AIS operation: '{value}'"))
    }
}

/// The five — and only five — public semantic AIS operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SemanticOpKind {
    #[serde(rename = "model.call")]
    ModelCall,
    #[serde(rename = "capability.invoke")]
    CapabilityInvoke,
    #[serde(rename = "program.new")]
    ProgramNew,
    #[serde(rename = "program.invoke")]
    ProgramInvoke,
    #[serde(rename = "await.event")]
    AwaitEvent,
}

impl SemanticOpKind {
    /// Canonical wire string identical to `apxm.air.v1` / FrontendGraph `op`.
    #[must_use]
    pub const fn wire(self) -> &'static str {
        match self {
            Self::ModelCall => "model.call",
            Self::CapabilityInvoke => "capability.invoke",
            Self::ProgramNew => "program.new",
            Self::ProgramInvoke => "program.invoke",
            Self::AwaitEvent => "await.event",
        }
    }

    /// C++ class generated by TableGen for this semantic operation.
    #[must_use]
    pub const fn mlir_cpp_class(self) -> &'static str {
        match self {
            Self::ModelCall => "ModelCallOp",
            Self::CapabilityInvoke => "CapabilityInvokeOp",
            Self::ProgramNew => "ProgramNewOp",
            Self::ProgramInvoke => "ProgramInvokeOp",
            Self::AwaitEvent => "AwaitEventOp",
        }
    }

    /// Stable artifact wire index for canonical semantic operations (0..=4).
    #[must_use]
    pub const fn wire_index(self) -> u32 {
        match self {
            Self::ModelCall => 0,
            Self::CapabilityInvoke => 1,
            Self::ProgramNew => 2,
            Self::ProgramInvoke => 3,
            Self::AwaitEvent => 4,
        }
    }

    /// Maps a wire-format operation kind index to a semantic operation.
    #[must_use]
    pub fn from_wire_index(index: u32) -> Option<Self> {
        WIRE_INDEXED_OPERATIONS
            .iter()
            .find_map(|(wire_index, op)| (*wire_index == index).then_some(*op))
    }

    /// Inverse of [`from_wire_index`].
    #[must_use]
    pub fn to_wire_index(self) -> Option<u32> {
        Some(self.wire_index())
    }

    /// All semantic operations in stable wire-index order.
    #[must_use]
    pub const fn all() -> [Self; 5] {
        [
            Self::ModelCall,
            Self::CapabilityInvoke,
            Self::ProgramNew,
            Self::ProgramInvoke,
            Self::AwaitEvent,
        ]
    }
}

impl fmt::Display for SemanticOpKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.wire())
    }
}

impl std::str::FromStr for SemanticOpKind {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, String> {
        match value.trim() {
            "model.call" => Ok(Self::ModelCall),
            "capability.invoke" => Ok(Self::CapabilityInvoke),
            "program.new" => Ok(Self::ProgramNew),
            "program.invoke" => Ok(Self::ProgramInvoke),
            "await.event" => Ok(Self::AwaitEvent),
            other => Err(format!("Unknown semantic AIS operation: '{other}'")),
        }
    }
}

/// Canonical semantic operation type exposed to generated consumers.
pub type AISOperationType = SemanticOpKind;

/// Canonical artifact wire operation table for semantic operations only.
pub const WIRE_INDEXED_OPERATIONS: &[(u32, SemanticOpKind)] = &[
    (0, SemanticOpKind::ModelCall),
    (1, SemanticOpKind::CapabilityInvoke),
    (2, SemanticOpKind::ProgramNew),
    (3, SemanticOpKind::ProgramInvoke),
    (4, SemanticOpKind::AwaitEvent),
];

/// Indicates that an operation field references an external resource.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ReferenceType {
    Profile,
    Backend,
    Model,
    Capability,
    ProgramRef,
    ProgramInstanceRef,
    EventRef,
}

impl ReferenceType {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Profile => "agent profile",
            Self::Backend => "backend",
            Self::Model => "model",
            Self::Capability => "capability",
            Self::ProgramRef => "program reference",
            Self::ProgramInstanceRef => "program instance reference",
            Self::EventRef => "event reference",
        }
    }

    pub const fn list_command(self) -> &'static str {
        match self {
            Self::Profile => "apxm agent list",
            Self::Backend | Self::Model => "apxm backend list",
            Self::Capability => "apxm tool list",
            Self::ProgramRef | Self::ProgramInstanceRef => "apxm program list",
            Self::EventRef => "apxm event list",
        }
    }

    pub const fn add_command(self) -> &'static str {
        match self {
            Self::Profile => "apxm agent add",
            Self::Backend => "apxm backend add",
            Self::Model => "apxm backend add-model",
            Self::Capability => "apxm tool add",
            Self::ProgramRef | Self::ProgramInstanceRef => "apxm program publish",
            Self::EventRef => "apxm event register",
        }
    }
}

/// MLIR emission configuration for code generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct MlirEmissionSpec {
    pub primary_attr: Option<&'static str>,
    pub context_style: ContextStyle,
    pub result_type: MlirResultType,
    pub positional_attrs: &'static [&'static str],
    pub keywords: &'static [&'static str],
    pub syntactic_keywords: &'static [(&'static str, &'static str)],
}

/// Context style for MLIR emission.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ContextStyle {
    Bracketed,
    Parenthesized,
    Direct,
    None,
}

/// MLIR result type for operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MlirResultType {
    Token,
    Handle,
    Void,
}

/// A field in an operation specification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct OperationField {
    pub name: &'static str,
    pub required: bool,
    pub description: &'static str,
    pub ref_type: Option<ReferenceType>,
}

impl OperationField {
    pub const fn required(name: &'static str, description: &'static str) -> Self {
        Self {
            name,
            required: true,
            description,
            ref_type: None,
        }
    }

    pub const fn optional(name: &'static str, description: &'static str) -> Self {
        Self {
            name,
            required: false,
            description,
            ref_type: None,
        }
    }

    pub const fn required_ref(
        name: &'static str,
        description: &'static str,
        ref_type: ReferenceType,
    ) -> Self {
        Self {
            name,
            required: true,
            description,
            ref_type: Some(ref_type),
        }
    }

    pub const fn optional_ref(
        name: &'static str,
        description: &'static str,
        ref_type: ReferenceType,
    ) -> Self {
        Self {
            name,
            required: false,
            description,
            ref_type: Some(ref_type),
        }
    }
}

/// Expected latency tier for scheduler critical-path analysis.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum OperationLatency {
    None,
    Low,
    Medium,
    High,
}

impl OperationLatency {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Low => "low",
            Self::Medium => "medium",
            Self::High => "high",
        }
    }
}

impl fmt::Display for OperationLatency {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Complete specification of one public semantic operation.
#[derive(Debug, Clone, Serialize)]
pub struct OperationSpec {
    pub op_type: SemanticOpKind,
    pub name: &'static str,
    pub category: OperationCategory,
    pub description: &'static str,
    pub long_description: &'static str,
    pub latency: OperationLatency,
    pub example_json: Option<&'static str>,
    pub fields: &'static [OperationField],
    pub needs_submission: bool,
    pub min_inputs: u32,
    pub produces_output: bool,
    pub emission: MlirEmissionSpec,
}

impl OperationSpec {
    pub fn get_field(&self, name: &str) -> Option<&OperationField> {
        self.fields.iter().find(|f| f.name == name)
    }

    pub fn required_fields(&self) -> impl Iterator<Item = &OperationField> {
        self.fields.iter().filter(|f| f.required)
    }
}

const EMISSION_TOKEN_DIRECT: MlirEmissionSpec = MlirEmissionSpec {
    primary_attr: None,
    context_style: ContextStyle::Direct,
    result_type: MlirResultType::Token,
    positional_attrs: &[],
    keywords: &[],
    syntactic_keywords: &[],
};

/// Canonical semantic operation catalogue — exactly five public operations.
pub static AIS_OPERATIONS: &[OperationSpec] = &[
    OperationSpec {
        op_type: SemanticOpKind::ModelCall,
        name: "ModelCall",
        category: OperationCategory::Semantic,
        description: "Invoke an admitted model with explicit request and options",
        long_description: "Portable runtime effect that invokes exactly one admitted model binding. \
            Returns typed model output; operational evidence is recorded separately. Does not mutate \
            context or execute tool loops.",
        latency: OperationLatency::Medium,
        example_json: Some(
            r#"{"node_id":"model_1","op":"model.call","operands":{"model_ref":"summarizer_model","request":{"messages":[]},"options":{"temperature":0.2}}}"#,
        ),
        fields: &[
            OperationField::required_ref(
                "model_ref",
                "Exact admitted model target reference",
                ReferenceType::Model,
            ),
            OperationField::required("request", "Typed model request payload"),
            OperationField::optional("options", "Explicit model call options"),
        ],
        needs_submission: true,
        min_inputs: 0,
        produces_output: true,
        emission: EMISSION_TOKEN_DIRECT,
    },
    OperationSpec {
        op_type: SemanticOpKind::CapabilityInvoke,
        name: "CapabilityInvoke",
        category: OperationCategory::Semantic,
        description: "Invoke one admitted Capability through the authority/effect chokepoint",
        long_description: "The only executable Capability chokepoint. Admission, grant validation, \
            effect identity, retry, cancellation, and audit apply here.",
        latency: OperationLatency::Medium,
        example_json: Some(
            r#"{"node_id":"cap_1","op":"capability.invoke","operands":{"capability_ref":"search_docs","arguments":{"query":"release checklist"}}}"#,
        ),
        fields: &[
            OperationField::required_ref(
                "capability_ref",
                "Exact admitted capability reference",
                ReferenceType::Capability,
            ),
            OperationField::required("arguments", "Typed capability input payload"),
            OperationField::optional(
                "context_projection",
                "Optional typed context projection for the capability call",
            ),
        ],
        needs_submission: true,
        min_inputs: 0,
        produces_output: true,
        emission: EMISSION_TOKEN_DIRECT,
    },
    OperationSpec {
        op_type: SemanticOpKind::ProgramNew,
        name: "ProgramNew",
        category: OperationCategory::Semantic,
        description: "Create a stateful Program Instance from an exact Program reference",
        long_description: "Records logical Program Instance creation against an exact imported \
            ProgramRef and optional typed initial context.",
        latency: OperationLatency::Low,
        example_json: Some(
            r#"{"node_id":"new_1","op":"program.new","operands":{"program_ref":"specialist","initial_context":{"domain":"security"}}}"#,
        ),
        fields: &[
            OperationField::required_ref(
                "program_ref",
                "Exact imported program reference",
                ReferenceType::ProgramRef,
            ),
            OperationField::optional(
                "initial_context",
                "Typed initial Program Context when the program requires construction",
            ),
        ],
        needs_submission: true,
        min_inputs: 0,
        produces_output: true,
        emission: EMISSION_TOKEN_DIRECT,
    },
    OperationSpec {
        op_type: SemanticOpKind::ProgramInvoke,
        name: "ProgramInvoke",
        category: OperationCategory::Semantic,
        description: "Invoke a ProgramRef one-shot or a ProgramInstanceRef statefully",
        long_description: "Receiver union selects one-shot versus stateful semantics. The only \
            caller-data operand is typed input `I`.",
        latency: OperationLatency::Medium,
        example_json: Some(
            r#"{"node_id":"invoke_1","op":"program.invoke","operands":{"receiver":{"program_instance_ref":"specialist_inst"},"input":{"question":"status?"}}}"#,
        ),
        fields: &[
            OperationField::required(
                "receiver",
                "ProgramRef or ProgramInstanceRef receiver union",
            ),
            OperationField::required("input", "Typed invocation input"),
        ],
        needs_submission: true,
        min_inputs: 0,
        produces_output: true,
        emission: EMISSION_TOKEN_DIRECT,
    },
    OperationSpec {
        op_type: SemanticOpKind::AwaitEvent,
        name: "AwaitEvent",
        category: OperationCategory::Semantic,
        description: "Suspend on a typed durable external event or approval signal",
        long_description: "Parks the current Program Invocation until a typed EventRef terminal \
            value is available. Does not commit an invocation boundary.",
        latency: OperationLatency::High,
        example_json: Some(
            r#"{"node_id":"await_1","op":"await.event","operands":{"event_ref":"approval_42","timeout_ms":300000}}"#,
        ),
        fields: &[
            OperationField::required_ref(
                "event_ref",
                "Typed durable event reference",
                ReferenceType::EventRef,
            ),
            OperationField::optional("timeout_ms", "Optional await timeout in milliseconds"),
            OperationField::optional(
                "cancellation",
                "Optional cancellation scope bound to the await occurrence",
            ),
        ],
        needs_submission: true,
        min_inputs: 0,
        produces_output: true,
        emission: EMISSION_TOKEN_DIRECT,
    },
];

/// Lookup one semantic operation specification.
#[must_use]
pub fn get_operation_spec(op: SemanticOpKind) -> Option<&'static OperationSpec> {
    AIS_OPERATIONS.iter().find(|spec| spec.op_type == op)
}

/// Iterate all semantic operation specifications.
pub fn get_all_operations() -> impl Iterator<Item = &'static OperationSpec> {
    AIS_OPERATIONS.iter()
}

#[cfg(test)]
mod absence_tests {
    use super::*;

    #[test]
    fn catalogue_reports_exactly_five_public_semantic_operations() {
        assert_eq!(AIS_OPERATIONS.len(), 5);
        assert_eq!(WIRE_INDEXED_OPERATIONS.len(), 5);
        assert_eq!(SemanticOpKind::all().len(), 5);
    }

    #[test]
    fn wire_indices_are_dense_zero_based() {
        let mut indices: Vec<u32> = WIRE_INDEXED_OPERATIONS
            .iter()
            .map(|(index, _)| *index)
            .collect();
        indices.sort_unstable();
        assert_eq!(indices, vec![0, 1, 2, 3, 4]);
    }

    #[test]
    fn no_retired_or_structural_escape_in_semantic_catalogue() {
        for spec in AIS_OPERATIONS {
            let wire = spec.op_type.wire();
            assert!(
                !wire.contains("nop")
                    && !wire.contains("branch")
                    && !wire.contains("loop")
                    && !wire.contains("yield")
                    && !wire.contains("return")
                    && !wire.contains("switch")
                    && !wire.contains("try")
                    && !wire.contains("checkpoint")
                    && wire != "agent",
                "semantic catalogue must not contain structural/retired escape: {wire}"
            );
        }
    }

    #[test]
    fn tablegen_attrs_are_canonical() {
        for spec in AIS_OPERATIONS {
            for field in spec.fields {
                if field.name.contains('.') {
                    panic!(
                        "semantic operand field names must be flat identifiers: {}",
                        field.name
                    );
                }
            }
        }
    }
}
