//! `op-spec.v1` catalog generation.
//!
//! Emits a canonical, machine-readable snapshot of every AIS operation
//! (name, category, arity/operand shape, docs, and whether it is a
//! "pseudo-op") derived directly from [`AIS_OPERATIONS`] and
//! [`WIRE_INDEXED_OPERATIONS`] — the same source of truth the compiler and
//! runtime dispatcher consume. Nothing here is hand-maintained; both files
//! this module renders are regenerated by `apxm codegen op-spec` and
//! diff-checked in CI (see `drift_gate` tests below and
//! `crates/tools/cli/src/commands/codegen.rs`).
//!
//! A "pseudo-op" is an `AISOperationType` with no entry in
//! [`WIRE_INDEXED_OPERATIONS`] — i.e. it never appears as a wire-format
//! artifact instruction. Today that's exactly `AGENT` (a metadata
//! declaration, not an executed instruction) and `YIELD` (resolved inline
//! while splicing a `SWITCH` case sub-DAG, never dispatched on its own).

use super::definitions::{AIS_OPERATIONS, AISOperationType, WIRE_INDEXED_OPERATIONS};
use serde::Serialize;

/// Schema version tag embedded in the catalog file.
pub const OP_SPEC_SCHEMA_VERSION: &str = "apxm.op-spec.v1";
/// Schema version tag embedded in the vectors/fixture file.
pub const OP_SPEC_VECTORS_SCHEMA_VERSION: &str = "apxm.op-spec-vectors.v1";

/// Filename for the catalog, relative to its output directory.
pub const OP_SPEC_CATALOG_FILE: &str = "op-spec.v1.json";
/// Filename for the vectors/fixture file, relative to its output directory.
pub const OP_SPEC_VECTORS_FILE: &str = "op-spec.vectors.v1.json";

fn wire_index_for(op: AISOperationType) -> Option<u32> {
    WIRE_INDEXED_OPERATIONS
        .iter()
        .find(|(_, candidate)| *candidate == op)
        .map(|(index, _)| *index)
}

#[derive(Serialize)]
struct OpSpecField {
    name: &'static str,
    required: bool,
    description: &'static str,
    ref_type: Option<&'static str>,
}

#[derive(Serialize)]
struct OpSpecEntry {
    /// Wire mnemonic / display name, e.g. "QMEM" (matches `Display` and the
    /// serialized `AISOperationType` tag).
    op: AISOperationType,
    /// Rust enum variant name, e.g. "QMem".
    rust_variant: &'static str,
    /// Human-readable name, e.g. "QueryMemory".
    name: &'static str,
    category: super::category::OperationCategory,
    description: &'static str,
    long_description: &'static str,
    latency: super::definitions::OperationLatency,
    /// Artifact wire-format operation-kind index. `None` for pseudo-ops.
    wire_index: Option<u32>,
    /// True when this op has no wire-format representation (see module docs).
    is_pseudo_op: bool,
    min_inputs: u32,
    produces_output: bool,
    needs_submission: bool,
    fields: Vec<OpSpecField>,
    example_json: Option<&'static str>,
}

#[derive(Serialize)]
struct OpSpecCatalog {
    schema_version: &'static str,
    generated_from: &'static str,
    total_operations: usize,
    pseudo_op_count: usize,
    operations: Vec<OpSpecEntry>,
}

fn build_entries() -> Vec<OpSpecEntry> {
    AIS_OPERATIONS
        .iter()
        .map(|spec| OpSpecEntry {
            op: spec.op_type,
            rust_variant: rust_variant_name(spec.op_type),
            name: spec.name,
            category: spec.category,
            description: spec.description,
            long_description: spec.long_description,
            latency: spec.latency,
            wire_index: wire_index_for(spec.op_type),
            is_pseudo_op: wire_index_for(spec.op_type).is_none(),
            min_inputs: spec.min_inputs,
            produces_output: spec.produces_output,
            needs_submission: spec.needs_submission,
            fields: spec
                .fields
                .iter()
                .map(|field| OpSpecField {
                    name: field.name,
                    required: field.required,
                    description: field.description,
                    ref_type: field.ref_type.map(|r| r.label()),
                })
                .collect(),
            example_json: spec.example_json,
        })
        .collect()
}

/// `{op:?}` gives the Rust variant name (e.g. "QMem") — the same helper
/// `artifact_wire.rs` uses for the C++ enum names.
fn rust_variant_name(op: AISOperationType) -> &'static str {
    // AISOperationType has no data, so `{:?}` is always the bare variant
    // name; `Box::leak` is unnecessary because we only need `'static`
    // string literals that already exist as such via a lookup table.
    match op {
        AISOperationType::Agent => "Agent",
        AISOperationType::QMem => "QMem",
        AISOperationType::UMem => "UMem",
        AISOperationType::Ask => "Ask",
        AISOperationType::Think => "Think",
        AISOperationType::Reason => "Reason",
        AISOperationType::Plan => "Plan",
        AISOperationType::Reflect => "Reflect",
        AISOperationType::Verify => "Verify",
        AISOperationType::InvCap => "InvCap",
        AISOperationType::Exc => "Exc",
        AISOperationType::Print => "Print",
        AISOperationType::Jump => "Jump",
        AISOperationType::BranchOnValue => "BranchOnValue",
        AISOperationType::Return => "Return",
        AISOperationType::Switch => "Switch",
        AISOperationType::FlowCall => "FlowCall",
        AISOperationType::WorkflowSpawn => "WorkflowSpawn",
        AISOperationType::Merge => "Merge",
        AISOperationType::Fence => "Fence",
        AISOperationType::WaitAll => "WaitAll",
        AISOperationType::TryCatch => "TryCatch",
        AISOperationType::Err => "Err",
        AISOperationType::Communicate => "Communicate",
        AISOperationType::Handoff => "Handoff",
        AISOperationType::UpdateGoal => "UpdateGoal",
        AISOperationType::Pause => "Pause",
        AISOperationType::Resume => "Resume",
        AISOperationType::Delegate => "Delegate",
        AISOperationType::Nop => "Nop",
        AISOperationType::Identity => "Identity",
        AISOperationType::SpawnAgent => "SpawnAgent",
        AISOperationType::RegisterCapability => "RegisterCapability",
        AISOperationType::RegisterHook => "RegisterHook",
        AISOperationType::Autonomous => "Autonomous",
        AISOperationType::Checkpoint => "Checkpoint",
        AISOperationType::ConstStr => "ConstStr",
        AISOperationType::Yield => "Yield",
    }
}

/// Render the `op-spec.v1` catalog as pretty-printed JSON (stable key order,
/// trailing newline). Pure function of [`AIS_OPERATIONS`] /
/// [`WIRE_INDEXED_OPERATIONS`] — regenerating it is always deterministic.
pub fn generate_op_spec_catalog() -> String {
    let entries = build_entries();
    let pseudo_op_count = entries.iter().filter(|e| e.is_pseudo_op).count();
    let catalog = OpSpecCatalog {
        schema_version: OP_SPEC_SCHEMA_VERSION,
        generated_from: "crates/machine/ais/src/operations/definitions.rs",
        total_operations: entries.len(),
        pseudo_op_count,
        operations: entries,
    };
    let mut json = serde_json::to_string_pretty(&catalog).expect("serialize op-spec catalog");
    json.push('\n');
    json
}

#[derive(Serialize)]
struct VectorFixture {
    op: AISOperationType,
    example_json: &'static str,
    bytes: usize,
}

#[derive(Serialize)]
struct OpSpecVectors {
    schema_version: &'static str,
    generated_from: &'static str,
    fixtures: Vec<VectorFixture>,
}

/// Render the `op-spec` vectors/fixture file: one entry per operation that
/// declares a minimal example (`OperationSpec::example_json`), in
/// declaration order. Ops without an example are intentionally omitted
/// rather than padded with a placeholder.
pub fn generate_op_spec_vectors() -> String {
    let fixtures: Vec<VectorFixture> = AIS_OPERATIONS
        .iter()
        .filter_map(|spec| {
            spec.example_json.map(|example| VectorFixture {
                op: spec.op_type,
                example_json: example,
                bytes: example.len(),
            })
        })
        .collect();
    let vectors = OpSpecVectors {
        schema_version: OP_SPEC_VECTORS_SCHEMA_VERSION,
        generated_from: "crates/machine/ais/src/operations/definitions.rs",
        fixtures,
    };
    let mut json = serde_json::to_string_pretty(&vectors).expect("serialize op-spec vectors");
    json.push('\n');
    json
}

/// Render both generated files as `(filename, content)` pairs, matching the
/// shape `crate::frontend::render_generated_python` uses in the CLI crate.
pub fn render_op_spec_files() -> [(&'static str, String); 2] {
    [
        (OP_SPEC_CATALOG_FILE, generate_op_spec_catalog()),
        (OP_SPEC_VECTORS_FILE, generate_op_spec_vectors()),
    ]
}

#[cfg(test)]
mod drift_gate {
    use super::*;
    use std::path::PathBuf;

    fn generated_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("generated")
    }

    /// Drift gate: the committed `op-spec.v1.json` / vectors file must
    /// always equal a fresh render of `AIS_OPERATIONS`. If `definitions.rs`
    /// changes (an op is added/removed/edited) without regenerating the
    /// catalog via `apxm codegen op-spec`, this test fails the build —
    /// exactly like `codegen frontend|typescript --check` does for the
    /// Python/TypeScript frontend bindings, but enforced unconditionally in
    /// `cargo test` since `apxm-ais` (unlike `apxm-cli`) is not excluded
    /// from CI.
    #[test]
    fn op_spec_catalog_matches_definitions() {
        let path = generated_dir().join(OP_SPEC_CATALOG_FILE);
        let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "missing committed op-spec catalog at {} ({e}); run `apxm codegen op-spec`",
                path.display()
            )
        });
        let fresh = generate_op_spec_catalog();
        assert_eq!(
            committed, fresh,
            "op-spec.v1.json is stale relative to AIS_OPERATIONS/WIRE_INDEXED_OPERATIONS \
             in definitions.rs — rerun `apxm codegen op-spec` and commit the result"
        );
    }

    #[test]
    fn op_spec_vectors_match_definitions() {
        let path = generated_dir().join(OP_SPEC_VECTORS_FILE);
        let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "missing committed op-spec vectors at {} ({e}); run `apxm codegen op-spec`",
                path.display()
            )
        });
        let fresh = generate_op_spec_vectors();
        assert_eq!(
            committed, fresh,
            "op-spec.vectors.v1.json is stale relative to AIS_OPERATIONS in definitions.rs — \
             rerun `apxm codegen op-spec` and commit the result"
        );
    }

    #[test]
    fn pseudo_ops_are_exactly_agent_and_yield() {
        // Ground-truth check for the "pseudo-op" concept this module
        // invents: any AISOperationType absent from WIRE_INDEXED_OPERATIONS.
        // Locks the definition down so a future op addition/removal is
        // forced to reconsider this list explicitly.
        let entries = build_entries();
        let mut pseudo: Vec<&'static str> = entries
            .iter()
            .filter(|e| e.is_pseudo_op)
            .map(|e| e.rust_variant)
            .collect();
        pseudo.sort_unstable();
        assert_eq!(pseudo, vec!["Agent", "Yield"]);
    }
}
