# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.
_CODEGEN_HASH: str = "9af8166c588881a8"
"""MLIR emission helpers for AIS operations."""
import json
from collections.abc import Callable
from typing import Any, Final

def _quote(s: str) -> str:
    escaped = s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t').replace('\r', '\\r')
    return f'"{escaped}"'


def _format_attr_value(v: Any) -> str:
    if v is None:
        return _quote("null")
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return f"{v} : i64"
    if isinstance(v, float):
        if v == int(v):
            return f"{v:.1f} : f64"
        return f"{v} : f64"
    if isinstance(v, str):
        return _quote(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_format_attr_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return _quote(json.dumps(v))
    return _quote(str(v))


def emit_agent(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for AGENT operation."""
    ctx = ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"ais.agent{primary}{syn_kw}{ctx}{kw_str}"


def emit_qmem(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for QMEM operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["query"]))}' if "query" in attrs else ""
    syn_kw = ""
    kw_parts = []
    if "memory_tier" in attrs and attrs["memory_tier"] is not None:
        kw_parts.append(f'memory_tier = {_format_attr_value(attrs["memory_tier"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.qmem{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_umem(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for UMEM operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["key"]))}' if "key" in attrs else ""
    syn_kw = ""
    kw_parts = []
    if "memory_tier" in attrs and attrs["memory_tier"] is not None:
        kw_parts.append(f'memory_tier = {_format_attr_value(attrs["memory_tier"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.umem{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_ask(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for ASK operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["template_str"]))}' if "template_str" in attrs else ""
    syn_kw = ""
    kw_parts = []
    if "temperature" in attrs and attrs["temperature"] is not None:
        kw_parts.append(f'temperature = {_format_attr_value(attrs["temperature"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "provider" in attrs and attrs["provider"] is not None:
        kw_parts.append(f'provider = {_format_attr_value(attrs["provider"])}')
    if "backend" in attrs and attrs["backend"] is not None:
        kw_parts.append(f'backend = {_format_attr_value(attrs["backend"])}')
    if "system_prompt" in attrs and attrs["system_prompt"] is not None:
        kw_parts.append(f'system_prompt = {_format_attr_value(attrs["system_prompt"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.ask{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_think(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for THINK operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["template_str"]))}' if "template_str" in attrs else ""
    syn_kw = ""
    kw_parts = []
    if "budget" in attrs and attrs["budget"] is not None:
        kw_parts.append(f'budget = {_format_attr_value(attrs["budget"])}')
    if "temperature" in attrs and attrs["temperature"] is not None:
        kw_parts.append(f'temperature = {_format_attr_value(attrs["temperature"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "provider" in attrs and attrs["provider"] is not None:
        kw_parts.append(f'provider = {_format_attr_value(attrs["provider"])}')
    if "backend" in attrs and attrs["backend"] is not None:
        kw_parts.append(f'backend = {_format_attr_value(attrs["backend"])}')
    if "system_prompt" in attrs and attrs["system_prompt"] is not None:
        kw_parts.append(f'system_prompt = {_format_attr_value(attrs["system_prompt"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.think{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_reason(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for REASON operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["template_str"]))}' if "template_str" in attrs else ""
    syn_kw = ""
    kw_parts = []
    if "temperature" in attrs and attrs["temperature"] is not None:
        kw_parts.append(f'temperature = {_format_attr_value(attrs["temperature"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "provider" in attrs and attrs["provider"] is not None:
        kw_parts.append(f'provider = {_format_attr_value(attrs["provider"])}')
    if "backend" in attrs and attrs["backend"] is not None:
        kw_parts.append(f'backend = {_format_attr_value(attrs["backend"])}')
    if "system_prompt" in attrs and attrs["system_prompt"] is not None:
        kw_parts.append(f'system_prompt = {_format_attr_value(attrs["system_prompt"])}')
    if "structured" in attrs and attrs["structured"] is not None:
        kw_parts.append(f'structured = {_format_attr_value(attrs["structured"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.reason{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_plan(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for PLAN operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["goal"]))}' if "goal" in attrs else ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.plan{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_reflect(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for REFLECT operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["trace_query"]))}' if "trace_query" in attrs else ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.reflect{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_verify(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for VERIFY operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.verify{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_inv_tool(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for INV_TOOL operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["capability"]))}' if "capability" in attrs else ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.inv_tool{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_exc(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for EXC operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["code"]))}' if "code" in attrs else ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.exc{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_print(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for PRINT operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["message"]))}' if "message" in attrs else ""
    syn_kw = ""
    kw_str = ""
    return f"ais.print{primary}{syn_kw}{ctx}{kw_str}"


def emit_jump(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for JUMP operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.jump{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_branch_on_value(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for BRANCH_ON_VALUE operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.branch_on_value{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_loop_start(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for LOOP_START operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.loop_start{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_loop_end(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for LOOP_END operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.loop_end{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_return(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for RETURN operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.return{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_switch(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for SWITCH operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.switch{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_flow_call(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for FLOW_CALL operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.flow_call{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_merge(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for MERGE operation."""
    ctx = f" {', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.merge{primary}{syn_kw}{ctx}{kw_str} -> !ais.token"


def emit_fence(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for FENCE operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.fence{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_wait_all(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for WAIT_ALL operation."""
    ctx = f" {', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.wait_all{primary}{syn_kw}{ctx}{kw_str} -> !ais.token"


def emit_try_catch(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for TRY_CATCH operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.try_catch{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_err(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for ERR operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.err{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_communicate(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for COMMUNICATE operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["message"]))}' if "message" in attrs else ""
    syn_parts = []
    if "recipient" in attrs and attrs["recipient"] is not None:
        syn_parts.append(f' to {_quote(str(attrs["recipient"]))}')
    syn_kw = "".join(syn_parts)
    kw_parts = []
    if "protocol" in attrs and attrs["protocol"] is not None:
        kw_parts.append(f'protocol = {_format_attr_value(attrs["protocol"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.communicate{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_update_goal(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for UPDATE_GOAL operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.update_goal{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_guard(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for GUARD operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.guard{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_claim(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for CLAIM operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.claim{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_pause(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for PAUSE operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.pause{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_resume(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for RESUME operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.resume{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_delegate(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for DELEGATE operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["task_spec"]))}' if "task_spec" in attrs else ""
    syn_parts = []
    if "target_agent" in attrs and attrs["target_agent"] is not None:
        syn_parts.append(f' to {_quote(str(attrs["target_agent"]))}')
    syn_kw = "".join(syn_parts)
    kw_str = ""
    return f"{ssa_name} = ais.delegate{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_negotiate(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for NEGOTIATE operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.negotiate{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_nop(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for NOP operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.nop{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_identity(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for IDENTITY operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.identity{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_spawn_agent(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for SPAWN_AGENT operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["agent_name"]))}' if "agent_name" in attrs else ""
    syn_kw = ""
    kw_parts = []
    if "profile" in attrs and attrs["profile"] is not None:
        kw_parts.append(f'profile = {_format_attr_value(attrs["profile"])}')
    if "mode" in attrs and attrs["mode"] is not None:
        kw_parts.append(f'mode = {_format_attr_value(attrs["mode"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "cwd" in attrs and attrs["cwd"] is not None:
        kw_parts.append(f'cwd = {_format_attr_value(attrs["cwd"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.spawn_agent{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_spawn_team(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for SPAWN_TEAM operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["team_name"]))}' if "team_name" in attrs else ""
    syn_kw = ""
    kw_parts = []
    if "cwd" in attrs and attrs["cwd"] is not None:
        kw_parts.append(f'cwd = {_format_attr_value(attrs["cwd"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.spawn_team{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_register_capability(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for REGISTER_CAPABILITY operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["capability_name"]))}' if "capability_name" in attrs else ""
    syn_kw = ""
    kw_parts = []
    if "description" in attrs and attrs["description"] is not None:
        kw_parts.append(f'description = {_format_attr_value(attrs["description"])}')
    if "parameters_schema" in attrs and attrs["parameters_schema"] is not None:
        kw_parts.append(f'parameters_schema = {_format_attr_value(attrs["parameters_schema"])}')
    if "python_handler_id" in attrs and attrs["python_handler_id"] is not None:
        kw_parts.append(f'python_handler_id = {_format_attr_value(attrs["python_handler_id"])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.register_capability{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_autonomous(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for AUTONOMOUS operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["region"]))}' if "region" in attrs else ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.autonomous{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_checkpoint(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for CHECKPOINT operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["checkpoint_id"]))}' if "checkpoint_id" in attrs else ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.checkpoint{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_const_str(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for CONST_STR operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["value"]))}' if "value" in attrs else ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.const_str{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_yield(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for YIELD operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.yield{primary}{syn_kw}{ctx}{kw_str} : !ais.token"


EMITTERS: dict[str, Callable] = {
    "AGENT": emit_agent,
    "QMEM": emit_qmem,
    "UMEM": emit_umem,
    "ASK": emit_ask,
    "THINK": emit_think,
    "REASON": emit_reason,
    "PLAN": emit_plan,
    "REFLECT": emit_reflect,
    "VERIFY": emit_verify,
    "INV_TOOL": emit_inv_tool,
    "EXC": emit_exc,
    "PRINT": emit_print,
    "JUMP": emit_jump,
    "BRANCH_ON_VALUE": emit_branch_on_value,
    "LOOP_START": emit_loop_start,
    "LOOP_END": emit_loop_end,
    "RETURN": emit_return,
    "SWITCH": emit_switch,
    "FLOW_CALL": emit_flow_call,
    "MERGE": emit_merge,
    "FENCE": emit_fence,
    "WAIT_ALL": emit_wait_all,
    "TRY_CATCH": emit_try_catch,
    "ERR": emit_err,
    "COMMUNICATE": emit_communicate,
    "UPDATE_GOAL": emit_update_goal,
    "GUARD": emit_guard,
    "CLAIM": emit_claim,
    "PAUSE": emit_pause,
    "RESUME": emit_resume,
    "DELEGATE": emit_delegate,
    "NEGOTIATE": emit_negotiate,
    "NOP": emit_nop,
    "IDENTITY": emit_identity,
    "SPAWN_AGENT": emit_spawn_agent,
    "SPAWN_TEAM": emit_spawn_team,
    "REGISTER_CAPABILITY": emit_register_capability,
    "AUTONOMOUS": emit_autonomous,
    "CHECKPOINT": emit_checkpoint,
    "CONST_STR": emit_const_str,
    "YIELD": emit_yield,
}

VOID_OPS: Final[frozenset] = frozenset({"AGENT", "PRINT", "JUMP", "BRANCH_ON_VALUE", "LOOP_START", "LOOP_END", "FENCE"})

TEMPLATE_ATTRS: Final[frozenset] = frozenset({"template_str", "prompt", "template", "value"})
