# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.
_CODEGEN_HASH: str = "41e491aea8f7a4c5"
"""MLIR emission helpers for AIS operations."""
import json
from collections.abc import Callable
from typing import Any, Final

def _quote(s: str) -> str:
    escaped = s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t').replace('\r', '\\r')
    return f'"{escaped}"'


def _format_attr_value(v: Any) -> str:
    if v is None:
        return _quote("null")
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return f"{v} : i64"
    if isinstance(v, float):
        if v == int(v):
            return f"{v:.1f} : f64"
        return f"{v} : f64"
    if isinstance(v, str):
        return _quote(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_format_attr_value(x) for x in v) + "]"
    if isinstance(v, dict):
        items = []
        for key in sorted(v.keys()):
            items.append(f'{str(key)} = {_format_attr_value(v[key])}')
        return "{" + ", ".join(items) + "}"
    return _quote(str(v))


def emit_agent(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for AGENT operation."""
    ctx = ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"ais.agent{primary}{positional}{syn_kw}{ctx}{kw_str}"


def emit_qmem(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for QMEM operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["query"]))}' if "query" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "memory_tier" in attrs and attrs["memory_tier"] is not None:
        kw_parts.append(f'memory_tier = {_format_attr_value(attrs["memory_tier"])}')
    for key in sorted(attrs.keys()):
        if key in {"memory_tier", "query"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.qmem{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_umem(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for UMEM operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["key"]))}' if "key" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "memory_tier" in attrs and attrs["memory_tier"] is not None:
        kw_parts.append(f'memory_tier = {_format_attr_value(attrs["memory_tier"])}')
    for key in sorted(attrs.keys()):
        if key in {"key", "memory_tier"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.umem{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_ask(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for ASK operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["template_str"]))}' if "template_str" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "temperature" in attrs and attrs["temperature"] is not None:
        kw_parts.append(f'temperature = {_format_attr_value(attrs["temperature"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "provider" in attrs and attrs["provider"] is not None:
        kw_parts.append(f'provider = {_format_attr_value(attrs["provider"])}')
    if "backend" in attrs and attrs["backend"] is not None:
        kw_parts.append(f'backend = {_format_attr_value(attrs["backend"])}')
    if "system_prompt" in attrs and attrs["system_prompt"] is not None:
        kw_parts.append(f'system_prompt = {_format_attr_value(attrs["system_prompt"])}')
    for key in sorted(attrs.keys()):
        if key in {"backend", "model", "provider", "system_prompt", "temperature", "template_str"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.ask{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_think(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for THINK operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["template_str"]))}' if "template_str" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "budget" in attrs and attrs["budget"] is not None:
        kw_parts.append(f'budget = {_format_attr_value(attrs["budget"])}')
    if "temperature" in attrs and attrs["temperature"] is not None:
        kw_parts.append(f'temperature = {_format_attr_value(attrs["temperature"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "provider" in attrs and attrs["provider"] is not None:
        kw_parts.append(f'provider = {_format_attr_value(attrs["provider"])}')
    if "backend" in attrs and attrs["backend"] is not None:
        kw_parts.append(f'backend = {_format_attr_value(attrs["backend"])}')
    if "system_prompt" in attrs and attrs["system_prompt"] is not None:
        kw_parts.append(f'system_prompt = {_format_attr_value(attrs["system_prompt"])}')
    for key in sorted(attrs.keys()):
        if key in {"backend", "budget", "model", "provider", "system_prompt", "temperature", "template_str"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.think{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_reason(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for REASON operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["template_str"]))}' if "template_str" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "temperature" in attrs and attrs["temperature"] is not None:
        kw_parts.append(f'temperature = {_format_attr_value(attrs["temperature"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "provider" in attrs and attrs["provider"] is not None:
        kw_parts.append(f'provider = {_format_attr_value(attrs["provider"])}')
    if "backend" in attrs and attrs["backend"] is not None:
        kw_parts.append(f'backend = {_format_attr_value(attrs["backend"])}')
    if "system_prompt" in attrs and attrs["system_prompt"] is not None:
        kw_parts.append(f'system_prompt = {_format_attr_value(attrs["system_prompt"])}')
    if "structured" in attrs and attrs["structured"] is not None:
        kw_parts.append(f'structured = {_format_attr_value(attrs["structured"])}')
    for key in sorted(attrs.keys()):
        if key in {"backend", "model", "provider", "structured", "system_prompt", "temperature", "template_str"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.reason{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_plan(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for PLAN operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["goal"]))}' if "goal" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    for key in sorted(attrs.keys()):
        if key in {"goal"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.plan{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_reflect(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for REFLECT operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["trace_query"]))}' if "trace_query" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    for key in sorted(attrs.keys()):
        if key in {"trace_query"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.reflect{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_verify(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for VERIFY operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.verify{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_inv_tool(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for INV_TOOL operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["capability"]))}' if "capability" in attrs else ""
    params_json = _quote(str(attrs.get("params_json", json.dumps({}))))
    positional = f" ({params_json})"
    syn_kw = ""
    kw_parts = []
    for key in sorted(attrs.keys()):
        if key in {"capability", "params_json"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.inv_tool{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_exc(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for EXC operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["code"]))}' if "code" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    for key in sorted(attrs.keys()):
        if key in {"code"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.exc{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_print(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for PRINT operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = f' {_quote(str(attrs["message"]))}' if "message" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    for key in sorted(attrs.keys()):
        if key in {"message"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"ais.print{primary}{positional}{syn_kw}{ctx}{kw_str}"


def emit_jump(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for JUMP operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.jump{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_branch_on_value(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for BRANCH_ON_VALUE operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.branch_on_value{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_loop_start(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for LOOP_START operation."""
    ctx = ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "max_iterations" in attrs and attrs["max_iterations"] is not None:
        kw_parts.append(f'max_iterations = {_format_attr_value(attrs["max_iterations"])}')
    if "label" in attrs and attrs["label"] is not None:
        kw_parts.append(f'label = {_format_attr_value(attrs["label"])}')
    for key in sorted(attrs.keys()):
        if key in {"label", "max_iterations"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.loop_start{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_loop_end(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for LOOP_END operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.loop_end{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_return(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for RETURN operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.return{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_switch(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for SWITCH operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.switch{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_flow_call(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for FLOW_CALL operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["agent_name"]))}' if "agent_name" in attrs else ""
    positional_parts = []
    if "flow_name" in attrs and attrs["flow_name"] is not None:
        positional_parts.append(f' {_quote(str(attrs["flow_name"]))}')
    positional = "".join(positional_parts)
    syn_kw = ""
    kw_parts = []
    if "args" in attrs and attrs["args"] is not None:
        kw_parts.append(f'args = {_format_attr_value(attrs["args"])}')
    if "input_names" in attrs and attrs["input_names"] is not None:
        kw_parts.append(f'input_names = {_format_attr_value(attrs["input_names"])}')
    for key in sorted(attrs.keys()):
        if key in {"agent_name", "args", "flow_name", "input_names"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.flow_call{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_workflow_spawn(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for WORKFLOW_SPAWN operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["target_kind"]))}' if "target_kind" in attrs else ""
    positional_parts = []
    if "target" in attrs and attrs["target"] is not None:
        positional_parts.append(f' {_quote(str(attrs["target"]))}')
    positional = "".join(positional_parts)
    syn_kw = ""
    kw_parts = []
    if "args" in attrs and attrs["args"] is not None:
        kw_parts.append(f'args = {_format_attr_value(attrs["args"])}')
    if "input_names" in attrs and attrs["input_names"] is not None:
        kw_parts.append(f'input_names = {_format_attr_value(attrs["input_names"])}')
    if "session_root" in attrs and attrs["session_root"] is not None:
        kw_parts.append(f'session_root = {_format_attr_value(attrs["session_root"])}')
    if "await_result" in attrs and attrs["await_result"] is not None:
        kw_parts.append(f'await_result = {_format_attr_value(attrs["await_result"])}')
    for key in sorted(attrs.keys()):
        if key in {"args", "await_result", "input_names", "session_root", "target", "target_kind"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.workflow_spawn{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_call_skill(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for CALL_SKILL operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["skill_id"]))}' if "skill_id" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "args" in attrs and attrs["args"] is not None:
        kw_parts.append(f'args = {_format_attr_value(attrs["args"])}')
    if "input_names" in attrs and attrs["input_names"] is not None:
        kw_parts.append(f'input_names = {_format_attr_value(attrs["input_names"])}')
    for key in sorted(attrs.keys()):
        if key in {"args", "input_names", "skill_id"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.call_skill{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_merge(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for MERGE operation."""
    ctx = f" {', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.merge{primary}{positional}{syn_kw}{ctx}{kw_str} -> !ais.token"


def emit_fence(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for FENCE operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.fence{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_wait_all(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for WAIT_ALL operation."""
    ctx = f" {', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.wait_all{primary}{positional}{syn_kw}{ctx}{kw_str} -> !ais.token"


def emit_try_catch(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for TRY_CATCH operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.try_catch{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_err(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for ERR operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.err{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_communicate(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for COMMUNICATE operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["message"]))}' if "message" in attrs else ""
    positional = ""
    syn_parts = []
    if "recipient" in attrs and attrs["recipient"] is not None:
        syn_parts.append(f' to {_quote(str(attrs["recipient"]))}')
    syn_kw = "".join(syn_parts)
    kw_parts = []
    if "protocol" in attrs and attrs["protocol"] is not None:
        kw_parts.append(f'protocol = {_format_attr_value(attrs["protocol"])}')
    for key in sorted(attrs.keys()):
        if key in {"message", "protocol", "recipient"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.communicate{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_handoff(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for HANDOFF operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["handoff_from"]))}' if "handoff_from" in attrs else ""
    positional = ""
    syn_parts = []
    if "handoff_to" in attrs and attrs["handoff_to"] is not None:
        syn_parts.append(f' to {_quote(str(attrs["handoff_to"]))}')
    syn_kw = "".join(syn_parts)
    kw_parts = []
    if "transfer_state" in attrs and attrs["transfer_state"] is not None:
        kw_parts.append(f'transfer_state = {_format_attr_value(attrs["transfer_state"])}')
    for key in sorted(attrs.keys()):
        if key in {"handoff_from", "handoff_to", "transfer_state"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.handoff{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_update_goal(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for UPDATE_GOAL operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.update_goal{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_guard(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for GUARD operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.guard{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_claim(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for CLAIM operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.claim{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_pause(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for PAUSE operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.pause{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_resume(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for RESUME operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.resume{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_delegate(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for DELEGATE operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["task_spec"]))}' if "task_spec" in attrs else ""
    positional = ""
    syn_parts = []
    if "target_agent" in attrs and attrs["target_agent"] is not None:
        syn_parts.append(f' to {_quote(str(attrs["target_agent"]))}')
    syn_kw = "".join(syn_parts)
    kw_parts = []
    for key in sorted(attrs.keys()):
        if key in {"target_agent", "task_spec"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.delegate{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_negotiate(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for NEGOTIATE operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["proposal"]))}' if "proposal" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "parties" in attrs and attrs["parties"] is not None:
        kw_parts.append(f'parties = {_format_attr_value(attrs["parties"])}')
    if "max_rounds" in attrs and attrs["max_rounds"] is not None:
        kw_parts.append(f'max_rounds = {_format_attr_value(attrs["max_rounds"])}')
    for key in sorted(attrs.keys()):
        if key in {"max_rounds", "parties", "proposal"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.negotiate{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_nop(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for NOP operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.nop{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_identity(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for IDENTITY operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.identity{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_spawn_agent(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for SPAWN_AGENT operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["agent_name"]))}' if "agent_name" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "profile" in attrs and attrs["profile"] is not None:
        kw_parts.append(f'profile = {_format_attr_value(attrs["profile"])}')
    if "agent_route" in attrs and attrs["agent_route"] is not None:
        kw_parts.append(f'agent_route = {_format_attr_value(attrs["agent_route"])}')
    if "required_capabilities" in attrs and attrs["required_capabilities"] is not None:
        kw_parts.append(f'required_capabilities = {_format_attr_value(attrs["required_capabilities"])}')
    if "preferred_profiles" in attrs and attrs["preferred_profiles"] is not None:
        kw_parts.append(f'preferred_profiles = {_format_attr_value(attrs["preferred_profiles"])}')
    if "mode" in attrs and attrs["mode"] is not None:
        kw_parts.append(f'mode = {_format_attr_value(attrs["mode"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "cwd" in attrs and attrs["cwd"] is not None:
        kw_parts.append(f'cwd = {_format_attr_value(attrs["cwd"])}')
    if "system_prompt" in attrs and attrs["system_prompt"] is not None:
        kw_parts.append(f'system_prompt = {_format_attr_value(attrs["system_prompt"])}')
    for key in sorted(attrs.keys()):
        if key in {"agent_name", "agent_route", "cwd", "mode", "model", "preferred_profiles", "profile", "required_capabilities", "system_prompt"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.spawn_agent{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_spawn_team(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for SPAWN_TEAM operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["team_name"]))}' if "team_name" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "cwd" in attrs and attrs["cwd"] is not None:
        kw_parts.append(f'cwd = {_format_attr_value(attrs["cwd"])}')
    for key in sorted(attrs.keys()):
        if key in {"cwd", "team_name"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.spawn_team{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_register_capability(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for REGISTER_CAPABILITY operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["capability_name"]))}' if "capability_name" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "description" in attrs and attrs["description"] is not None:
        kw_parts.append(f'description = {_format_attr_value(attrs["description"])}')
    if "parameters_schema" in attrs and attrs["parameters_schema"] is not None:
        kw_parts.append(f'parameters_schema = {_format_attr_value(attrs["parameters_schema"])}')
    if "python_handler_id" in attrs and attrs["python_handler_id"] is not None:
        kw_parts.append(f'python_handler_id = {_format_attr_value(attrs["python_handler_id"])}')
    for key in sorted(attrs.keys()):
        if key in {"capability_name", "description", "parameters_schema", "python_handler_id"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.register_capability{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_register_hook(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for REGISTER_HOOK operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["hook_event"]))}' if "hook_event" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "hook_match" in attrs and attrs["hook_match"] is not None:
        kw_parts.append(f'hook_match = {_format_attr_value(attrs["hook_match"])}')
    if "hook_mode" in attrs and attrs["hook_mode"] is not None:
        kw_parts.append(f'hook_mode = {_format_attr_value(attrs["hook_mode"])}')
    if "python_hook_handler_id" in attrs and attrs["python_hook_handler_id"] is not None:
        kw_parts.append(f'python_hook_handler_id = {_format_attr_value(attrs["python_hook_handler_id"])}')
    for key in sorted(attrs.keys()):
        if key in {"hook_event", "hook_match", "hook_mode", "python_hook_handler_id"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.register_hook{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_autonomous(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for AUTONOMOUS operation."""
    ctx = f" ({', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))})" if inputs else ""
    primary = f' {_quote(str(attrs["prompt"]))}' if "prompt" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    if "max_iterations" in attrs and attrs["max_iterations"] is not None:
        kw_parts.append(f'max_iterations = {_format_attr_value(attrs["max_iterations"])}')
    if "backend" in attrs and attrs["backend"] is not None:
        kw_parts.append(f'backend = {_format_attr_value(attrs["backend"])}')
    if "model" in attrs and attrs["model"] is not None:
        kw_parts.append(f'model = {_format_attr_value(attrs["model"])}')
    if "provider" in attrs and attrs["provider"] is not None:
        kw_parts.append(f'provider = {_format_attr_value(attrs["provider"])}')
    if "system_prompt" in attrs and attrs["system_prompt"] is not None:
        kw_parts.append(f'system_prompt = {_format_attr_value(attrs["system_prompt"])}')
    if "temperature" in attrs and attrs["temperature"] is not None:
        kw_parts.append(f'temperature = {_format_attr_value(attrs["temperature"])}')
    for key in sorted(attrs.keys()):
        if key in {"backend", "max_iterations", "model", "prompt", "provider", "system_prompt", "temperature"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.autonomous{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_checkpoint(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for CHECKPOINT operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["checkpoint_id"]))}' if "checkpoint_id" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    for key in sorted(attrs.keys()):
        if key in {"checkpoint_id"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.checkpoint{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_const_str(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for CONST_STR operation."""
    ctx = ""
    primary = f' {_quote(str(attrs["value"]))}' if "value" in attrs else ""
    positional = ""
    syn_kw = ""
    kw_parts = []
    for key in sorted(attrs.keys()):
        if key in {"value"} or attrs[key] is None:
            continue
        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')
    kw_str = f' {{{", ".join(kw_parts)}}}' if kw_parts else ""
    return f"{ssa_name} = ais.const_str{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


def emit_yield(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:
    """Emit MLIR for YIELD operation."""
    ctx = f" [{', '.join(inputs)} : {', '.join(['!ais.token'] * len(inputs))}]" if inputs else ""
    primary = ""
    positional = ""
    syn_kw = ""
    kw_str = ""
    return f"{ssa_name} = ais.yield{primary}{positional}{syn_kw}{ctx}{kw_str} : !ais.token"


EMITTERS: dict[str, Callable] = {
    "AGENT": emit_agent,
    "QMEM": emit_qmem,
    "UMEM": emit_umem,
    "ASK": emit_ask,
    "THINK": emit_think,
    "REASON": emit_reason,
    "PLAN": emit_plan,
    "REFLECT": emit_reflect,
    "VERIFY": emit_verify,
    "INV_TOOL": emit_inv_tool,
    "EXC": emit_exc,
    "PRINT": emit_print,
    "JUMP": emit_jump,
    "BRANCH_ON_VALUE": emit_branch_on_value,
    "LOOP_START": emit_loop_start,
    "LOOP_END": emit_loop_end,
    "RETURN": emit_return,
    "SWITCH": emit_switch,
    "FLOW_CALL": emit_flow_call,
    "WORKFLOW_SPAWN": emit_workflow_spawn,
    "CALL_SKILL": emit_call_skill,
    "MERGE": emit_merge,
    "FENCE": emit_fence,
    "WAIT_ALL": emit_wait_all,
    "TRY_CATCH": emit_try_catch,
    "ERR": emit_err,
    "COMMUNICATE": emit_communicate,
    "HANDOFF": emit_handoff,
    "UPDATE_GOAL": emit_update_goal,
    "GUARD": emit_guard,
    "CLAIM": emit_claim,
    "PAUSE": emit_pause,
    "RESUME": emit_resume,
    "DELEGATE": emit_delegate,
    "NEGOTIATE": emit_negotiate,
    "NOP": emit_nop,
    "IDENTITY": emit_identity,
    "SPAWN_AGENT": emit_spawn_agent,
    "SPAWN_TEAM": emit_spawn_team,
    "REGISTER_CAPABILITY": emit_register_capability,
    "REGISTER_HOOK": emit_register_hook,
    "AUTONOMOUS": emit_autonomous,
    "CHECKPOINT": emit_checkpoint,
    "CONST_STR": emit_const_str,
    "YIELD": emit_yield,
}

VOID_OPS: Final[frozenset] = frozenset({"AGENT", "PRINT", "JUMP", "BRANCH_ON_VALUE", "LOOP_START", "LOOP_END", "FENCE"})

TEMPLATE_ATTRS: Final[frozenset] = frozenset({"template_str", "prompt", "template", "message", "params_json", "task_spec", "proposal", "goal", "condition", "claim", "evidence", "trace_id", "discriminant", "recovery_template"})
