#!/usr/bin/env python3
"""release_notes.py — synthesize CHANGELOG [Unreleased] from git log.

Reads commits since the last semver tag, classifies them into
Keep-a-Changelog categories (Added/Changed/Fixed/Removed) using
commit-message prefix conventions (feat:/fix:/refactor:/etc.), and
emits a Markdown diff against the current `[Unreleased]` block in
CHANGELOG.md. Maintainer accept-as-is rate is the headline metric;
results are stored in `.apxm/evaluation/agentic/dogfood/<TS>/release-notes.json`.

Pure stdlib + git. No GPU, no APXM runtime dependency — runs locally on
any contributor machine.

Usage:
    python3 tools/devtools/release_notes.py [--since <ref>] [--out <path>]
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[2]
CHANGELOG_PATH = REPO_ROOT / "CHANGELOG.md"
MANIFEST_DIR = REPO_ROOT / ".apxm" / "evaluation" / "agentic" / "dogfood"

# Keep-a-Changelog section names → list of commit prefixes that route here.
# Order matters: first match wins. Ground-truth on prefix conventions
# from `git log` reveals the actual mix; the table here is the
# straightforward Conventional-Commits → Keep-a-Changelog mapping with
# project-specific additions (preregister:, hygiene:).
SECTION_FOR_PREFIX: list[tuple[str, list[str]]] = [
    ("Added", ["feat"]),
    ("Fixed", ["fix"]),
    ("Changed", ["refactor", "perf", "docs", "test", "preregister", "hygiene", "chore"]),
    ("Removed", ["remove", "revert"]),
]
PREFIX_RE = re.compile(r"^([a-z]+)(?:\([^)]*\))?:\s*(.+)$")


def _git(*args: str) -> str:
    """Run git from REPO_ROOT, return stripped stdout. Raises on
    non-zero exit so callers can fail fast on a broken repo."""
    proc = subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return proc.stdout.strip()


def _last_release_ref(explicit: str | None) -> str:
    """Return the ref to scan from. Prefers the most recent semver tag
    (vX.Y.Z) when --since is not given, falling back to the repo's
    first commit if no tag exists yet."""
    if explicit:
        return explicit
    try:
        tags = _git("tag", "--list", "--sort=-v:refname").splitlines()
    except subprocess.CalledProcessError:
        tags = []
    semver = re.compile(r"^v?\d+\.\d+\.\d+$")
    for t in tags:
        if semver.match(t):
            return t
    return _git("rev-list", "--max-parents=0", "HEAD")


def _classify(subject: str) -> tuple[str, str]:
    """Map a commit subject to a (section, cleaned-summary) pair."""
    match = PREFIX_RE.match(subject)
    if not match:
        return ("Changed", subject)
    prefix = match.group(1).lower()
    cleaned = match.group(2).rstrip(".")
    for section, prefixes in SECTION_FOR_PREFIX:
        if prefix in prefixes:
            return (section, cleaned)
    return ("Changed", subject)


def _commits_since(ref: str) -> list[tuple[str, str]]:
    """Return [(sha, subject)] for HEAD..ref exclusive of ref itself.
    Merge commits are skipped — they're noise in release-notes."""
    raw = _git(
        "log",
        f"{ref}..HEAD",
        "--no-merges",
        "--pretty=format:%h%x00%s",
    )
    if not raw:
        return []
    out: list[tuple[str, str]] = []
    for line in raw.splitlines():
        sha, _, subject = line.partition("\x00")
        if sha and subject:
            out.append((sha, subject))
    return out


def _render(sections: dict[str, list[tuple[str, str]]], ref: str) -> str:
    """Emit Markdown matching the project's CHANGELOG style."""
    lines: list[str] = []
    lines.append("## [Unreleased]")
    lines.append("")
    lines.append(f"> Draft synthesized 2026 from commits since `{ref}`.")
    lines.append(
        "> Generated by `tools/devtools/release_notes.py`; review for "
        "narrative accuracy before publishing — the classifier uses "
        "commit-prefix conventions, not deep semantic analysis."
    )
    lines.append("")
    keepachangelog_order = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]
    for section in keepachangelog_order:
        entries = sections.get(section, [])
        if not entries:
            continue
        lines.append(f"### {section}")
        for sha, summary in entries:
            lines.append(f"- {summary} (`{sha}`).")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _current_unreleased_block(text: str) -> str:
    """Extract the existing `## [Unreleased]` block (up to next H2)."""
    m = re.search(r"^## \[Unreleased\].*?(?=^## )", text, re.MULTILINE | re.DOTALL)
    return m.group(0).rstrip() if m else ""


def _write_manifest(
    *,
    timestamp: datetime,
    ref: str,
    commits: list[tuple[str, str]],
    draft_path: Path,
) -> Path:
    """Per-run manifest line for the dogfooding claim trail."""
    MANIFEST_DIR.mkdir(parents=True, exist_ok=True)
    run_dir = MANIFEST_DIR / timestamp.strftime("%Y%m%dT%H%M%SZ")
    run_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "command": "release-notes",
        "started_at": timestamp.isoformat(),
        "since_ref": ref,
        "commits_scanned": len(commits),
        "draft_path": str(draft_path.relative_to(REPO_ROOT)),
        "apxm_sha": _git("rev-parse", "HEAD"),
    }
    path = run_dir / "release-notes.json"
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return path


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--since",
        help="Git ref to scan commits from (exclusive). Defaults to the last vX.Y.Z tag.",
    )
    p.add_argument(
        "--out",
        type=Path,
        help=(
            "Write draft to this path. Defaults to stdout for review. "
            "Pass an existing CHANGELOG.md path to overwrite in place — "
            "the dogfooder reviews the resulting diff before committing."
        ),
    )
    p.add_argument(
        "--no-manifest",
        action="store_true",
        help="Skip writing the .apxm/evaluation/agentic/dogfood manifest. "
             "Use only for quick local previews.",
    )
    return p.parse_args()


def main() -> int:
    args = _parse_args()
    ref = _last_release_ref(args.since)
    commits = _commits_since(ref)
    if not commits:
        print(f"[release-notes] no commits since {ref}", file=sys.stderr)
        return 0

    sections: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for sha, subject in commits:
        section, cleaned = _classify(subject)
        sections[section].append((sha, cleaned))

    draft = _render(sections, ref)
    timestamp = datetime.now(timezone.utc)

    if args.out:
        args.out.write_text(draft, encoding="utf-8")
        draft_path = args.out.resolve()
        print(f"[release-notes] wrote draft to {draft_path}", file=sys.stderr)
    else:
        sys.stdout.write(draft)
        draft_path = MANIFEST_DIR / timestamp.strftime("%Y%m%dT%H%M%SZ") / "draft.md"
        draft_path.parent.mkdir(parents=True, exist_ok=True)
        draft_path.write_text(draft, encoding="utf-8")

    if not args.no_manifest:
        manifest_path = _write_manifest(
            timestamp=timestamp,
            ref=ref,
            commits=commits,
            draft_path=draft_path,
        )
        print(f"[release-notes] manifest: {manifest_path}", file=sys.stderr)

    print(
        f"[release-notes] scanned {len(commits)} commits since {ref} → "
        f"{sum(len(v) for v in sections.values())} entries",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
