#!/usr/bin/env python3
"""Generate the demo's local APXM config.

The three workflow files in `workflows/` reference symbolic route aliases
(`showcase`, `benchmark`) — never a hardcoded model id. This script discovers
the registered vLLM model at the given base URL and writes a generated
`config.toml` that maps both aliases onto that model. The result lives entirely
under the run directory so the demo never touches the user's global APXM
config.

Usage:
    python3 examples/python/demos/gemma4/scripts/run_demo.py \\
        --run-dir <path>/runs/<UTC>-three-cases \\
        --backend vllm-fork \\
        --model google/gemma-4-31B-it
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import URLError
from urllib.request import Request, urlopen


DEFAULT_BASE_URL = "http://127.0.0.1:8916/v1"
SHOWCASE_ALIAS = "showcase"
BENCHMARK_ALIAS = "benchmark"


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run-dir", required=True, type=Path, help="Run directory; generated/config.toml is written here.")
    parser.add_argument("--backend", required=True, help="Registered backend name to target (e.g. vllm-fork).")
    parser.add_argument("--model", required=True, help="Model id served at --base-url (e.g. google/gemma-4-31B-it).")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help=f"vLLM OpenAI-compatible URL (default: {DEFAULT_BASE_URL}).")
    parser.add_argument("--skip-probe", action="store_true", help="Do not probe --base-url for /v1/models.")
    return parser.parse_args(argv)


def _probe_models(base_url: str, timeout: float = 5.0) -> list[str]:
    url = base_url.rstrip("/") + "/models"
    try:
        with urlopen(Request(url, headers={"Accept": "application/json"}), timeout=timeout) as resp:
            payload = json.load(resp)
    except (URLError, TimeoutError, OSError) as exc:
        raise SystemExit(f"error: probe of {url} failed: {exc}") from exc
    return [entry["id"] for entry in payload.get("data", []) if isinstance(entry, dict) and "id" in entry]


def _verify_model(base_url: str, requested: str) -> None:
    served = _probe_models(base_url)
    if not served:
        raise SystemExit(f"error: {base_url}/models returned no models")
    if requested not in served:
        served_list = ", ".join(served)
        raise SystemExit(
            f"error: requested model '{requested}' not served at {base_url}.\n"
            f"  served: {served_list}"
        )


def _render_config(*, backend: str, model: str, base_url: str) -> str:
    timestamp = datetime.now(timezone.utc).isoformat()
    return textwrap.dedent(f"""\
        # Generated by examples/python/demos/gemma4/scripts/run_demo.py
        # Generated at: {timestamp}
        # Backend: {backend}    Model: {model}    Base URL: {base_url}
        #
        # Maps the demo's symbolic aliases ('showcase', 'benchmark') onto a
        # single registered vLLM model. Workflows under workflows/0N_*.py only
        # ever reference the alias.

        [backends.{backend}]
        type     = "vllm"
        endpoint = "{base_url}"

        [[backends.{backend}.aliases]]
        name = "{SHOWCASE_ALIAS}"
        id   = "{model}"

        [[backends.{backend}.aliases]]
        name = "{BENCHMARK_ALIAS}"
        id   = "{model}"
    """)


def main(argv: list[str]) -> int:
    args = _parse_args(argv)
    if not args.skip_probe:
        _verify_model(args.base_url, args.model)

    generated_dir = args.run_dir / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)
    config_path = generated_dir / "config.toml"
    config_path.write_text(_render_config(backend=args.backend, model=args.model, base_url=args.base_url))

    print(f"wrote {config_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
