use std::collections::hash_map::DefaultHasher;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::Path;

use anyhow::Result;

use apxm_core::constants::mlir::types as mlir_types;
use apxm_core::types::{
    WORKFLOW_SPAWN_PATH_TARGET_KINDS, WORKFLOW_TARGET_KIND_ARTIFACT_PATH,
    WORKFLOW_TARGET_KIND_GRAPH_PATH, WORKFLOW_TARGET_KIND_REGISTERED_FLOW,
    WORKFLOW_TARGET_KIND_WORKFLOW_PATH,
};

use super::registry::{
    FrontendAgentTemplate, FrontendConstant, FrontendEmissionSpec, FrontendModelSpec,
    agent_templates, builtin_models, builtin_providers, emission_specs, graph_attr_constants,
    graph_metadata_constants, operation_specs, provider_protocols, valid_param_types,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFrontendFiles {
    pub constants_py: String,
    pub operations_py: String,
    pub agents_py: String,
    pub emission_py: String,
    pub providers_py: String,
    pub models_py: String,
}

pub fn render_generated_files() -> GeneratedFrontendFiles {
    GeneratedFrontendFiles {
        constants_py: stamp_codegen_hash(&render_constants_module()),
        operations_py: stamp_codegen_hash(&render_operations_module()),
        agents_py: stamp_codegen_hash(&render_agents_module()),
        emission_py: stamp_codegen_hash(&render_emission_module()),
        providers_py: stamp_codegen_hash(&render_providers_module()),
        models_py: stamp_codegen_hash(&render_models_module()),
    }
}

pub fn render_generated_init() -> String {
    let mut buf = String::new();
    buf.push_str("\"\"\"Auto-generated APXM frontend bindings.\"\"\"\n\n");
    buf.push_str("from .agents import *\n");
    buf.push_str("from .constants import *\n");
    buf.push_str("from .emission import *\n");
    buf.push_str("from .models import *\n");
    buf.push_str("from .operations import *\n");
    buf.push_str("from .providers import *\n");
    buf
}

pub fn render_generated_python() -> Vec<(&'static str, String)> {
    let rendered = render_generated_files();
    vec![
        ("__init__.py", render_generated_init()),
        ("constants.py", rendered.constants_py),
        ("operations.py", rendered.operations_py),
        ("agents.py", rendered.agents_py),
        ("emission.py", rendered.emission_py),
        ("models.py", rendered.models_py),
        ("providers.py", rendered.providers_py),
    ]
}

pub fn write_generated_python(output_dir: impl AsRef<Path>) -> Result<()> {
    let output_dir = output_dir.as_ref();
    fs::create_dir_all(output_dir)?;

    for (filename, content) in render_generated_python() {
        fs::write(output_dir.join(filename), content)?;
    }

    Ok(())
}

fn render_constants_module() -> String {
    let mut buf = String::new();
    buf.push_str("# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.\n");
    buf.push_str("from typing import Final\n\n");

    buf.push_str("# Graph metadata keys\n");
    for item in graph_metadata_constants() {
        render_constant(&mut buf, &item);
    }

    buf.push_str("\n# Graph attribute keys\n");
    for item in graph_attr_constants() {
        render_constant(&mut buf, &item);
    }

    buf.push_str("\n# Workflow target kinds\n");
    buf.push_str(&format!(
        "WORKFLOW_TARGET_KIND_REGISTERED_FLOW: Final[str] = {}\n",
        py_string(WORKFLOW_TARGET_KIND_REGISTERED_FLOW)
    ));
    buf.push_str(&format!(
        "WORKFLOW_TARGET_KIND_GRAPH_PATH: Final[str] = {}\n",
        py_string(WORKFLOW_TARGET_KIND_GRAPH_PATH)
    ));
    buf.push_str(&format!(
        "WORKFLOW_TARGET_KIND_ARTIFACT_PATH: Final[str] = {}\n",
        py_string(WORKFLOW_TARGET_KIND_ARTIFACT_PATH)
    ));
    buf.push_str(&format!(
        "WORKFLOW_TARGET_KIND_WORKFLOW_PATH: Final[str] = {}\n",
        py_string(WORKFLOW_TARGET_KIND_WORKFLOW_PATH)
    ));
    let workflow_spawn_target_kinds = WORKFLOW_SPAWN_PATH_TARGET_KINDS
        .iter()
        .map(|kind| py_string(kind))
        .collect::<Vec<_>>()
        .join(", ");
    buf.push_str(&format!(
        "WORKFLOW_SPAWN_PATH_TARGET_KINDS: Final[tuple[str, ...]] = ({workflow_spawn_target_kinds})\n"
    ));

    // Valid parameter types
    let types = valid_param_types();
    let types_set = types
        .iter()
        .map(|t| py_string(t))
        .collect::<Vec<_>>()
        .join(", ");
    buf.push_str(&format!(
        "\nVALID_PARAM_TYPES: Final[frozenset[str]] = frozenset({{{types_set}}})\n"
    ));

    // Python type → APXM type mapping (derived from valid param types + Python aliases)
    let mut mapping_parts = Vec::new();
    for t in types {
        mapping_parts.push(format!("{}: {}", py_string(t), py_string(t)));
    }
    // Additional Python-specific aliases that map to APXM "json"
    mapping_parts.push(format!("{}: {}", py_string("dict"), py_string("json")));
    mapping_parts.push(format!("{}: {}", py_string("list"), py_string("json")));
    mapping_parts.push(format!("{}: {}", py_string("Any"), py_string("json")));
    buf.push_str(&format!(
        "PYTHON_TYPE_TO_APXM: Final[dict[str, str]] = {{{}}}\n",
        mapping_parts.join(", ")
    ));

    buf
}

fn render_operations_module() -> String {
    let mut buf = String::new();
    buf.push_str("# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.\n");
    buf.push_str("from dataclasses import dataclass\n");
    buf.push_str("from typing import Final\n\n");

    buf.push_str("@dataclass(frozen=True)\n");
    buf.push_str("class FieldSpec:\n");
    buf.push_str("    name: str\n");
    buf.push_str("    description: str\n");
    buf.push_str("    required: bool\n");
    buf.push_str("    ref_type: str | None\n\n");

    buf.push_str("@dataclass(frozen=True)\n");
    buf.push_str("class OpSpec:\n");
    buf.push_str("    op: str\n");
    buf.push_str("    name: str\n");
    buf.push_str("    category: str\n");
    buf.push_str("    description: str\n");
    buf.push_str("    long_description: str\n");
    buf.push_str("    latency: str\n");
    buf.push_str("    fields: tuple[FieldSpec, ...]\n");
    buf.push_str("    produces_output: bool\n");
    buf.push_str("    needs_submission: bool\n");
    buf.push_str("    min_inputs: int\n");
    buf.push_str("    example_json: str | None\n\n");

    let ops = operation_specs();
    for spec in &ops {
        let ident = py_identifier(&spec.op).to_ascii_uppercase();
        buf.push_str(&format!("{ident}: Final = OpSpec(\n"));
        buf.push_str(&format!("    op={},\n", py_string(&spec.op)));
        buf.push_str(&format!("    name={},\n", py_string(spec.name)));
        buf.push_str(&format!("    category={},\n", py_string(spec.category)));
        buf.push_str(&format!(
            "    description={},\n",
            py_string(spec.description)
        ));
        buf.push_str(&format!(
            "    long_description={},\n",
            py_string(spec.long_description)
        ));
        buf.push_str(&format!("    latency={},\n", py_string(spec.latency)));
        buf.push_str(&format!(
            "    fields={},\n",
            py_field_specs_tuple(&spec.fields)
        ));
        buf.push_str(&format!(
            "    produces_output={},\n",
            py_bool(spec.produces_output)
        ));
        buf.push_str(&format!(
            "    needs_submission={},\n",
            py_bool(spec.needs_submission)
        ));
        buf.push_str(&format!("    min_inputs={},\n", spec.min_inputs));
        buf.push_str(&format!(
            "    example_json={},\n",
            py_optional_string(spec.example_json)
        ));
        buf.push_str(")\n\n");
    }

    buf.push_str("ALL_OPERATIONS: Final[tuple[OpSpec, ...]] = (\n");
    for spec in &ops {
        let ident = py_identifier(&spec.op).to_ascii_uppercase();
        buf.push_str(&format!("    {ident},\n"));
    }
    buf.push_str(")\n\n");

    // Category constants
    let categories = [
        ("CATEGORY_METADATA", "metadata"),
        ("CATEGORY_MEMORY", "memory"),
        ("CATEGORY_REASONING", "reasoning"),
        ("CATEGORY_TOOLS", "tools"),
        ("CATEGORY_CONTROL_FLOW", "control_flow"),
        ("CATEGORY_SYNCHRONIZATION", "synchronization"),
        ("CATEGORY_ERROR_HANDLING", "error_handling"),
        ("CATEGORY_COMMUNICATION", "communication"),
        ("CATEGORY_COORDINATION", "coordination"),
        ("CATEGORY_IDENTITY", "identity"),
        ("CATEGORY_INTERNAL", "internal"),
    ];
    for (name, value) in &categories {
        buf.push_str(&format!("{name}: Final[str] = {}\n", py_string(value)));
    }

    // OP_* constants
    buf.push('\n');
    for spec in &ops {
        let const_name = format!("OP_{}", spec.op);
        buf.push_str(&format!(
            "{const_name}: Final[str] = {}\n",
            py_string(&spec.op)
        ));
    }

    // LLM_OPS — pre-computed from reasoning category
    let llm_ops: Vec<&str> = ops
        .iter()
        .filter(|s| s.category == "reasoning")
        .map(|s| s.op.as_str())
        .collect();
    buf.push_str(&format!(
        "\nLLM_OPS: Final[frozenset] = frozenset({{{}}})\n",
        llm_ops
            .iter()
            .map(|op| py_string(op))
            .collect::<Vec<_>>()
            .join(", "),
    ));

    buf
}

fn render_agents_module() -> String {
    let mut buf = String::new();
    buf.push_str("# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.\n");
    buf.push_str("from dataclasses import dataclass\n");
    buf.push_str("from typing import Final\n\n");
    buf.push_str("@dataclass(frozen=True)\n");
    buf.push_str("class AgentRef:\n");
    buf.push_str("    name: str\n");
    buf.push_str("    command: str\n");
    buf.push_str("    default_mode: str | None\n");
    buf.push_str("    default_model: str | None\n\n");

    let templates = agent_templates();
    for item in &templates {
        let ident = py_identifier(&item.name);
        render_agent_ref(&mut buf, &ident, item);
    }

    buf.push_str("ALL_AGENTS: Final[tuple[AgentRef, ...]] = (\n");
    for item in &templates {
        buf.push_str(&format!("    {},\n", py_identifier(&item.name)));
    }
    buf.push_str(")\n");
    buf
}

fn render_emission_module() -> String {
    let mut buf = String::new();
    buf.push_str("# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.\n");
    buf.push_str("\"\"\"MLIR emission helpers for AIS operations.\"\"\"\n");
    buf.push_str("import json\n");
    buf.push_str("from collections.abc import Callable\n");
    buf.push_str("from typing import Any, Final\n\n");

    buf.push_str("def _quote(s: str) -> str:\n");
    buf.push_str("    escaped = s.replace('\\\\', '\\\\\\\\').replace('\"', '\\\\\"').replace('\\n', '\\\\n').replace('\\t', '\\\\t').replace('\\r', '\\\\r')\n");
    buf.push_str("    return f'\"");
    buf.push_str("{escaped}");
    buf.push_str("\"'\n\n\n");

    // bool comes before int because bool is a subclass of int in Python.
    buf.push_str("def _format_attr_value(v: Any) -> str:\n");
    buf.push_str("    if v is None:\n");
    buf.push_str("        return _quote(\"null\")\n");
    buf.push_str("    if isinstance(v, bool):\n");
    buf.push_str("        return \"true\" if v else \"false\"\n");
    buf.push_str("    if isinstance(v, int):\n");
    buf.push_str("        return f\"{v} : i64\"\n");
    buf.push_str("    if isinstance(v, float):\n");
    buf.push_str("        if v == int(v):\n");
    buf.push_str("            return f\"{v:.1f} : f64\"\n");
    buf.push_str("        return f\"{v} : f64\"\n");
    buf.push_str("    if isinstance(v, str):\n");
    buf.push_str("        return _quote(v)\n");
    buf.push_str("    if isinstance(v, (list, tuple)):\n");
    buf.push_str("        return \"[\" + \", \".join(_format_attr_value(x) for x in v) + \"]\"\n");
    buf.push_str("    if isinstance(v, dict):\n");
    buf.push_str("        items = []\n");
    buf.push_str("        for key in sorted(v.keys()):\n");
    buf.push_str("            items.append(f'{str(key)} = {_format_attr_value(v[key])}')\n");
    buf.push_str("        return \"{\" + \", \".join(items) + \"}\"\n");
    buf.push_str("    return _quote(str(v))\n\n\n");

    let specs = emission_specs();
    for spec in &specs {
        render_emission_fn(&mut buf, spec);
    }

    // EMITTERS dispatch dict
    buf.push_str("EMITTERS: dict[str, Callable] = {\n");
    for spec in &specs {
        let fn_name = format!("emit_{}", spec.op.to_lowercase());
        buf.push_str(&format!("    {}: {},\n", py_string(&spec.op), fn_name));
    }
    buf.push_str("}\n");

    // VOID_OPS — operations that produce no output (produces_output == false)
    let ops = operation_specs();
    let void_ops: Vec<&str> = ops
        .iter()
        .filter(|s| !s.produces_output)
        .map(|s| s.op.as_str())
        .collect();
    buf.push_str(&format!(
        "\nVOID_OPS: Final[frozenset] = frozenset({{{}}})\n",
        void_ops
            .iter()
            .map(|op| py_string(op))
            .collect::<Vec<_>>()
            .join(", "),
    ));

    // TEMPLATE_ATTRS — attrs that can contain template placeholders
    buf.push_str("\nTEMPLATE_ATTRS: Final[frozenset] = frozenset({\"template_str\", \"prompt\", \"template\", \"value\"})\n");

    buf
}

fn render_emission_fn(buf: &mut String, spec: &FrontendEmissionSpec) {
    let fn_name = format!("emit_{}", spec.op.to_lowercase());

    // New signature: matches _emit_op() call convention
    buf.push_str(&format!(
        "def {}(ssa_name: str, attrs: dict[str, Any], inputs: list[str]) -> str:\n",
        fn_name
    ));
    buf.push_str(&format!(
        "    \"\"\"Emit MLIR for {} operation.\"\"\"\n",
        spec.op
    ));

    // Context formatting
    let delims = match spec.context_style.as_str() {
        "Bracketed" => Some(("[", "]")),
        "Parenthesized" => Some(("(", ")")),
        _ => None,
    };
    let is_direct = spec.context_style == "Direct";
    if is_direct {
        buf.push_str(&format!(
            "    ctx = f\" {{', '.join(inputs)}} : {{', '.join(['{}'] * len(inputs))}}\" if inputs else \"\"\n",
            mlir_types::TOKEN
        ));
    } else if let Some((open, close)) = delims {
        buf.push_str(&format!(
            "    ctx = f\" {open}{{', '.join(inputs)}} : {{', '.join(['{}'] * len(inputs))}}{close}\" if inputs else \"\"\n",
            mlir_types::TOKEN
        ));
    } else {
        buf.push_str("    ctx = \"\"\n");
    }

    if let Some(primary) = &spec.primary_attr {
        buf.push_str(&format!(
            "    primary = f' {{_quote(str(attrs[\"{}\"]))}}' if \"{}\" in attrs else \"\"\n",
            primary, primary
        ));
    } else {
        buf.push_str("    primary = \"\"\n");
    }

    if spec.positional_attrs.is_empty() {
        buf.push_str("    positional = \"\"\n");
    } else {
        buf.push_str("    positional_parts = []\n");
        for attr in &spec.positional_attrs {
            buf.push_str(&format!(
                "    if \"{}\" in attrs and attrs[\"{}\"] is not None:\n",
                attr, attr
            ));
            buf.push_str(&format!(
                "        positional_parts.append(f' {{_quote(str(attrs[\"{}\"]))}}')\n",
                attr
            ));
        }
        buf.push_str("    positional = \"\".join(positional_parts)\n");
    }

    if spec.syntactic_keywords.is_empty() {
        buf.push_str("    syn_kw = \"\"\n");
    } else {
        buf.push_str("    syn_parts = []\n");
        for (kw, attr) in &spec.syntactic_keywords {
            buf.push_str(&format!(
                "    if \"{}\" in attrs and attrs[\"{}\"] is not None:\n",
                attr, attr
            ));
            buf.push_str(&format!(
                "        syn_parts.append(f' {} {{_quote(str(attrs[\"{}\"]))}}')\n",
                kw, attr
            ));
        }
        buf.push_str("    syn_kw = \"\".join(syn_parts)\n");
    }

    if !spec.keywords.is_empty() || !spec.positional_attrs.is_empty() || spec.primary_attr.is_some()
    {
        buf.push_str("    kw_parts = []\n");
        for kw in &spec.keywords {
            buf.push_str(&format!(
                "    if \"{}\" in attrs and attrs[\"{}\"] is not None:\n",
                kw, kw
            ));
            buf.push_str(&format!(
                "        kw_parts.append(f'{} = {{_format_attr_value(attrs[\"{}\"])}}')\n",
                kw, kw
            ));
        }
        let mut consumed = spec.keywords.clone();
        consumed.extend(spec.positional_attrs.iter().cloned());
        if let Some(primary) = &spec.primary_attr {
            consumed.push(primary.clone());
        }
        for (_, attr) in &spec.syntactic_keywords {
            consumed.push(attr.clone());
        }
        consumed.sort();
        consumed.dedup();
        buf.push_str("    for key in sorted(attrs.keys()):\n");
        buf.push_str(&format!(
            "        if key in {{{}}} or attrs[key] is None:\n",
            consumed
                .iter()
                .map(|value| py_string(value))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        buf.push_str("            continue\n");
        buf.push_str("        kw_parts.append(f'{key} = {_format_attr_value(attrs[key])}')\n");
        buf.push_str("    kw_str = f' {{{\", \".join(kw_parts)}}}' if kw_parts else \"\"\n");
    } else {
        buf.push_str("    kw_str = \"\"\n");
    }

    if spec.result_type == "Void" {
        buf.push_str(&format!(
            "    return f\"ais.{}{{primary}}{{positional}}{{syn_kw}}{{ctx}}{{kw_str}}\"\n\n\n",
            spec.mlir_mnemonic
        ));
    } else {
        let type_str = match spec.result_type.as_str() {
            "Handle" => mlir_types::HANDLE,
            _ => mlir_types::TOKEN,
        };
        let sep = if is_direct { " ->" } else { " :" };
        buf.push_str(&format!(
            "    return f\"{{ssa_name}} = ais.{}{{primary}}{{positional}}{{syn_kw}}{{ctx}}{{kw_str}}{sep} {}\"\n\n\n",
            spec.mlir_mnemonic, type_str
        ));
    }
}

fn render_providers_module() -> String {
    let mut buf = String::new();
    buf.push_str("# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.\n");
    buf.push_str("from dataclasses import dataclass\n");
    buf.push_str("from typing import Final\n\n");

    buf.push_str("@dataclass(frozen=True)\n");
    buf.push_str("class ProviderSpec:\n");
    buf.push_str("    id: str\n");
    buf.push_str("    protocol: str\n");
    buf.push_str("    default_base_url: str | None\n");
    buf.push_str("    requires_api_key: bool\n");
    buf.push_str("    api_key_env_var: str | None\n");
    buf.push_str("    aliases: tuple[str, ...]\n\n");

    let providers = builtin_providers();
    for p in &providers {
        let ident = p.id.to_ascii_uppercase();
        buf.push_str(&format!("{ident}: Final = ProviderSpec(\n"));
        buf.push_str(&format!("    id={},\n", py_string(p.id)));
        buf.push_str(&format!("    protocol={},\n", py_string(p.protocol)));
        buf.push_str(&format!(
            "    default_base_url={},\n",
            py_optional_string(p.default_base_url)
        ));
        buf.push_str(&format!(
            "    requires_api_key={},\n",
            py_bool(p.requires_api_key)
        ));
        buf.push_str(&format!(
            "    api_key_env_var={},\n",
            py_optional_string(p.api_key_env_var)
        ));
        buf.push_str(&format!(
            "    aliases={},\n",
            py_static_str_tuple(p.aliases)
        ));
        buf.push_str(")\n\n");
    }

    buf.push_str("BUILTIN_PROVIDERS: Final[tuple[ProviderSpec, ...]] = (\n");
    for p in &providers {
        let ident = p.id.to_ascii_uppercase();
        buf.push_str(&format!("    {ident},\n"));
    }
    buf.push_str(")\n\n");

    let protocols = provider_protocols();
    buf.push_str(&format!(
        "PROVIDER_PROTOCOLS: Final[tuple[str, ...]] = {}\n",
        py_static_str_tuple(&protocols)
    ));

    // REGISTERED_PROVIDERS lookup dict (canonical name + aliases)
    buf.push_str("\nREGISTERED_PROVIDERS: dict[str, ProviderSpec] = {}\n");
    buf.push_str("for _p in BUILTIN_PROVIDERS:\n");
    buf.push_str("    REGISTERED_PROVIDERS[_p.id] = _p\n");
    buf.push_str("    for _a in _p.aliases:\n");
    buf.push_str("        REGISTERED_PROVIDERS[_a] = _p\n");
    buf.push_str("\n");

    // resolve_provider()
    buf.push_str("def resolve_provider(name: str) -> ProviderSpec:\n");
    buf.push_str("    spec = REGISTERED_PROVIDERS.get(name.lower())\n");
    buf.push_str("    if spec is None:\n");
    buf.push_str("        valid = sorted({p.id for p in BUILTIN_PROVIDERS})\n");
    buf.push_str("        raise ValueError(\n");
    buf.push_str("            f\"Unknown provider '{name}'. \"\n");
    buf.push_str("            f\"Registered APXM providers: {', '.join(valid)}. \"\n");
    buf.push_str("            f\"To add a custom provider, register it in apxm-core and apxm-backends first.\"\n");
    buf.push_str("        )\n");
    buf.push_str("    return spec\n\n");

    // list_providers()
    buf.push_str("def list_providers() -> list[str]:\n");
    buf.push_str("    return sorted({p.id for p in BUILTIN_PROVIDERS})\n");

    buf
}

fn render_models_module() -> String {
    let mut buf = String::new();
    buf.push_str("# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.\n");
    buf.push_str("from typing import Final\n\n\n");

    // ModelId class
    buf.push_str("class ModelId:\n");
    buf.push_str("    \"\"\"Typed model identifier.\"\"\"\n");
    buf.push_str("    __slots__ = (\"_value\",)\n\n");
    buf.push_str("    def __init__(self, value: str) -> None:\n");
    buf.push_str("        self._value = value\n\n");
    buf.push_str("    def __str__(self) -> str:\n");
    buf.push_str("        return self._value\n\n");
    buf.push_str("    def __repr__(self) -> str:\n");
    buf.push_str("        return f\"ModelId({self._value!r})\"\n\n");
    buf.push_str("    def __eq__(self, other: object) -> bool:\n");
    buf.push_str("        if isinstance(other, ModelId):\n");
    buf.push_str("            return self._value == other._value\n");
    buf.push_str("        if isinstance(other, str):\n");
    buf.push_str("            return self._value == other\n");
    buf.push_str("        return NotImplemented\n\n");
    buf.push_str("    def __hash__(self) -> int:\n");
    buf.push_str("        return hash(self._value)\n\n\n");

    // Group models by provider
    let models = builtin_models();
    let mut providers: Vec<&str> = models.iter().map(|m| m.provider).collect();
    providers.sort();
    providers.dedup();

    for provider in &providers {
        let class_name = provider_class_name(provider);
        buf.push_str(&format!("class {class_name}:\n"));

        let provider_models: Vec<&FrontendModelSpec> =
            models.iter().filter(|m| m.provider == *provider).collect();

        let mut default_const = None;
        for m in &provider_models {
            let const_name = to_model_constant(m.id);
            buf.push_str(&format!(
                "    {const_name}: Final[ModelId] = ModelId({id})\n",
                id = py_string(m.id)
            ));
            if m.is_default {
                default_const = Some(const_name.clone());
            }
        }

        if let Some(ref default) = default_const {
            buf.push_str(&format!("    DEFAULT: Final[ModelId] = {default}\n"));
        }

        buf.push_str("\n\n");
    }

    // ALL_MODELS tuple
    buf.push_str("ALL_MODELS: Final[tuple[ModelId, ...]] = (\n");
    for provider in &providers {
        let class_name = provider_class_name(provider);
        let provider_models: Vec<&FrontendModelSpec> =
            models.iter().filter(|m| m.provider == *provider).collect();
        for m in &provider_models {
            let const_name = to_model_constant(m.id);
            buf.push_str(&format!("    {class_name}.{const_name},\n"));
        }
    }
    buf.push_str(")\n");

    buf
}

/// Convert a model id to a Python constant name.
///
/// Rules:
/// - Replace `-` and `.` with `_`
/// - Strip date suffixes (e.g. `-20241022`, `-20240229`)
/// - Uppercase
fn to_model_constant(id: &str) -> String {
    // Hugging-Face style ids (`vendor/name`) get a richer transform so that
    // e.g. "Qwen/Qwen2.5-7B-Instruct" becomes "QWEN_2_5_7B".
    let has_vendor_prefix = id.contains('/');
    let after_slash = id.rsplit('/').next().unwrap_or(id);

    // Strip common suffix tokens (instruction-tuned variants).
    let trimmed_suffix = ["-Instruct", "-instruct", "-Chat", "-chat"]
        .iter()
        .fold(after_slash, |acc, suf| acc.strip_suffix(suf).unwrap_or(acc));

    // Strip trailing date suffixes like -20241022
    let stripped = if trimmed_suffix.len() > 9 {
        let suffix = &trimmed_suffix[trimmed_suffix.len() - 9..];
        if suffix.starts_with('-')
            && suffix[1..].chars().all(|c| c.is_ascii_digit())
            && suffix.len() == 9
        {
            &trimmed_suffix[..trimmed_suffix.len() - 9]
        } else {
            trimmed_suffix
        }
    } else {
        trimmed_suffix
    };

    // For HF-style ids, insert separator between a letter and a following
    // digit so "Qwen2.5" → "QWEN_2_5" and "Llama3.1" → "LLAMA_3_1".
    // Skipped for non-vendor ids to preserve names like "GPT_4O" and "O1_MINI".
    let spaced = if has_vendor_prefix {
        let mut buf = String::with_capacity(stripped.len() + 4);
        let mut prev: Option<char> = None;
        for ch in stripped.chars() {
            if let Some(p) = prev {
                if p.is_ascii_alphabetic() && ch.is_ascii_digit() {
                    buf.push('-');
                }
            }
            buf.push(ch);
            prev = Some(ch);
        }
        buf
    } else {
        stripped.to_string()
    };

    spaced.replace(['-', '.', '/'], "_").to_ascii_uppercase()
}

/// Map provider id to a Python class name.
fn provider_class_name(provider: &str) -> String {
    match provider {
        "openai" => "OpenAI".to_string(),
        _ => {
            let mut chars = provider.chars();
            match chars.next() {
                Some(first) => {
                    let mut name = first.to_uppercase().to_string();
                    name.extend(chars);
                    name
                }
                None => provider.to_string(),
            }
        }
    }
}

fn render_constant(buf: &mut String, item: &FrontendConstant) {
    buf.push_str(&format!(
        "{}: Final[str] = {}\n",
        item.name,
        py_string(item.value)
    ));
}

fn render_agent_ref(buf: &mut String, ident: &str, item: &FrontendAgentTemplate) {
    buf.push_str(&format!("{ident}: Final = AgentRef(\n"));
    buf.push_str(&format!("    name={},\n", py_string(&item.name)));
    buf.push_str(&format!("    command={},\n", py_string(&item.command)));
    buf.push_str(&format!(
        "    default_mode={},\n",
        py_optional_string(item.default_mode.as_deref())
    ));
    buf.push_str(&format!(
        "    default_model={},\n",
        py_optional_string(item.default_model.as_deref())
    ));
    buf.push_str(")\n\n");
}

fn py_identifier(value: &str) -> String {
    let mut result = String::new();

    for (idx, ch) in value.chars().enumerate() {
        let mapped = if ch.is_ascii_alphanumeric() || ch == '_' {
            ch
        } else {
            '_'
        };

        if idx == 0 && mapped.is_ascii_digit() {
            result.push('_');
        }

        result.push(mapped.to_ascii_lowercase());
    }

    if result.is_empty() {
        "_generated".to_string()
    } else {
        result
    }
}

fn py_optional_string(value: Option<&str>) -> String {
    match value {
        Some(value) => py_string(value),
        None => "None".to_string(),
    }
}

fn py_string(value: &str) -> String {
    serde_json::to_string(value).expect("python string literal")
}

fn py_static_str_tuple(values: &[&str]) -> String {
    match values.len() {
        0 => "()".to_string(),
        1 => format!("({},)", py_string(values[0])),
        _ => {
            let joined = values
                .iter()
                .map(|value| py_string(value))
                .collect::<Vec<_>>()
                .join(", ");
            format!("({joined})")
        }
    }
}

fn py_field_specs_tuple(fields: &[super::registry::FrontendFieldSpec]) -> String {
    if fields.is_empty() {
        return "()".to_string();
    }
    let mut parts = Vec::new();
    for f in fields {
        parts.push(format!(
            "FieldSpec(name={}, description={}, required={}, ref_type={})",
            py_string(f.name),
            py_string(f.description),
            py_bool(f.required),
            py_optional_string(f.ref_type),
        ));
    }
    if parts.len() == 1 {
        format!("({},)", parts[0])
    } else {
        format!("({})", parts.join(", "))
    }
}

fn py_bool(value: bool) -> &'static str {
    if value { "True" } else { "False" }
}

/// Compute a content hash and prepend it as a `_CODEGEN_HASH` constant.
///
/// The hash covers the body content (everything after the header), so any
/// manual edit to a generated file can be detected at import time.
fn stamp_codegen_hash(body: &str) -> String {
    let mut hasher = DefaultHasher::new();
    body.hash(&mut hasher);
    let hash = hasher.finish();
    format!(
        "# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.\n_CODEGEN_HASH: str = \"{:016x}\"\n{}",
        hash,
        // Strip the old header line if present so we don't duplicate
        body.strip_prefix("# AUTO-GENERATED by apxm-frontend; DO NOT EDIT.\n")
            .unwrap_or(body),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn constants_module_renders_model_constant() {
        let rendered = render_generated_files();
        assert!(
            rendered
                .constants_py
                .contains("MODEL: Final[str] = \"model\"")
        );
    }

    #[test]
    fn operations_module_renders_spawn_agent() {
        let rendered = render_generated_files();
        assert!(
            rendered
                .operations_py
                .contains("SPAWN_AGENT: Final = OpSpec(")
        );
        assert!(!rendered.operations_py.contains("produces_output=false"));
        assert!(!rendered.operations_py.contains("produces_output=true"));
    }

    #[test]
    fn agents_module_renders_claude() {
        let rendered = render_generated_files();
        assert!(rendered.agents_py.contains("claude: Final = AgentRef("));
    }

    #[test]
    fn providers_module_renders_openai() {
        let rendered = render_generated_files();
        assert!(
            rendered
                .providers_py
                .contains("OPENAI: Final = ProviderSpec(")
        );
        assert!(rendered.providers_py.contains("BUILTIN_PROVIDERS"));
        assert!(rendered.providers_py.contains("PROVIDER_PROTOCOLS"));
        assert!(rendered.providers_py.contains("REGISTERED_PROVIDERS"));
        assert!(rendered.providers_py.contains("def resolve_provider("));
        assert!(rendered.providers_py.contains("def list_providers("));
    }

    #[test]
    fn operations_module_renders_field_specs() {
        let rendered = render_generated_files();
        assert!(rendered.operations_py.contains("class FieldSpec:"));
        assert!(rendered.operations_py.contains("long_description="));
        assert!(rendered.operations_py.contains("latency="));
    }

    #[test]
    fn models_module_renders_provider_classes() {
        let rendered = render_generated_files();
        assert!(rendered.models_py.contains("class ModelId:"));
        assert!(rendered.models_py.contains("class Anthropic:"));
        assert!(rendered.models_py.contains("class OpenAI:"));
        assert!(rendered.models_py.contains("class Google:"));
        assert!(rendered.models_py.contains("ALL_MODELS"));
    }

    #[test]
    fn models_module_renders_defaults() {
        let rendered = render_generated_files();
        assert!(
            rendered
                .models_py
                .contains("CLAUDE_SONNET_4_5: Final[ModelId] = ModelId(\"claude-sonnet-4-5\")")
        );
        assert!(
            rendered
                .models_py
                .contains("DEFAULT: Final[ModelId] = CLAUDE_SONNET_4_6")
        );
    }

    #[test]
    fn emission_module_renders_emitters_dict() {
        let rendered = render_generated_files();
        assert!(
            rendered
                .emission_py
                .contains("EMITTERS: dict[str, Callable]")
        );
        assert!(rendered.emission_py.contains("VOID_OPS: Final[frozenset]"));
        assert!(
            rendered
                .emission_py
                .contains("TEMPLATE_ATTRS: Final[frozenset]")
        );
        // Check new function signature
        assert!(
            rendered
                .emission_py
                .contains("def emit_ask(ssa_name: str, attrs: dict[str, Any], inputs: list[str])")
        );
    }

    #[test]
    fn model_constant_naming() {
        assert_eq!(
            super::to_model_constant("claude-sonnet-4-5"),
            "CLAUDE_SONNET_4_5"
        );
        assert_eq!(super::to_model_constant("gpt-4o-mini"), "GPT_4O_MINI");
        assert_eq!(
            super::to_model_constant("gemini-2.5-flash"),
            "GEMINI_2_5_FLASH"
        );
        assert_eq!(super::to_model_constant("o1-mini"), "O1_MINI");
        assert_eq!(
            super::to_model_constant("claude-3-5-sonnet-20241022"),
            "CLAUDE_3_5_SONNET"
        );
        assert_eq!(super::to_model_constant("gpt-5.1"), "GPT_5_1");
        // Hugging-Face style ids used by vLLM.
        assert_eq!(
            super::to_model_constant("Qwen/Qwen2.5-7B-Instruct"),
            "QWEN_2_5_7B"
        );
        assert_eq!(
            super::to_model_constant("Qwen/Qwen2.5-14B-Instruct"),
            "QWEN_2_5_14B"
        );
        assert_eq!(
            super::to_model_constant("meta-llama/Llama-3.1-8B-Instruct"),
            "LLAMA_3_1_8B"
        );
        assert_eq!(
            super::to_model_constant("meta-llama/Llama-3.1-70B-Instruct"),
            "LLAMA_3_1_70B"
        );
    }

    #[test]
    fn models_module_renders_vllm_class() {
        let rendered = render_generated_files();
        assert!(rendered.models_py.contains("class Vllm:"));
        assert!(
            rendered
                .models_py
                .contains("QWEN_2_5_7B: Final[ModelId] = ModelId(\"Qwen/Qwen2.5-7B-Instruct\")")
        );
        assert!(rendered.models_py.contains("QWEN_2_5_14B: Final[ModelId]"));
        assert!(rendered.models_py.contains("LLAMA_3_1_8B: Final[ModelId]"));
        assert!(rendered.models_py.contains("LLAMA_3_1_70B: Final[ModelId]"));
        assert!(
            !rendered
                .models_py
                .contains("DEFAULT: Final[ModelId] = QWEN_2_5_7B")
        );
    }

    #[test]
    fn constants_module_renders_valid_param_types() {
        let rendered = render_generated_files();
        assert!(
            rendered
                .constants_py
                .contains("VALID_PARAM_TYPES: Final[frozenset[str]]")
        );
        assert!(
            rendered
                .constants_py
                .contains("PYTHON_TYPE_TO_APXM: Final[dict[str, str]]")
        );
        assert!(
            rendered
                .constants_py
                .contains("WORKFLOW_TARGET_KIND_GRAPH_PATH: Final[str] = \"graph_path\"")
        );
        assert!(
            rendered
                .constants_py
                .contains("WORKFLOW_SPAWN_PATH_TARGET_KINDS: Final[tuple[str, ...]]")
        );
    }
}
