//! SQLite-backed thread index (Codex pattern).
//!
//! The index is a derived view: every row can be regenerated by walking
//! the JSONL files via [`rebuild_index_from_disk`]. The JSONL is the
//! source of truth; the SQLite is the fast-lookup sidecar.

use std::path::Path;

use rusqlite::{Connection, OptionalExtension, params};
use walkdir::WalkDir;

use crate::line::{RolloutLine, RolloutPayload};
use crate::loader::load_rollout;
use crate::paths::RolloutPaths;

#[derive(Debug, thiserror::Error)]
pub enum IndexError {
    #[error("sqlite error: {0}")]
    Sqlite(#[from] rusqlite::Error),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadIndexEntry {
    pub thread_id: String,
    pub parent_thread_id: Option<String>,
    pub session_id: String,
    pub started_at: String,
    pub completed_at: Option<String>,
    pub status: String,
    pub agent_role: String,
    pub agent_code: Option<String>,
    pub file_path: String,
    pub line_count: i64,
    pub file_bytes: i64,
}

pub struct IndexDb {
    conn: Connection,
}

impl IndexDb {
    pub fn open(path: &Path) -> Result<Self, IndexError> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let conn = Connection::open(path)?;
        conn.execute_batch(SCHEMA_SQL)?;
        Ok(Self { conn })
    }

    /// Open or initialize a test-only in-memory db.
    pub fn open_in_memory() -> Result<Self, IndexError> {
        let conn = Connection::open_in_memory()?;
        conn.execute_batch(SCHEMA_SQL)?;
        Ok(Self { conn })
    }

    pub fn insert_or_update(&self, entry: &ThreadIndexEntry) -> Result<(), IndexError> {
        self.conn.execute(
            r#"INSERT INTO threads
               (thread_id, parent_thread_id, session_id, started_at, completed_at,
                status, agent_role, agent_code, file_path, line_count, file_bytes)
               VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
               ON CONFLICT(thread_id) DO UPDATE SET
                 parent_thread_id = excluded.parent_thread_id,
                 session_id = excluded.session_id,
                 started_at = excluded.started_at,
                 completed_at = excluded.completed_at,
                 status = excluded.status,
                 agent_role = excluded.agent_role,
                 agent_code = excluded.agent_code,
                 file_path = excluded.file_path,
                 line_count = excluded.line_count,
                 file_bytes = excluded.file_bytes"#,
            params![
                entry.thread_id,
                entry.parent_thread_id,
                entry.session_id,
                entry.started_at,
                entry.completed_at,
                entry.status,
                entry.agent_role,
                entry.agent_code,
                entry.file_path,
                entry.line_count,
                entry.file_bytes,
            ],
        )?;
        Ok(())
    }

    pub fn get(&self, thread_id: &str) -> Result<Option<ThreadIndexEntry>, IndexError> {
        Ok(self
            .conn
            .query_row(
                "SELECT thread_id, parent_thread_id, session_id, started_at, completed_at,
                        status, agent_role, agent_code, file_path, line_count, file_bytes
                 FROM threads WHERE thread_id = ?1",
                params![thread_id],
                row_to_entry,
            )
            .optional()?)
    }

    pub fn list_recent(&self, limit: usize) -> Result<Vec<ThreadIndexEntry>, IndexError> {
        let mut stmt = self.conn.prepare(
            "SELECT thread_id, parent_thread_id, session_id, started_at, completed_at,
                    status, agent_role, agent_code, file_path, line_count, file_bytes
             FROM threads ORDER BY started_at DESC LIMIT ?1",
        )?;
        let rows = stmt
            .query_map(params![limit as i64], row_to_entry)?
            .collect::<Result<Vec<_>, _>>()?;
        Ok(rows)
    }

    /// Threads whose rollout `status` is not `running`.
    ///
    /// Used by `POST /v1/runs/clear` so index-only runs (visible via the `GET /v1/runs`
    /// rollout-index fallback after restart) receive a run-history tombstone and disappear
    /// from the operator list.
    pub fn list_settled_threads(&self, limit: i64) -> Result<Vec<ThreadIndexEntry>, IndexError> {
        let mut stmt = self.conn.prepare(
            "SELECT thread_id, parent_thread_id, session_id, started_at, completed_at,
                    status, agent_role, agent_code, file_path, line_count, file_bytes
             FROM threads
            WHERE LOWER(status) != 'running'
            ORDER BY started_at DESC
            LIMIT ?1",
        )?;
        let rows = stmt
            .query_map(params![limit], row_to_entry)?
            .collect::<Result<Vec<_>, _>>()?;
        Ok(rows)
    }

    pub fn list_by_session(&self, session_id: &str) -> Result<Vec<ThreadIndexEntry>, IndexError> {
        let mut stmt = self.conn.prepare(
            "SELECT thread_id, parent_thread_id, session_id, started_at, completed_at,
                    status, agent_role, agent_code, file_path, line_count, file_bytes
             FROM threads WHERE session_id = ?1 ORDER BY started_at DESC",
        )?;
        let rows = stmt
            .query_map(params![session_id], row_to_entry)?
            .collect::<Result<Vec<_>, _>>()?;
        Ok(rows)
    }

    pub fn children_of(&self, parent_thread_id: &str) -> Result<Vec<ThreadIndexEntry>, IndexError> {
        let mut stmt = self.conn.prepare(
            "SELECT thread_id, parent_thread_id, session_id, started_at, completed_at,
                    status, agent_role, agent_code, file_path, line_count, file_bytes
             FROM threads WHERE parent_thread_id = ?1 ORDER BY started_at ASC",
        )?;
        let rows = stmt
            .query_map(params![parent_thread_id], row_to_entry)?
            .collect::<Result<Vec<_>, _>>()?;
        Ok(rows)
    }

    pub fn count(&self) -> Result<usize, IndexError> {
        let count: i64 = self
            .conn
            .query_row("SELECT COUNT(*) FROM threads", [], |row| row.get(0))?;
        Ok(count as usize)
    }
}

fn row_to_entry(row: &rusqlite::Row<'_>) -> rusqlite::Result<ThreadIndexEntry> {
    Ok(ThreadIndexEntry {
        thread_id: row.get(0)?,
        parent_thread_id: row.get(1)?,
        session_id: row.get(2)?,
        started_at: row.get(3)?,
        completed_at: row.get(4)?,
        status: row.get(5)?,
        agent_role: row.get(6)?,
        agent_code: row.get(7)?,
        file_path: row.get(8)?,
        line_count: row.get(9)?,
        file_bytes: row.get(10)?,
    })
}

const SCHEMA_SQL: &str = r#"
CREATE TABLE IF NOT EXISTS threads (
    thread_id        TEXT PRIMARY KEY,
    parent_thread_id TEXT,
    session_id       TEXT,
    started_at       TEXT,
    completed_at     TEXT,
    status           TEXT,
    agent_role       TEXT,
    agent_code       TEXT,
    file_path        TEXT,
    line_count       INTEGER,
    file_bytes       INTEGER
);
CREATE INDEX IF NOT EXISTS idx_threads_session ON threads(session_id);
CREATE INDEX IF NOT EXISTS idx_threads_parent  ON threads(parent_thread_id);
CREATE INDEX IF NOT EXISTS idx_threads_started ON threads(started_at);
"#;

/// Walk the rollouts tree and rebuild the SQLite index from scratch.
///
/// Reads only the first line of each `.jsonl` (the SessionMeta) to keep
/// rebuild bounded — listing 50k threads stays linear in file count, not
/// in line count.
pub async fn rebuild_index_from_disk(paths: &RolloutPaths) -> Result<usize, IndexError> {
    let db_path = paths.index_db_path();
    // Drop the existing db file when present so a half-rebuilt index can't
    // shadow the rebuild.
    if db_path.exists() {
        std::fs::remove_file(&db_path)?;
    }
    let db = IndexDb::open(&db_path)?;

    let root = paths.sessions_root().join("rollouts");
    if !root.exists() {
        return Ok(0);
    }
    let mut inserted = 0usize;
    for entry in WalkDir::new(&root).into_iter().filter_map(Result::ok) {
        let path = entry.path();
        if path.is_file()
            && path.extension().and_then(|s| s.to_str()) == Some("jsonl")
            && path
                .file_name()
                .and_then(|s| s.to_str())
                .is_some_and(|n| n.starts_with("rollout-") || n.starts_with("agent-"))
        {
            let (items, _) = match load_rollout(path).await {
                Ok(v) => v,
                Err(_) => continue,
            };
            let Some(first) = items.first() else { continue };
            let session_meta = match &first.payload {
                RolloutPayload::SessionMeta(m) => (**m).clone(),
                _ => continue,
            };
            let file_bytes = std::fs::metadata(path).map(|m| m.len() as i64).unwrap_or(0);
            db.insert_or_update(&ThreadIndexEntry {
                thread_id: session_meta.thread_id,
                parent_thread_id: session_meta.parent_thread_id,
                session_id: session_meta.session_id,
                started_at: session_meta.started_at,
                completed_at: None,
                status: "unknown".to_string(),
                agent_role: session_meta.agent_role,
                agent_code: session_meta.agent_code,
                file_path: path.to_string_lossy().into_owned(),
                line_count: items.len() as i64,
                file_bytes,
            })?;
            inserted += 1;
        }
    }
    Ok(inserted)
}

/// Helper to materialize a single index entry from a rollout file on disk.
/// Useful for the apxm-server sink to update the index after opening or
/// closing a recorder.
pub async fn index_entry_for_file(
    path: &Path,
    line: &RolloutLine,
    status: &str,
) -> Result<ThreadIndexEntry, IndexError> {
    let meta = match &line.payload {
        RolloutPayload::SessionMeta(m) => (**m).clone(),
        _ => {
            return Err(IndexError::Sqlite(rusqlite::Error::InvalidQuery));
        }
    };
    let file_bytes = std::fs::metadata(path).map(|m| m.len() as i64).unwrap_or(0);
    Ok(ThreadIndexEntry {
        thread_id: meta.thread_id,
        parent_thread_id: meta.parent_thread_id,
        session_id: meta.session_id,
        started_at: meta.started_at,
        completed_at: None,
        status: status.to_string(),
        agent_role: meta.agent_role,
        agent_code: meta.agent_code,
        file_path: path.to_string_lossy().into_owned(),
        line_count: 1,
        file_bytes,
    })
}
