//! Bound-tree contract record codegen: every `apxm.frontend-graph` `$defs`
//! object and discriminated union, projected into both authoring frontends
//! from the published schema itself.
//!
//! This is §4 item 1 of `docs/ideas/frontend-vocabulary-generation.md`: for
//! each `$defs` entry with `type: object`, `required`, `properties`, and
//! `additionalProperties: false`, emit one record type named for its `$defs`
//! key. A `$defs` entry that is instead a `oneOf` discriminated by a `const`
//! property (`ValueExpression`, `ControlPredicate`, `PredicateLiteral`) emits
//! a union of one record per branch. Enum- and const-typed fields resolve
//! through the same `FAMILIES` table `codegen_frontend_vocabulary` projects,
//! via `family_for_def_enum` / `family_for_discriminated_const`, so a set the
//! schema widens or narrows moves here without a second schema-path resolver.
//!
//! `PredicateLiteral`'s three-branch `oneOf` is the one place the schema does
//! not name its branches: unlike `ValueExpression` and `ControlPredicate`,
//! whose branches are all `$ref`s into named `$defs` entries, `PredicateLiteral`
//! states its branches as anonymous inline objects discriminated by
//! `scalar_type`. `BRANCH_NAMES` assigns `BooleanLiteral` / `StringLiteral` /
//! `IntegerLiteral` / `NullLiteral` — a naming convention this generator
//! invents, not one the contract states, because nothing else names them.
//!
//! `PermissionDecision` is a `$ref` target here (`CapabilityRequirement.requested_permission`)
//! but is not re-emitted: `codegen_permissions` already owns it as `Permission`,
//! and that generated type is imported rather than duplicated.
//!
//! This module implements §4 item 1 only. §4 item 2 (composing `BoundCall` /
//! `BoundControl` from these records) is hand-written in `_bound_tree.py` and
//! `bound-tree.ts`; §4 item 3 (`bound-tree.ts` itself) is hand-written; §6
//! (diagnostic-code wiring) is not implemented here. §5's serializers are
//! generated beside these types by `codegen_frontend_serializers`, which reads
//! `RECORDS`, `UNIONS`, and `fields_for` from here so one field list serves the
//! record type and its serializer.

use serde_json::Value;

use super::codegen_frontend_vocabulary::{
    family_for_def_enum, family_for_discriminated_const, schema,
};

pub const PYTHON_FRONTEND_RECORDS_FILE: &str = "frontend_records.py";
pub const TYPESCRIPT_FRONTEND_RECORDS_FILE: &str = "frontend-records.ts";

const PYTHON_HEADER: &str = "# AUTO-GENERATED by apxm codegen frontend-records; DO NOT EDIT.";
const TYPESCRIPT_HEADER: &str = "// AUTO-GENERATED by apxm codegen frontend-records; DO NOT EDIT.";

const IDENTIFIER_REF: &str = "apxm.contract-common.v1#/$defs/Identifier";
const DIGEST_REF: &str = "apxm.contract-common.v1#/$defs/Digest";
const PERMISSION_DECISION_REF: &str = "#/$defs/PermissionDecision";

/// Every `$defs` object record `apxm.frontend-graph` states, in schema order.
/// Excludes the three discriminated unions (`ValueExpression`,
/// `ControlPredicate`, `PredicateLiteral`, handled by `UNIONS`) and
/// `PermissionDecision` (owned by `codegen_permissions`).
pub(crate) const RECORDS: &[&str] = &[
    "ProgramDefinition",
    "ImportedProgramRef",
    "Declaration",
    "FunctionDef",
    "Parameter",
    "Value",
    "SsaExpression",
    "ContextExpression",
    "ProjectionExpression",
    "ObjectExpression",
    "ValueField",
    "ArrayExpression",
    "StringExpression",
    "IntegerExpression",
    "BooleanExpression",
    "NullExpression",
    "Block",
    "Region",
    "DataEdge",
    "CallIntent",
    "ControlIntent",
    "TruthyPredicate",
    "EqualsPredicate",
    "NotEqualsPredicate",
    "ContextEdge",
    "HookBinding",
    "CapabilityRequirement",
    "ModelRequirement",
    "SkillRequirement",
    "SkillEntrySource",
    "SkillInlineSource",
];

/// One discriminated union: the `$defs` key stating the `oneOf`, and each
/// branch either a `$ref` into a `$defs` entry already in `RECORDS`, or (for
/// `PredicateLiteral` only) an inline schema this generator names.
pub(crate) struct UnionDef {
    pub(crate) name: &'static str,
    pub(crate) branches: &'static [Branch],
}

pub(crate) enum Branch {
    /// A `oneOf` branch stated as `{ "$ref": "#/$defs/<name>" }`.
    Named(&'static str),
    /// A `oneOf` branch stated as an anonymous inline object, found at
    /// `oneOf[index]` and named by this generator (see module docs).
    Inline { name: &'static str, index: usize },
}

pub(crate) const UNIONS: &[UnionDef] = &[
    UnionDef {
        name: "ValueExpression",
        branches: &[
            Branch::Named("SsaExpression"),
            Branch::Named("ContextExpression"),
            Branch::Named("ProjectionExpression"),
            Branch::Named("ObjectExpression"),
            Branch::Named("ArrayExpression"),
            Branch::Named("StringExpression"),
            Branch::Named("IntegerExpression"),
            Branch::Named("BooleanExpression"),
            Branch::Named("NullExpression"),
        ],
    },
    UnionDef {
        name: "ControlPredicate",
        branches: &[
            Branch::Named("TruthyPredicate"),
            Branch::Named("EqualsPredicate"),
            Branch::Named("NotEqualsPredicate"),
        ],
    },
    UnionDef {
        name: "SkillInstructionSource",
        branches: &[
            Branch::Named("SkillEntrySource"),
            Branch::Named("SkillInlineSource"),
        ],
    },
    UnionDef {
        name: "PredicateLiteral",
        branches: &[
            Branch::Inline {
                name: "BooleanLiteral",
                index: 0,
            },
            Branch::Inline {
                name: "StringLiteral",
                index: 1,
            },
            Branch::Inline {
                name: "IntegerLiteral",
                index: 2,
            },
            Branch::Inline {
                name: "NullLiteral",
                index: 3,
            },
        ],
    },
];

/// The union a branch record's own `oneOf` discriminant resolves against.
/// `SsaExpression.kind`, for instance, is typed through the `ValueExpression`
/// union's `kind` discriminant, not through a (nonexistent) family keyed by
/// `SsaExpression` itself.
fn discriminant_owner(def: &str) -> &str {
    for union in UNIONS {
        for branch in union.branches {
            if let Branch::Named(name) = branch
                && *name == def
            {
                return union.name;
            }
        }
    }
    def
}

/// One record field's resolved type, independent of language.
pub(crate) enum FieldKind {
    Str,
    Int,
    Bool,
    StrTuple,
    /// A FrontendGraph vocabulary type this generator does not own —
    /// projected by `codegen_frontend_vocabulary` and imported here.
    Vocabulary(&'static str),
    /// `codegen_permissions`'s `Permission`, imported rather than re-emitted.
    Permission,
    /// A record or union this generator emits, referenced by name.
    Local(String),
    LocalTuple(String),
}

pub(crate) struct RecordField {
    pub(crate) name: String,
    pub(crate) kind: FieldKind,
    pub(crate) required: bool,
}

/// Resolve one property schema to a field type, per §4 item 1's literal rules.
fn field_kind(
    prop_schema: &Value,
    own_def: &str,
    discriminant_owner: &str,
    prop_name: &str,
) -> FieldKind {
    if let Some(reference) = prop_schema.get("$ref").and_then(Value::as_str) {
        if reference == IDENTIFIER_REF || reference == DIGEST_REF {
            return FieldKind::Str;
        }
        if reference == PERMISSION_DECISION_REF {
            return FieldKind::Permission;
        }
        if let Some(local) = reference.strip_prefix("#/$defs/") {
            if local == "PropertyPath" || local == "NonEmptyPropertyPath" {
                return FieldKind::StrTuple;
            }
            return FieldKind::Local(local.to_string());
        }
        panic!("frontend-records: unhandled $ref {reference} at {own_def}.{prop_name}");
    }
    if prop_schema.get("enum").is_some() {
        let family = family_for_def_enum(own_def, prop_name).unwrap_or_else(|| {
            panic!("frontend-records: no vocabulary family for {own_def}.{prop_name} enum")
        });
        return FieldKind::Vocabulary(family.type_name);
    }
    if let Some(constant) = prop_schema.get("const")
        && constant.is_string()
    {
        let family = family_for_discriminated_const(discriminant_owner, prop_name)
            .unwrap_or_else(|| {
                panic!(
                    "frontend-records: no vocabulary family for {discriminant_owner}.{prop_name} const"
                )
            });
        return FieldKind::Vocabulary(family.type_name);
    }
    match prop_schema.get("type").and_then(Value::as_str) {
        Some("integer") => FieldKind::Int,
        Some("boolean") => FieldKind::Bool,
        Some("string") => FieldKind::Str,
        Some("array") => {
            let items = &prop_schema["items"];
            match field_kind(items, own_def, discriminant_owner, prop_name) {
                FieldKind::Str => FieldKind::StrTuple,
                FieldKind::Local(name) => FieldKind::LocalTuple(name),
                _ => {
                    panic!("frontend-records: unhandled array item shape at {own_def}.{prop_name}")
                }
            }
        }
        other => {
            panic!("frontend-records: unhandled property shape {other:?} at {own_def}.{prop_name}")
        }
    }
}

/// Every field of one object schema (a `$defs` record or a `PredicateLiteral`
/// branch), required fields first in `required` order, then the rest in
/// schema-map (alphabetical) order.
pub(crate) fn fields_for(def_schema: &Value, own_def: &str) -> Vec<RecordField> {
    let owner = discriminant_owner(own_def);
    let required: Vec<String> = def_schema["required"]
        .as_array()
        .unwrap_or_else(|| panic!("{own_def}.required states an array"))
        .iter()
        .map(|value| {
            value
                .as_str()
                .unwrap_or_else(|| panic!("{own_def}.required member is a string"))
                .to_string()
        })
        .collect();
    let properties = def_schema["properties"]
        .as_object()
        .unwrap_or_else(|| panic!("{own_def}.properties states an object"));

    let mut fields = Vec::new();
    for name in &required {
        let prop_schema = properties
            .get(name)
            .unwrap_or_else(|| panic!("{own_def}.properties.{name} is required but absent"));
        fields.push(RecordField {
            name: name.clone(),
            kind: field_kind(prop_schema, own_def, owner, name),
            required: true,
        });
    }
    for (name, prop_schema) in properties {
        if required.contains(name) {
            continue;
        }
        fields.push(RecordField {
            name: name.clone(),
            kind: field_kind(prop_schema, own_def, owner, name),
            required: false,
        });
    }
    fields
}

fn py_type(kind: &FieldKind) -> String {
    match kind {
        FieldKind::Str => "str".to_string(),
        FieldKind::Int => "int".to_string(),
        FieldKind::Bool => "bool".to_string(),
        FieldKind::StrTuple => "tuple[str, ...]".to_string(),
        FieldKind::Vocabulary(name) => (*name).to_string(),
        FieldKind::Permission => "Permission".to_string(),
        FieldKind::Local(name) => name.clone(),
        FieldKind::LocalTuple(name) => format!("tuple[{name}, ...]"),
    }
}

fn ts_type(kind: &FieldKind) -> String {
    match kind {
        FieldKind::Str => "string".to_string(),
        FieldKind::Int => "number".to_string(),
        FieldKind::Bool => "boolean".to_string(),
        FieldKind::StrTuple => "readonly string[]".to_string(),
        FieldKind::Vocabulary(name) => (*name).to_string(),
        FieldKind::Permission => "Permission".to_string(),
        FieldKind::Local(name) => name.clone(),
        FieldKind::LocalTuple(name) => format!("readonly {name}[]"),
    }
}

fn render_py_record(name: &str, fields: &[RecordField]) -> String {
    let mut buf = format!(
        "\n@dataclass(frozen=True, slots=True)\nclass {name}:\n    \"\"\"One `{name}` record from the apxm.frontend-graph contract.\"\"\"\n\n"
    );
    for field in fields {
        if field.required {
            buf.push_str(&format!("    {}: {}\n", field.name, py_type(&field.kind)));
        } else {
            buf.push_str(&format!(
                "    {}: Optional[{}] = None\n",
                field.name,
                py_type(&field.kind)
            ));
        }
    }
    buf
}

fn render_ts_record(name: &str, fields: &[RecordField]) -> String {
    let mut buf = format!("\nexport type {name} = {{\n");
    for field in fields {
        if field.required {
            buf.push_str(&format!(
                "  readonly {}: {};\n",
                field.name,
                ts_type(&field.kind)
            ));
        } else {
            buf.push_str(&format!(
                "  readonly {}?: {};\n",
                field.name,
                ts_type(&field.kind)
            ));
        }
    }
    buf.push_str("};\n");
    buf
}

/// Every vocabulary family name and whether `Permission` is used, across every
/// record and inline branch this generator emits — the import list for both
/// languages.
fn used_imports(schema: &Value) -> (Vec<&'static str>, bool) {
    let mut families: Vec<&'static str> = Vec::new();
    let mut uses_permission = false;
    let note =
        |kind: &FieldKind, families: &mut Vec<&'static str>, uses_permission: &mut bool| match kind
        {
            FieldKind::Vocabulary(name) => {
                if !families.contains(name) {
                    families.push(name);
                }
            }
            FieldKind::Permission => *uses_permission = true,
            _ => {}
        };
    for record in RECORDS.iter().copied() {
        let def_schema = &schema["$defs"][record];
        for field in fields_for(def_schema, record) {
            note(&field.kind, &mut families, &mut uses_permission);
        }
    }
    for branch_schema in predicate_literal_branch_schemas(schema) {
        for field in fields_for(&branch_schema, "PredicateLiteral") {
            note(&field.kind, &mut families, &mut uses_permission);
        }
    }
    (families, uses_permission)
}

fn predicate_literal_branch_schemas(schema: &Value) -> Vec<Value> {
    schema["$defs"]["PredicateLiteral"]["oneOf"]
        .as_array()
        .expect("$defs.PredicateLiteral.oneOf states an array")
        .clone()
}

pub fn render_frontend_records_python() -> String {
    let schema = schema();
    let (families, uses_permission) = used_imports(&schema);

    let mut buf = String::new();
    buf.push_str(PYTHON_HEADER);
    buf.push_str(
        "\n\"\"\"The apxm.frontend-graph contract records, generated one per $defs entry.\n\n\
         Each record's fields, required-ness, and enum/union typing are projected from\n\
         the schema at generation time: a field the contract adds, narrows, or drops\n\
         moves here on the next regeneration rather than needing a hand edit. These are\n\
         the wire records the contract states exactly — no authoring-time extra (a source\n\
         span, an operand's consumer slot) lives here. `_bound_tree.BoundCall` and\n\
         `_bound_tree.BoundControl` carry one of these plus those extras; every other\n\
         bound-tree record is one of these directly.\n\"\"\"\n\n\
         from __future__ import annotations\n\n\
         from dataclasses import dataclass\n\
         from typing import Optional, TypeAlias, Union\n",
    );

    if !families.is_empty() {
        buf.push_str(&format!("\nfrom .frontend_graph import (\n{}\n)\n", {
            let mut sorted = families.clone();
            sorted.sort_unstable();
            sorted
                .iter()
                .map(|name| format!("    {name},"))
                .collect::<Vec<_>>()
                .join("\n")
        }));
    }
    if uses_permission {
        buf.push_str("\nfrom .permissions import Permission\n");
    }

    for record in RECORDS.iter().copied() {
        let def_schema = &schema["$defs"][record];
        let fields = fields_for(def_schema, record);
        buf.push_str(&render_py_record(record, &fields));
    }

    for union in UNIONS {
        for branch in union.branches {
            if let Branch::Inline { name, index } = branch {
                let branch_schema = &schema["$defs"][union.name]["oneOf"][*index];
                let fields = fields_for(branch_schema, union.name);
                buf.push_str(&render_py_record(name, &fields));
            }
        }
        let branch_names: Vec<String> = union
            .branches
            .iter()
            .map(|branch| match branch {
                Branch::Named(name) => (*name).to_string(),
                Branch::Inline { name, .. } => (*name).to_string(),
            })
            .collect();
        buf.push_str(&format!(
            "\n{}: TypeAlias = Union[{}]\n",
            union.name,
            branch_names.join(", ")
        ));
    }

    buf.push_str("\n__all__ = [");
    for record in RECORDS {
        buf.push_str(&format!("\n    \"{record}\",",));
    }
    for union in UNIONS {
        for branch in union.branches {
            if let Branch::Inline { name, .. } = branch {
                buf.push_str(&format!("\n    \"{name}\",",));
            }
        }
        buf.push_str(&format!("\n    \"{}\",", union.name));
    }
    buf.push_str("\n]\n");
    buf
}

pub fn render_frontend_records_typescript() -> String {
    let schema = schema();
    let (families, uses_permission) = used_imports(&schema);

    let mut buf = String::new();
    buf.push_str(TYPESCRIPT_HEADER);
    buf.push_str(
        "\n// The apxm.frontend-graph contract records, generated one per $defs entry.\n\
         //\n\
         // Each record's fields, required-ness, and enum/union typing are projected from\n\
         // the schema at generation time. These are the wire records the contract states\n\
         // exactly — no authoring-time extra (a source span, an operand's consumer\n\
         // slot) lives here. `bound-tree.ts`'s `BoundCall` and `BoundControl` carry one\n\
         // of these plus those extras; every other bound-tree record is one of these\n\
         // directly.\n",
    );

    if !families.is_empty() {
        let mut sorted = families.clone();
        sorted.sort_unstable();
        buf.push_str(&format!(
            "\nimport type {{\n{}\n}} from \"./frontend-graph.js\";\n",
            sorted
                .iter()
                .map(|name| format!("  {name},"))
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }
    if uses_permission {
        buf.push_str("\nimport type { Permission } from \"./permissions.js\";\n");
    }

    for record in RECORDS.iter().copied() {
        let def_schema = &schema["$defs"][record];
        let fields = fields_for(def_schema, record);
        buf.push_str(&render_ts_record(record, &fields));
    }

    for union in UNIONS {
        for branch in union.branches {
            if let Branch::Inline { name, index } = branch {
                let branch_schema = &schema["$defs"][union.name]["oneOf"][*index];
                let fields = fields_for(branch_schema, union.name);
                buf.push_str(&render_ts_record(name, &fields));
            }
        }
        let branch_names: Vec<String> = union
            .branches
            .iter()
            .map(|branch| match branch {
                Branch::Named(name) => (*name).to_string(),
                Branch::Inline { name, .. } => (*name).to_string(),
            })
            .collect();
        buf.push_str(&format!(
            "\nexport type {} =\n{};\n",
            union.name,
            branch_names
                .iter()
                .map(|name| format!("  | {name}"))
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    const FRONTEND_SURFACE_MANIFEST: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../contracts/vectors/apxm.frontend-surface.json"
    ));

    fn generated() -> [String; 2] {
        [
            render_frontend_records_python(),
            render_frontend_records_typescript(),
        ]
    }

    /// Every `$defs` object record and every discriminated union names its
    /// generated type, in both languages.
    #[test]
    fn every_record_and_union_is_emitted() {
        for rendered in generated() {
            for record in RECORDS.iter().copied() {
                assert!(rendered.contains(record), "{record} missing");
            }
            for union in UNIONS {
                assert!(rendered.contains(union.name), "{} missing", union.name);
                for branch in union.branches {
                    let name = match branch {
                        Branch::Named(name) => *name,
                        Branch::Inline { name, .. } => name,
                    };
                    assert!(rendered.contains(name), "{name} missing");
                }
            }
        }
    }

    /// `PredicateLiteral`'s branches carry no `$defs` name; this generator
    /// invents one. Losing this test would let a regeneration silently rename
    /// (and so break) every reader of these four types.
    #[test]
    fn predicate_literal_branches_keep_their_invented_names() {
        for rendered in generated() {
            for expected in [
                "BooleanLiteral",
                "StringLiteral",
                "IntegerLiteral",
                "NullLiteral",
            ] {
                assert!(rendered.contains(expected), "{expected}");
            }
        }
    }

    /// Enum- and const-typed fields resolve through the FrontendGraph
    /// vocabulary generator's own types rather than restating the closed set.
    #[test]
    fn enum_and_const_fields_resolve_through_the_vocabulary_generator() {
        let python = render_frontend_records_python();
        assert!(python.contains("decl_kind: DeclKind"));
        assert!(python.contains("scope: HookScope"));
        assert!(python.contains("comparator: PredicateComparator"));
        assert!(python.contains("kind: ValueExpressionKind"));
        assert!(python.contains("from .frontend_graph import"));

        let typescript = render_frontend_records_typescript();
        assert!(typescript.contains("readonly decl_kind: DeclKind;"));
        assert!(typescript.contains("from \"./frontend-graph.js\";"));
    }

    /// `PermissionDecision` is imported as `codegen_permissions`'s `Permission`,
    /// never re-emitted as a second `PermissionDecision` spelling.
    #[test]
    fn permission_decision_is_imported_not_reemitted() {
        for rendered in generated() {
            assert!(!rendered.contains("PermissionDecision"));
            assert!(rendered.contains("Permission"));
        }
        assert!(render_frontend_records_python().contains("from .permissions import Permission"));
        assert!(
            render_frontend_records_typescript()
                .contains("import type { Permission } from \"./permissions.js\";")
        );
    }

    /// Required fields are positional; optional fields default to `None` /
    /// are marked `?`, matching §4 item 1's rule.
    #[test]
    fn required_and_optional_fields_are_typed_accordingly() {
        let python = render_frontend_records_python();
        assert!(python.contains("target_ref: Optional[str] = None"));
        assert!(python.contains("program_id: str"));
        assert!(!python.contains("program_id: Optional[str]"));

        let typescript = render_frontend_records_typescript();
        assert!(typescript.contains("readonly target_ref?: string;"));
        assert!(typescript.contains("readonly program_id: string;"));
    }

    /// This module lands inside the installable authoring packages, so it
    /// must not carry a name the frontend-surface manifest marks non-public.
    #[test]
    fn no_non_public_name_reaches_the_authoring_packages() {
        let manifest: Value =
            serde_json::from_str(FRONTEND_SURFACE_MANIFEST).expect("frontend-surface manifest");
        let forbidden: Vec<String> = manifest["non_public"]
            .as_array()
            .expect("non_public states an array")
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .expect("non_public member is a string")
                    .to_string()
            })
            .collect();
        assert!(forbidden.contains(&"FIVE_OPS".to_string()));

        for rendered in generated() {
            let tokens: Vec<&str> = rendered
                .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '_' || ch == '.'))
                .collect();
            let offenders: Vec<&String> = forbidden
                .iter()
                .filter(|name| tokens.contains(&name.as_str()))
                .collect();
            assert!(
                offenders.is_empty(),
                "non-public names leaked: {offenders:?}"
            );
        }
    }
}
